changelog:
  categories:
    - title: Added
      labels: [new]
    - title: Fixed
      labels: [bug]
    - title: Balanced
      labels: [balance]
    - title: Dependencies
      labels: [dependencies]
    - title: Other
      labels: ["*"]
