using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static UnityEngine.ParticleSystem.PlaybackState;
using UnityEngine;

namespace MyFirstPlugin.GeneratorData
{
    static internal class Words
    {
        /// <summary>
        /// 200 grim dark adjectives
        /// </summary>
        static public string[] Adjectives =
        {
            "Bleak",
            "Ruthless",
            "Morbid",
            "Desolate",
            "Brutal",
            "Malignant",
            "Forsaken",
            "Grotesque",
            "Dystopian",
            "Hollow",
            "Gruesome",
            "Harrowing",
            "Malevolent",
            "Oppressive",
            "Visceral",
            "Mutilated",
            "Cursed",
            "Macabre",
            "Noxious",
            "Tormented",
            "Ominous",
            "Rancid",
            "Suffering",
            "Wretched",
            "Sinister",
            "Melancholic",
            "Feral",
            "Mournful",
            "Pernicious",
            "Bleeding",
            "Carnal",
            "Decayed",
            "Malformed",
            "Savage",
            "Ravaged",
            "Corroded",
            "Vile",
            "Tainted",
            "Blighted",
            "Fetid",
            "Grim",
            "Unholy",
            "Nefarious",
            "Blasphemous",
            "Abominable",
            "Haunting",
            "Deathly",
            "Charnel",
            "Abyssal",
            "Ghastly",
            "Insidious",
            "Foreboding",
            "Eroded",
            "Lamentable",
            "Sepulchral",
            "Dismal",
            "Rotten",
            "Drab",
            "Infested",
            "Profane",
            "Grisly",
            "Terrifying",
            "Desecrated",
            "Dire",
            "Maddening",
            "Gory",
            "Searing",
            "Putrid",
            "Cadaverous",
            "Gaunt",
            "Soulless",
            "Ashen",
            "Deranged",
            "Murky",
            "Sullied",
            "Decrepit",
            "Ruinous",
            "Morose",
            "Piteous",
            "Calamitous",
            "Lurid",
            "Bleached",
            "Tenebrous",
            "Anguished",
            "Ravenous",
            "Unsettling",
            "Marred",
            "Disquieting",
            "Dreadful",
            "Malign",
            "Stifling",
            "Pervasive",
            "Gloom-ridden",
            "Stark",
            "Bereft",
            "Shattered",
            "Broken",
            "Eviscerated",
            "Cacophonous",
            "Grimy",
            "Disturbing",
            "Shadowy",
            "War-torn",
            "Cataclysmic",
            "Waning",
            "Bane-filled",
            "Doomed",
            "Catastrophic",
            "Muted",
            "Festering",
            "Barren",
            "Fading",
            "Atrophied",
            "Diminished",
            "Eerie",
            "Discordant",
            "Tumultuous",
            "Raving",
            "Merciless",
            "Malefic",
            "Crumbling",
            "Haggard",
            "Pained",
            "Ravishing",
            "Venomous",
            "Withered",
            "Spiteful",
            "Obsidian",
            "Battered",
            "Appalling",
            "Unrelenting",
            "Bloodthirsty",
            "Sable",
            "Annihilated",
            "Drowning",
            "Sanguine",
            "Infernal",
            "Tortured",
            "Scarred",
            "Searing",
            "Horrifying",
            "Blackened",
            "Splintered",
            "Enervated",
            "Heinous",
            "Smoldering",
            "Pestilent",
            "Accursed",
            "Frenzied",
            "Decimating",
            "Fractured",
            "Toxic",
            "Pallid",
            "Despairing",
            "Despondent",
            "Relentless",
            "Wailing",
            "Traumatized",
            "Ravaging",
            "Twisted",
            "Seething",
            "Caustic",
            "Scorched",
            "Tattered",
            "Lecherous",
            "Vexed",
            "Void",
            "Wounded",
            "Befouled",
            "Stricken",
            "Degenerate",
            "Consumed",
            "Demonic",
            "Raging",
            "Vitiated",
            "Corrupted",
            "Hellish",
            "Purgatorial",
            "Defiled",
            "Repugnant",
            "Sacrilegious",
            "Blasted",
            "Bewitched",
            "Entropic",
            "Deteriorated",
            "Wrathful",
            "Plagued",
            "Waning",
            "Brooding",
            "Abject",
            "Disheveled",
            "Chilling",
            "Loathsome",
            "Maddened",
            "Melting",
            "Perishing",
            "Throttled",
            "Eclipsed",
            "Shriveling",
            "Maleficent"
        };

        /// <summary>
        /// Nouns to be used as names for a rundown
        /// </summary>
        static public string[] NounsRundown =
        {
            // Hole synonyms
            "Abyss",
            "Chasm",
            "Void",
            "Maw",
            "Underworld",
            "Cavern",
            "Labyrinth",
            "Catacomb",
            "Pitfall",
            "Gorge",
            "Hollow",
            "Subterrane",
            "Burrow",
            "Crevasse",
            "Gullet",
            "Tenebrous Tunnel",
            "Darkwell",
            "Fissure",
            "Undercrypt",
            "Oblivion",

            // Mission synonyms
            "Crusade",
            "Vendetta",
            "Ordeal",
            "Bloodquest",
            "Reckoning",
            "Purge",
            "Conquest",
            "Expurgation",
            "Vengeance",
            "Retribution",
            "Endeavor",
            "Extermination",
            "Annihilation",
            "Obliteration",
            "Decimation",
            "Dominion",
            "Insurrection",
            "Onslaught",
            "Sacrifice",
            "Inquisition",
            "Siege",
            "Desolation",
            "Persecution",
            "Incursion",
            "Culling",
            "Exorcism",
            "Enthronement",
            "Subjugation",
            "Redemption",
            "Ravage",
        };

        /// <summary>
        /// Nouns for Level names
        /// </summary>
        static public string[] NounsLevel =
        {
            "Dissolution",
            "Enigma Void",
            "Malevolence",
            "Bleak Nexus",
            "Catacomb Depth",
            "Aberration",
            "Desolation Pulse",
            "Grim Ascent",
            "Cryptic Relic",
            "Shadow's Descent",
            "Forlorn Vault",
            "Abyssal Rift",
            "Blight's Reach",
            "Mire",
            "Decay's Hold",
            "Obliterate",
            "Infernal Passage",
            "Isolation",
            "Torment's Lair",
            "Veil of Despair",
            "Sable Depths",
            "Entropy's Grasp",
            "Lost Reverie",
            "Despair's Domain",
            "Wane",
            "Nocturnal Hollow",
            "Fractured Echo",
            "Endless Chasm",
            "Voidwalk",
            "Eroded Memories",
            "Forsaken Sanctuary",
            "Vortex of Silence",
            "Mortal Coil",
            "Spectral Divide",
            "Haunting Expanse",
            "Tenebrous Labyrinth",
            "Corroded Chambers",
            "Bane's Descent",
            "Dread Core",
            "Lost Purgatory",
            "Umbral Stretch",
            "Grave's Whisper",
            "Malignant Nexus",
            "Fallen Dominion",
            "Ephemeral Passage",
            "Netherbound",
            "Gloom's Heart",
            "Stygian Abyss",
            "Ruination",
            "Cursed Gallery",
            "Eclipsed Reality",
            "Doom's Cradle",
            "Mourning Depths",
            "Harbinger's Hold",
            "Catastrophic Crevasse",
            "Blighted Reliquary",
            "Shadow's Embrace",
            "Sorrow's Enclave",
            "Dusk's Demise",
            "Ghastly Gorge",
            "Inferno's Mouth",
            "Vice's Grasp",
            "Bleak Bastion",
            "Silent Sunder",
            "Dark Nexus",
            "Obsidian Oubliette",
            "Ravaged Resonance",
            "Dreadnaught's Depth",
            "Twilight Tomb",
            "Void's Verge",
            "Bane's Breach",
            "Ethereal Edge",
            "Fathomless",
            "Grim Gallery",
            "Haunt's Halls",
            "Mist's Murk",
            "Descent into Darkness",
            "Petrified Path",
            "Eerie Expanse",
            "Lurk's Labyrinth",
            "Perdition's Pits",
            "Spectral Spire",
            "Torrid Tunnels",
            "Wraith's Wake",
            "Desolate Divide",
            "Graveyard Grotto",
            "Hollow's Heart",
            "Sable Sorrow",
            "Twisted Terrain",
            "Umbral Underbelly",
            "Void's Vestige",
            "Wither's Way",
            "Crypt's Crux",
            "Eldritch Elevations",
            "Fallen's Folly",
            "Gloom's Gulch",
            "Hell's Hinge",
            "Infernal Interstice",
            "Jagged Jaws",
            "Kiln of Khaos",
            "Lament's Landing",
            "Maw's Murmur",
            "Necrotic Niche",
            "Oblivion's Overture",
            "Phantom's Phalanx",
            "Quarry of Quietude",
            "Riven Realm",
            "Shadow's Shroud",
            "Turbid Trench",
            "Unraveling Umbras",
            "Vexed Vistas",
            "Whisper's Wane",
            "Xenolith Expanse",
            "Yawning Yoke",
            "Zenith of Zero"
        };

        /// <summary>
        /// Present participle verbs of failure
        /// </summary>
        static public string[] VerbsPresentParticiple =
        {
            "Withering",
            "Crumbling",
            "Decaying",
            "Floundering",
            "Suffering",
            "Languishing",
            "Deteriorating",
            "Collapsing",
            "Disintegrating",
            "Perishing",
            "Degenerating",
            "Fading",
            "Declining",
            "Eroding",
            "Wasting",
            "Dissipating",
            "Wilting",
            "Corroding",
            "Regressing",
            "Despairing",
            "Weakening",
            "Struggling",
            "Depleting",
            "Atrophying",
            "Wrecking",
            "Diminishing",
            "Bleeding",
            "Slipping",
            "Moldering",
            "Drowning",
            "Fraying",
            "Succumbing",
            "Breaking",
            "Sinking",
            "Fading",
            "Ravaging",
            "Dissolving",
            "Caving",
            "Fumbling",
            "Draining"
        };
    }
}
