namespace AutogenRundown.GeneratorData
{
    static public class Words
    {
        /// <summary>
        /// Creates a list of names to pull from
        /// </summary>
        /// <returns></returns>
        static public List<string> NewLevelNamesPack()
        {
            var predefinedNames = new List<string>(NounsLevel);
            var first = new List<string>(Level_FirstWord);
            var last = new List<string>(Level_LastWord);
            var verb = new List<string>(VerbsPresentParticiple);

            var list = new List<string>();

            for (var i = 0; i < 30; i++)
            {
                // Add a predefined name that we have fully generated
                if (Generator.Flip(0.15))
                {
                    var name = Generator.Draw(predefinedNames)!;

                    list.Add(name);
                    continue;
                }

                // Create a new name
                var firstWord = Generator.Draw(Generator.Flip(0.3) ? verb : first);
                var lastWord = Generator.Draw(last);

                list.Add($"{firstWord} {lastWord}");
            }

            return list;
        }

        public static string RundownNameMonthly()
        {
            var noun = Generator.MonthNumber switch
            {
                // January
                1 => Generator.Pick(new List<string>
                {
                    "Bleakburrow", "Mooncrypt", "Obsidian Grotto", "Chillmarrow", "Dampvault", "Umbral Cage",
                    "Nightfissure", "Wraithclot", "Pale Labyrinth", "Blackmarsh"
                }),
                // February
                2 => Generator.Pick(new List<string>
                {
                    // "Depthshroud", "Fallowchasm", "Ravencrypt", "Silent Hollow", "Marrowfane", "Crowvault",
                    // "Lurid Veil", "Creviceborn", "Dire Maw", "Sunken Gloom"
                    "Kovac's Shroud"
                }),
                // March
                3 => Generator.Pick(new List<string>
                {
                    "Sourgrove", "Waning Crypt", "Fetid Mine", "Gravewhisper", "Underrot", // "Stagnant Grotto",
                    "Mireclaw", "Stillroot", "Gloomchoke", "Weeping Den"
                }),
                // April
                4 => Generator.Pick(new List<string>
                {
                    "Fogshard", "Drearnest", "Rotwood", "Witherspine", "Sporefen", "Tanglechasm", "Musty Hollow",
                    "Duskreef", "Faint Maze", "Subtlecrag"
                }),
                // May
                5 => Generator.Pick(new List<string>
                {
                    "Fetid Thicket", "Wormblight", "Ashen Vault", "Goreburrow", "Briarcrypt", "Umbraspore",
                    "Gullychill", "Soulchoke", "Darkfen", "Verdant Rot"
                }),
                // June
                6 => Generator.Pick(new List<string>
                {
                    "Cinderdeep", "Molded Pit", "Charfall", "Blightbarrow", "Grimwarren", "Gorecliff", "Dusthusk",
                    "Marrow Reach", "Wraith Fane", "Hollow Thorn"
                }),
                // July
                7 => Generator.Pick(new List<string>
                {
                    "Bonechoke", "Rotcairn", "Dreggrotto", "Wraithknell", "Palechasm", "Dustwraith", "Husked Vale",
                    "Bleakcyst", "Sunless Maw", "Murkspan"
                }),
                // August
                8 => Generator.Pick(new List<string>
                {
                    "Gorechoke", "Hollowrift", "Lurid Pit", "Cavernfrost", "Wormclot", "Faintcrawl", "Midnight Grotto",
                    "Wraithscar", "Ember Hollow", "Sour Vault"
                }),
                // September
                9 => Generator.Pick(new List<string>
                {
                    "Underclaw", "Duskmarsh", "Cindercrypt", "Fallow Maw", "Grimspire", "Dregfen", "Shadowchoke",
                    "Hazecrypt", "Briarchasm", "Twilight Burrow"
                }),
                // October
                10 => Generator.Pick(new List<string>
                {
                    "Wraithgrove", "Hollowthorn", "Ragged Depths", "Twilight Rift", "Musty Chasm", "Blackburrow",
                    "Rotspire", "Moonfen", "Nightflare", "Molderclaw"
                }),
                // November
                11 => Generator.Pick(new List<string>
                {
                    "Frostwhisper", "Eboncrypt", "Shadowfen", "Dimthorn", "Quiet Grotto", "Waning Hollow", "Bleak Haze",
                    "Underfissure", "Grey Rot", "Stygian Vault"
                }),
                // December
                12 => Generator.Pick(new List<string>
                {
                    "Night Shiver", "Bone Whisper", "Gloom Fane", "Cinderhusk", "Riftgloom", "Soul Hollow",
                    "Midnightfen", "Plague Claw", "Umbral Crypt", "Bleakharrow"
                }),
            };

            return noun;
        }

        /// <summary>
        /// 200 grim dark adjectives
        /// </summary>
        static public string[] Adjectives =
        {
            "Bleak",
            "Ruthless",
            "Morbid",
            "Desolate",
            "Brutal",
            "Malignant",
            "Forsaken",
            "Grotesque",
            "Dystopian",
            "Hollow",
            "Gruesome",
            "Harrowing",
            "Malevolent",
            "Oppressive",
            "Visceral",
            "Mutilated",
            "Cursed",
            "Macabre",
            "Noxious",
            "Tormented",
            "Ominous",
            "Rancid",
            "Suffering",
            "Wretched",
            "Sinister",
            "Melancholic",
            "Feral",
            "Mournful",
            "Pernicious",
            "Bleeding",
            "Carnal",
            "Decayed",
            "Malformed",
            "Savage",
            "Ravaged",
            "Corroded",
            "Vile",
            "Tainted",
            "Blighted",
            "Fetid",
            "Grim",
            "Unholy",
            "Nefarious",
            "Blasphemous",
            "Abominable",
            "Haunting",
            "Deathly",
            "Charnel",
            "Abyssal",
            "Ghastly",
            "Insidious",
            "Foreboding",
            "Eroded",
            "Lamentable",
            "Sepulchral",
            "Dismal",
            "Rotten",
            "Drab",
            "Infested",
            "Profane",
            "Grisly",
            "Terrifying",
            "Desecrated",
            "Dire",
            "Maddening",
            "Gory",
            "Searing",
            "Putrid",
            "Cadaverous",
            "Gaunt",
            "Soulless",
            "Ashen",
            "Deranged",
            "Murky",
            "Sullied",
            "Decrepit",
            "Ruinous",
            "Morose",
            "Piteous",
            "Calamitous",
            "Lurid",
            "Bleached",
            "Tenebrous",
            "Anguished",
            "Ravenous",
            "Unsettling",
            "Marred",
            "Disquieting",
            "Dreadful",
            "Malign",
            "Stifling",
            "Pervasive",
            "Gloom-ridden",
            "Stark",
            "Bereft",
            "Shattered",
            "Broken",
            "Eviscerated",
            "Cacophonous",
            "Grimy",
            "Disturbing",
            "Shadowy",
            "War-torn",
            "Cataclysmic",
            "Waning",
            "Bane-filled",
            "Doomed",
            "Catastrophic",
            "Muted",
            "Festering",
            "Barren",
            "Fading",
            "Atrophied",
            "Diminished",
            "Eerie",
            "Discordant",
            "Tumultuous",
            "Raving",
            "Merciless",
            "Malefic",
            "Crumbling",
            "Haggard",
            "Pained",
            "Ravishing",
            "Venomous",
            "Withered",
            "Spiteful",
            "Obsidian",
            "Battered",
            "Appalling",
            "Unrelenting",
            "Bloodthirsty",
            "Sable",
            "Annihilated",
            "Drowning",
            "Sanguine",
            "Infernal",
            "Tortured",
            "Scarred",
            "Searing",
            "Horrifying",
            "Blackened",
            "Splintered",
            "Enervated",
            "Heinous",
            "Smoldering",
            "Pestilent",
            "Accursed",
            "Frenzied",
            "Decimating",
            "Fractured",
            "Toxic",
            "Pallid",
            "Despairing",
            "Despondent",
            "Relentless",
            "Wailing",
            "Traumatized",
            "Ravaging",
            "Twisted",
            "Seething",
            "Caustic",
            "Scorched",
            "Tattered",
            "Lecherous",
            "Vexed",
            "Void",
            "Wounded",
            "Befouled",
            "Stricken",
            "Degenerate",
            "Consumed",
            "Demonic",
            "Raging",
            "Vitiated",
            "Corrupted",
            "Hellish",
            "Purgatorial",
            "Defiled",
            "Repugnant",
            "Sacrilegious",
            "Blasted",
            "Bewitched",
            "Entropic",
            "Deteriorated",
            "Wrathful",
            "Plagued",
            "Waning",
            "Brooding",
            "Abject",
            "Disheveled",
            "Chilling",
            "Loathsome",
            "Maddened",
            "Melting",
            "Perishing",
            "Throttled",
            "Eclipsed",
            "Shriveling",
            "Maleficent"
        };

        /// <summary>
        /// Nouns to be used as names for a rundown
        /// </summary>
        static public string[] NounsRundown =
        {
            // Hole synonyms
            "Abyss",
            "Chasm",
            "Void",
            "Maw",
            "Underworld",
            "Cavern",
            "Labyrinth",
            "Catacomb",
            "Pitfall",
            "Gorge",
            "Hollow",
            "Subterrane",
            "Burrow",
            "Crevasse",
            "Gullet",
            "Tenebrous Tunnel",
            "Darkwell",
            "Fissure",
            "Undercrypt",
            "Oblivion",

            // Mission synonyms
            "Crusade",
            "Vendetta",
            "Ordeal",
            "Bloodquest",
            "Reckoning",
            "Purge",
            "Conquest",
            "Expurgation",
            "Vengeance",
            "Retribution",
            "Endeavor",
            "Extermination",
            "Annihilation",
            "Obliteration",
            "Decimation",
            "Dominion",
            "Insurrection",
            "Onslaught",
            "Sacrifice",
            "Inquisition",
            "Siege",
            "Desolation",
            "Persecution",
            "Incursion",
            "Culling",
            "Exorcism",
            "Enthronement",
            "Subjugation",
            "Redemption",
            "Ravage",
        };

        static public string[] Level_FirstWord =
        {
            "Abandon",
            "Agony",
            "Anomaly",
            "Apparition",
            "Ashes",
            "Asylum",
            "Banishment",
            "Banshee",
            "Barrow",
            "Betrayal",
            "Charnel",
            "Collapse",
            "Corruption",
            "Crypt",
            "Cursed",
            "Darkness",
            "Decay",
            "Deception",
            "Decrepit",
            "Defilement",
            "Dementia",
            "Derelict",
            "Despair",
            "Detritus",
            "Dread",
            "Echoes",
            "Eclipse",
            "Eldritch",
            "Emptiness",
            "Enigma",
            "Erosion",
            "Evocation",
            "Extinction",
            "Faded",
            "Fallen",
            "Famine",
            "Fissure",
            "Forsaken",
            "Fright",
            "Ghost",
            "Gloom",
            "Grave",
            "Grim",
            "Haunted",
            "Havoc",
            "Horror",
            "Hostility",
            "Inferno",
            "Isolation",
            "Labyrinth",
            "Lament",
            "Leviathan",
            "Lurking",
            "Malevolent",
            "Malice",
            "Menace",
            "Mire",
            "Misery",
            "Morbid",
            "Mournful",
            "Nightmare",
            "Oblivion",
            "Omen",
            "Pandemonium",
            "Paranoia",
            "Perdition",
            "Phantom",
            "Plague",
            "Portal",
            "Ravine",
            "Reaper",
            "Ruin",
            "Shadows",
            "Sinister",
            "Specter",
            "Spiral",
            "Stalker",
            "Stasis",
            "Subterfuge",
            "Terror",
            "Threnody",
            "Torment",
            "Torture",
            "Treachery",
            "Trepidation",
            "Tryst",
            "Twilight",
            "Unholy",
            "Vampire",
            "Vengeance",
            "Venom",
            "Vile",
            "Vortex",
            "Wailing",
            "Wasteland",
            "Whisper",
            "Wicked",
            "Wrath",
            "Wretched",
            "Zephyr"
        };

        static public string[] Level_LastWord =
        {
            "Abyss",
            "Anomaly",
            "Apparition",
            "Ascent",
            "Ashes",
            "Banishment",
            "Barrow",
            "Bastion",
            "Beacon",
            "Burial",
            "Cascade",
            "Cataclysm",
            "Cavern",
            "Chasm",
            "Collapse",
            "Conundrum",
            "Corridor",
            "Corrupter",
            "Crevasse",
            "Crypt",
            "Cyst",
            "Darkness",
            "Death",
            "Delirium",
            "Demise",
            "Depth",
            "Descent",
            "Detritus",
            "Dread",
            "Eclipse",
            "Embrace",
            "Empire",
            "End",
            "Erosion",
            "Expanse",
            "Fissure",
            "Gallows",
            "Gloom",
            "Grave",
            "Halls",
            "Hollow",
            "Horror",
            "Inferno",
            "Labyrinth",
            "Lament",
            "Legacy",
            "Maw",
            "Maze",
            "Mirage",
            "Monolith",
            "Morass",
            "Morgue",
            "Nadir",
            "Necropolis",
            "Obelisk",
            "Oblivion",
            "Obscurity",
            "Obstruction",
            "Omen",
            "Pandemonium",
            "Paradigm",
            "Paradox",
            "Passage",
            "Phantasm",
            "Pit",
            "Portal",
            "Purgatory",
            "Quagmire",
            "Realm",
            "Reckoning",
            "Relic",
            "Requiem",
            "Rift",
            "Sanctuary",
            "Sarcophagus",
            "Scourge",
            "Sepulcher",
            "Shrine",
            "Spire",
            "Tomb",
            "Torment",
            "Trench",
            "Trove",
            "Tundra",
            "Undertow",
            "Underworld",
            "Vale",
            "Vault",
            "Veil",
            "Vestige",
            "Vortex",
            "Wasteland",
            "Whisper",
            "Womb",
            "Wraith",
            "Wreck",
            "Yawning",
            "Zenith"
        };

        /// <summary>
        /// Nouns for Level names
        /// </summary>
        static public string[] NounsLevel =
        {
            "Dissolution",
            "Enigma Void",
            "Malevolence",
            "Bleak Nexus",
            "Catacomb Depth",
            "Aberration",
            "Desolation Pulse",
            "Grim Ascent",
            "Cryptic Relic",
            "Shadow's Descent",
            "Forlorn Vault",
            "Abyssal Rift",
            "Blight's Reach",
            "Mire",
            "Decay's Hold",
            "Obliterate",
            "Infernal Passage",
            "Isolation",
            "Torment's Lair",
            "Veil of Despair",
            "Sable Depths",
            "Entropy's Grasp",
            "Lost Reverie",
            "Despair's Domain",
            "Wane",
            "Nocturnal Hollow",
            "Fractured Echo",
            "Endless Chasm",
            "Voidwalk",
            "Eroded Memories",
            "Forsaken Sanctuary",
            "Vortex of Silence",
            "Mortal Coil",
            "Spectral Divide",
            "Haunting Expanse",
            "Tenebrous Labyrinth",
            "Corroded Chambers",
            "Bane's Descent",
            "Dread Core",
            "Lost Purgatory",
            "Umbral Stretch",
            "Grave's Whisper",
            "Malignant Nexus",
            "Fallen Dominion",
            "Ephemeral Passage",
            "Netherbound",
            "Gloom's Heart",
            "Stygian Abyss",
            "Ruination",
            "Cursed Gallery",
            "Eclipsed Reality",
            "Doom's Cradle",
            "Mourning Depths",
            "Harbinger's Hold",
            "Catastrophic Crevasse",
            "Blighted Reliquary",
            "Shadow's Embrace",
            "Sorrow's Enclave",
            "Dusk's Demise",
            "Ghastly Gorge",
            "Inferno's Mouth",
            "Vice's Grasp",
            "Bleak Bastion",
            "Silent Sunder",
            "Dark Nexus",
            "Obsidian Oubliette",
            "Ravaged Resonance",
            "Dreadnaught's Depth",
            "Twilight Tomb",
            "Void's Verge",
            "Bane's Breach",
            "Ethereal Edge",
            "Fathomless",
            "Grim Gallery",
            "Haunt's Halls",
            "Mist's Murk",
            "Descent into Darkness",
            "Petrified Path",
            "Eerie Expanse",
            "Lurk's Labyrinth",
            "Perdition's Pits",
            "Spectral Spire",
            "Torrid Tunnels",
            "Wraith's Wake",
            "Desolate Divide",
            "Graveyard Grotto",
            "Hollow's Heart",
            "Sable Sorrow",
            "Twisted Terrain",
            "Umbral Underbelly",
            "Void's Vestige",
            "Wither's Way",
            "Crypt's Crux",
            "Eldritch Elevations",
            "Fallen's Folly",
            "Gloom's Gulch",
            "Hell's Hinge",
            "Infernal Interstice",
            "Jagged Jaws",
            "Kiln of Khaos",
            "Lament's Landing",
            "Maw's Murmur",
            "Necrotic Niche",
            "Oblivion's Overture",
            "Phantom's Phalanx",
            "Quarry of Quietude",
            "Riven Realm",
            "Shadow's Shroud",
            "Turbid Trench",
            "Unraveling Umbras",
            "Vexed Vistas",
            "Whisper's Wane",
            "Xenolith Expanse",
            "Yawning Yoke",
            "Zenith of Zero"
        };

        /// <summary>
        /// Present participle verbs of failure
        /// </summary>
        static public string[] VerbsPresentParticiple =
        {
            "Atrophying",
            "Bleeding",
            "Breaking",
            "Caving",
            "Collapsing",
            "Corroding",
            "Crumbling",
            "Decaying",
            "Declining",
            "Degenerating",
            "Depleting",
            "Despairing",
            "Deteriorating",
            "Diminishing",
            "Disintegrating",
            "Dissipating",
            "Dissolving",
            "Draining",
            "Drowning",
            "Eroding",
            "Fading",
            "Fading",
            "Floundering",
            "Fraying",
            "Fumbling",
            "Languishing",
            "Moldering",
            "Perishing",
            "Ravaging",
            "Regressing",
            "Sinking",
            "Slipping",
            "Struggling",
            "Succumbing",
            "Suffering",
            "Wasting",
            "Weakening",
            "Wilting",
            "Withering",
            "Wrecking"
        };

        /// <summary>
        /// GTFO enemy names
        /// </summary>
        static public string[] GtfoEnemies =
        {
            "Striker",
            "Shooter",
            "Charger",
            "Shadow",
            "Giant Striker",
            "Giant Shooter",
            "Giant Charger",
            "Shadow Giant",
            "Hybrid",
            "Scout",
            "Charger Scout",
            "Shadow Scout",
            "Tank",
            "Immortal",
            "Mother",
            "P-Mother",
        };

        /// <summary>
        /// Words used for human readable seed strings
        /// </summary>
        static public string[] SeedWords =
        {
            "apple",
            "banana",
            "cherry",
            "dog",
            "cat",
            "bird",
            "fish",
            "house",
            "chair",
            "table",
            "book",
            "pen",
            "hat",
            "car",
            "bus",
            "shoe",
            "sock",
            "bag",
            "tree",
            "sun",
            "moon",
            "star",
            "water",
            "river",
            "lake",
            "ocean",
            "beach",
            "sand",
            "wind",
            "rain",
            "snow",
            "cloud",
            "storm",
            "grass",
            "leaf",
            "flower",
            "rose",
            "tulip",
            "daisy",
            "lily",
            "bird",
            "eagle",
            "hawk",
            "dove",
            "raven",
            "paper",
            "pencil",
            "eraser",
            "ruler",
            "desk",
            "phone",
            "clock",
            "watch",
            "lamp",
            "light",
            "music",
            "song",
            "dance",
            "play",
            "game",
            "ball",
            "bat",
            "glove",
            "goal",
            "run",
            "walk",
            "sit",
            "stand",
            "jump",
            "dance",
            "sing",
            "laugh",
            "cry",
            "smile",
            "frown",
            "speak",
            "listen",
            "read",
            "write",
            "draw",
            "paint",
            "color",
            "print",
            "ship",
            "boat",
            "plane",
            "train",
            "car",
            "bus",
            "bike",
            "bell",
            "ring",
            "gift",
            "card",
            "party",
            "cake",
            "pie",
            "ice",
            "cream",
            "sugar",
            "salt",
            "spice",
            "bread",
            "meat",
            "egg",
            "milk",
            "cheese",
            "pasta",
            "rice",
            "soup",
            "salad",
            "fruit",
            "grape",
            "orange",
            "lemon",
            "lime",
            "melon",
            "berry",
            "nut",
            "date",
            "honey",
            "butter",
            "jam",
            "jelly",
            "candy",
            "choco",
            "cookie",
            "muffin",
            "donut",
            "coffee",
            "tea",
            "juice",
            "soda",
            "water",
            "beer",
            "wine",
            "drink",
            "glass",
            "plate",
            "bowl",
            "spoon",
            "fork",
            "knife",
            "napkin",
            "towel",
            "sheet",
            "blanket",
            "pillow",
            "bed",
            "sofa",
            "chair",
            "bench",
            "floor",
            "wall",
            "door",
            "window",
            "roof",
            "chimney",
            "fence",
            "yard",
            "garden",
            "field",
            "farm",
            "barn",
            "stable",
            "horse",
            "cow",
            "pig",
            "sheep",
            "goat",
            "chicken",
            "turkey",
            "duck",
            "pond",
            "pool",
            "park",
            "zoo",
            "forest",
            "hill",
            "mountain",
            "valley",
            "desert",
            "island",
            "beach",
            "wave",
            "tide",
            "coral",
            "fish",
            "whale",
            "shark",
            "dolphin",
            "seal",
            "crab",
            "lobster",
            "squid",
            "octopus",
            "snail",
            "turtle",
            "lizard",
            "snake",
            "frog",
            "spider",
            "ant",
            "bee",
            "bug",
            "fly",
            "worm",
            "rat",
            "mouse",
            "rabbit",
            "bear",
            "tiger",
            "lion",
            "leopard",
            "panther",
            "wolf",
            "fox",
            "deer",
            "moose",
            "elk",
            "beaver",
            "otter",
            "raccoon",
            "skunk",
            "bat",
            "owl",
            "city",
            "town",
            "village",
            "road",
            "street",
            "alley",
            "avenue",
            "highway",
            "bridge",
            "tunnel",
            "port",
            "harbor",
            "station",
            "hotel",
            "motel",
            "inn",
            "bank",
            "market",
            "mall",
            "store",
            "shop",
            "office",
            "factory",
            "school",
            "church",
            "temple",
            "mosque",
            "museum",
            "library",
            "zoo",
            "park",
            "garden",
            "circus",
            "theater",
            "cinema",
            "cafe",
            "bar",
            "club",
            "gym",
            "spa",
            "salon",
            "hospital",
            "clinic",
            "prison",
            "police",
            "army",
            "navy",
            "air",
            "fire",
            "metal",
            "wood",
            "cloth",
            "silk",
            "wool",
            "cotton",
            "paper",
            "stone",
            "rock",
            "brick",
            "clay",
            "glass",
            "gold",
            "silver",
            "bronze",
            "steel",
            "iron",
            "copper",
            "lead",
            "tin",
            "zinc",
            "nickel",
            "chrome",
            "plastic",
            "rubber",
            "leather",
            "fur",
            "feather",
            "wool",
            "rope",
            "wire",
            "chain",
            "nail",
            "screw",
            "bolt",
            "nut",
            "wheel",
            "tire",
            "pedal",
            "gear",
            "brake",
            "seat",
            "belt",
            "hat",
            "cap",
            "helmet",
            "scarf",
            "glove",
            "sock",
            "shoe",
            "boot",
            "sandal",
            "shirt",
            "blouse",
            "dress",
            "skirt",
            "pants",
            "jeans",
            "suit",
            "tie",
            "jacket",
            "coat",
            "sweater",
            "vest",
            "cape",
            "robe",
            "pajama",
            "underwear",
            "bra",
            "panty",
            "diaper",
            "purse",
            "wallet",
            "bag",
            "suitcase",
            "box",
            "can",
            "jar",
            "bottle",
            "jug",
            "cup",
            "mug",
            "plate",
            "bowl",
            "spoon",
            "fork",
            "knife",
            "chopstick",
            "pin",
            "needle",
            "thread",
            "button",
            "zipper",
            "scissors",
            "razor",
            "comb",
            "brush",
            "mirror",
            "towel",
            "soap",
            "shampoo",
            "lotion",
            "perfume",
            "makeup",
            "lipstick",
            "eyeshadow",
            "mascara",
            "nailpolish",
            "ring",
            "earring",
            "necklace",
            "bracelet",
            "watch",
            "clock",
            "radio",
            "phone",
            "camera",
            "computer",
            "printer",
            "scanner",
            "TV",
            "DVD",
            "CD",
            "disk",
            "tape",
            "book",
            "magazine",
            "newspaper",
            "letter",
            "card",
            "envelope",
            "stamp",
            "pen",
            "pencil",
            "marker",
            "crayon",
            "paint",
            "brush",
            "easel",
            "canvas",
            "paper",
            "notebook",
            "binder",
            "folder",
            "file",
            "clip",
            "staple",
            "glue",
            "tape",
            "ruler",
            "calculator",
            "lamp",
            "bulb",
            "plug",
            "wire",
            "battery",
            "charger",
            "remote",
            "headset",
            "speaker",
            "microphone",
            "keyboard",
            "mouse",
            "screen",
            "monitor",
            "drive",
            "router",
            "modem",
            "antenna",
            "satellite",
            "rocket",
            "plane",
            "helicopter",
            "drone",
            "ship",
            "boat",
            "car",
            "truck",
            "bus",
            "train",
            "tram",
            "bike",
            "scooter",
            "skateboard",
            "rollerblade",
            "sled",
            "ski",
            "surfboard",
            "parachute",
            "tent",
            "sleepingbag",
            "backpack",
            "flashlight",
            "lantern",
            "match",
            "lighter",
            "stove",
            "oven",
            "microwave",
            "refrigerator",
            "freezer",
            "dishwasher",
            "washingmachine",
            "dryer",
            "vacuum",
            "broom",
            "mop",
            "bucket",
            "bin",
            "trash",
            "recycle",
            "leaf",
            "grass",
            "flower",
            "tree",
            "bush",
            "vine",
            "mushroom",
            "fruit",
            "vegetable",
            "grain",
            "bean",
            "nut",
            "meat",
            "poultry",
            "fish",
            "seafood",
            "dairy",
            "egg",
            "cheese",
            "butter",
            "oil",
            "sugar",
            "salt",
            "spice",
            "tea",
            "coffee",
            "cocoa",
            "water",
            "juice",
            "soda",
            "wine",
            "beer",
            "liquor",
            "cocktail",
            "soup",
            "salad",
            "sandwich",
            "pizza",
            "pasta",
            "rice",
            "bread",
            "cake",
            "pie",
            "cookie",
            "candy",
            "icecream",
            "jelly",
            "jam",
            "honey",
            "syrup",
            "vinegar",
            "sauce",
            "ketchup",
            "mustard",
            "mayo",
            "pepper",
            "chili",
            "garlic",
            "onion",
            "potato",
            "carrot",
            "bean",
            "pea",
            "corn",
            "cucumber",
            "lettuce",
            "tomato",
            "pepper",
            "broccoli",
            "spinach",
            "mushroom",
            "olive",
            "pickle",
            "apple",
            "banana",
            "orange",
            "berry",
            "grape",
            "lemon",
            "lime",
            "melon",
            "mango",
            "papaya",
            "pineapple",
            "coconut",
            "cherry",
            "plum",
            "peach",
            "apricot",
            "nut",
            "almond",
            "peanut",
            "walnut",
            "chestnut",
            "hazelnut",
            "meat",
            "pork",
            "beef",
            "lamb",
            "chicken",
            "turkey",
            "duck",
            "fish",
            "salmon",
            "tuna",
            "shrimp",
            "crab",
            "lobster",
            "oyster",
            "clam",
            "mussel",
            "squid",
            "octopus",
            "egg",
            "milk",
            "cheese",
            "yogurt",
            "butter",
            "cream",
            "icecream",
            "chocolate",
            "candy",
            "cookie",
            "cake",
            "pie",
            "muffin",
            "donut",
            "bread",
            "toast",
            "bagel",
            "roll",
            "croissant",
            "pancake",
            "waffle",
            "cereal",
            "oatmeal",
            "rice",
            "pasta",
            "noodle",
            "sushi",
            "pizza",
            "burger",
            "hotdog",
            "sandwich",
            "wrap",
            "taco",
            "burrito",
            "salad",
            "soup",
            "stew",
            "chili",
            "curry",
            "sauce",
            "gravy",
            "dressing",
            "ketchup",
            "mustard",
            "mayo",
            "relish",
            "pickles",
            "olives",
            "jam",
            "jelly",
            "honey",
            "syrup",
            "butter",
            "oil",
            "vinegar",
            "salt",
            "pepper",
            "spice",
            "herb",
            "garlic",
            "onion",
            "tomato",
            "potato",
            "carrot",
            "celery",
            "lettuce",
            "cabbage",
            "spinach",
            "broccoli",
            "pepper",
            "bean",
            "pea",
            "corn",
            "cucumber",
            "zucchini",
            "squash",
            "pumpkin",
            "eggplant",
            "mushroom",
            "olive",
            "apple",
            "banana",
            "orange",
            "berry",
            "grape",
            "lemon",
            "lime",
            "melon",
            "mango",
            "papaya",
            "pineapple",
            "coconut",
            "cherry",
            "plum",
            "peach",
            "apricot",
            "berry",
            "kiwi",
            "date",
            "fig",
            "raisin",
            "nut",
            "almond",
            "peanut",
            "walnut",
            "chestnut",
            "hazelnut",
            "cashew",
            "pecan",
            "macadamia",
            "meat",
            "pork",
            "beef",
            "lamb",
            "chicken",
            "turkey",
            "duck",
            "fish",
            "salmon",
            "tuna",
            "shrimp",
            "crab",
            "lobster",
            "oyster",
            "clam",
            "mussel",
            "squid",
            "octopus",
            "caviar",
            "egg",
            "milk",
            "cheese",
            "yogurt",
            "butter",
            "cream",
            "icecream",
            "chocolate",
            "candy",
            "cookie",
            "cake",
            "pie",
            "muffin",
            "donut",
            "bread",
            "toast",
            "bagel",
            "roll",
            "croissant",
            "pancake",
            "waffle",
            "cereal",
            "oatmeal",
            "rice",
            "pasta",
            "noodle",
            "sushi",
            "pizza",
            "burger",
            "hotdog",
            "sandwich",
            "wrap",
            "taco",
            "burrito",
            "salad",
            "soup",
            "stew",
            "chili",
            "curry",
            "sauce",
            "gravy",
            "dressing",
            "ketchup",
            "mustard",
            "mayo",
            "relish",
            "pickles",
            "olives",
            "jam",
            "jelly",
            "honey",
            "syrup",
            "butter",
            "oil",
            "vinegar",
            "salt",
            "pepper",
            "spice",
            "herb",
            "garlic",
            "onion",
            "tomato",
            "potato",
            "carrot",
            "celery",
            "lettuce",
            "cabbage",
            "spinach",
            "broccoli",
            "pepper",
            "bean",
            "pea",
            "corn",
            "cucumber",
            "zucchini",
            "squash",
            "pumpkin",
            "eggplant",
            "mushroom",
            "olive",
            "apple",
            "banana",
            "orange",
            "berry",
            "grape",
            "lemon",
            "lime",
            "melon",
            "mango",
            "papaya",
            "pineapple",
            "coconut",
            "cherry",
            "plum",
            "peach",
            "apricot",
            "berry",
            "kiwi",
            "date",
            "fig",
            "raisin",
            "nut",
            "almond",
            "peanut",
            "walnut",
            "chestnut",
            "hazelnut",
            "cashew",
            "pecan",
            "macadamia",
            "meat",
            "pork",
            "beef",
            "lamb",
            "chicken",
            "turkey",
            "duck",
            "fish",
            "salmon",
            "tuna",
            "shrimp",
            "crab",
            "lobster",
            "oyster",
            "clam",
            "mussel",
            "squid",
            "octopus",
            "caviar",
            "egg",
            "milk",
            "cheese",
            "yogurt",
            "butter",
            "cream",
            "icecream",
            "chocolate",
            "candy",
            "cookie",
            "cake",
            "pie",
            "muffin",
            "donut",
            "bread",
            "toast",
            "bagel",
            "roll",
            "croissant",
            "pancake",
            "waffle",
            "cereal",
            "oatmeal",
            "rice",
            "pasta",
            "noodle",
            "sushi",
            "pizza",
            "burger",
            "hotdog",
            "sandwich",
            "wrap",
            "taco",
            "burrito",
            "salad",
            "soup",
            "stew",
            "chili",
            "curry",
            "sauce",
            "gravy",
            "dressing",
            "ketchup",
            "mustard",
            "mayo",
            "relish",
            "pickles",
            "olives",
            "jam",
            "jelly",
            "honey",
            "syrup",
            "butter",
            "oil",
            "vinegar",
            "salt",
            "pepper",
            "spice",
            "herb",
            "garlic",
            "onion",
            "tomato",
            "potato",
            "carrot",
            "celery",
            "lettuce",
            "cabbage",
            "spinach",
            "broccoli",
            "pepper",
            "bean",
            "pea",
            "corn",
            "cucumber",
            "zucchini",
            "squash",
            "pumpkin",
            "eggplant",
            "mushroom",
            "olive",
            "apple",
            "banana",
            "orange",
            "berry",
            "grape",
            "lemon",
            "lime",
            "melon",
            "mango",
            "papaya",
            "pineapple",
            "coconut",
            "cherry",
            "plum",
            "peach",
            "apricot",
            "berry",
            "kiwi",
            "date",
            "fig",
            "raisin",
            "nut",
            "almond",
            "peanut",
            "walnut",
            "chestnut",
            "hazelnut",
            "cashew",
            "pecan",
            "macadamia",
            "meat",
            "pork",
            "beef",
            "lamb",
            "chicken",
            "turkey",
            "duck",
            "fish",
            "salmon",
            "tuna",
            "shrimp",
            "crab",
            "lobster",
            "oyster",
            "clam",
            "mussel",
            "squid",
            "octopus",
            "caviar",
            "egg",
            "milk",
            "cheese",
            "yogurt",
            "butter",
            "cream",
            "icecream",
            "chocolate",
            "candy",
            "cookie",
            "cake",
            "pie",
            "muffin",
            "donut"
        };
    }
}
