namespace AutogenRundown.GeneratorData;

static public class Words
{
    /// <summary>
    /// Creates a list of names to pull from
    /// </summary>
    /// <returns></returns>
    static public List<string> NewLevelNamesPack()
    {
        var predefinedNames = new List<string>(NounsLevel);
        var first = new List<string>(Level_FirstWord);
        var last = new List<string>(Level_LastWord);

        var adjective = new List<string>(Adjectives);
        var verb = new List<string>(VerbsPresentParticiple);

        var list = new List<string>();

        for (var i = 0; i < 30; i++)
        {
            // Add a predefined name that we have fully generated
            if (Generator.Flip(0.30))
            {
                var name = Generator.Draw(predefinedNames)!;

                list.Add(name);
                continue;
            }

            // Create a new name
            var firstWord = Generator.Draw(
                Generator.Select(new List<(double, List<string>)>
                {
                    (0.1, verb),
                    (0.2, adjective),
                    (0.7, first),
                }));
            var lastWord = Generator.Draw(last);

            list.Add($"{firstWord} {lastWord}");
        }

        return list;
    }

    public static string RundownNameMonthly()
    {
        var noun = Generator.MonthNumber switch
        {
            // January
            1 => Generator.Pick(new List<string>
            {
                "Bleakburrow", "Mooncrypt", "Obsidian Grotto", "Chillmarrow", "Dampvault", "Umbral Cage",
                "Nightfissure", "Wraithclot", "Pale Labyrinth", "Blackmarsh"
            }),
            // February
            2 => Generator.Pick(new List<string>
            {
                "Depthshroud", "Fallowchasm", "Ravencrypt", "Silent Hollow", "Marrowfane", "Crowvault",
                "Lurid Veil", "Creviceborn", "Dire Maw", "Sunken Gloom"
            }),
            // March
            3 => Generator.Pick(new List<string>
            {
                "Sourgrove", "Waning Crypt", "Fetid Mine", "Gravewhisper", "Underrot", // "Stagnant Grotto",
                "Mireclaw", "Stillroot", "Gloomchoke", "Weeping Den"
            }),
            // April
            4 => Generator.Pick(new List<string>
            {
                "Fogshard", "Drearnest", "Rotwood", "Witherspine", "Sporefen", "Tanglechasm", "Musty Hollow",
                "Duskreef", "Faint Maze", "Subtlecrag"
            }),
            // May
            5 => Generator.Pick(new List<string>
            {
                "Fetid Thicket", "Wormblight", "Ashen Vault", "Goreburrow", "Briarcrypt", "Umbraspore",
                "Gullychill", "Soulchoke", "Darkfen", "Verdant Rot"
            }),
            // June
            6 => Generator.Pick(new List<string>
            {
                "Cinderdeep", /*"Charfall", "Blightbarrow", "Grimwarren", "Gorecliff", "Dusthusk",
                "Marrow Reach", "Wraith Fane", "Hollow Thorn"*/
                // "Molded Pit",
            }),
            // July
            7 => Generator.Pick(new List<string>
            {
                "Bonechoke", "Rotcairn", "Dreggrotto", "Wraithknell", "Palechasm", "Dustwraith", "Husked Vale",
                "Bleakcyst", "Sunless Maw", "Murkspan"
            }),
            // August
            8 => Generator.Pick(new List<string>
            {
                "Gorechoke", "Hollowrift", "Lurid Pit", "Cavernfrost", "Wormclot", "Faintcrawl", "Midnight Grotto",
                "Wraithscar", "Ember Hollow", "Sour Vault"
            }),
            // September
            9 => Generator.Pick(new List<string>
            {
                "Underclaw", "Duskmarsh", "Cindercrypt", "Fallow Maw", "Grimspire", "Dregfen", "Shadowchoke",
                "Hazecrypt", "Briarchasm", "Twilight Burrow"
            }),
            // October
            10 => Generator.Pick(new List<string>
            {
                "Wraithgrove", "Hollowthorn", "Ragged Depths", "Twilight Rift", "Musty Chasm", "Blackburrow",
                "Rotspire", "Moonfen", "Nightflare", "Molderclaw"
            }),
            // November
            11 => Generator.Pick(new List<string>
            {
                "Frostwhisper", "Eboncrypt", "Shadowfen", "Dimthorn", "Quiet Grotto", "Waning Hollow", "Bleak Haze",
                "Underfissure", "Grey Rot", "Stygian Vault"
            }),
            // December
            12 => Generator.Pick(new List<string>
            {
                "Night Shiver", "Bone Whisper", "Gloom Fane", "Cinderhusk", "Riftgloom", "Soul Hollow",
                "Midnightfen", "Plague Claw", "Umbral Crypt", "Bleakharrow"
            }),
            _ => "Schaeffer's Bane"
        };

        return noun ?? string.Empty;
    }

    /// <summary>
    /// 200 grim dark adjectives
    /// </summary>
    static public string[] Adjectives =
    {
        "Bleak",
        "Ruthless",
        "Morbid",
        "Desolate",
        "Brutal",
        "Malignant",
        "Forsaken",
        "Grotesque",
        "Dystopian",
        "Hollow",
        "Gruesome",
        "Harrowing",
        "Malevolent",
        "Oppressive",
        "Visceral",
        "Mutilated",
        "Cursed",
        "Macabre",
        "Noxious",
        "Tormented",
        "Ominous",
        "Rancid",
        "Suffering",
        "Wretched",
        "Sinister",
        "Melancholic",
        "Feral",
        "Mournful",
        "Pernicious",
        "Bleeding",
        "Carnal",
        "Decayed",
        "Malformed",
        "Savage",
        "Ravaged",
        "Corroded",
        "Vile",
        "Tainted",
        "Blighted",
        "Fetid",
        "Grim",
        "Unholy",
        "Nefarious",
        "Blasphemous",
        "Abominable",
        "Haunting",
        "Deathly",
        "Charnel",
        "Abyssal",
        "Ghastly",
        "Insidious",
        "Foreboding",
        "Eroded",
        "Lamentable",
        "Sepulchral",
        "Dismal",
        "Rotten",
        "Drab",
        "Infested",
        "Profane",
        "Grisly",
        "Terrifying",
        "Desecrated",
        "Dire",
        "Maddening",
        "Gory",
        "Searing",
        "Putrid",
        "Cadaverous",
        "Gaunt",
        "Soulless",
        "Ashen",
        "Deranged",
        "Murky",
        "Sullied",
        "Decrepit",
        "Ruinous",
        "Morose",
        "Piteous",
        "Calamitous",
        "Lurid",
        "Bleached",
        "Tenebrous",
        "Anguished",
        "Ravenous",
        "Unsettling",
        "Marred",
        "Disquieting",
        "Dreadful",
        "Malign",
        "Stifling",
        "Pervasive",
        "Gloom-ridden",
        "Stark",
        "Bereft",
        "Shattered",
        "Broken",
        "Eviscerated",
        "Cacophonous",
        "Grimy",
        "Disturbing",
        "Shadowy",
        "War-torn",
        "Cataclysmic",
        "Waning",
        "Bane-filled",
        "Doomed",
        "Catastrophic",
        "Muted",
        "Festering",
        "Barren",
        "Fading",
        "Atrophied",
        "Diminished",
        "Eerie",
        "Discordant",
        "Tumultuous",
        "Raving",
        "Merciless",
        "Malefic",
        "Crumbling",
        "Haggard",
        "Pained",
        "Ravishing",
        "Venomous",
        "Withered",
        "Spiteful",
        "Obsidian",
        "Battered",
        "Appalling",
        "Unrelenting",
        "Bloodthirsty",
        "Sable",
        "Annihilated",
        "Drowning",
        "Sanguine",
        "Infernal",
        "Tortured",
        "Scarred",
        "Searing",
        "Horrifying",
        "Blackened",
        "Splintered",
        "Enervated",
        "Heinous",
        "Smoldering",
        "Pestilent",
        "Accursed",
        "Frenzied",
        "Decimating",
        "Fractured",
        "Toxic",
        "Pallid",
        "Despairing",
        "Despondent",
        "Relentless",
        "Wailing",
        "Traumatized",
        "Ravaging",
        "Twisted",
        "Seething",
        "Caustic",
        "Scorched",
        "Tattered",
        "Lecherous",
        "Vexed",
        "Void",
        "Wounded",
        "Befouled",
        "Stricken",
        "Degenerate",
        "Consumed",
        "Demonic",
        "Raging",
        "Vitiated",
        "Corrupted",
        "Hellish",
        "Purgatorial",
        "Defiled",
        "Repugnant",
        "Sacrilegious",
        "Blasted",
        "Bewitched",
        "Entropic",
        "Deteriorated",
        "Wrathful",
        "Plagued",
        "Waning",
        "Brooding",
        "Abject",
        "Disheveled",
        "Chilling",
        "Loathsome",
        "Maddened",
        "Melting",
        "Perishing",
        "Throttled",
        "Eclipsed",
        "Shriveling",
        "Maleficent"
    };

    /// <summary>
    /// Nouns to be used as names for a rundown
    /// </summary>
    static public string[] NounsRundown =
    {
        // Hole synonyms
        "Abyss",
        "Chasm",
        "Void",
        "Maw",
        "Underworld",
        "Cavern",
        "Labyrinth",
        "Catacomb",
        "Pitfall",
        "Gorge",
        "Hollow",
        "Subterrane",
        "Burrow",
        "Crevasse",
        "Gullet",
        "Tenebrous Tunnel",
        "Darkwell",
        "Fissure",
        "Undercrypt",
        "Oblivion",

        // Mission synonyms
        "Crusade",
        "Vendetta",
        "Ordeal",
        "Bloodquest",
        "Reckoning",
        "Purge",
        "Conquest",
        "Expurgation",
        "Vengeance",
        "Retribution",
        "Endeavor",
        "Extermination",
        "Annihilation",
        "Obliteration",
        "Decimation",
        "Dominion",
        "Insurrection",
        "Onslaught",
        "Sacrifice",
        "Inquisition",
        "Siege",
        "Desolation",
        "Persecution",
        "Incursion",
        "Culling",
        "Exorcism",
        "Enthronement",
        "Subjugation",
        "Redemption",
        "Ravage",
    };

    static public string[] Level_FirstWord =
    {
        "Abandon",
        "Abyss",
        "Affliction",
        "Aftermath",
        "Agony",
        "Altar",
        "Anguish",
        "Annihilation",
        "Anomaly",
        "Apocalypse",
        "Apparition",
        "Arcanum",
        "Ashes",
        "Ashfall",
        "Asylum",
        "Atrocity",
        "Bane",
        "Banish",
        "Banishment",
        "Banshee",
        "Barrow",
        "Bastion",
        "Behemoth",
        "Betrayal",
        "Blasphemy",
        "Blight",
        "Blood",
        "Bloodletting",
        "Bloodshed",
        "Bone",
        "Bones",
        "Burial",
        "Cadaver",
        "Canker",
        "Carrion",
        "Cataclysm",
        "Catacomb",
        "Cauldron",
        "Charnel",
        "Chasm",
        "Chill",
        "Choke",
        "Claw",
        "Cold",
        "Collapse",
        "Confinement",
        "Conjuration",
        "Consequence",
        "Contagion",
        "Corpse",
        "Corruption",
        "Crimson",
        "Crucible",
        "Crypt",
        "Cryptic",
        "Curse",
        "Cursed",
        "Damnation",
        "Darkfall",
        "Darkness",
        "Dead",
        "Death",
        "Deathless",
        "Decay",
        "Deception",
        "Decrepit",
        "Defiance",
        "Defilement",
        "Delirium",
        "Deliverance",
        "Dementia",
        "Derelict",
        "Desolate",
        "Desolation",
        "Despair",
        "Detritus",
        "Devastation",
        "Dire",
        "Dirge",
        "Disaster",
        "Discord",
        "Disquiet",
        "Distress",
        "Doom",
        "Doomsday",
        "Dread",
        "Dreadnought",
        "Dregs",
        "Dusk",
        "Dust",
        "Echoes",
        "Eclipse",
        "Eldritch",
        "Ember",
        "Emptiness",
        "Endless",
        "Enigma",
        "Entombed",
        "Entropy",
        "Erosion",
        "Eternal",
        "Evocation",
        "Exile",
        "Exsanguination",
        "Extinction",
        "Faded",
        "Fallen",
        "Fallout",
        "Famine",
        "Famineborn",
        "Fear",
        "Feral",
        "Festering",
        "Fissure",
        "Flesh",
        "Forgotten",
        "Forsaken",
        "Forsaking",
        "Fracture",
        "Fragment",
        "Frenzy",
        "Fright",
        "Frost",
        "Frozen",
        "Gaol",
        "Ghast",
        "Ghost",
        "Ghoul",
        "Gloom",
        "Gore",
        "Grave",
        "Graven",
        "Grief",
        "Grim",
        "Groan",
        "Groundless",
        "Harbinger",
        "Haunted",
        "Havoc",
        "Hell",
        "Hellfire",
        "Hollow",
        "Horror",
        "Hostile",
        "Hostility",
        "Howl",
        "Husk",
        "Icebound",
        "Illusion",
        "Immolate",
        "Imprisoned",
        "Incantation",
        "Incursion",
        "Infection",
        "Infernal",
        "Inferno",
        "Insanity",
        "Isolation",
        "Isolationist",
        "Judgment",
        "Labour",
        "Labyrinth",
        "Laceration",
        "Lair",
        "Lament",
        "Languor",
        "Lash",
        "Leper",
        "Leviathan",
        "Lich",
        "Loathing",
        "Lost",
        "Lurk",
        "Lurking",
        "Malediction",
        "Malefic",
        "Malevolence",
        "Malevolent",
        "Malice",
        "Martyrdom",
        "Massacre",
        "Menace",
        "Mephitic",
        "Miasma",
        "Midnight",
        "Mire",
        "Misery",
        "Molder",
        "Monstrosity",
        "Moonless",
        "Morbid",
        "Mourn",
        "Mournful",
        "Murder",
        "Nameless",
        "Necrosis",
        "Necrotic",
        "Nemesis",
        "Night",
        "Nightmare",
        "Noose",
        "Null",
        "Oblivion",
        "Obscene",
        "Obscurity",
        "Occult",
        "Omen",
        "Ooze",
        "Oppression",
        "Pain",
        "Pale",
        "Pallor",
        "Pandemonium",
        "Paradox",
        "Paranoia",
        "Parasite",
        "Perdition",
        "Phantom",
        "Pit",
        "Plague",
        "Poison",
        "Portal",
        "Profane",
        "Purgatory",
        "Putrescence",
        "Pyre",
        "Quarantine",
        "Rage",
        "Rapture",
        "Ravine",
        "Reaper",
        "Relic",
        "Remnant",
        "Residue",
        "Restless",
        "Rot",
        "Rotting",
        "Ruin",
        "Sacrifice",
        "Sanctum",
        "Scorn",
        "Scourge",
        "Screams",
        "Seclusion",
        "Seethe",
        "Sepulcher",
        "Shade",
        "Shadows",
        "Shriek",
        "Shrine",
        "Silence",
        "Sinister",
        "Skeletal",
        "Skinless",
        "Skull",
        "Slaughter",
        "Sludge",
        "Smother",
        "Sorrow",
        "Soul",
        "Soulless",
        "Specter",
        "Spectral",
        "Spine",
        "Spiral",
        "Stain",
        "Stalker",
        "Starvation",
        "Stasis",
        "Stench",
        "Stillness",
        "Storm",
        "Strain",
        "Strife",
        "Subjugation",
        "Subterfuge",
        "Suffering",
        "Suppression",
        "Taint",
        "Terror",
        "Thirst",
        "Threnody",
        "Tomb",
        "Torment",
        "Torpid",
        "Torture",
        "Tragedy",
        "Treachery",
        "Tremor",
        "Trepidation",
        "Tribunal",
        "Trudge",
        "Tryst",
        "Twilight",
        "Unending",
        "Unholy",
        "Unrest",
        "Unyielding",
        "Vacancy",
        "Vampire",
        "Vengeance",
        "Venom",
        "Vermin",
        "Vesper",
        "Vigil",
        "Vile",
        "Viscera",
        "Void",
        "Vortex",
        "Wailing",
        "Wasteland",
        "Whisper",
        "Wicked",
        "Wither",
        "Woe",
        "Wound",
        "Wrath",
        "Wretched",
        "Zephyr"
    };

    static public string[] Level_LastWord =
    {
        "Abattoir",
        "Abyss",
        "Affliction",
        "Aftermath",
        "Alcove",
        "Anomaly",
        "Antechamber",
        "Apparition",
        "Archway",
        "Arena",
        "Artery",
        "Ascent",
        "Ashes",
        "Ashfall",
        "Asylum",
        "Balustrade",
        "Banishment",
        "Barrow",
        "Barrowfield",
        "Basement",
        "Bastille",
        "Bastion",
        "Beacon",
        "Bedlam",
        "Blackout",
        "Blight",
        "Bloodfall",
        "Bloodstone",
        "Bonefield",
        "Breakwater",
        "Breath",
        "Brink",
        "Burial",
        "Burrow",
        "Butchery",
        "Cascade",
        "Casket",
        "Cataclysm",
        "Cathedral",
        "Cauldron",
        "Cavern",
        "Cenotaph",
        "Chamber",
        "Charnel",
        "Chasm",
        "Citadel",
        "Cliff",
        "Collapse",
        "Colossus",
        "Columbarium",
        "Conclave",
        "Confinement",
        "Conflux",
        "Conundrum",
        "Convergence",
        "Corpsefield",
        "Corridor",
        "Corridorum",
        "Corrupter",
        "Coven",
        "Cradle",
        "Crematorium",
        "Crevasse",
        "Crown",
        "Crypt",
        "Cryptswell",
        "Curse",
        "Cycle",
        "Cyclone",
        "Cyst",
        "Damnation",
        "Darkness",
        "Darkwell",
        "Dawn",
        "Daybreak",
        "Deadlock",
        "Death",
        "Deathsong",
        "Decadence",
        "Deeps",
        "Defile",
        "Delirium",
        "Demise",
        "Depth",
        "Descent",
        "Desecration",
        "Despair",
        "Destiny",
        "Detritus",
        "Dichotomy",
        "Dirge",
        "Discord",
        "Disorder",
        "Dissolution",
        "Dominion",
        "Downfall",
        "Dread",
        "Dream",
        "Dreamscape",
        "Dregs",
        "Dungeon",
        "Dustfall",
        "Eclipse",
        "Eden",
        "Effigy",
        "Embrace",
        "Empire",
        "End",
        "Endtime",
        "Engram",
        "Entropy",
        "Epitaph",
        "Epoch",
        "Erosion",
        "Eternity",
        "Exile",
        "Expanse",
        "Extinction",
        "Fall",
        "Fallout",
        "Fane",
        "Fang",
        "Fate",
        "Fathom",
        "Feast",
        "Fen",
        "Feralground",
        "Finale",
        "Fissure",
        "Flood",
        "Flux",
        "Forfeit",
        "Forsaking",
        "Fragment",
        "Fray",
        "Frenzy",
        "Frozenreach",
        "Funeral",
        "Gallows",
        "Gaol",
        "Gate",
        "Genesis",
        "Ghast",
        "Gibbet",
        "Gloom",
        "Gloomspire",
        "Gorge",
        "Grave",
        "Grimoire",
        "Grip",
        "Ground",
        "Guillotine",
        "Halls",
        "Haunt",
        "Haven",
        "Heart",
        "Helix",
        "Hellmouth",
        "Hereticum",
        "Hold",
        "Hollow",
        "Horizon",
        "Horror",
        "Host",
        "Howl",
        "Hungering",
        "Husk",
        "Illusion",
        "Imbalance",
        "Immolation",
        "Immolator",
        "Imprisonment",
        "Incantation",
        "Incision",
        "Infection",
        "Inferno",
        "Infernum",
        "Inheritance",
        "Insanity",
        "Isolation",
        "Judgment",
        "Keep",
        "Knavery",
        "Knell",
        "Labyrinth",
        "Labyrinthine",
        "Lair",
        "Lament",
        "Lattice",
        "Legacy",
        "Leviathan",
        "Liturgy",
        "Loam",
        "Loathing",
        "Losthold",
        "Lull",
        "Lurch",
        "Machination",
        "Malady",
        "Malebolge",
        "Malediction",
        "Manifest",
        "Massacre",
        "Mausoleum",
        "Maw",
        "Maze",
        "Membrane",
        "Memory",
        "Midnight",
        "Mirage",
        "Mirestone",
        "Monastery",
        "Monolith",
        "Morass",
        "Morgue",
        "Mortuary",
        "Mosaic",
        "Mutation",
        "Mythos",
        "Nadir",
        "Nadiric Depths",
        "Narthex",
        "Necropolis",
        "Necrosis",
        "Nexus",
        "Nightfall",
        "Nightwell",
        "Nocturne",
        "Nomad",
        "Obeisance",
        "Obelisk",
        "Oblivion",
        "Obliviscence",
        "Obscurity",
        "Obstruction",
        "Occultation",
        "Offering",
        "Omen",
        "Oracle",
        "Orchard",
        "Origin",
        "Outpost",
        "Overhang",
        "Palace",
        "Paleground",
        "Pandemonium",
        "Paradigm",
        "Paradox",
        "Parish",
        "Passage",
        "Perdition",
        "Phantasm",
        "Phylactery",
        "Pit",
        "Plaguewell",
        "Plateau",
        "Plea",
        "Polycrypt",
        "Portal",
        "Prayer",
        "Prison",
        "Providence",
        "Purgatory",
        "Pyre",
        "Quagmire",
        "Quarry",
        "Quietus",
        "Rapture",
        "Ravinehold",
        "Realm",
        "Reckoning",
        "Relic",
        "Reliquary",
        "Remains",
        "Remnant",
        "Repose",
        "Requiem",
        "Residuum",
        "Rest",
        "Rift",
        "Rotunda",
        "Ruination",
        "Runestone",
        "Sacellum",
        "Sacrifice",
        "Sanatorium",
        "Sanctuary",
        "Sanctum",
        "Sanguine Hall",
        "Sarcophagus",
        "Scaffold",
        "Scourge",
        "Sepulcher",
        "Sepulchrum",
        "Shadowfall",
        "Shrine",
        "Shroud",
        "Silence",
        "Skerry",
        "Skullspire",
        "Slab",
        "Slaughterhouse",
        "Slough",
        "Sojourn",
        "Solstice",
        "Sorcery",
        "Spectacle",
        "Spindle",
        "Spire",
        "Sprawl",
        "Stain",
        "Stasis",
        "Steeple",
        "Stigma",
        "Stillness",
        "Stonefall",
        "Storm",
        "Stratum",
        "Stronghold",
        "Suffering",
        "Summit",
        "Supplication",
        "Tally",
        "Tangle",
        "Tenebris",
        "Terminus",
        "Threshold",
        "Throat",
        "Throne",
        "Thrum",
        "Tide",
        "Tomb",
        "Tor",
        "Torment",
        "Torpor",
        "Treason",
        "Trench",
        "Tribunal",
        "Trinity",
        "Triumph",
        "Trove",
        "Truce",
        "Tumulus",
        "Tundra",
        "Tyranny",
        "Undercroft",
        "Underscape",
        "Undertow",
        "Underworld",
        "Unhallowed",
        "Unmaking",
        "Uprising",
        "Vacancy",
        "Vale",
        "Valhalla",
        "Vanishing",
        "Vault",
        "Veil",
        "Vestige",
        "Vigil",
        "Viscera",
        "Voidreach",
        "Vortex",
        "Wane",
        "Ward",
        "Warren",
        "Wasteland",
        "Watch",
        "Well",
        "Whisper",
        "Withering",
        "Woe",
        "Womb",
        "Wound",
        "Wraith",
        "Wreck",
        "Yawning",
        "Zenith"
    };

    /// <summary>
    /// Nouns for Level names
    /// </summary>
    static public string[] NounsLevel =
    {
        "Aberration",
        "Abject Core",
        "Abyssal Rift",
        "Abyssal Trace",
        "Abyssborne",
        "Abyssroot",
        "Abyssthorn",
        "Aching Maw",
        "Ashen Reprieve",
        "Ashen Tremor",
        "Bane's Breach",
        "Bane's Descent",
        "Bitter Hollow",
        "Bleak Bastion",
        "Bleak Nexus",
        "Bleeding Verge",
        "Blight's Reach",
        "Blighted Reliquary",
        "Blightline",
        "Blightmargin",
        "Blightwound",
        "Blistering Maw",
        "Bloodvault",
        "Burden Spire",
        "Cadaver Coil",
        "Canker Maw",
        "Carrion Thread",
        "Carrion Vault",
        "Catacomb Depth",
        "Catacomb Verge",
        "Catastrophic Crevasse",
        "Cavern of Grief",
        "Charnel Root",
        "Charroot",
        "Chasm of Silence",
        "Chasm of Wane",
        "Choked Meridian",
        "Choked Passage",
        "Cindered Path",
        "Clotted Descent",
        "Coagulated Maw",
        "Coiled Expanse",
        "Collapsed Bastion",
        "Corroded Chambers",
        "Corrosion Maw",
        "Cradle of Night",
        "Cradle of Ruin",
        "Crimson Vow",
        "Crushed Dominion",
        "Crushed Shrine",
        "Crypt's Crux",
        "Cryptic Relic",
        "Cryptthread",
        "Cryptward Verge",
        "Cursed Gallery",
        "Cystfield",
        "Dark Nexus",
        "Deafened Hollow",
        "Decay's Hold",
        "Descent into Darkness",
        "Desecrated Hollows",
        "Desolate Divide",
        "Desolation Pulse",
        "Despair Cradle",
        "Despair's Domain",
        "Dire Fissure",
        "Disjoint Sanctum",
        "Dissolution",
        "Doom's Cradle",
        "Dread Core",
        "Dreadcoil",
        "Dreadnaught's Depth",
        "Drownspire",
        "Dusk's Demise",
        "Dusk's Grasp",
        "Echoing Breach",
        "Eclipsed Reality",
        "Eerie Expanse",
        "Elder Depth",
        "Elder Maw",
        "Eldritch Elevations",
        "Embalmed Depths",
        "Endless Chasm",
        "Endless Hunger",
        "Enigma Void",
        "Entombed Vestige",
        "Entropic Maw",
        "Entropy's Grasp",
        "Ephemeral Passage",
        "Eroded Memories",
        "Erosive Wane",
        "Ethereal Edge",
        "Exile Chasm",
        "Exsanguine Rise",
        "Fallen Dominion",
        "Fallen's Folly",
        "Fanged Passage",
        "Fathomless",
        "Festerpit",
        "Festerwatch",
        "Filthspire",
        "Fissure of Woe",
        "Fleshreach",
        "Fleshward Depth",
        "Fleshwell",
        "Forgotten Rise",
        "Forlorn Vault",
        "Forsaken Sanctuary",
        "Fracture's Toll",
        "Fractured Echo",
        "Fractured Maw",
        "Fungal Core",
        "Fungal Spasm",
        "Gasping Veil",
        "Ghastly Gorge",
        "Glare Cradle",
        "Gloam Gate",
        "Gloamwound",
        "Gloom's Gulch",
        "Gloom's Heart",
        "Glutted Passage",
        "Gluttonous Divide",
        "Gnashed Hollows",
        "Gnashing Depths",
        "Goreloom",
        "Gorethrottle",
        "Gorevault",
        "Grave's Whisper",
        "Graveclot",
        "Gravegut",
        "Graven Refuge",
        "Graveyard Grotto",
        "Grief Spiral",
        "Grim Ascent",
        "Grim Gallery",
        "Grimwake Verge",
        "Grimwatch",
        "Harbinger's Hold",
        "Haunt's Halls",
        "Haunting Expanse",
        "Hell's Hinge",
        "Hollow March",
        "Hollow's Heart",
        "Hollowcoil",
        "Hollowfang",
        "Hollowflare",
        "Howling Rapture",
        "Husk Spiral",
        "Infected Gate",
        "Infernal Interstice",
        "Infernal Passage",
        "Inferno's Mouth",
        "Infested Channel",
        "Isolation",
        "Jagged Jaws",
        "Kiln of Khaos",
        "Lament's Landing",
        "Lichspire",
        "Lost Purgatory",
        "Lost Reverie",
        "Lurid Hollow",
        "Lurk's Labyrinth",
        "Lurker's Domain",
        "Lurking Trace",
        "Maddened Root",
        "Malevolence",
        "Malice Threshold",
        "Malignant Nexus",
        "Maw's Murmur",
        "Mawdrip",
        "Mire",
        "Mireveil",
        "Mist's Murk",
        "Molten Hollow",
        "Molten Verge",
        "Morbid Vestibule",
        "Mortal Coil",
        "Mourning Depths",
        "Mourning Mire",
        "Mycelial Dread",
        "Nameless Depth",
        "Necrotic Funnel",
        "Necrotic Niche",
        "Nesting Hollow",
        "Nether Nest",
        "Netherbound",
        "Nightbane Vault",
        "Nocturnal Hollow",
        "Nox Womb",
        "Obliterate",
        "Oblivion Runnel",
        "Oblivion's Overture",
        "Obsidian Oubliette",
        "Obsidian Spire",
        "Ossified Depths",
        "Ossuary Gate",
        "Pale Nest",
        "Pale Requiem",
        "Parasite Verge",
        "Perdition's Pits",
        "Perished Echelon",
        "Petrified Path",
        "Phantom's Phalanx",
        "Plaguebend",
        "Plaguerot",
        "Pulse of Dread",
        "Putrefied Vale",
        "Putrid Hollow",
        "Quarry of Quietude",
        "Ragged Coil",
        "Ragged Maw",
        "Ravaged Resonance",
        "Reddened Tomb",
        "Retch Spiral",
        "Revenant Cradle",
        "Riven Realm",
        "Riven Tomb",
        "Rotheart",
        "Ruination",
        "Ruinspire",
        "Ruinworn",
        "Ruptured Axis",
        "Ruptured Hollow",
        "Sable Depths",
        "Sable Embrace",
        "Sable Sorrow",
        "Sallow Crawl",
        "Scalded Verge",
        "Searpath",
        "Seething Nest",
        "Sepulchral Coil",
        "Severed Reach",
        "Shadow's Descent",
        "Shadow's Embrace",
        "Shadow's Shroud",
        "Shattered Egress",
        "Shattered Scar",
        "Shivering Tomb",
        "Shrouded Bastille",
        "Sickroot Depth",
        "Silent Cyst",
        "Silent Reprise",
        "Silent Sunder",
        "Smoldering Hollow",
        "Sootgorge",
        "Sootroot",
        "Sorrow Husk",
        "Sorrow's Enclave",
        "Soul Vein",
        "Spectral Divide",
        "Spectral Spire",
        "Spinal Hollows",
        "Spite Gorge",
        "Splinter Maw",
        "Splintered Sepulchre",
        "Splinterrift",
        "Stifled Realm",
        "Stygian Abyss",
        "Sulfur Oubliette",
        "Sunken Conduit",
        "Sunken Omen",
        "Sunless Embrace",
        "Suppurating Rift",
        "Tainted Grasp",
        "Tarn Veil",
        "Tattered Maw",
        "Tenebral Scar",
        "Tenebrous Labyrinth",
        "Tetherclot",
        "Tethered Echo",
        "Tethered Void",
        "Thirsting Crypt",
        "Thorned Grasp",
        "Thornhusk",
        "Tomb of Guilt",
        "Torment's Lair",
        "Torpid Grasp",
        "Torrid Tunnels",
        "Trembling Hollows",
        "Turbid Trench",
        "Twilight Husk",
        "Twilight Tomb",
        "Twilight Verge",
        "Twisted Sump",
        "Twisted Terrain",
        "Umbral Stretch",
        "Umbral Underbelly",
        "Unbound Grief",
        "Unraveling Umbras",
        "Veil of Despair",
        "Vein of Woe",
        "Vex Hollow",
        "Vexed Vistas",
        "Vice's Grasp",
        "Viscera Sprawl",
        "Void's Verge",
        "Void's Vestige",
        "Voidgorge",
        "Voidgrasp",
        "Voidwalk",
        "Vortex of Silence",
        "Wailing Rift",
        "Wailing Span",
        "Wane",
        "Waning Channel",
        "Waning Rites",
        "Weeping Core",
        "Weeping Divide",
        "Whisper's Wane",
        "Wither's Way",
        "Witherflesh",
        "Wraith's Wake",
        "Wraithcoil",
        "Wraithcrack",
        "Wretchcoil",
        "Wretched Grotto",
        "Wretchrift",
        "Xenolith Expanse",
        "Yawning Yoke",
        "Zenith of Zero",
    };

    /// <summary>
    /// Present participle verbs of failure
    /// </summary>
    static public string[] VerbsPresentParticiple =
    {
        "Atrophying",
        "Bleeding",
        "Breaking",
        "Caving",
        "Collapsing",
        "Corroding",
        "Crumbling",
        "Decaying",
        "Declining",
        "Degenerating",
        "Depleting",
        "Despairing",
        "Deteriorating",
        "Diminishing",
        "Disintegrating",
        "Dissipating",
        "Dissolving",
        "Draining",
        "Drowning",
        "Eroding",
        "Fading",
        "Fading",
        "Floundering",
        "Fraying",
        "Fumbling",
        "Languishing",
        "Moldering",
        "Perishing",
        "Ravaging",
        "Regressing",
        "Sinking",
        "Slipping",
        "Struggling",
        "Succumbing",
        "Suffering",
        "Wasting",
        "Weakening",
        "Wilting",
        "Withering",
        "Wrecking"
    };

    /// <summary>
    /// GTFO enemy names
    /// </summary>
    static public string[] GtfoEnemies =
    {
        "Striker",
        "Shooter",
        "Charger",
        "Shadow",
        "Giant Striker",
        "Giant Shooter",
        "Giant Charger",
        "Shadow Giant",
        "Hybrid",
        "Scout",
        "Charger Scout",
        "Shadow Scout",
        "Tank",
        "Immortal",
        "Mother",
        "P-Mother",
    };

    /// <summary>
    /// Words used for human readable seed strings
    /// </summary>
    static public string[] SeedWords =
    {
        "apple",
        "banana",
        "cherry",
        "dog",
        "cat",
        "bird",
        "fish",
        "house",
        "chair",
        "table",
        "book",
        "pen",
        "hat",
        "car",
        "bus",
        "shoe",
        "sock",
        "bag",
        "tree",
        "sun",
        "moon",
        "star",
        "water",
        "river",
        "lake",
        "ocean",
        "beach",
        "sand",
        "wind",
        "rain",
        "snow",
        "cloud",
        "storm",
        "grass",
        "leaf",
        "flower",
        "rose",
        "tulip",
        "daisy",
        "lily",
        "bird",
        "eagle",
        "hawk",
        "dove",
        "raven",
        "paper",
        "pencil",
        "eraser",
        "ruler",
        "desk",
        "phone",
        "clock",
        "watch",
        "lamp",
        "light",
        "music",
        "song",
        "dance",
        "play",
        "game",
        "ball",
        "bat",
        "glove",
        "goal",
        "run",
        "walk",
        "sit",
        "stand",
        "jump",
        "dance",
        "sing",
        "laugh",
        "cry",
        "smile",
        "frown",
        "speak",
        "listen",
        "read",
        "write",
        "draw",
        "paint",
        "color",
        "print",
        "ship",
        "boat",
        "plane",
        "train",
        "car",
        "bus",
        "bike",
        "bell",
        "ring",
        "gift",
        "card",
        "party",
        "cake",
        "pie",
        "ice",
        "cream",
        "sugar",
        "salt",
        "spice",
        "bread",
        "meat",
        "egg",
        "milk",
        "cheese",
        "pasta",
        "rice",
        "soup",
        "salad",
        "fruit",
        "grape",
        "orange",
        "lemon",
        "lime",
        "melon",
        "berry",
        "nut",
        "date",
        "honey",
        "butter",
        "jam",
        "jelly",
        "candy",
        "choco",
        "cookie",
        "muffin",
        "donut",
        "coffee",
        "tea",
        "juice",
        "soda",
        "water",
        "beer",
        "wine",
        "drink",
        "glass",
        "plate",
        "bowl",
        "spoon",
        "fork",
        "knife",
        "napkin",
        "towel",
        "sheet",
        "blanket",
        "pillow",
        "bed",
        "sofa",
        "chair",
        "bench",
        "floor",
        "wall",
        "door",
        "window",
        "roof",
        "chimney",
        "fence",
        "yard",
        "garden",
        "field",
        "farm",
        "barn",
        "stable",
        "horse",
        "cow",
        "pig",
        "sheep",
        "goat",
        "chicken",
        "turkey",
        "duck",
        "pond",
        "pool",
        "park",
        "zoo",
        "forest",
        "hill",
        "mountain",
        "valley",
        "desert",
        "island",
        "beach",
        "wave",
        "tide",
        "coral",
        "fish",
        "whale",
        "shark",
        "dolphin",
        "seal",
        "crab",
        "lobster",
        "squid",
        "octopus",
        "snail",
        "turtle",
        "lizard",
        "snake",
        "frog",
        "spider",
        "ant",
        "bee",
        "bug",
        "fly",
        "worm",
        "rat",
        "mouse",
        "rabbit",
        "bear",
        "tiger",
        "lion",
        "leopard",
        "panther",
        "wolf",
        "fox",
        "deer",
        "moose",
        "elk",
        "beaver",
        "otter",
        "raccoon",
        "skunk",
        "bat",
        "owl",
        "city",
        "town",
        "village",
        "road",
        "street",
        "alley",
        "avenue",
        "highway",
        "bridge",
        "tunnel",
        "port",
        "harbor",
        "station",
        "hotel",
        "motel",
        "inn",
        "bank",
        "market",
        "mall",
        "store",
        "shop",
        "office",
        "factory",
        "school",
        "church",
        "temple",
        "mosque",
        "museum",
        "library",
        "zoo",
        "park",
        "garden",
        "circus",
        "theater",
        "cinema",
        "cafe",
        "bar",
        "club",
        "gym",
        "spa",
        "salon",
        "hospital",
        "clinic",
        "prison",
        "police",
        "army",
        "navy",
        "air",
        "fire",
        "metal",
        "wood",
        "cloth",
        "silk",
        "wool",
        "cotton",
        "paper",
        "stone",
        "rock",
        "brick",
        "clay",
        "glass",
        "gold",
        "silver",
        "bronze",
        "steel",
        "iron",
        "copper",
        "lead",
        "tin",
        "zinc",
        "nickel",
        "chrome",
        "plastic",
        "rubber",
        "leather",
        "fur",
        "feather",
        "wool",
        "rope",
        "wire",
        "chain",
        "nail",
        "screw",
        "bolt",
        "nut",
        "wheel",
        "tire",
        "pedal",
        "gear",
        "brake",
        "seat",
        "belt",
        "hat",
        "cap",
        "helmet",
        "scarf",
        "glove",
        "sock",
        "shoe",
        "boot",
        "sandal",
        "shirt",
        "blouse",
        "dress",
        "skirt",
        "pants",
        "jeans",
        "suit",
        "tie",
        "jacket",
        "coat",
        "sweater",
        "vest",
        "cape",
        "robe",
        "pajama",
        "underwear",
        "bra",
        "panty",
        "diaper",
        "purse",
        "wallet",
        "bag",
        "suitcase",
        "box",
        "can",
        "jar",
        "bottle",
        "jug",
        "cup",
        "mug",
        "plate",
        "bowl",
        "spoon",
        "fork",
        "knife",
        "chopstick",
        "pin",
        "needle",
        "thread",
        "button",
        "zipper",
        "scissors",
        "razor",
        "comb",
        "brush",
        "mirror",
        "towel",
        "soap",
        "shampoo",
        "lotion",
        "perfume",
        "makeup",
        "lipstick",
        "eyeshadow",
        "mascara",
        "nailpolish",
        "ring",
        "earring",
        "necklace",
        "bracelet",
        "watch",
        "clock",
        "radio",
        "phone",
        "camera",
        "computer",
        "printer",
        "scanner",
        "TV",
        "DVD",
        "CD",
        "disk",
        "tape",
        "book",
        "magazine",
        "newspaper",
        "letter",
        "card",
        "envelope",
        "stamp",
        "pen",
        "pencil",
        "marker",
        "crayon",
        "paint",
        "brush",
        "easel",
        "canvas",
        "paper",
        "notebook",
        "binder",
        "folder",
        "file",
        "clip",
        "staple",
        "glue",
        "tape",
        "ruler",
        "calculator",
        "lamp",
        "bulb",
        "plug",
        "wire",
        "battery",
        "charger",
        "remote",
        "headset",
        "speaker",
        "microphone",
        "keyboard",
        "mouse",
        "screen",
        "monitor",
        "drive",
        "router",
        "modem",
        "antenna",
        "satellite",
        "rocket",
        "plane",
        "helicopter",
        "drone",
        "ship",
        "boat",
        "car",
        "truck",
        "bus",
        "train",
        "tram",
        "bike",
        "scooter",
        "skateboard",
        "rollerblade",
        "sled",
        "ski",
        "surfboard",
        "parachute",
        "tent",
        "sleepingbag",
        "backpack",
        "flashlight",
        "lantern",
        "match",
        "lighter",
        "stove",
        "oven",
        "microwave",
        "refrigerator",
        "freezer",
        "dishwasher",
        "washingmachine",
        "dryer",
        "vacuum",
        "broom",
        "mop",
        "bucket",
        "bin",
        "trash",
        "recycle",
        "leaf",
        "grass",
        "flower",
        "tree",
        "bush",
        "vine",
        "mushroom",
        "fruit",
        "vegetable",
        "grain",
        "bean",
        "nut",
        "meat",
        "poultry",
        "fish",
        "seafood",
        "dairy",
        "egg",
        "cheese",
        "butter",
        "oil",
        "sugar",
        "salt",
        "spice",
        "tea",
        "coffee",
        "cocoa",
        "water",
        "juice",
        "soda",
        "wine",
        "beer",
        "liquor",
        "cocktail",
        "soup",
        "salad",
        "sandwich",
        "pizza",
        "pasta",
        "rice",
        "bread",
        "cake",
        "pie",
        "cookie",
        "candy",
        "icecream",
        "jelly",
        "jam",
        "honey",
        "syrup",
        "vinegar",
        "sauce",
        "ketchup",
        "mustard",
        "mayo",
        "pepper",
        "chili",
        "garlic",
        "onion",
        "potato",
        "carrot",
        "bean",
        "pea",
        "corn",
        "cucumber",
        "lettuce",
        "tomato",
        "pepper",
        "broccoli",
        "spinach",
        "mushroom",
        "olive",
        "pickle",
        "apple",
        "banana",
        "orange",
        "berry",
        "grape",
        "lemon",
        "lime",
        "melon",
        "mango",
        "papaya",
        "pineapple",
        "coconut",
        "cherry",
        "plum",
        "peach",
        "apricot",
        "nut",
        "almond",
        "peanut",
        "walnut",
        "chestnut",
        "hazelnut",
        "meat",
        "pork",
        "beef",
        "lamb",
        "chicken",
        "turkey",
        "duck",
        "fish",
        "salmon",
        "tuna",
        "shrimp",
        "crab",
        "lobster",
        "oyster",
        "clam",
        "mussel",
        "squid",
        "octopus",
        "egg",
        "milk",
        "cheese",
        "yogurt",
        "butter",
        "cream",
        "icecream",
        "chocolate",
        "candy",
        "cookie",
        "cake",
        "pie",
        "muffin",
        "donut",
        "bread",
        "toast",
        "bagel",
        "roll",
        "croissant",
        "pancake",
        "waffle",
        "cereal",
        "oatmeal",
        "rice",
        "pasta",
        "noodle",
        "sushi",
        "pizza",
        "burger",
        "hotdog",
        "sandwich",
        "wrap",
        "taco",
        "burrito",
        "salad",
        "soup",
        "stew",
        "chili",
        "curry",
        "sauce",
        "gravy",
        "dressing",
        "ketchup",
        "mustard",
        "mayo",
        "relish",
        "pickles",
        "olives",
        "jam",
        "jelly",
        "honey",
        "syrup",
        "butter",
        "oil",
        "vinegar",
        "salt",
        "pepper",
        "spice",
        "herb",
        "garlic",
        "onion",
        "tomato",
        "potato",
        "carrot",
        "celery",
        "lettuce",
        "cabbage",
        "spinach",
        "broccoli",
        "pepper",
        "bean",
        "pea",
        "corn",
        "cucumber",
        "zucchini",
        "squash",
        "pumpkin",
        "eggplant",
        "mushroom",
        "olive",
        "apple",
        "banana",
        "orange",
        "berry",
        "grape",
        "lemon",
        "lime",
        "melon",
        "mango",
        "papaya",
        "pineapple",
        "coconut",
        "cherry",
        "plum",
        "peach",
        "apricot",
        "berry",
        "kiwi",
        "date",
        "fig",
        "raisin",
        "nut",
        "almond",
        "peanut",
        "walnut",
        "chestnut",
        "hazelnut",
        "cashew",
        "pecan",
        "macadamia",
        "meat",
        "pork",
        "beef",
        "lamb",
        "chicken",
        "turkey",
        "duck",
        "fish",
        "salmon",
        "tuna",
        "shrimp",
        "crab",
        "lobster",
        "oyster",
        "clam",
        "mussel",
        "squid",
        "octopus",
        "caviar",
        "egg",
        "milk",
        "cheese",
        "yogurt",
        "butter",
        "cream",
        "icecream",
        "chocolate",
        "candy",
        "cookie",
        "cake",
        "pie",
        "muffin",
        "donut",
        "bread",
        "toast",
        "bagel",
        "roll",
        "croissant",
        "pancake",
        "waffle",
        "cereal",
        "oatmeal",
        "rice",
        "pasta",
        "noodle",
        "sushi",
        "pizza",
        "burger",
        "hotdog",
        "sandwich",
        "wrap",
        "taco",
        "burrito",
        "salad",
        "soup",
        "stew",
        "chili",
        "curry",
        "sauce",
        "gravy",
        "dressing",
        "ketchup",
        "mustard",
        "mayo",
        "relish",
        "pickles",
        "olives",
        "jam",
        "jelly",
        "honey",
        "syrup",
        "butter",
        "oil",
        "vinegar",
        "salt",
        "pepper",
        "spice",
        "herb",
        "garlic",
        "onion",
        "tomato",
        "potato",
        "carrot",
        "celery",
        "lettuce",
        "cabbage",
        "spinach",
        "broccoli",
        "pepper",
        "bean",
        "pea",
        "corn",
        "cucumber",
        "zucchini",
        "squash",
        "pumpkin",
        "eggplant",
        "mushroom",
        "olive",
        "apple",
        "banana",
        "orange",
        "berry",
        "grape",
        "lemon",
        "lime",
        "melon",
        "mango",
        "papaya",
        "pineapple",
        "coconut",
        "cherry",
        "plum",
        "peach",
        "apricot",
        "berry",
        "kiwi",
        "date",
        "fig",
        "raisin",
        "nut",
        "almond",
        "peanut",
        "walnut",
        "chestnut",
        "hazelnut",
        "cashew",
        "pecan",
        "macadamia",
        "meat",
        "pork",
        "beef",
        "lamb",
        "chicken",
        "turkey",
        "duck",
        "fish",
        "salmon",
        "tuna",
        "shrimp",
        "crab",
        "lobster",
        "oyster",
        "clam",
        "mussel",
        "squid",
        "octopus",
        "caviar",
        "egg",
        "milk",
        "cheese",
        "yogurt",
        "butter",
        "cream",
        "icecream",
        "chocolate",
        "candy",
        "cookie",
        "cake",
        "pie",
        "muffin",
        "donut",
        "bread",
        "toast",
        "bagel",
        "roll",
        "croissant",
        "pancake",
        "waffle",
        "cereal",
        "oatmeal",
        "rice",
        "pasta",
        "noodle",
        "sushi",
        "pizza",
        "burger",
        "hotdog",
        "sandwich",
        "wrap",
        "taco",
        "burrito",
        "salad",
        "soup",
        "stew",
        "chili",
        "curry",
        "sauce",
        "gravy",
        "dressing",
        "ketchup",
        "mustard",
        "mayo",
        "relish",
        "pickles",
        "olives",
        "jam",
        "jelly",
        "honey",
        "syrup",
        "butter",
        "oil",
        "vinegar",
        "salt",
        "pepper",
        "spice",
        "herb",
        "garlic",
        "onion",
        "tomato",
        "potato",
        "carrot",
        "celery",
        "lettuce",
        "cabbage",
        "spinach",
        "broccoli",
        "pepper",
        "bean",
        "pea",
        "corn",
        "cucumber",
        "zucchini",
        "squash",
        "pumpkin",
        "eggplant",
        "mushroom",
        "olive",
        "apple",
        "banana",
        "orange",
        "berry",
        "grape",
        "lemon",
        "lime",
        "melon",
        "mango",
        "papaya",
        "pineapple",
        "coconut",
        "cherry",
        "plum",
        "peach",
        "apricot",
        "berry",
        "kiwi",
        "date",
        "fig",
        "raisin",
        "nut",
        "almond",
        "peanut",
        "walnut",
        "chestnut",
        "hazelnut",
        "cashew",
        "pecan",
        "macadamia",
        "meat",
        "pork",
        "beef",
        "lamb",
        "chicken",
        "turkey",
        "duck",
        "fish",
        "salmon",
        "tuna",
        "shrimp",
        "crab",
        "lobster",
        "oyster",
        "clam",
        "mussel",
        "squid",
        "octopus",
        "caviar",
        "egg",
        "milk",
        "cheese",
        "yogurt",
        "butter",
        "cream",
        "icecream",
        "chocolate",
        "candy",
        "cookie",
        "cake",
        "pie",
        "muffin",
        "donut"
    };
}
