namespace AutogenRundown.GeneratorData;

static public class Words
{
    /// <summary>
    /// Creates a list of names to pull from
    /// </summary>
    /// <returns></returns>
    static public List<string> NewLevelNamesPack()
    {
        var predefinedNames = new List<string>(NounsLevel);
        var first = new List<string>(Level_FirstWord);
        var last = new List<string>(Level_LastWord);

        var adjective = new List<string>(Adjectives);
        var verb = new List<string>(VerbsPresentParticiple);

        var list = new List<string>();

        for (var i = 0; i < 30; i++)
        {
            // Add a predefined name that we have fully generated
            if (Generator.Flip(0.30))
            {
                var name = Generator.Draw(predefinedNames)!;

                list.Add(name);
                continue;
            }

            // Create a new name
            var firstWord = Generator.Draw(
                Generator.Select(new List<(double, List<string>)>
                {
                    (0.1, verb),
                    (0.2, adjective),
                    (0.7, first),
                }));
            var lastWord = Generator.Draw(last);

            list.Add($"{firstWord} {lastWord}");
        }

        return list;
    }

    public static string RundownNameMonthly()
    {
        var noun = Generator.MonthNumber switch
        {
            // January
            1 => Generator.Pick(new List<string>
            {
                "Bleakburrow", "Mooncrypt", "Obsidian Grotto", "Chillmarrow", "Dampvault", "Umbral Cage",
                "Nightfissure", "Wraithclot", "Pale Labyrinth", "Blackmarsh"
            }),
            // February
            2 => Generator.Pick(new List<string>
            {
                "Depthshroud", "Fallowchasm", "Ravencrypt", "Silent Hollow", "Marrowfane", "Crowvault",
                "Lurid Veil", "Creviceborn", "Dire Maw", "Sunken Gloom"
            }),
            // March
            3 => Generator.Pick(new List<string>
            {
                "Sourgrove", "Waning Crypt", "Fetid Mine", "Gravewhisper", "Underrot", // "Stagnant Grotto",
                "Mireclaw", "Stillroot", "Gloomchoke", "Weeping Den"
            }),
            // April
            4 => Generator.Pick(new List<string>
            {
                "Fogshard", "Drearnest", "Rotwood", "Witherspine", "Sporefen", "Tanglechasm", "Musty Hollow",
                "Duskreef", "Faint Maze", "Subtlecrag"
            }),
            // May
            5 => Generator.Pick(new List<string>
            {
                "Fetid Thicket", "Wormblight", "Ashen Vault", "Goreburrow", "Briarcrypt", "Umbraspore",
                "Gullychill", "Soulchoke", "Darkfen", "Verdant Rot"
            }),
            // June
            6 => Generator.Pick(new List<string>
            {
                "Cinderdeep", /*"Charfall", "Blightbarrow", "Grimwarren", "Gorecliff", "Dusthusk",
                "Marrow Reach", "Wraith Fane", "Hollow Thorn"*/
                // "Molded Pit",
            }),
            // July
            7 => Generator.Pick(new List<string>
            {
                "Bonechoke", "Rotcairn", "Dreggrotto", "Wraithknell", "Palechasm", "Dustwraith", "Husked Vale",
                "Bleakcyst", "Sunless Maw", "Murkspan"
            }),
            // August
            8 => Generator.Pick(new List<string>
            {
                "Gorechoke", "Hollowrift", "Lurid Pit", "Cavernfrost", "Wormclot", "Faintcrawl", "Midnight Grotto",
                "Wraithscar", "Ember Hollow", "Sour Vault"
            }),
            // September
            9 => Generator.Pick(new List<string>
            {
                "Underclaw", "Duskmarsh", "Cindercrypt", "Fallow Maw", "Grimspire", "Dregfen", "Shadowchoke",
                "Hazecrypt", "Briarchasm", "Twilight Burrow"
            }),
            // October
            10 => Generator.Pick(new List<string>
            {
                "Wraithgrove", "Hollowthorn", "Ragged Depths", "Twilight Rift", "Musty Chasm", "Blackburrow",
                "Rotspire", "Moonfen", "Nightflare", "Molderclaw"
            }),
            // November
            11 => Generator.Pick(new List<string>
            {
                "Frostwhisper", "Eboncrypt", "Shadowfen", "Dimthorn", "Quiet Grotto", "Waning Hollow", "Bleak Haze",
                "Underfissure", "Grey Rot", "Stygian Vault"
            }),
            // December
            12 => Generator.Pick(new List<string>
            {
                "Night Shiver", "Bone Whisper", "Gloom Fane", "Cinderhusk", "Riftgloom", "Soul Hollow",
                "Midnightfen", "Plague Claw", "Umbral Crypt", "Bleakharrow"
            }),
            _ => "Schaeffer's Bane"
        };

        return noun ?? string.Empty;
    }

    /// <summary>
    /// 200 grim dark adjectives
    /// </summary>
    static public string[] Adjectives =
    {
        "Bleak",
        "Ruthless",
        "Morbid",
        "Desolate",
        "Brutal",
        "Malignant",
        "Forsaken",
        "Grotesque",
        "Dystopian",
        "Hollow",
        "Gruesome",
        "Harrowing",
        "Malevolent",
        "Oppressive",
        "Visceral",
        "Mutilated",
        "Cursed",
        "Macabre",
        "Noxious",
        "Tormented",
        "Ominous",
        "Rancid",
        "Suffering",
        "Wretched",
        "Sinister",
        "Melancholic",
        "Feral",
        "Mournful",
        "Pernicious",
        "Bleeding",
        "Carnal",
        "Decayed",
        "Malformed",
        "Savage",
        "Ravaged",
        "Corroded",
        "Vile",
        "Tainted",
        "Blighted",
        "Fetid",
        "Grim",
        "Unholy",
        "Nefarious",
        "Blasphemous",
        "Abominable",
        "Haunting",
        "Deathly",
        "Charnel",
        "Abyssal",
        "Ghastly",
        "Insidious",
        "Foreboding",
        "Eroded",
        "Lamentable",
        "Sepulchral",
        "Dismal",
        "Rotten",
        "Drab",
        "Infested",
        "Profane",
        "Grisly",
        "Terrifying",
        "Desecrated",
        "Dire",
        "Maddening",
        "Gory",
        "Searing",
        "Putrid",
        "Cadaverous",
        "Gaunt",
        "Soulless",
        "Ashen",
        "Deranged",
        "Murky",
        "Sullied",
        "Decrepit",
        "Ruinous",
        "Morose",
        "Piteous",
        "Calamitous",
        "Lurid",
        "Bleached",
        "Tenebrous",
        "Anguished",
        "Ravenous",
        "Unsettling",
        "Marred",
        "Disquieting",
        "Dreadful",
        "Malign",
        "Stifling",
        "Pervasive",
        "Gloom-ridden",
        "Stark",
        "Bereft",
        "Shattered",
        "Broken",
        "Eviscerated",
        "Cacophonous",
        "Grimy",
        "Disturbing",
        "Shadowy",
        "War-torn",
        "Cataclysmic",
        "Waning",
        "Bane-filled",
        "Doomed",
        "Catastrophic",
        "Muted",
        "Festering",
        "Barren",
        "Fading",
        "Atrophied",
        "Diminished",
        "Eerie",
        "Discordant",
        "Tumultuous",
        "Raving",
        "Merciless",
        "Malefic",
        "Crumbling",
        "Haggard",
        "Pained",
        "Ravishing",
        "Venomous",
        "Withered",
        "Spiteful",
        "Obsidian",
        "Battered",
        "Appalling",
        "Unrelenting",
        "Bloodthirsty",
        "Sable",
        "Annihilated",
        "Drowning",
        "Sanguine",
        "Infernal",
        "Tortured",
        "Scarred",
        "Searing",
        "Horrifying",
        "Blackened",
        "Splintered",
        "Enervated",
        "Heinous",
        "Smoldering",
        "Pestilent",
        "Accursed",
        "Frenzied",
        "Decimating",
        "Fractured",
        "Toxic",
        "Pallid",
        "Despairing",
        "Despondent",
        "Relentless",
        "Wailing",
        "Traumatized",
        "Ravaging",
        "Twisted",
        "Seething",
        "Caustic",
        "Scorched",
        "Tattered",
        "Lecherous",
        "Vexed",
        "Void",
        "Wounded",
        "Befouled",
        "Stricken",
        "Degenerate",
        "Consumed",
        "Demonic",
        "Raging",
        "Vitiated",
        "Corrupted",
        "Hellish",
        "Purgatorial",
        "Defiled",
        "Repugnant",
        "Sacrilegious",
        "Blasted",
        "Bewitched",
        "Entropic",
        "Deteriorated",
        "Wrathful",
        "Plagued",
        "Waning",
        "Brooding",
        "Abject",
        "Disheveled",
        "Chilling",
        "Loathsome",
        "Maddened",
        "Melting",
        "Perishing",
        "Throttled",
        "Eclipsed",
        "Shriveling",
        "Maleficent"
    };

    /// <summary>
    /// Nouns to be used as names for a rundown
    /// </summary>
    static public string[] NounsRundown =
    {
        // Hole synonyms
        "Abyss",
        "Chasm",
        "Void",
        "Maw",
        "Underworld",
        "Cavern",
        "Labyrinth",
        "Catacomb",
        "Pitfall",
        "Gorge",
        "Hollow",
        "Subterrane",
        "Burrow",
        "Crevasse",
        "Gullet",
        "Tenebrous Tunnel",
        "Darkwell",
        "Fissure",
        "Undercrypt",
        "Oblivion",

        // Mission synonyms
        "Crusade",
        "Vendetta",
        "Ordeal",
        "Bloodquest",
        "Reckoning",
        "Purge",
        "Conquest",
        "Expurgation",
        "Vengeance",
        "Retribution",
        "Endeavor",
        "Extermination",
        "Annihilation",
        "Obliteration",
        "Decimation",
        "Dominion",
        "Insurrection",
        "Onslaught",
        "Sacrifice",
        "Inquisition",
        "Siege",
        "Desolation",
        "Persecution",
        "Incursion",
        "Culling",
        "Exorcism",
        "Enthronement",
        "Subjugation",
        "Redemption",
        "Ravage",
    };

    static public string[] Level_FirstWord =
    {
        "Abandon",
        "Abhorrent",
        "Abject",
        "Ablation",
        "Ablaze",
        "Abnormal",
        "Abscess",
        "Absent",
        "Absorb",
        "Abstain",
        "Abysm",
        "Abyss",
        "Accrete",
        "Acerbic",
        "Ache",
        "Acid",
        "Acidic",
        "Acrid",
        "Afflict",
        "Affliction",
        "Aftermath",
        "Aghast",
        "Agitate",
        "Agony",
        "Agrieve",
        "Ailing",
        "Airless",
        "Airtight",
        "Alarm",
        "Algid",
        "Alien",
        "Alkaline",
        "Altar",
        "Amass",
        "Ambush",
        "Amnesia",
        "Ample",
        "Amputate",
        "Anathema",
        "Anchor",
        "Anemic",
        "Anguish",
        "Annihilation",
        "Anoint",
        "Anomalous",
        "Anomaly",
        "Anoxic",
        "Apnea",
        "Apocalypse",
        "Apparition",
        "Arachnid",
        "Arcanum",
        "Arterial",
        "Asbestos",
        "Ash",
        "Ashen",
        "Ashes",
        "Ashfall",
        "Asphyxia",
        "Asylum",
        "Atavistic",
        "Atone",
        "Atrocity",
        "Atrophy",
        "Austere",
        "Autopsy",
        "Avalanche",
        "Bacillus",
        "Bale",
        "Bane",
        "Banish",
        "Banishment",
        "Banshee",
        "Barbed",
        "Barnacle",
        "Barometric",
        "Barrage",
        "Barren",
        "Barricade",
        "Barrow",
        "Basalt",
        "Bastion",
        "Battery",
        "Bedlam",
        "Bedrock",
        "Befall",
        "Befoul",
        "Behemoth",
        "Belch",
        "Bellows",
        "Bereave",
        "Bestial",
        "Betray",
        "Betrayal",
        "Bile",
        "Bilge",
        "Biomass",
        "Biome",
        "Bitten",
        "Bitter",
        "Black",
        "Blackened",
        "Blackout",
        "Blade",
        "Blanch",
        "Blare",
        "Blasphemy",
        "Blast",
        "Bleach",
        "Bleak",
        "Bleed",
        "Bleeding",
        "Blight",
        "Blind",
        "Blister",
        "Bloat",
        "Bloated",
        "Blood",
        "Bloodborne",
        "Bloodcurdle",
        "Bloodletting",
        "Bloodshed",
        "Blot",
        "Bludgeon",
        "Blunt",
        "Blurt",
        "Boil",
        "Bolt",
        "Bolted",
        "Bondage",
        "Bone",
        "Bones",
        "Bore",
        "Bound",
        "Bracketed",
        "Brackish",
        "Brain",
        "Braze",
        "Breach",
        "Break",
        "Brimstone",
        "Brine",
        "Bristle",
        "Brittle",
        "Broken",
        "Brood",
        "Bruise",
        "Brumal",
        "Brutal",
        "Buckle",
        "Bulge",
        "Burden",
        "Burgeon",
        "Burial",
        "Burn",
        "Burning",
        "Burnt",
        "Cadaver",
        "Cage",
        "Calcified",
        "Calcite",
        "Callous",
        "Callus",
        "Canker",
        "Captive",
        "Capture",
        "Carbide",
        "Carbon",
        "Carcass",
        "Carnage",
        "Carrion",
        "Carve",
        "Cataclysm",
        "Catacomb",
        "Catalyst",
        "Cataract",
        "Cauldron",
        "Causeway",
        "Caustic",
        "Cauterize",
        "Cesspool",
        "Chain",
        "Char",
        "Charnel",
        "Chasm",
        "Chemical",
        "Chill",
        "Choke",
        "Cinder",
        "Cindered",
        "Clamber",
        "Clamp",
        "Clang",
        "Claw",
        "Cleave",
        "Clinch",
        "Clink",
        "Clot",
        "Coagulate",
        "Coal",
        "Coarse",
        "Cobalt",
        "Coerce",
        "Cold",
        "Collapse",
        "Colony",
        "Combustion",
        "Compound",
        "Compress",
        "Condemn",
        "Condemned",
        "Condense",
        "Conduct",
        "Configure",
        "Confinement",
        "Congealed",
        "Conjuration",
        "Consequence",
        "Constrict",
        "Consume",
        "Contagion",
        "Contaminant",
        "Contaminate",
        "Contort",
        "Contusion",
        "Convulsion",
        "Copper",
        "Corpse",
        "Corrode",
        "Corroded",
        "Corrosion",
        "Corruption",
        "Covet",
        "Crackle",
        "Cradle",
        "Cramp",
        "Cranial",
        "Crater",
        "Crawl",
        "Creep",
        "Crescent",
        "Crevice",
        "Crimson",
        "Cringe",
        "Cripple",
        "Croak",
        "Croup",
        "Crucible",
        "Crucify",
        "Crude",
        "Cruel",
        "Crumble",
        "Crush",
        "Crust",
        "Crypt",
        "Cryptic",
        "Crystallize",
        "Cull",
        "Curdled",
        "Curse",
        "Cursed",
        "Cyst",
        "Damnation",
        "Damp",
        "Dampen",
        "Darken",
        "Darkfall",
        "Darkness",
        "Dead",
        "Deadened",
        "Deadlock",
        "Death",
        "Deathless",
        "Debris",
        "Decay",
        "Deception",
        "Decimate",
        "Decrepit",
        "Deep",
        "Defiance",
        "Defiled",
        "Defilement",
        "Deform",
        "Deformed",
        "Degrade",
        "Delirious",
        "Delirium",
        "Deliverance",
        "Deluge",
        "Dementia",
        "Demolish",
        "Dense",
        "Deplete",
        "Deprive",
        "Derail",
        "Derelict",
        "Desolate",
        "Desolation",
        "Despair",
        "Despise",
        "Detach",
        "Detritus",
        "Devastation",
        "Devoid",
        "Devour",
        "Diffuse",
        "Dilute",
        "Dim",
        "Dire",
        "Dirge",
        "Dirty",
        "Disaster",
        "Discord",
        "Disembowel",
        "Disgorge",
        "Disinter",
        "Dislocate",
        "Dislodge",
        "Dismal",
        "Dismay",
        "Dismember",
        "Disorder",
        "Displace",
        "Disquiet",
        "Dissect",
        "Dissolve",
        "Distend",
        "Distort",
        "Distress",
        "Doom",
        "Doomsday",
        "Downturn",
        "Drain",
        "Dread",
        "Dreadnought",
        "Drear",
        "Dredge",
        "Dregs",
        "Drench",
        "Dried",
        "Drip",
        "Drone",
        "Dross",
        "Drought",
        "Drown",
        "Dry",
        "Dulcet",
        "Dullard",
        "Dulled",
        "Dusk",
        "Dust",
        "Dwindle",
        "Dyspnea",
        "Ebon",
        "Echoes",
        "Eclipse",
        "Effluent",
        "Effuse",
        "Eldritch",
        "Emaciate",
        "Embed",
        "Ember",
        "Embolism",
        "Embroil",
        "Emesis",
        "Emptiness",
        "Encrust",
        "Endless",
        "Engulf",
        "Enigma",
        "Enmesh",
        "Enshroud",
        "Entombed",
        "Entrap",
        "Entropy",
        "Erode",
        "Erosion",
        "Erupt",
        "Eruption",
        "Eternal",
        "Evacuate",
        "Eviscerate",
        "Evocation",
        "Excavate",
        "Exhale",
        "Exhaust",
        "Exhume",
        "Exile",
        "Exorcism",
        "Exsanguination",
        "Extinction",
        "Extinguish",
        "Extract",
        "Exude",
        "Eyeless",
        "Faded",
        "Fallen",
        "Fallout",
        "Famine",
        "Famineborn",
        "Fang",
        "Fathom",
        "Fatten",
        "Fear",
        "Febrile",
        "Fecund",
        "Feint",
        "Feral",
        "Ferric",
        "Fester",
        "Festering",
        "Fetid",
        "Fever",
        "Fibrous",
        "Fierce",
        "Filament",
        "Filth",
        "Final",
        "Fireblack",
        "Fissile",
        "Fissure",
        "Flail",
        "Flare",
        "Flatline",
        "Flay",
        "Flesh",
        "Flicker",
        "Flinch",
        "Flood",
        "Flotsam",
        "Flux",
        "Fog",
        "Fondle",
        "Forgotten",
        "Forlorn",
        "Forsake",
        "Forsaken",
        "Forsaking",
        "Foul",
        "Fractal",
        "Fracture",
        "Fragile",
        "Fragment",
        "Frantic",
        "Frayed",
        "Frenzy",
        "Friction",
        "Fright",
        "Frigid",
        "Frost",
        "Frostbitten",
        "Frozen",
        "Fugue",
        "Fuliginous",
        "Fume",
        "Fungal",
        "Furnace",
        "Fury",
        "Fuse",
        "Futile",
        "Gall",
        "Gallows",
        "Gangrenous",
        "Gangway",
        "Gaol",
        "Gape",
        "Garble",
        "Garish",
        "Gash",
        "Gasp",
        "Gaunt",
        "Gaze",
        "Gelatin",
        "Gelid",
        "Ghast",
        "Ghost",
        "Ghoul",
        "Girder",
        "Glacial",
        "Glaciate",
        "Gloom",
        "Gnarlèd",
        "Gnash",
        "Gnaw",
        "Golem",
        "Gone",
        "Gore",
        "Gorge",
        "Gouge",
        "Granite",
        "Grasp",
        "Grave",
        "Gravel",
        "Graven",
        "Gray",
        "Graze",
        "Grease",
        "Grief",
        "Grim",
        "Grind",
        "Grisly",
        "Gristle",
        "Grit",
        "Groan",
        "Grope",
        "Groundless",
        "Grout",
        "Growl",
        "Grudge",
        "Gruel",
        "Gruesome",
        "Gut",
        "Gutted",
        "Gutter",
        "Hackle",
        "Hallow",
        "Hallowed",
        "Hallucination",
        "Hammer",
        "Hapless",
        "Harbinger",
        "Hardpan",
        "Harrowed",
        "Harsh",
        "Hatred",
        "Haunted",
        "Havoc",
        "Hazard",
        "Haze",
        "Heartless",
        "Hell",
        "Hellfire",
        "Hemlock",
        "Hemorrhage",
        "Heretic",
        "Hollow",
        "Hone",
        "Hopeless",
        "Horrid",
        "Horror",
        "Hostile",
        "Hostility",
        "Howl",
        "Hull",
        "Humid",
        "Hunger",
        "Husk",
        "Hydra",
        "Hydraulic",
        "Hypothermic",
        "Hysteria",
        "Icebound",
        "Ichor",
        "Ignite",
        "Illusion",
        "Immolate",
        "Impact",
        "Impale",
        "Imprison",
        "Imprisoned",
        "Impure",
        "Inane",
        "Incantation",
        "Incendiary",
        "Incision",
        "Incubate",
        "Incursion",
        "Induce",
        "Inert",
        "Infect",
        "Infection",
        "Infernal",
        "Inferno",
        "Infest",
        "Infiltrate",
        "Inflame",
        "Inject",
        "Injure",
        "Inner",
        "Insanity",
        "Insect",
        "Insipid",
        "Insular",
        "Intoxicate",
        "Invade",
        "Iron",
        "Irradiate",
        "Isolate",
        "Isolation",
        "Isolationist",
        "Jagged",
        "Jetsam",
        "Jolt",
        "Judder",
        "Judgment",
        "Keen",
        "Kerosene",
        "Kiln",
        "Kindle",
        "Knell",
        "Knotted",
        "Labour",
        "Labyrinth",
        "Lacerate",
        "Laceration",
        "Lair",
        "Lament",
        "Lance",
        "Languor",
        "Lapse",
        "Larva",
        "Larval",
        "Lash",
        "Lather",
        "Lattice",
        "Leach",
        "Lead",
        "Leaden",
        "Leak",
        "Leper",
        "Leprous",
        "Lesion",
        "Lethal",
        "Leviathan",
        "Lich",
        "Lightless",
        "Liquefy",
        "Lithic",
        "Livid",
        "Lividity",
        "Loathe",
        "Loathing",
        "Lockdown",
        "Lone",
        "Looming",
        "Lost",
        "Lurch",
        "Lurid",
        "Lurk",
        "Lurking",
        "Lymph",
        "Macabre",
        "Maddened",
        "Maggot",
        "Magma",
        "Malaise",
        "Malcontent",
        "Malediction",
        "Malefic",
        "Malevolence",
        "Malevolent",
        "Malformed",
        "Malice",
        "Malignant",
        "Mangle",
        "Mangled",
        "Mantle",
        "Marrow",
        "Martyr",
        "Martyrdom",
        "Massacre",
        "Matted",
        "Maw",
        "Melt",
        "Membrane",
        "Menace",
        "Meniscus",
        "Mephitic",
        "Mercury",
        "Mercy",
        "Meridian",
        "Methane",
        "Miasma",
        "Miasmic",
        "Midnight",
        "Mildew",
        "Mine",
        "Mineral",
        "Mire",
        "Misery",
        "Moist",
        "Molar",
        "Mold",
        "Molder",
        "Molten",
        "Mongrel",
        "Monstrosity",
        "Moonless",
        "Morass",
        "Morbid",
        "Mortal",
        "Mortify",
        "Mottle",
        "Mourn",
        "Mournful",
        "Mucoid",
        "Mucus",
        "Murder",
        "Murk",
        "Murky",
        "Mutation",
        "Mute",
        "Muzzle",
        "Mycelial",
        "Nail",
        "Nameless",
        "Narcotic",
        "Narrow",
        "Nasal",
        "Naught",
        "Nausea",
        "Necrosis",
        "Necrotic",
        "Nectar",
        "Needle",
        "Nemesis",
        "Nerve",
        "Nether",
        "Neural",
        "Neutralize",
        "Night",
        "Nightmare",
        "Nitric",
        "Nocturnal",
        "Noose",
        "Noxious",
        "Null",
        "Numb",
        "Oblique",
        "Oblivion",
        "Obscene",
        "Obscure",
        "Obscurity",
        "Obsidian",
        "Obtuse",
        "Occlude",
        "Occult",
        "Oleaginous",
        "Omen",
        "Ominous",
        "Ooze",
        "Opaque",
        "Oppress",
        "Oppression",
        "Ordeal",
        "Ore",
        "Organ",
        "Ossified",
        "Oxidize",
        "Ozone",
        "Pain",
        "Pale",
        "Pallid",
        "Pallor",
        "Pandemic",
        "Pandemonium",
        "Paradox",
        "Paralysis",
        "Paranoia",
        "Parasite",
        "Parch",
        "Pathogen",
        "Pathology",
        "Peeling",
        "Perdition",
        "Peril",
        "Pestilent",
        "Petrify",
        "Phantom",
        "Phlegm",
        "Phosphor",
        "Pinch",
        "Pit",
        "Pitch",
        "Plague",
        "Plunge",
        "Pneumatic",
        "Poison",
        "Pollute",
        "Portal",
        "Pox",
        "Predator",
        "Pressure",
        "Profane",
        "Prostrate",
        "Pulp",
        "Pulse",
        "Puncture",
        "Pungent",
        "Purgatory",
        "Purge",
        "Putrescence",
        "Putrid",
        "Pyre",
        "Quarantine",
        "Quench",
        "Rabid",
        "Racked",
        "Radiation",
        "Rage",
        "Rancid",
        "Rapture",
        "Rash",
        "Ravage",
        "Ravine",
        "Raw",
        "Reaper",
        "Recoil",
        "Relic",
        "Remnant",
        "Rend",
        "Residue",
        "Restless",
        "Rigor",
        "Rot",
        "Rotting",
        "Ruin",
        "Rupture",
        "Rust",
        "Rusted",
        "Ruthless",
        "Sable",
        "Sacrifice",
        "Sanctum",
        "Sanguine",
        "Savage",
        "Scab",
        "Scald",
        "Scar",
        "Scarred",
        "Scathe",
        "Scorn",
        "Scour",
        "Scourge",
        "Scrape",
        "Screams",
        "Searing",
        "Seclusion",
        "Sediment",
        "Seethe",
        "Seizure",
        "Sepsis",
        "Septic",
        "Sepulcher",
        "Sever",
        "Shade",
        "Shadows",
        "Shale",
        "Shallow",
        "Shard",
        "Shatter",
        "Shear",
        "Shiver",
        "Shock",
        "Shriek",
        "Shrine",
        "Shrivel",
        "Silence",
        "Sinew",
        "Sinister",
        "Skeletal",
        "Skinless",
        "Skull",
        "Slag",
        "Slash",
        "Slaughter",
        "Sludge",
        "Smolder",
        "Smother",
        "Smothered",
        "Soot",
        "Sore",
        "Sorrow",
        "Soul",
        "Soulless",
        "Sour",
        "Specter",
        "Spectral",
        "Spine",
        "Spiral",
        "Splinter",
        "Spore",
        "Stagnant",
        "Stain",
        "Stalker",
        "Starless",
        "Starvation",
        "Stasis",
        "Steaming",
        "Steel",
        "Stench",
        "Sterile",
        "Stifle",
        "Stillness",
        "Sting",
        "Stitch",
        "Stone",
        "Storm",
        "Strain",
        "Strangle",
        "Strife",
        "Strychnine",
        "Subjugation",
        "Subterfuge",
        "Succumb",
        "Suffering",
        "Suffocate",
        "Sulfur",
        "Sunken",
        "Sunless",
        "Suppression",
        "Suppurate",
        "Surgery",
        "Surplus",
        "Swarm",
        "Sweat",
        "Swell",
        "Swollen",
        "Taint",
        "Tar",
        "Tarnish",
        "Tendon",
        "Tepid",
        "Terminal",
        "Termite",
        "Terror",
        "Thaw",
        "Thirst",
        "Thorn",
        "Threnody",
        "Throb",
        "Throttle",
        "Tide",
        "Tomb",
        "Tongue",
        "Torment",
        "Torpid",
        "Torrent",
        "Torture",
        "Toxic",
        "Tragedy",
        "Trauma",
        "Treachery",
        "Tremor",
        "Trench",
        "Trepidation",
        "Tribunal",
        "Trudge",
        "Tryst",
        "Tumor",
        "Turbid",
        "Twilight",
        "Ulcer",
        "Umbra",
        "Unclean",
        "Undead",
        "Unending",
        "Unholy",
        "Unknown",
        "Unrest",
        "Unstable",
        "Unyielding",
        "Vacancy",
        "Vacuum",
        "Vampire",
        "Vanquish",
        "Vapor",
        "Vengeance",
        "Venom",
        "Vermin",
        "Vesper",
        "Vicious",
        "Vigil",
        "Vile",
        "Viral",
        "Virulent",
        "Virus",
        "Viscera",
        "Void",
        "Volatile",
        "Vortex",
        "Vulture",
        "Wailing",
        "Wane",
        "Warped",
        "Wasteland",
        "Wasting",
        "Weld",
        "Welded",
        "Whisper",
        "Wicked",
        "Wilt",
        "Wither",
        "Woe",
        "Wound",
        "Wrath",
        "Wretched",
        "Writhe",
        "Xenolith",
        "Zephyr"
    };

    static public string[] Level_LastWord =
    {
        "Abattoir",
        "Abscess",
        "Abscission",
        "Absolution",
        "Abstraction",
        "Abyss",
        "Access",
        "Accumulation",
        "Acropolis",
        "Adit",
        "Aether",
        "Affliction",
        "Afterbirth",
        "Aftermath",
        "Agglomeration",
        "Agony",
        "Airlock",
        "Alcove",
        "Alley",
        "Altar",
        "Amalgam",
        "Anchor",
        "Annex",
        "Anomaly",
        "Antechamber",
        "Antrum",
        "Aperture",
        "Apex",
        "Apparatus",
        "Apparition",
        "Appendage",
        "Aqueduct",
        "Arc",
        "Arch",
        "Archway",
        "Arena",
        "Armature",
        "Armory",
        "Array",
        "Arson",
        "Artery",
        "Ascension",
        "Ascent",
        "Ashes",
        "Ashfall",
        "Asylum",
        "Atrium",
        "Autopsy",
        "Axle",
        "Backwash",
        "Ballast",
        "Balustrade",
        "Bane",
        "Banishment",
        "Barb",
        "Barracks",
        "Barricade",
        "Barrier",
        "Barrow",
        "Barrowfield",
        "Basal",
        "Basement",
        "Basin",
        "Bastille",
        "Bastion",
        "Bay",
        "Beacon",
        "Bed",
        "Bedlam",
        "Bedrock",
        "Belfry",
        "Berth",
        "Bile",
        "Biopsy",
        "Blackout",
        "Blast",
        "Bleed",
        "Blight",
        "Blister",
        "Block",
        "Blockade",
        "Bloodfall",
        "Bloodstone",
        "Bloom",
        "Boiler",
        "Bolt",
        "Boltholt",
        "Bondage",
        "Bonefield",
        "Borderland",
        "Bore",
        "Bottom",
        "Boundary",
        "Bowel",
        "Bracket",
        "Bramble",
        "Breach",
        "Breakwater",
        "Breath",
        "Bridge",
        "Brine",
        "Brink",
        "Bristle",
        "Brood",
        "Bulge",
        "Bulkhead",
        "Bunker",
        "Burden",
        "Burial",
        "Burn",
        "Burrow",
        "Butchery",
        "Buttress",
        "Cage",
        "Cairn",
        "Calcification",
        "Caldera",
        "Canal",
        "Canopy",
        "Cap",
        "Carbuncle",
        "Carcass",
        "Cargo",
        "Carnage",
        "Carrion",
        "Cartilage",
        "Cascade",
        "Casemate",
        "Casket",
        "Cataclysm",
        "Catacomb",
        "Catch",
        "Cathedral",
        "Cauldron",
        "Cavern",
        "Cavity",
        "Cell",
        "Cenotaph",
        "Center",
        "Centrifuge",
        "Chain",
        "Chamber",
        "Channel",
        "Charnel",
        "Chasm",
        "Chimney",
        "Churn",
        "Chute",
        "Cinder",
        "Circuit",
        "Cistern",
        "Citadel",
        "Clamp",
        "Cleave",
        "Cleft",
        "Cliff",
        "Cloister",
        "Closure",
        "Clot",
        "Clutch",
        "Coagulation",
        "Coil",
        "Collapse",
        "Colossus",
        "Columbarium",
        "Column",
        "Complex",
        "Compound",
        "Compress",
        "Concavity",
        "Conclave",
        "Conduit",
        "Configuration",
        "Confinement",
        "Conflux",
        "Containment",
        "Contamination",
        "Contortion",
        "Contusion",
        "Conundrum",
        "Convergence",
        "Convolution",
        "Cordon",
        "Core",
        "Cornice",
        "Corpsefield",
        "Corpuscle",
        "Corridor",
        "Corridorum",
        "Corrupter",
        "Cortex",
        "Coupling",
        "Cove",
        "Coven",
        "Cover",
        "Crack",
        "Cradle",
        "Crag",
        "Crank",
        "Crater",
        "Crawl",
        "Crawlspace",
        "Crematorium",
        "Crescent",
        "Crevasse",
        "Crevice",
        "Crisis",
        "Crossing",
        "Crown",
        "Crucible",
        "Crucifixion",
        "Crush",
        "Crypt",
        "Cryptswell",
        "Culvert",
        "Cupola",
        "Curse",
        "Cusp",
        "Cycle",
        "Cyclone",
        "Cyst",
        "Damnation",
        "Darkness",
        "Darkwell",
        "Dawn",
        "Daybreak",
        "Deadlock",
        "Death",
        "Deathsong",
        "Deathtrap",
        "Debris",
        "Decadence",
        "Decay",
        "Declination",
        "Decomposition",
        "Deeps",
        "Defile",
        "Deformation",
        "Delirium",
        "Deluge",
        "Demise",
        "Den",
        "Depot",
        "Depression",
        "Deprivation",
        "Depth",
        "Derivation",
        "Descent",
        "Desecration",
        "Despair",
        "Destiny",
        "Detritus",
        "Deviation",
        "Device",
        "Dew",
        "Dichotomy",
        "Dirge",
        "Discord",
        "Disorder",
        "Dissolution",
        "Distension",
        "Distortion",
        "Ditch",
        "Dock",
        "Dolmen",
        "Dome",
        "Dominion",
        "Downdraft",
        "Downfall",
        "Drain",
        "Dread",
        "Dream",
        "Dreamscape",
        "Dregs",
        "Drift",
        "Dropoff",
        "Duct",
        "Dungeon",
        "Dustfall",
        "Dystopia",
        "Eclipse",
        "Eden",
        "Edge",
        "Effigy",
        "Effusion",
        "Ejection",
        "Electrode",
        "Elevation",
        "Embankment",
        "Embolism",
        "Embrace",
        "Emergence",
        "Emission",
        "Empire",
        "Encasement",
        "Enclave",
        "Enclosure",
        "End",
        "Endtime",
        "Engram",
        "Engulfment",
        "Entanglement",
        "Entrance",
        "Entropy",
        "Epitaph",
        "Epoch",
        "Erection",
        "Erosion",
        "Eruption",
        "Escarpment",
        "Estuary",
        "Eternity",
        "Event",
        "Excavation",
        "Excrescence",
        "Exhaust",
        "Exile",
        "Expanse",
        "Expiration",
        "Extension",
        "Extinction",
        "Extraction",
        "Extremity",
        "Facade",
        "Facet",
        "Failure",
        "Fall",
        "Fallout",
        "Fallow",
        "Fane",
        "Fang",
        "Fascicle",
        "Fate",
        "Fathom",
        "Fault",
        "Feast",
        "Fen",
        "Fenestration",
        "Feralground",
        "Filament",
        "Filter",
        "Finale",
        "Fissure",
        "Fixture",
        "Flaw",
        "Flesh",
        "Flood",
        "Floodgate",
        "Floor",
        "Floss",
        "Flue",
        "Flume",
        "Flux",
        "Focus",
        "Fold",
        "Follicle",
        "Foothold",
        "Footprint",
        "Forfeit",
        "Forge",
        "Forsaking",
        "Fosse",
        "Foundation",
        "Foundry",
        "Fracture",
        "Fragment",
        "Frame",
        "Fray",
        "Frenzy",
        "Friction",
        "Fringe",
        "Frozenreach",
        "Fulcrum",
        "Fume",
        "Funeral",
        "Funnel",
        "Furnace",
        "Furrow",
        "Fusion",
        "Gallows",
        "Ganglion",
        "Gangrene",
        "Gangway",
        "Gantry",
        "Gaol",
        "Gap",
        "Garrison",
        "Gate",
        "Gateway",
        "Gauge",
        "Gear",
        "Generator",
        "Genesis",
        "Geode",
        "Ghast",
        "Gibbet",
        "Girder",
        "Glaze",
        "Gloom",
        "Gloomspire",
        "Gorge",
        "Gouge",
        "Gradient",
        "Graft",
        "Granule",
        "Grate",
        "Grave",
        "Grillwork",
        "Grimoire",
        "Grip",
        "Groove",
        "Grotto",
        "Ground",
        "Grove",
        "Growth",
        "Guillotine",
        "Gulch",
        "Gullet",
        "Gutter",
        "Halls",
        "Hangar",
        "Hasp",
        "Hatch",
        "Haul",
        "Haunt",
        "Haven",
        "Hazard",
        "Headwall",
        "Heap",
        "Heart",
        "Hearth",
        "Helix",
        "Hellmouth",
        "Hereticum",
        "Hernia",
        "Hinge",
        "Hitch",
        "Hive",
        "Hoistway",
        "Hold",
        "Hollow",
        "Hook",
        "Hoop",
        "Horizon",
        "Horror",
        "Host",
        "Howl",
        "Hub",
        "Hull",
        "Hungering",
        "Husk",
        "Hydraulic",
        "Hypogeum",
        "Icefield",
        "Illusion",
        "Imbalance",
        "Immolation",
        "Immolator",
        "Impasse",
        "Implant",
        "Imprint",
        "Imprisonment",
        "Incandescence",
        "Incantation",
        "Incision",
        "Inclination",
        "Incline",
        "Indenture",
        "Index",
        "Infection",
        "Inferno",
        "Infernum",
        "Infirmary",
        "Influx",
        "Ingress",
        "Inheritance",
        "Inlet",
        "Insanity",
        "Insert",
        "Intake",
        "Interior",
        "Interlock",
        "Interment",
        "Intersect",
        "Interval",
        "Intrusion",
        "Inversion",
        "Iridescence",
        "Irrigation",
        "Isolate",
        "Isolation",
        "Jack",
        "Jamb",
        "Jar",
        "Jaws",
        "Jetty",
        "Joinery",
        "Judgment",
        "Junction",
        "Juncture",
        "Karst",
        "Keep",
        "Kettle",
        "Keystroke",
        "Kiln",
        "Knavery",
        "Knell",
        "Labyrinth",
        "Labyrinthine",
        "Lacuna",
        "Lair",
        "Lament",
        "Landing",
        "Lattice",
        "Lava",
        "Layer",
        "Leak",
        "Lean",
        "Ledge",
        "Legacy",
        "Lesion",
        "Level",
        "Leviathan",
        "Ligature",
        "Limb",
        "Limit",
        "Link",
        "Lip",
        "Liturgy",
        "Loam",
        "Loathing",
        "Lobe",
        "Lock",
        "Lode",
        "Lodge",
        "Loom",
        "Loop",
        "Losthold",
        "Lot",
        "Lull",
        "Lung",
        "Lurch",
        "Lymph",
        "Machination",
        "Main",
        "Malady",
        "Malebolge",
        "Malediction",
        "Mandible",
        "Manifest",
        "Manifold",
        "Mantle",
        "Margin",
        "Mark",
        "Marrow",
        "Massacre",
        "Matrix",
        "Mausoleum",
        "Maw",
        "Maze",
        "Mechanism",
        "Membrane",
        "Memory",
        "Meridian",
        "Mesh",
        "Mezzanine",
        "Miasma",
        "Midnight",
        "Mine",
        "Mirage",
        "Mirestone",
        "Moat",
        "Mold",
        "Monastery",
        "Monolith",
        "Morass",
        "Morgue",
        "Mortar",
        "Mortuary",
        "Mosaic",
        "Mouth",
        "Mutation",
        "Mythos",
        "Nadir",
        "Nadiric Depths",
        "Narthex",
        "Nave",
        "Navel",
        "Necropolis",
        "Necrosis",
        "Nerve",
        "Nest",
        "Nexus",
        "Niche",
        "Nightfall",
        "Nightwell",
        "Nocturne",
        "Node",
        "Nomad",
        "Nook",
        "Notch",
        "Nucleus",
        "Obeisance",
        "Obelisk",
        "Oblivion",
        "Obliviscence",
        "Obscurity",
        "Obstruction",
        "Occultation",
        "Offal",
        "Offering",
        "Omen",
        "Opening",
        "Operation",
        "Oracle",
        "Orbit",
        "Orchard",
        "Ore",
        "Organ",
        "Origin",
        "Ossuary",
        "Oubliette",
        "Outfall",
        "Outlet",
        "Outpost",
        "Output",
        "Overflow",
        "Overhang",
        "Oxide",
        "Palace",
        "Paleground",
        "Palisade",
        "Pallor",
        "Pandemonium",
        "Panel",
        "Paradigm",
        "Paradox",
        "Parapet",
        "Parish",
        "Partition",
        "Passage",
        "Passageway",
        "Patch",
        "Pathway",
        "Pattern",
        "Pavilion",
        "Peak",
        "Pedestal",
        "Peel",
        "Pen",
        "Perdition",
        "Perforation",
        "Perimeter",
        "Pestilence",
        "Phantasm",
        "Phase",
        "Phylactery",
        "Piece",
        "Pier",
        "Pile",
        "Pillar",
        "Pillow",
        "Pinion",
        "Pipeline",
        "Piston",
        "Pit",
        "Plaguewell",
        "Plait",
        "Plaque",
        "Plate",
        "Plateau",
        "Platform",
        "Plaza",
        "Plea",
        "Plexus",
        "Plinth",
        "Plug",
        "Pocket",
        "Point",
        "Polycrypt",
        "Polyp",
        "Pool",
        "Pore",
        "Port",
        "Portal",
        "Prayer",
        "Precipice",
        "Prism",
        "Prison",
        "Probe",
        "Process",
        "Promontory",
        "Protrusion",
        "Providence",
        "Prow",
        "Pulp",
        "Pulpit",
        "Pulse",
        "Pump",
        "Purgatory",
        "Purge",
        "Putrefaction",
        "Pylon",
        "Pyre",
        "Quagmire",
        "Quarantine",
        "Quarry",
        "Quarter",
        "Quietus",
        "Rafter",
        "Ramp",
        "Rampart",
        "Range",
        "Rapture",
        "Rash",
        "Ravage",
        "Ravine",
        "Ravinehold",
        "Reach",
        "Reactor",
        "Realm",
        "Receptacle",
        "Recess",
        "Reckoning",
        "Refinery",
        "Refuse",
        "Register",
        "Relay",
        "Relic",
        "Reliquary",
        "Remains",
        "Remnant",
        "Repose",
        "Requiem",
        "Reservoir",
        "Residue",
        "Residuum",
        "Resonance",
        "Rest",
        "Retreat",
        "Ridge",
        "Rift",
        "Rig",
        "Rim",
        "Ring",
        "Rivulet",
        "Rod",
        "Root",
        "Rot",
        "Rotunda",
        "Route",
        "Rubble",
        "Ruin",
        "Ruination",
        "Runestone",
        "Runnel",
        "Rupture",
        "Rust",
        "Rut",
        "Sacellum",
        "Sacrifice",
        "Salve",
        "Sanatorium",
        "Sanctuary",
        "Sanctum",
        "Sanguine Hall",
        "Sap",
        "Sarcophagus",
        "Scaffold",
        "Scale",
        "Scar",
        "Scarp",
        "Schism",
        "Scourge",
        "Scratch",
        "Screen",
        "Seal",
        "Seam",
        "Section",
        "Sector",
        "Sediment",
        "Segment",
        "Sepsis",
        "Sepulcher",
        "Sepulchrum",
        "Sequence",
        "Shadowfall",
        "Shaft",
        "Shallows",
        "Shank",
        "Shard",
        "Shelf",
        "Shell",
        "Shelter",
        "Shift",
        "Shiv",
        "Shock",
        "Shore",
        "Shrine",
        "Shroud",
        "Shunt",
        "Side",
        "Sieve",
        "Silence",
        "Silo",
        "Sinkhole",
        "Siren",
        "Site",
        "Skerry",
        "Skullspire",
        "Slab",
        "Slat",
        "Slaughterhouse",
        "Sleeve",
        "Slide",
        "Slit",
        "Slot",
        "Slough",
        "Sluice",
        "Smelt",
        "Snare",
        "Socket",
        "Soil",
        "Sojourn",
        "Sole",
        "Solitude",
        "Solstice",
        "Sorcery",
        "Sorption",
        "Source",
        "Space",
        "Span",
        "Spark",
        "Spasm",
        "Specimen",
        "Spectacle",
        "Spill",
        "Spindle",
        "Spine",
        "Spire",
        "Spit",
        "Splint",
        "Spoke",
        "Spore",
        "Spot",
        "Sprawl",
        "Spur",
        "Squat",
        "Stain",
        "Stairwell",
        "Stake",
        "Stall",
        "Stand",
        "Stasis",
        "Station",
        "Steeple",
        "Stem",
        "Step",
        "Stigma",
        "Stillness",
        "Stitch",
        "Stock",
        "Stonefall",
        "Stopper",
        "Store",
        "Storm",
        "Strait",
        "Strand",
        "Strap",
        "Stratum",
        "Streak",
        "Stream",
        "Stress",
        "Strike",
        "Strip",
        "Stroke",
        "Stronghold",
        "Strop",
        "Stub",
        "Stud",
        "Stump",
        "Substation",
        "Substrate",
        "Suction",
        "Suffering",
        "Sulfur",
        "Summit",
        "Sump",
        "Supplication",
        "Surge",
        "Swell",
        "Swirl",
        "Switch",
        "Synapse",
        "Tab",
        "Tally",
        "Tangle",
        "Tank",
        "Tape",
        "Tarn",
        "Tear",
        "Temple",
        "Tendency",
        "Tendon",
        "Tenebris",
        "Terminal",
        "Terminus",
        "Terrace",
        "Texture",
        "Thread",
        "Threshold",
        "Throat",
        "Throne",
        "Thrum",
        "Tic",
        "Tide",
        "Tier",
        "Tissue",
        "Token",
        "Toll",
        "Tomb",
        "Tongue",
        "Tor",
        "Torment",
        "Torpor",
        "Torsion",
        "Tower",
        "Trace",
        "Track",
        "Tract",
        "Transmitter",
        "Trap",
        "Traverse",
        "Tread",
        "Treason",
        "Trench",
        "Trestle",
        "Tribunal",
        "Trigger",
        "Trim",
        "Trinity",
        "Triumph",
        "Trough",
        "Trove",
        "Truce",
        "Truss",
        "Tube",
        "Tuft",
        "Tumulus",
        "Tundra",
        "Tunnel",
        "Turbine",
        "Turn",
        "Turret",
        "Twist",
        "Tyranny",
        "Ulcer",
        "Umbilicus",
        "Underbelly",
        "Undercroft",
        "Underpass",
        "Underscape",
        "Underscore",
        "Undertow",
        "Underworld",
        "Unhallowed",
        "Unmaking",
        "Uprising",
        "Uptake",
        "Vacancy",
        "Vacuum",
        "Vale",
        "Valhalla",
        "Valley",
        "Valve",
        "Vanishing",
        "Vapor",
        "Variation",
        "Vault",
        "Veil",
        "Vestige",
        "Vigil",
        "Viscera",
        "Voidreach",
        "Vortex",
        "Wane",
        "Ward",
        "Warren",
        "Wasteland",
        "Watch",
        "Well",
        "Whisper",
        "Withering",
        "Woe",
        "Womb",
        "Wound",
        "Wraith",
        "Wreck",
        "Yawning",
        "Zenith"
    };

    /// <summary>
    /// Nouns for Level names
    /// </summary>
    static public string[] NounsLevel =
    {
        "Abattoir Vault",
        "Aberration",
        "Abject Core",
        "Abscess Vault",
        "Abyssal Drain",
        "Abyssal Rift",
        "Abyssal Trace",
        "Abyssborne",
        "Abyssroot",
        "Abyssthorn",
        "Aching Maw",
        "Acid Bloom",
        "Acid Corridor",
        "Acid Vein",
        "Acidwash Corridor",
        "Acrid Shaft",
        "Adhesion Corridor",
        "Adrenal Vault",
        "Afflicted Passage",
        "Agonal Depths",
        "Agonized Expanse",
        "Agony Shaft",
        "Airlock Tomb",
        "Alkaline Depths",
        "Ammonia Hollow",
        "Amniotic Vault",
        "Amputation Ward",
        "Anemic Corridor",
        "Anguished Shaft",
        "Annihilation Ward",
        "Anoxic Hollow",
        "Antechamber of Dread",
        "Aperture of Dread",
        "Arterial Sprawl",
        "Arterial Tomb",
        "Aseptic Corridor",
        "Ashen Corridor",
        "Ashen Reprieve",
        "Ashen Tremor",
        "Ashfall Trench",
        "Ashgut",
        "Asphyxia Chamber",
        "Asphyxiant Corridor",
        "Atrophied Core",
        "Atrophied Span",
        "Autopsy Vault",
        "Bacteric Depths",
        "Bane's Breach",
        "Bane's Descent",
        "Barbed Descent",
        "Barren Cistern",
        "Barren Conduit",
        "Basalt Corridor",
        "Basilar Fracture",
        "Bedrock Hollow",
        "Benighted Hollow",
        "Benthic Hollow",
        "Bile Corridor",
        "Bile Duct",
        "Bilespine",
        "Biofilm Descent",
        "Biohazard Vestibule",
        "Biopsy Corridor",
        "Bisected Hollow",
        "Bitter Hollow",
        "Blackened Canal",
        "Blackened Threshold",
        "Blackened Vault",
        "Blacklung Depth",
        "Blackout Corridor",
        "Blackrot",
        "Bleak Bastion",
        "Bleak Nexus",
        "Bleared Passage",
        "Bleeding Verge",
        "Bleedout Corridor",
        "Blight's Reach",
        "Blighted Corridor",
        "Blighted Reliquary",
        "Blighted Terminus",
        "Blightline",
        "Blightmargin",
        "Blightwound",
        "Blistered Conduit",
        "Blistering Maw",
        "Bloated Corridor",
        "Bloodmire",
        "Bloodrust Chamber",
        "Bloodvault",
        "Blotched Depths",
        "Bone Lattice",
        "Bonepit",
        "Bonethread",
        "Boreal Crypt",
        "Bowel Shaft",
        "Brackish Descent",
        "Brackish Vault",
        "Breach of Torment",
        "Bristled Hollow",
        "Brittle Descent",
        "Broken Circuit",
        "Broken Meridian",
        "Broodpit",
        "Bruised Cavity",
        "Bulkhead Ruin",
        "Burden Spire",
        "Buried Resonance",
        "Burncore",
        "Burnout Corridor",
        "Burnt Hollow",
        "Burnt Terminus",
        "Cadaver Coil",
        "Calcified Reach",
        "Calcified Vein",
        "Calcined Passage",
        "Callous Hollow",
        "Cancerous Hollow",
        "Canker Maw",
        "Canker Passage",
        "Cankerbite",
        "Capillary Ruin",
        "Carbolic Corridor",
        "Carbuncle Sprawl",
        "Carcass Vault",
        "Cardiac Corridor",
        "Carious Descent",
        "Carrion Chamber",
        "Carrion Thread",
        "Carrion Vault",
        "Catacomb Depth",
        "Catacomb Verge",
        "Catastrophic Crevasse",
        "Cauterized Passage",
        "Cauterized Vault",
        "Cavern of Grief",
        "Cavernous Rot",
        "Cavity of Ruin",
        "Cellar of Woe",
        "Centrifuge Tomb",
        "Cesspit Verge",
        "Chamber of Ashes",
        "Chamber of Wailing",
        "Channel of Sickness",
        "Charnel Root",
        "Charroot",
        "Chasm of Silence",
        "Chasm of Wane",
        "Chemical Corridor",
        "Chimney of Ruin",
        "Choked Meridian",
        "Choked Passage",
        "Chokehold Corridor",
        "Chronic Descent",
        "Cinder Vault",
        "Cindered Path",
        "Circuitrot",
        "Cistern of Grief",
        "Clathrate Tomb",
        "Cleft of Agony",
        "Clogged Arterial",
        "Clotted Descent",
        "Coagulant Depths",
        "Coagulated Maw",
        "Coiled Expanse",
        "Collapsed Bastion",
        "Collapsed Sinus",
        "Compound Fracture",
        "Conduit of Ruin",
        "Congealed Stretch",
        "Consumption Ward",
        "Contagion Reach",
        "Containment Ruin",
        "Contaminated Atrium",
        "Contorted Vault",
        "Contusion Depths",
        "Convergence Hollow",
        "Convulsing Depths",
        "Coronal Ruin",
        "Corpsewalk",
        "Corroded Chambers",
        "Corroded Meridian",
        "Corroded Vent",
        "Corrosion Maw",
        "Corrosive Sprawl",
        "Cradle of Night",
        "Cradle of Ruin",
        "Cramped Descent",
        "Cratered Descent",
        "Crawling Dark",
        "Creeping Hollow",
        "Cremation Vault",
        "Crimson Vow",
        "Crumbling Cistern",
        "Crushed Dominion",
        "Crushed Shrine",
        "Crusted Hollow",
        "Crypt's Crux",
        "Cryptic Relic",
        "Cryptthread",
        "Cryptward Verge",
        "Culled Expanse",
        "Cursed Gallery",
        "Cystfield",
        "Cystwall",
        "Damprot Corridor",
        "Dark Nexus",
        "Darkened Meridian",
        "Dead Corridor",
        "Deadlight Trench",
        "Deafened Hollow",
        "Death's Meridian",
        "Debrided Hollow",
        "Debridement Ward",
        "Decay's Hold",
        "Decayed Meridian",
        "Decayed Terminus",
        "Decomposed Reach",
        "Deep Lesion",
        "Defiled Sanctum",
        "Deformed Passage",
        "Degloved Corridor",
        "Delirious Depths",
        "Depthrot",
        "Derelict Hollow",
        "Descent into Darkness",
        "Desecrated Hollows",
        "Desiccated Duct",
        "Desolate Divide",
        "Desolation Pulse",
        "Despair Cradle",
        "Despair's Domain",
        "Devitalized Vault",
        "Devoured Threshold",
        "Dim Corridor",
        "Dire Fissure",
        "Dire Sump",
        "Disemboweled Passage",
        "Disjoint Sanctum",
        "Dislocated Reach",
        "Dismal Corridor",
        "Dissolution",
        "Distended Vault",
        "Doom's Cradle",
        "Dormant Blight",
        "Drained Vestibule",
        "Drainspire",
        "Dread Core",
        "Dreadcoil",
        "Dreadmire",
        "Dreadnaught's Depth",
        "Dreadpulse",
        "Dripping Sanctum",
        "Dross Descent",
        "Drowned Corridor",
        "Drownspire",
        "Dulled Expanse",
        "Dusk's Demise",
        "Dusk's Grasp",
        "Dustlung Cavity",
        "Echoed Vault",
        "Echoing Breach",
        "Eclipsed Reality",
        "Eerie Expanse",
        "Effaced Corridor",
        "Effluent Corridor",
        "Eidolon Passage",
        "Elder Depth",
        "Elder Maw",
        "Eldritch Elevations",
        "Emaciated Depths",
        "Embalmed Depths",
        "Embered Ruin",
        "Emptied Vault",
        "Encrusted Passage",
        "Endless Chasm",
        "Endless Hunger",
        "Endosteal Hollow",
        "Enigma Void",
        "Entombed Vestige",
        "Entrails Corridor",
        "Entropic Maw",
        "Entropy's Grasp",
        "Ephemeral Passage",
        "Epidemic Passage",
        "Eroded Memories",
        "Eroded Span",
        "Eroded Vault",
        "Erosive Wane",
        "Ethereal Edge",
        "Evacuated Hollow",
        "Eviscerated Ward",
        "Excised Hollow",
        "Exhaust Tomb",
        "Exile Chasm",
        "Exsanguine Rise",
        "Extinguished Vault",
        "Extraction Failure",
        "Eyeless Descent",
        "Fallen Dominion",
        "Fallen's Folly",
        "Famine Corridor",
        "Famished Corridor",
        "Fanged Passage",
        "Fathomless",
        "Faulted Expanse",
        "Febrile Passage",
        "Feculent Hollow",
        "Fermented Depths",
        "Ferrousgut",
        "Festered Artery",
        "Festerpit",
        "Festerwatch",
        "Fetid Expanse",
        "Fetid Sump",
        "Fettered Descent",
        "Fevered Corridor",
        "Fibrous Descent",
        "Filament of Ruin",
        "Filthspire",
        "Filthworm Corridor",
        "Fissure of Woe",
        "Fissured Vault",
        "Fistula Passage",
        "Flayed Conduit",
        "Flayed Threshold",
        "Fleshmaw",
        "Fleshreach",
        "Fleshrot",
        "Fleshward Depth",
        "Fleshwell",
        "Flickering Hollow",
        "Flooded Crypt",
        "Flotsam Depths",
        "Forgotten Rise",
        "Forlorn Vault",
        "Formaldehyde Vault",
        "Forsaken Conduit",
        "Forsaken Hollow",
        "Forsaken Sanctuary",
        "Fossil Corridor",
        "Foulbreath Shaft",
        "Fracture's Toll",
        "Fractured Echo",
        "Fractured Maw",
        "Fragmented Vault",
        "Frigid Passage",
        "Frostbitten Corridor",
        "Frothing Depths",
        "Frozen Arterial",
        "Frozen Descent",
        "Fulminant Hollow",
        "Fungal Core",
        "Fungal Spasm",
        "Fungal Sprawl",
        "Furnace Hollow",
        "Fuselage Tomb",
        "Gangrene Corridor",
        "Gangrenous Hall",
        "Gangrenwound",
        "Gaping Corridor",
        "Gasping Veil",
        "Gastric Ruin",
        "Gelid Passage",
        "Germinal Depths",
        "Ghastly Gorge",
        "Girder Tomb",
        "Glacial Tomb",
        "Glaciated Depths",
        "Glare Cradle",
        "Gloam Gate",
        "Gloamwound",
        "Gloom's Gulch",
        "Gloom's Heart",
        "Glutted Passage",
        "Gluttonous Divide",
        "Gnashed Hollows",
        "Gnashing Depths",
        "Gnawing Hollow",
        "Gored Passage",
        "Goreloom",
        "Gorethrottle",
        "Gorevault",
        "Gouged Expanse",
        "Granulated Tomb",
        "Grave's Whisper",
        "Graveclot",
        "Gravegut",
        "Graven Refuge",
        "Graveyard Grotto",
        "Gravid Hollow",
        "Grief Spiral",
        "Grim Ascent",
        "Grim Gallery",
        "Grimwake Verge",
        "Grimwatch",
        "Grindcore Shaft",
        "Gristle Corridor",
        "Gristleweave",
        "Groanvault",
        "Grotesque Sprawl",
        "Growthpit",
        "Gullet Descent",
        "Gurgling Depths",
        "Gutterspire",
        "Guttural Depths",
        "Hacksaw Corridor",
        "Hallowed Ruin",
        "Harbinger's Hold",
        "Harrowed Duct",
        "Haunt's Halls",
        "Haunting Expanse",
        "Hazard Meridian",
        "Heatstroke Vault",
        "Hell's Hinge",
        "Hematic Corridor",
        "Hemlock Corridor",
        "Hemorrhage Sprawl",
        "Hermetic Passage",
        "Hollow Graft",
        "Hollow March",
        "Hollow's Heart",
        "Hollowcoil",
        "Hollowed Descent",
        "Hollowfang",
        "Hollowflare",
        "Hookworm Passage",
        "Hookwound",
        "Horrid Expanse",
        "Howling Rapture",
        "Hull Breach",
        "Hungering Shaft",
        "Husk Spiral",
        "Husked Corridor",
        "Hydric Depths",
        "Hydrostatic Tomb",
        "Hypertrophic Maw",
        "Ichor Trench",
        "Ichorous Descent",
        "Icteric Hollow",
        "Imbibed Hollow",
        "Impacted Core",
        "Impaled Reach",
        "Imploded Shaft",
        "Impure Descent",
        "Incised Corridor",
        "Incision Depths",
        "Incubation Vault",
        "Indurated Passage",
        "Industrial Grave",
        "Infected Gate",
        "Infernal Interstice",
        "Infernal Passage",
        "Inferno's Mouth",
        "Infested Channel",
        "Infested Cistern",
        "Innards Corridor",
        "Inoperable Depths",
        "Insidious Passage",
        "Intercostal Ruin",
        "Intestinal Sprawl",
        "Intubation Vault",
        "Iridescent Ruin",
        "Iron Cyst",
        "Iron Sepulchre",
        "Irradiated Vault",
        "Isolation",
        "Jagged Jaws",
        "Jarring Descent",
        "Jawbone Corridor",
        "Junctured Hollow",
        "Keening Depths",
        "Keratinous Hollow",
        "Kiln of Khaos",
        "Knell Corridor",
        "Knotbone Corridor",
        "Knotted Passage",
        "Kyphotic Corridor",
        "Lacerated Corridor",
        "Lacerated Span",
        "Laceration Depths",
        "Lament's Landing",
        "Languishing Depths",
        "Larval Hollow",
        "Latent Contagion",
        "Lattice of Bone",
        "Lazar Corridor",
        "Leached Corridor",
        "Leprous Descent",
        "Lesion Sprawl",
        "Lesioned Vault",
        "Lichspire",
        "Ligament Stretch",
        "Livid Trench",
        "Lividity Corridor",
        "Lockdown Crypt",
        "Lockjaw Passage",
        "Looming Corridor",
        "Lopsided Descent",
        "Lost Purgatory",
        "Lost Reverie",
        "Lurid Hollow",
        "Lurk's Labyrinth",
        "Lurker's Domain",
        "Lurking Trace",
        "Lymphatic Ruin",
        "Macerated Hollow",
        "Maddened Root",
        "Maggotspire",
        "Malevolence",
        "Malformed Corridor",
        "Malice Threshold",
        "Malignant Nexus",
        "Mangled Vestibule",
        "Marrow Corridor",
        "Marrowdrain",
        "Marrowsplit",
        "Maw's Murmur",
        "Mawdrip",
        "Mawthread",
        "Meatlocker Descent",
        "Medullary Hollow",
        "Membrane Breach",
        "Membrane Hollow",
        "Meridian of Ash",
        "Metastatic Sprawl",
        "Miasma Shaft",
        "Miasmal Corridor",
        "Mildewed Expanse",
        "Mire",
        "Mireveil",
        "Mist's Murk",
        "Moldering Passage",
        "Molten Hollow",
        "Molten Verge",
        "Morbid Vestibule",
        "Mortal Coil",
        "Mortician's Corridor",
        "Mortified Conduit",
        "Mortuary Descent",
        "Moth-Eaten Passage",
        "Mourning Depths",
        "Mourning Mire",
        "Mucoid Trench",
        "Muffled Descent",
        "Muted Corridor",
        "Mycelial Dread",
        "Mycelium Sprawl",
        "Nameless Depth",
        "Narcotic Depths",
        "Narrow Blight",
        "Nauseant Corridor",
        "Necrolith",
        "Necroseal",
        "Necrotic Funnel",
        "Necrotic Niche",
        "Necrotic Sprawl",
        "Needle Corridor",
        "Nerve Cluster",
        "Nesting Hollow",
        "Nether Nest",
        "Netherbound",
        "Nevermore Corridor",
        "Nightbane Vault",
        "Nightblind Shaft",
        "Nocturnal Hollow",
        "Nox Womb",
        "Noxious Vault",
        "Nucleus of Dread",
        "Nullpoint Descent",
        "Numb Expanse",
        "Oblique Descent",
        "Obliterate",
        "Oblivion Runnel",
        "Oblivion's Overture",
        "Obsidian Oubliette",
        "Obsidian Spire",
        "Occluded Passage",
        "Offal Trench",
        "Oozing Threshold",
        "Opalescent Ruin",
        "Opened Wound",
        "Oppressive Corridor",
        "Organ Vault",
        "Ossified Corridor",
        "Ossified Depths",
        "Ossuary Gate",
        "Outbreak Corridor",
        "Overgrown Cistern",
        "Overrun Passage",
        "Oviduct Corridor",
        "Oxidized Reach",
        "Pained Expanse",
        "Pale Nest",
        "Pale Requiem",
        "Pallid Corridor",
        "Pallid Descent",
        "Pallid Fissure",
        "Palsied Corridor",
        "Pandemic Passage",
        "Parasite Verge",
        "Parasitic Depths",
        "Parched Hollow",
        "Pathogen Sprawl",
        "Peel of Flesh",
        "Peeling Corridor",
        "Perdition's Pits",
        "Perished Echelon",
        "Petrified Path",
        "Phantom's Phalanx",
        "Phlegmatic Hollow",
        "Phosphor Crypt",
        "Pipeline Grave",
        "Pit of Gnawing",
        "Plaguebend",
        "Plaguecrawl",
        "Plaguerot",
        "Plasma Corridor",
        "Pockmarked Descent",
        "Polluted Cistern",
        "Pooled Silence",
        "Porous Ruin",
        "Precipice of Woe",
        "Pressurized Tomb",
        "Prion Vault",
        "Prolapsed Corridor",
        "Prosthetic Ruin",
        "Protoplasmic Hollow",
        "Puddled Ruin",
        "Pulse of Dread",
        "Pulsing Corridor",
        "Pulverized Duct",
        "Punctured Core",
        "Purgatorial Span",
        "Purged Hollow",
        "Purulent Depth",
        "Pustule Core",
        "Pustulecrawl",
        "Putrefied Vale",
        "Putrid Hollow",
        "Quarantine Breach",
        "Quarantine Hollow",
        "Quarry of Quietude",
        "Quartzbone Vault",
        "Quenched Abyss",
        "Quiet Hemorrhage",
        "Quivering Depths",
        "Quivering Passage",
        "Rabid Corridor",
        "Ragged Coil",
        "Ragged Maw",
        "Rancid Corridor",
        "Rancid Depths",
        "Rancorous Corridor",
        "Rancorous Vault",
        "Ravaged Hollow",
        "Ravaged Resonance",
        "Raw Expanse",
        "Razorwound",
        "Reactor Crypt",
        "Rebreather Tomb",
        "Recessed Hollow",
        "Recrudescent Depths",
        "Reddened Tomb",
        "Redlined Corridor",
        "Refuse Pit",
        "Remnant Corridor",
        "Rendspire",
        "Residual Hollow",
        "Resinated Depths",
        "Respirator Ruin",
        "Retch Spiral",
        "Retching Hollow",
        "Revenant Cradle",
        "Ribcage Corridor",
        "Rigor Passage",
        "Riven Realm",
        "Riven Tomb",
        "Riveted Tomb",
        "Roiling Depths",
        "Rootblight",
        "Rootworm Hollow",
        "Rotheart",
        "Rothollow",
        "Rotmarrow",
        "Rotting Meridian",
        "Roughcast Tomb",
        "Ruination",
        "Ruined Arterial",
        "Ruinspire",
        "Ruinworn",
        "Runoff Corridor",
        "Ruptured Axis",
        "Ruptured Hollow",
        "Ruptured Valve",
        "Rusted Meridian",
        "Rusted Sanctum",
        "Rustlung Corridor",
        "Sable Depths",
        "Sable Descent",
        "Sable Embrace",
        "Sable Sorrow",
        "Sagging Corridor",
        "Sallow Crawl",
        "Salted Wound",
        "Sanitized Ruin",
        "Scab Corridor",
        "Scabbed Vault",
        "Scabrous Expanse",
        "Scalded Verge",
        "Scalpel's Edge",
        "Scaphoid Hollow",
        "Scarified Depths",
        "Scarred Conduit",
        "Scarred Meridian",
        "Sclerosed Corridor",
        "Sclerotic Passage",
        "Scorched Atrium",
        "Scorched Meridian",
        "Scoured Passage",
        "Scourge Depths",
        "Screaming Hollow",
        "Seared Vestibule",
        "Searpath",
        "Sector of Silence",
        "Sediment Crypt",
        "Seeping Corridor",
        "Seeping Hollow",
        "Seething Nest",
        "Seizure Corridor",
        "Sepsis Corridor",
        "Septic Sprawl",
        "Sepulchral Coil",
        "Serrated Depths",
        "Serum Corridor",
        "Severed Reach",
        "Severed Vein",
        "Shadow's Descent",
        "Shadow's Embrace",
        "Shadow's Shroud",
        "Shattered Egress",
        "Shattered Implant",
        "Shattered Scar",
        "Shellrot",
        "Shivering Tomb",
        "Shriveled Hollow",
        "Shrouded Bastille",
        "Shrouded Conduit",
        "Shuddering Depths",
        "Shutdown Corridor",
        "Sickroot Depth",
        "Sickward",
        "Silent Cyst",
        "Silent Reprise",
        "Silent Sunder",
        "Silo of Decay",
        "Sinew Corridor",
        "Sinewthread",
        "Sinkhole Tomb",
        "Siphon Corridor",
        "Siphoned Hollow",
        "Skeletal Reach",
        "Skinned Vault",
        "Slaked Depths",
        "Slaughterpit",
        "Slickwall Descent",
        "Slime Corridor",
        "Slithered Passage",
        "Sloughed Passage",
        "Sluggish Depths",
        "Smoldering Hollow",
        "Smothered Expanse",
        "Soiled Reach",
        "Solvent Corridor",
        "Somatic Corridor",
        "Sootgorge",
        "Sootroot",
        "Sorrow Husk",
        "Sorrow's Enclave",
        "Soul Vein",
        "Soured Depths",
        "Spasm Vault",
        "Spasming Depths",
        "Spawning Depths",
        "Spectral Divide",
        "Spectral Spire",
        "Spinal Hollows",
        "Spine of Malice",
        "Spinecrack",
        "Spite Gorge",
        "Splinter Maw",
        "Splintered Sepulchre",
        "Splinterrift",
        "Sporebloom Depths",
        "Sporecrawl",
        "Spurting Corridor",
        "Squamous Hollow",
        "Stagnant Core",
        "Stagnant Reach",
        "Stained Corridor",
        "Stalactite Tomb",
        "Stale Corridor",
        "Starvation Hollow",
        "Static Hollow",
        "Sterile Ruin",
        "Stifled Realm",
        "Stillborn Chamber",
        "Stillborn Depths",
        "Stitch Corridor",
        "Strangled Conduit",
        "Striated Hollow",
        "Stripped Corridor",
        "Strychnine Vault",
        "Stygian Abyss",
        "Subcutaneous Sprawl",
        "Submerged Crypt",
        "Subsidence Vault",
        "Substrate Hollow",
        "Subterra Wound",
        "Sucking Hollow",
        "Suffocated Ward",
        "Suffocation Depths",
        "Sulfur Oubliette",
        "Sullen Depths",
        "Sunken Conduit",
        "Sunken Omen",
        "Sunless Embrace",
        "Suppurating Rift",
        "Surgical Ruin",
        "Surplus Tomb",
        "Suture Corridor",
        "Sutured Passage",
        "Swollen Passage",
        "Swollen Rift",
        "Symptom Corridor",
        "Synapse Ruin",
        "Syringe Vault",
        "Systemic Ruin",
        "Tainted Cistern",
        "Tainted Corridor",
        "Tainted Grasp",
        "Tainted Meridian",
        "Tarn Veil",
        "Tarnished Corridor",
        "Tattered Maw",
        "Tendon Sprawl",
        "Tenebral Scar",
        "Tenebrous Labyrinth",
        "Tenuous Corridor",
        "Terminal Descent",
        "Terminal Hollow",
        "Terminus of Rot",
        "Tetanus Corridor",
        "Tetherclot",
        "Tethered Echo",
        "Tethered Void",
        "Thermal Crypt",
        "Thirsting Crypt",
        "Thorned Grasp",
        "Thornhusk",
        "Throbbing Conduit",
        "Thrombotic Depths",
        "Throttled Corridor",
        "Tissue Vault",
        "Titanium Crypt",
        "Tomb of Guilt",
        "Tomb of Worms",
        "Tombspire",
        "Tonguerot",
        "Toothed Corridor",
        "Torment's Lair",
        "Torn Expanse",
        "Torpid Grasp",
        "Torrid Tunnels",
        "Tourniquet Hollow",
        "Toxic Meridian",
        "Toxic Sprawl",
        "Toxinwell",
        "Trampled Hollow",
        "Trauma Corridor",
        "Trautonium Vault",
        "Trembling Hollows",
        "Tremor Shaft",
        "Tremulous Hollow",
        "Trenchrot",
        "Trepanation Ward",
        "Triage Ruin",
        "Triskelion Vault",
        "Tubercular Depths",
        "Tubular Descent",
        "Tumorous Expanse",
        "Turbid Trench",
        "Turbine Crypt",
        "Twilight Husk",
        "Twilight Tomb",
        "Twilight Verge",
        "Twisted Sump",
        "Twisted Terrain",
        "Twitching Corridor",
        "Typhoid Corridor",
        "Ulcerated Depths",
        "Ulcerated Reach",
        "Ulcerous Corridor",
        "Umbilical Passage",
        "Umbral Stretch",
        "Umbral Underbelly",
        "Unbound Grief",
        "Underbelly of Ruin",
        "Undermaw",
        "Undertow Corridor",
        "Unhealed Corridor",
        "Unlit Passage",
        "Unmoored Vault",
        "Unnervingpit",
        "Unraveling Umbras",
        "Unsanctioned Depths",
        "Unstable Corridor",
        "Unstitched Hollow",
        "Untreated Wound",
        "Upheaved Corridor",
        "Urethane Tomb",
        "Urnfield",
        "Vacant Depths",
        "Valvular Depths",
        "Vaporous Hollow",
        "Varicose Passage",
        "Vascular Ruin",
        "Vault of Misery",
        "Veil of Despair",
        "Vein of Woe",
        "Venomous Descent",
        "Ventilation Crypt",
        "Ventral Descent",
        "Ventricle Hollow",
        "Ventricle Tomb",
        "Vermiform Passage",
        "Vestigial Corridor",
        "Vex Hollow",
        "Vexed Vistas",
        "Vibrionsprawl",
        "Vice's Grasp",
        "Violated Sanctum",
        "Viral Descent",
        "Virulent Hollow",
        "Viscera Sprawl",
        "Visceral Corridor",
        "Vitreous Descent",
        "Vitrified Passage",
        "Void's Verge",
        "Void's Vestige",
        "Voided Sanctum",
        "Voidgorge",
        "Voidgrasp",
        "Voidmaw",
        "Voidwalk",
        "Vortex of Silence",
        "Vulture's Perch",
        "Wailing Corridor",
        "Wailing Rift",
        "Wailing Span",
        "Wane",
        "Waning Channel",
        "Waning Hollow",
        "Waning Rites",
        "Warpspine",
        "Wasted Corridor",
        "Wasting Hollow",
        "Waterlogged Descent",
        "Waxen Corridor",
        "Weeping Core",
        "Weeping Divide",
        "Welded Tomb",
        "Wellspring of Ruin",
        "Welted Corridor",
        "Wetlung Depths",
        "Whisper's Wane",
        "Wilt Corridor",
        "Wither's Way",
        "Withered Duct",
        "Withered Nexus",
        "Witherflesh",
        "Woethread",
        "Wormeaten Vault",
        "Wormhollow",
        "Wound Corridor",
        "Wracked Descent",
        "Wraith's Wake",
        "Wraithcoil",
        "Wraithcrack",
        "Wretchcoil",
        "Wretched Grotto",
        "Wretchrift",
        "Writhing Corridor",
        "Xenobiotic Vault",
        "Xenograft Corridor",
        "Xenolith Expanse",
        "Xeric Hollow",
        "Yawning Yoke",
        "Yellowed Corridor",
        "Yielding Corridor",
        "Zenith of Zero"
    };

    /// <summary>
    /// Present participle verbs of failure
    /// </summary>
    static public string[] VerbsPresentParticiple =
    {
        "Atrophying",
        "Bleeding",
        "Breaking",
        "Caving",
        "Collapsing",
        "Corroding",
        "Crumbling",
        "Decaying",
        "Declining",
        "Degenerating",
        "Depleting",
        "Despairing",
        "Deteriorating",
        "Diminishing",
        "Disintegrating",
        "Dissipating",
        "Dissolving",
        "Draining",
        "Drowning",
        "Eroding",
        "Fading",
        "Fading",
        "Floundering",
        "Fraying",
        "Fumbling",
        "Languishing",
        "Moldering",
        "Perishing",
        "Ravaging",
        "Regressing",
        "Sinking",
        "Slipping",
        "Struggling",
        "Succumbing",
        "Suffering",
        "Wasting",
        "Weakening",
        "Wilting",
        "Withering",
        "Wrecking"
    };

    /// <summary>
    /// GTFO enemy names
    /// </summary>
    static public string[] GtfoEnemies =
    {
        "Striker",
        "Shooter",
        "Charger",
        "Shadow",
        "Giant Striker",
        "Giant Shooter",
        "Giant Charger",
        "Shadow Giant",
        "Hybrid",
        "Scout",
        "Charger Scout",
        "Shadow Scout",
        "Tank",
        "Immortal",
        "Mother",
        "P-Mother",
    };

    /// <summary>
    /// Words used for human readable seed strings
    /// </summary>
    static public string[] SeedWords =
    {
        "apple",
        "banana",
        "cherry",
        "dog",
        "cat",
        "bird",
        "fish",
        "house",
        "chair",
        "table",
        "book",
        "pen",
        "hat",
        "car",
        "bus",
        "shoe",
        "sock",
        "bag",
        "tree",
        "sun",
        "moon",
        "star",
        "water",
        "river",
        "lake",
        "ocean",
        "beach",
        "sand",
        "wind",
        "rain",
        "snow",
        "cloud",
        "storm",
        "grass",
        "leaf",
        "flower",
        "rose",
        "tulip",
        "daisy",
        "lily",
        "bird",
        "eagle",
        "hawk",
        "dove",
        "raven",
        "paper",
        "pencil",
        "eraser",
        "ruler",
        "desk",
        "phone",
        "clock",
        "watch",
        "lamp",
        "light",
        "music",
        "song",
        "dance",
        "play",
        "game",
        "ball",
        "bat",
        "glove",
        "goal",
        "run",
        "walk",
        "sit",
        "stand",
        "jump",
        "dance",
        "sing",
        "laugh",
        "cry",
        "smile",
        "frown",
        "speak",
        "listen",
        "read",
        "write",
        "draw",
        "paint",
        "color",
        "print",
        "ship",
        "boat",
        "plane",
        "train",
        "car",
        "bus",
        "bike",
        "bell",
        "ring",
        "gift",
        "card",
        "party",
        "cake",
        "pie",
        "ice",
        "cream",
        "sugar",
        "salt",
        "spice",
        "bread",
        "meat",
        "egg",
        "milk",
        "cheese",
        "pasta",
        "rice",
        "soup",
        "salad",
        "fruit",
        "grape",
        "orange",
        "lemon",
        "lime",
        "melon",
        "berry",
        "nut",
        "date",
        "honey",
        "butter",
        "jam",
        "jelly",
        "candy",
        "choco",
        "cookie",
        "muffin",
        "donut",
        "coffee",
        "tea",
        "juice",
        "soda",
        "water",
        "beer",
        "wine",
        "drink",
        "glass",
        "plate",
        "bowl",
        "spoon",
        "fork",
        "knife",
        "napkin",
        "towel",
        "sheet",
        "blanket",
        "pillow",
        "bed",
        "sofa",
        "chair",
        "bench",
        "floor",
        "wall",
        "door",
        "window",
        "roof",
        "chimney",
        "fence",
        "yard",
        "garden",
        "field",
        "farm",
        "barn",
        "stable",
        "horse",
        "cow",
        "pig",
        "sheep",
        "goat",
        "chicken",
        "turkey",
        "duck",
        "pond",
        "pool",
        "park",
        "zoo",
        "forest",
        "hill",
        "mountain",
        "valley",
        "desert",
        "island",
        "beach",
        "wave",
        "tide",
        "coral",
        "fish",
        "whale",
        "shark",
        "dolphin",
        "seal",
        "crab",
        "lobster",
        "squid",
        "octopus",
        "snail",
        "turtle",
        "lizard",
        "snake",
        "frog",
        "spider",
        "ant",
        "bee",
        "bug",
        "fly",
        "worm",
        "rat",
        "mouse",
        "rabbit",
        "bear",
        "tiger",
        "lion",
        "leopard",
        "panther",
        "wolf",
        "fox",
        "deer",
        "moose",
        "elk",
        "beaver",
        "otter",
        "raccoon",
        "skunk",
        "bat",
        "owl",
        "city",
        "town",
        "village",
        "road",
        "street",
        "alley",
        "avenue",
        "highway",
        "bridge",
        "tunnel",
        "port",
        "harbor",
        "station",
        "hotel",
        "motel",
        "inn",
        "bank",
        "market",
        "mall",
        "store",
        "shop",
        "office",
        "factory",
        "school",
        "church",
        "temple",
        "mosque",
        "museum",
        "library",
        "zoo",
        "park",
        "garden",
        "circus",
        "theater",
        "cinema",
        "cafe",
        "bar",
        "club",
        "gym",
        "spa",
        "salon",
        "hospital",
        "clinic",
        "prison",
        "police",
        "army",
        "navy",
        "air",
        "fire",
        "metal",
        "wood",
        "cloth",
        "silk",
        "wool",
        "cotton",
        "paper",
        "stone",
        "rock",
        "brick",
        "clay",
        "glass",
        "gold",
        "silver",
        "bronze",
        "steel",
        "iron",
        "copper",
        "lead",
        "tin",
        "zinc",
        "nickel",
        "chrome",
        "plastic",
        "rubber",
        "leather",
        "fur",
        "feather",
        "wool",
        "rope",
        "wire",
        "chain",
        "nail",
        "screw",
        "bolt",
        "nut",
        "wheel",
        "tire",
        "pedal",
        "gear",
        "brake",
        "seat",
        "belt",
        "hat",
        "cap",
        "helmet",
        "scarf",
        "glove",
        "sock",
        "shoe",
        "boot",
        "sandal",
        "shirt",
        "blouse",
        "dress",
        "skirt",
        "pants",
        "jeans",
        "suit",
        "tie",
        "jacket",
        "coat",
        "sweater",
        "vest",
        "cape",
        "robe",
        "pajama",
        "underwear",
        "bra",
        "panty",
        "diaper",
        "purse",
        "wallet",
        "bag",
        "suitcase",
        "box",
        "can",
        "jar",
        "bottle",
        "jug",
        "cup",
        "mug",
        "plate",
        "bowl",
        "spoon",
        "fork",
        "knife",
        "chopstick",
        "pin",
        "needle",
        "thread",
        "button",
        "zipper",
        "scissors",
        "razor",
        "comb",
        "brush",
        "mirror",
        "towel",
        "soap",
        "shampoo",
        "lotion",
        "perfume",
        "makeup",
        "lipstick",
        "eyeshadow",
        "mascara",
        "nailpolish",
        "ring",
        "earring",
        "necklace",
        "bracelet",
        "watch",
        "clock",
        "radio",
        "phone",
        "camera",
        "computer",
        "printer",
        "scanner",
        "TV",
        "DVD",
        "CD",
        "disk",
        "tape",
        "book",
        "magazine",
        "newspaper",
        "letter",
        "card",
        "envelope",
        "stamp",
        "pen",
        "pencil",
        "marker",
        "crayon",
        "paint",
        "brush",
        "easel",
        "canvas",
        "paper",
        "notebook",
        "binder",
        "folder",
        "file",
        "clip",
        "staple",
        "glue",
        "tape",
        "ruler",
        "calculator",
        "lamp",
        "bulb",
        "plug",
        "wire",
        "battery",
        "charger",
        "remote",
        "headset",
        "speaker",
        "microphone",
        "keyboard",
        "mouse",
        "screen",
        "monitor",
        "drive",
        "router",
        "modem",
        "antenna",
        "satellite",
        "rocket",
        "plane",
        "helicopter",
        "drone",
        "ship",
        "boat",
        "car",
        "truck",
        "bus",
        "train",
        "tram",
        "bike",
        "scooter",
        "skateboard",
        "rollerblade",
        "sled",
        "ski",
        "surfboard",
        "parachute",
        "tent",
        "sleepingbag",
        "backpack",
        "flashlight",
        "lantern",
        "match",
        "lighter",
        "stove",
        "oven",
        "microwave",
        "refrigerator",
        "freezer",
        "dishwasher",
        "washingmachine",
        "dryer",
        "vacuum",
        "broom",
        "mop",
        "bucket",
        "bin",
        "trash",
        "recycle",
        "leaf",
        "grass",
        "flower",
        "tree",
        "bush",
        "vine",
        "mushroom",
        "fruit",
        "vegetable",
        "grain",
        "bean",
        "nut",
        "meat",
        "poultry",
        "fish",
        "seafood",
        "dairy",
        "egg",
        "cheese",
        "butter",
        "oil",
        "sugar",
        "salt",
        "spice",
        "tea",
        "coffee",
        "cocoa",
        "water",
        "juice",
        "soda",
        "wine",
        "beer",
        "liquor",
        "cocktail",
        "soup",
        "salad",
        "sandwich",
        "pizza",
        "pasta",
        "rice",
        "bread",
        "cake",
        "pie",
        "cookie",
        "candy",
        "icecream",
        "jelly",
        "jam",
        "honey",
        "syrup",
        "vinegar",
        "sauce",
        "ketchup",
        "mustard",
        "mayo",
        "pepper",
        "chili",
        "garlic",
        "onion",
        "potato",
        "carrot",
        "bean",
        "pea",
        "corn",
        "cucumber",
        "lettuce",
        "tomato",
        "pepper",
        "broccoli",
        "spinach",
        "mushroom",
        "olive",
        "pickle",
        "apple",
        "banana",
        "orange",
        "berry",
        "grape",
        "lemon",
        "lime",
        "melon",
        "mango",
        "papaya",
        "pineapple",
        "coconut",
        "cherry",
        "plum",
        "peach",
        "apricot",
        "nut",
        "almond",
        "peanut",
        "walnut",
        "chestnut",
        "hazelnut",
        "meat",
        "pork",
        "beef",
        "lamb",
        "chicken",
        "turkey",
        "duck",
        "fish",
        "salmon",
        "tuna",
        "shrimp",
        "crab",
        "lobster",
        "oyster",
        "clam",
        "mussel",
        "squid",
        "octopus",
        "egg",
        "milk",
        "cheese",
        "yogurt",
        "butter",
        "cream",
        "icecream",
        "chocolate",
        "candy",
        "cookie",
        "cake",
        "pie",
        "muffin",
        "donut",
        "bread",
        "toast",
        "bagel",
        "roll",
        "croissant",
        "pancake",
        "waffle",
        "cereal",
        "oatmeal",
        "rice",
        "pasta",
        "noodle",
        "sushi",
        "pizza",
        "burger",
        "hotdog",
        "sandwich",
        "wrap",
        "taco",
        "burrito",
        "salad",
        "soup",
        "stew",
        "chili",
        "curry",
        "sauce",
        "gravy",
        "dressing",
        "ketchup",
        "mustard",
        "mayo",
        "relish",
        "pickles",
        "olives",
        "jam",
        "jelly",
        "honey",
        "syrup",
        "butter",
        "oil",
        "vinegar",
        "salt",
        "pepper",
        "spice",
        "herb",
        "garlic",
        "onion",
        "tomato",
        "potato",
        "carrot",
        "celery",
        "lettuce",
        "cabbage",
        "spinach",
        "broccoli",
        "pepper",
        "bean",
        "pea",
        "corn",
        "cucumber",
        "zucchini",
        "squash",
        "pumpkin",
        "eggplant",
        "mushroom",
        "olive",
        "apple",
        "banana",
        "orange",
        "berry",
        "grape",
        "lemon",
        "lime",
        "melon",
        "mango",
        "papaya",
        "pineapple",
        "coconut",
        "cherry",
        "plum",
        "peach",
        "apricot",
        "berry",
        "kiwi",
        "date",
        "fig",
        "raisin",
        "nut",
        "almond",
        "peanut",
        "walnut",
        "chestnut",
        "hazelnut",
        "cashew",
        "pecan",
        "macadamia",
        "meat",
        "pork",
        "beef",
        "lamb",
        "chicken",
        "turkey",
        "duck",
        "fish",
        "salmon",
        "tuna",
        "shrimp",
        "crab",
        "lobster",
        "oyster",
        "clam",
        "mussel",
        "squid",
        "octopus",
        "caviar",
        "egg",
        "milk",
        "cheese",
        "yogurt",
        "butter",
        "cream",
        "icecream",
        "chocolate",
        "candy",
        "cookie",
        "cake",
        "pie",
        "muffin",
        "donut",
        "bread",
        "toast",
        "bagel",
        "roll",
        "croissant",
        "pancake",
        "waffle",
        "cereal",
        "oatmeal",
        "rice",
        "pasta",
        "noodle",
        "sushi",
        "pizza",
        "burger",
        "hotdog",
        "sandwich",
        "wrap",
        "taco",
        "burrito",
        "salad",
        "soup",
        "stew",
        "chili",
        "curry",
        "sauce",
        "gravy",
        "dressing",
        "ketchup",
        "mustard",
        "mayo",
        "relish",
        "pickles",
        "olives",
        "jam",
        "jelly",
        "honey",
        "syrup",
        "butter",
        "oil",
        "vinegar",
        "salt",
        "pepper",
        "spice",
        "herb",
        "garlic",
        "onion",
        "tomato",
        "potato",
        "carrot",
        "celery",
        "lettuce",
        "cabbage",
        "spinach",
        "broccoli",
        "pepper",
        "bean",
        "pea",
        "corn",
        "cucumber",
        "zucchini",
        "squash",
        "pumpkin",
        "eggplant",
        "mushroom",
        "olive",
        "apple",
        "banana",
        "orange",
        "berry",
        "grape",
        "lemon",
        "lime",
        "melon",
        "mango",
        "papaya",
        "pineapple",
        "coconut",
        "cherry",
        "plum",
        "peach",
        "apricot",
        "berry",
        "kiwi",
        "date",
        "fig",
        "raisin",
        "nut",
        "almond",
        "peanut",
        "walnut",
        "chestnut",
        "hazelnut",
        "cashew",
        "pecan",
        "macadamia",
        "meat",
        "pork",
        "beef",
        "lamb",
        "chicken",
        "turkey",
        "duck",
        "fish",
        "salmon",
        "tuna",
        "shrimp",
        "crab",
        "lobster",
        "oyster",
        "clam",
        "mussel",
        "squid",
        "octopus",
        "caviar",
        "egg",
        "milk",
        "cheese",
        "yogurt",
        "butter",
        "cream",
        "icecream",
        "chocolate",
        "candy",
        "cookie",
        "cake",
        "pie",
        "muffin",
        "donut",
        "bread",
        "toast",
        "bagel",
        "roll",
        "croissant",
        "pancake",
        "waffle",
        "cereal",
        "oatmeal",
        "rice",
        "pasta",
        "noodle",
        "sushi",
        "pizza",
        "burger",
        "hotdog",
        "sandwich",
        "wrap",
        "taco",
        "burrito",
        "salad",
        "soup",
        "stew",
        "chili",
        "curry",
        "sauce",
        "gravy",
        "dressing",
        "ketchup",
        "mustard",
        "mayo",
        "relish",
        "pickles",
        "olives",
        "jam",
        "jelly",
        "honey",
        "syrup",
        "butter",
        "oil",
        "vinegar",
        "salt",
        "pepper",
        "spice",
        "herb",
        "garlic",
        "onion",
        "tomato",
        "potato",
        "carrot",
        "celery",
        "lettuce",
        "cabbage",
        "spinach",
        "broccoli",
        "pepper",
        "bean",
        "pea",
        "corn",
        "cucumber",
        "zucchini",
        "squash",
        "pumpkin",
        "eggplant",
        "mushroom",
        "olive",
        "apple",
        "banana",
        "orange",
        "berry",
        "grape",
        "lemon",
        "lime",
        "melon",
        "mango",
        "papaya",
        "pineapple",
        "coconut",
        "cherry",
        "plum",
        "peach",
        "apricot",
        "berry",
        "kiwi",
        "date",
        "fig",
        "raisin",
        "nut",
        "almond",
        "peanut",
        "walnut",
        "chestnut",
        "hazelnut",
        "cashew",
        "pecan",
        "macadamia",
        "meat",
        "pork",
        "beef",
        "lamb",
        "chicken",
        "turkey",
        "duck",
        "fish",
        "salmon",
        "tuna",
        "shrimp",
        "crab",
        "lobster",
        "oyster",
        "clam",
        "mussel",
        "squid",
        "octopus",
        "caviar",
        "egg",
        "milk",
        "cheese",
        "yogurt",
        "butter",
        "cream",
        "icecream",
        "chocolate",
        "candy",
        "cookie",
        "cake",
        "pie",
        "muffin",
        "donut"
    };
}
