using AutogenRundown.DataBlocks.Objectives;

namespace AutogenRundown.DataBlocks;

/**
 * Objective: ClearPath
 *
 *
 * Fairly straight forward objective, get to the end zone. Some additional enemies
 * at the end make this a more interesting experience.
 *
 * This objective can only be for Main given it ends the level on completion
 */
public partial record WardenObjective
{
    public void Build_ClearPath(BuildDirector director, Level level)
    {
        var (dataLayer, layout) = GetObjectiveLayerAndLayout(director, level);

        // Find the exit zone
        var exit = level.Planner.GetZonesByTag(director.Bulkhead, "exit_elevator").First();

        MainObjective = new Text(() => $"Clear a path to the exit point in {Intel.Zone(exit, level.Planner)}");
        GoToWinCondition_CustomGeo = new Text(() => $"Go to the forward exit point in {Intel.Zone(exit, level.Planner)}");

        dataLayer.ObjectiveData.WinCondition = WardenObjectiveWinCondition.GoToElevator;
    }

    private void PostBuildIntel_ClearPath(Level level)
    {
        #region Warden Intel Messages
        level.ElevatorDropWardenIntel.Add((Generator.Between(1, 10), Generator.Draw(new List<string>
        {
            ">... Just keep moving forward.\r\n>... <size=200%><color=red>Don't look back.</color></size>\r\n>... [distant screaming]",
            ">... Where's the extraction point?\r\n>... <size=200%><color=red>I don't know!</color></size>\r\n>... Check the terminal!",
            ">... This is the wrong zone.\r\n>... We're going in circles!\r\n>... <size=200%><color=red>Are we lost?</color></size>",
            ">... [panting]\r\n>... How much farther?\r\n>... <size=200%><color=red>Keep running!</color></size>",
            ">... The exit's gotta be close.\r\n>... <size=200%><color=red>It better be.</color></size>\r\n>... [heavy breathing]",
            ">... Door's locked.\r\n>... <size=200%><color=red>Find the key!</color></size>\r\n>... Where?!",
            ">... I see the extraction zone!\r\n>... <size=200%><color=red>Don't celebrate yet.</color></size>\r\n>... [alarm blaring]",
            ">... Extraction's just ahead!\r\n>... Set up the sentries first!\r\n>... <size=200%><color=red>No time!</color></size>",
            ">... [gasping]\r\n>... <size=200%><color=red>I can't run anymore!</color></size>\r\n>... You have to!",
            ">... Almost there...\r\n>... Almost...\r\n>... <size=200%><color=red>[screaming]</color></size>",
            // ">... Which way to extraction?\r\n>... <size=200%><color=red>The terminal said Zone 45!</color></size>\r\n>... That was ten zones ago!",
            ">... This hallway goes on forever.\r\n>... Just keep moving.\r\n>... <size=200%><color=red>Something's following us.</color></size>",
            // ">... <size=200%><color=red>Power's out!</color></size>\r\n>... Find the generator.\r\n>... We don't have time for this!",
            // ">... Need a power cell for this door.\r\n>... <size=200%><color=red>Where do we get one?!</color></size>\r\n>... [distant roaring]",
            ">... The path forward is clear.\r\n>... <size=200%><color=red>Too clear.</color></size>\r\n>... Something's wrong...",
            ">... Wait, we passed this room before.\r\n>... <size=200%><color=red>We're going in circles!</color></size>\r\n>... [frustrated yelling]",
            ">... Bioscan required.\r\n>... This is gonna attract them.\r\n>... <size=200%><color=red>Do it anyway!</color></size>",
            ">... Where's everyone else?\r\n>... <size=200%><color=red>We got separated!</color></size>\r\n>... Regroup at extraction!",
            ">... I'm low on ammo.\r\n>... Save it for extraction.\r\n>... <size=200%><color=red>If we make it that far.</color></size>",
            ">... This is taking too long.\r\n>... <size=200%><color=red>They're everywhere now!</color></size>\r\n>... [gunfire]",
            ">... Security door ahead.\r\n>... <size=200%><color=red>It's got an alarm!</color></size>\r\n>... Of course it does...",
            ">... Extraction scan starting!\r\n>... <size=200%><color=red>Error alarm triggered!</color></size>\r\n>... [klaxon blaring]",
            ">... Hold the position!\r\n>... <size=200%><color=red>They're breaking through!</color></size>\r\n>... [gunfire intensifies]",
            ">... Scan's at 50%!\r\n>... Keep fighting!\r\n>... <size=200%><color=red>I'm out of bullets!</color></size>",
            ">... <size=200%><color=red>Giant incoming!</color></size>\r\n>... Focus fire!\r\n>... [explosion]",
            ">... Sentry's down!\r\n>... <size=200%><color=red>We're surrounded!</color></size>\r\n>... Stay in the scan zone!",
            ">... 75% complete!\r\n>... <size=200%><color=red>Just hold on!</color></size>\r\n>... [screaming]",
            ">... Where's the exit elevator?\r\n>... It should be in this zone!\r\n>... <size=200%><color=red>I don't see it!</color></size>",
            ">... PING says it's this way.\r\n>... <size=200%><color=red>Trust the terminal.</color></size>\r\n>... I hope you're right...",
            ">... This door needs a key.\r\n>... Which one?!\r\n>... <size=200%><color=red>LIST KEYS!</color></size>",
            // ">... Key's in Zone 38.\r\n>... That's three zones back!\r\n>... <size=200%><color=red>Someone go get it!</color></size>",
            ">... [whispering] Don't wake them.\r\n>... <size=200%><color=red>Just get to the exit.</color></size>\r\n>... [loud crash]",
            ">... They're all sleeping.\r\n>... Stealth to extraction?\r\n>... <size=200%><color=red>Worth a shot.</color></size>",
            ">... [whisper] Stay quiet.\r\n>... <size=200%><color=red>[whisper] Almost there.</color></size>\r\n>... [scout shriek]",
            ">... Run! RUN!\r\n>... <size=200%><color=red>Don't stop!</color></size>\r\n>... [footsteps pounding]",
            ">... Extraction in sight!\r\n>... Set up sentries now!\r\n>... <size=200%><color=red>Move! Move!</color></size>",
            ">... C-Foam this door!\r\n>... <size=200%><color=red>Behind us!</color></size>\r\n>... [hissing]",
            ">... How many sentries we got?\r\n>... Two.\r\n>... <size=200%><color=red>That's not enough.</color></size>",
            ">... Position the sentries here!\r\n>... <size=200%><color=red>They're coming!</color></size>\r\n>... Start the scan!",
            ">... Scan's starting!\r\n>... Everyone in position?\r\n>... <size=200%><color=red>DO IT!</color></size>",
            ">... Stay in the scan area!\r\n>... <size=200%><color=red>Don't leave!</color></size>\r\n>... [alarm blaring]",
            ">... Charger incoming!\r\n>... <size=200%><color=red>Shoot it!</color></size>\r\n>... [snarling]",
            ">... How long on this scan?!\r\n>... <size=200%><color=red>Too long!</color></size>\r\n>... [gunfire]",
            ">... They keep coming!\r\n>... <size=200%><color=red>Hold position!</color></size>\r\n>... [roaring]",
            ">... Scan's almost done!\r\n>... Thirty seconds!\r\n>... <size=200%><color=red>We're not gonna make it!</color></size>",
            ">... Keep firing!\r\n>... <size=200%><color=red>Don't let them through!</color></size>\r\n>... [continuous gunfire]",
            ">... Someone's down!\r\n>... <size=200%><color=red>Stay in the scan!</color></size>\r\n>... [screaming]",
            ">... 90% complete!\r\n>... <size=200%><color=red>Almost there!</color></size>\r\n>... [explosion]",
            ">... Scan complete!\r\n>... <size=200%><color=red>Get out! GET OUT!</color></size>\r\n>... [running footsteps]",
            ">... This way to extraction!\r\n>... You sure?\r\n>... <size=200%><color=red>No!</color></size>",
            ">... We're lost, aren't we?\r\n>... <size=200%><color=red>Completely.</color></size>\r\n>... [frustrated sigh]",
            ">... Back the way we came!\r\n>... <size=200%><color=red>It's blocked!</color></size>\r\n>... Find another route!",
            ">... This zone looks familiar.\r\n>... We've been here before.\r\n>... <size=200%><color=red>Damn it!</color></size>",
            ">... Check your map!\r\n>... <size=200%><color=red>What map?!</color></size>\r\n>... Use PING!",
            ">... How much ammo left?\r\n>... Not enough.\r\n>... <size=200%><color=red>Never enough.</color></size>",
            ">... Save your bullets!\r\n>... For what?\r\n>... <size=200%><color=red>Extraction!</color></size>",
            ">... Found a resource station!\r\n>... <size=200%><color=red>Grab everything!</color></size>\r\n>... [rustling]",
            ">... Health pack here!\r\n>... Take it!\r\n>... <size=200%><color=red>You need it more.</color></size>",
            ">... Tool refill station!\r\n>... <size=200%><color=red>Thank god.</color></size>\r\n>... Fill up quick!",
            // ">... This ladder goes down.\r\n>... Or up?\r\n>... <size=200%><color=red>Does it matter?</color></size>",
            ">... Another security door.\r\n>... <size=200%><color=red>Another alarm.</color></size>\r\n>... I'm so tired of this...",
            ">... Alarm incoming!\r\n>... Get ready!\r\n>... <size=200%><color=red>Here they come!</color></size>",
            ">... [alarm blaring]\r\n>... <size=200%><color=red>It won't stop!</color></size>\r\n>... Error alarm!",
            ">... Can't deactivate it!\r\n>... <size=200%><color=red>Just run!</color></size>\r\n>... [klaxon continues]",
            ">... Keep moving through the alarm!\r\n>... <size=200%><color=red>Don't stop to fight!</color></size>\r\n>... [gunfire while running]",
            ">... They're spawning everywhere!\r\n>... <size=200%><color=red>Go! Go! Go!</color></size>\r\n>... [panting heavily]",
            ">... Door's open!\r\n>... Through here!\r\n>... <size=200%><color=red>MOVE!</color></size>",
            ">... Is everyone through?\r\n>... <size=200%><color=red>Where's Bishop?!</color></size>\r\n>... He was right behind me!",
            ">... We're leaving him!\r\n>... <size=200%><color=red>We have to!</color></size>\r\n>... [distant screaming]",
            ">... I can see the exit!\r\n>... <size=200%><color=red>Don't slow down!</color></size>\r\n>... [heavy breathing]",
            ">... Extraction zone ahead!\r\n>... Finally!\r\n>... <size=200%><color=red>Don't relax yet.</color></size>",
            ">... We made it!\r\n>... <size=200%><color=red>Start the scan!</color></size>\r\n>... Wait, setup first!",
            ">... No time for setup!\r\n>... <size=200%><color=red>They're right behind us!</color></size>\r\n>... Scan now!",
            ">... This is gonna be rough.\r\n>... <size=200%><color=red>Just survive.</color></size>\r\n>... [loading weapons]",
            ">... Everybody ready?\r\n>... <size=200%><color=red>Do we have a choice?</color></size>\r\n>... Starting scan!",
            ">... [bioscan humming]\r\n>... <size=200%><color=red>Contact!</color></size>\r\n>... [gunfire]",
            ">... They're everywhere!\r\n>... <size=200%><color=red>Focus fire!</color></size>\r\n>... [shooting]",
            ">... Striker wave!\r\n>... <size=200%><color=red>Mow them down!</color></size>\r\n>... [automatic fire]",
            ">... Shooter on the ledge!\r\n>... <size=200%><color=red>I see it!</color></size>\r\n>... [burst fire]",
            ">... Shadow incoming!\r\n>... Where?!\r\n>... <size=200%><color=red>Behind you!</color></size>",
            ">... Multiple Giants!\r\n>... <size=200%><color=red>Target them!</color></size>\r\n>... [heavy footsteps]",
            ">... This scan is taking forever!\r\n>... <size=200%><color=red>Keep fighting!</color></size>\r\n>... [continuous combat]",
            ">... I'm out!\r\n>... Switching weapons!\r\n>... <size=200%><color=red>Cover me!</color></size>",
            ">... Reloading!\r\n>... <size=200%><color=red>Fall back!</color></size>\r\n>... [clicking]",
            ">... How much longer?!\r\n>... <size=200%><color=red>Sixty seconds!</color></size>\r\n>... [explosion]",
            ">... The sentry's taking damage!\r\n>... Protect it!\r\n>... <size=200%><color=red>Too many!</color></size>",
            ">... Sentry out of tool!\r\n>... <size=200%><color=red>We're on our own!</color></size>\r\n>... [intense gunfire]",
            ">... Stay together!\r\n>... <size=200%><color=red>Don't leave the scan!</color></size>\r\n>... [shouting]",
            ">... Someone's down!\r\n>... <size=200%><color=red>Keep scanning!</color></size>\r\n>... We need one person!",
            ">... I can't hold them!\r\n>... <size=200%><color=red>You have to!</color></size>\r\n>... [screaming]",
            ">... 80% done!\r\n>... <size=200%><color=red>Almost there!</color></size>\r\n>... Don't give up!",
            ">... They broke through!\r\n>... <size=200%><color=red>Melee! MELEE!</color></size>\r\n>... [swinging]",
            ">... Tank incoming!\r\n>... <size=200%><color=red>Aim for the back!</color></size>\r\n>... [heavy weapons fire]",
            ">... Mother spawning!\r\n>... Kill her fast!\r\n>... <size=200%><color=red>Before she births!</color></size>",
            ">... Scan's at 95%!\r\n>... <size=200%><color=red>Five more seconds!</color></size>\r\n>... [desperate fighting]",
            ">... Complete!\r\n>... <size=200%><color=red>RUN!</color></size>\r\n>... [sprinting]",
            ">... Into the elevator!\r\n>... <size=200%><color=red>GO! GO!</color></size>\r\n>... [footsteps]",
            // ">... We're out!\r\n>... [heavy breathing]\r\n>... <size=200%><color=red>We actually made it...</color></size>",
            // ">... How far to extraction?\r\n>... <size=200%><color=red>Terminal says 12 zones.</color></size>\r\n>... Fuck...",
            // ">... Twelve zones?!\r\n>... <size=200%><color=red>Start moving.</color></size>\r\n>... [resigned sigh]",
            ">... This is gonna take forever.\r\n>... One zone at a time.\r\n>... <size=200%><color=red>Let's go.</color></size>",
            ">... Another locked door.\r\n>... Another damn key.\r\n>... <size=200%><color=red>Check the terminal.</color></size>",
            // ">... KEY_217 required.\r\n>... <size=200%><color=red>Where is it?</color></size>\r\n>... QUERY KEY_217...",
            // ">... Key's in Zone 29.\r\n>... <size=200%><color=red>That's behind us!</color></size>\r\n>... Back we go...",
            ">... I'll get the key.\r\n>... <size=200%><color=red>Hurry back.</color></size>\r\n>... [running footsteps]",
            ">... Got the key!\r\n>... <size=200%><color=red>Opening door!</color></size>\r\n>... [mechanical whirring]",
            ">... Finally through.\r\n>... How many more?\r\n>... <size=200%><color=red>Don't ask.</color></size>",
            ">... This zone's clear.\r\n>... <size=200%><color=red>Keep pushing.</color></size>\r\n>... Next zone...",
            ">... Power's down in this section.\r\n>... <size=200%><color=red>Find the generator.</color></size>\r\n>... [flashlight clicking]",
            // ">... Generator here.\r\n>... Need a power cell.\r\n>... <size=200%><color=red>LIST CELL!</color></size>",
            // ">... Cell's over there.\r\n>... <size=200%><color=red>I'll get it.</color></size>\r\n>... [grunting]",
            // ">... This thing's heavy...\r\n>... <size=200%><color=red>[whispering] Quiet!</color></size>\r\n>... [heavy breathing]",
            ">... Power's back!\r\n>... <size=200%><color=red>Lights on!</color></size>\r\n>... [humming electricity]",
            ">... That's better.\r\n>... Can actually see now.\r\n>... <size=200%><color=red>Keep moving.</color></size>",
            ">... Scout ahead!\r\n>... <size=200%><color=red>I see one!</color></size>\r\n>... [shrieking]",
            ">... It's calling others!\r\n>... <size=200%><color=red>Kill it! Kill it!</color></size>\r\n>... [gunfire]",
            ">... Too late!\r\n>... <size=200%><color=red>They're awake!</color></size>\r\n>... [multiple roars]",
            ">... Fighting retreat!\r\n>... Back to the door!\r\n>... <size=200%><color=red>C-Foam it!</color></size>",
            ">... Door's foamed!\r\n>... <size=200%><color=red>That'll slow them!</color></size>\r\n>... [pounding on door]",
            ">... Won't hold long.\r\n>... <size=200%><color=red>Move faster!</color></size>\r\n>... [running]",
            ">... Next zone!\r\n>... How many left?\r\n>... <size=200%><color=red>Stop asking!</color></size>",
            ">... I need to know!\r\n>... <size=200%><color=red>Six more zones.</color></size>\r\n>... [groaning]",
            ">... Just six?\r\n>... <size=200%><color=red>JUST six?!</color></size>\r\n>... Could be worse...",
            ">... Bio tracker's pinging.\r\n>... <size=200%><color=red>Something's moving.</color></size>\r\n>... [beeping]",
            ">... Patrol ahead.\r\n>... Sneak past?\r\n>... <size=200%><color=red>Worth a try.</color></size>",
            ">... [whispering] Slowly...\r\n>... <size=200%><color=red>[whispering] Don't breathe.</color></size>\r\n>... [heartbeat thumping]",
            ">... [whisper] Keep going...\r\n>... [whisper] Almost past...\r\n>... <size=200%><color=red>[scout screech]</color></size>",
            ">... Shit!\r\n>... <size=200%><color=red>Run for it!</color></size>\r\n>... [sprinting]",
            ">... This way!\r\n>... <size=200%><color=red>Through the hub!</color></size>\r\n>... [panting]",
            ">... They're right behind!\r\n>... <size=200%><color=red>Don't look back!</color></size>\r\n>... [roar close by]",
            ">... Security door!\r\n>... <size=200%><color=red>Get through!</color></size>\r\n>... [door closing]",
            ">... Safe...\r\n>... [gasping for air]\r\n>... <size=200%><color=red>For now.</color></size>",
            ">... That was close.\r\n>... Too close.\r\n>... <size=200%><color=red>Let's keep moving.</color></size>",
            ">... Five zones left.\r\n>... <size=200%><color=red>We can do this.</color></size>\r\n>... I hope so...",
            ">... This zone's huge.\r\n>... <size=200%><color=red>Stay together.</color></size>\r\n>... [footsteps echoing]",
            ">... Hearing things?\r\n>... <size=200%><color=red>Just echoes.</color></size>\r\n>... I don't like it...",
            ">... Something feels wrong.\r\n>... <size=200%><color=red>It's too quiet.</color></size>\r\n>... [distant growling]",
            ">... Told you.\r\n>... <size=200%><color=red>Weapons up.</color></size>\r\n>... [loading]",
            ">... Contact!\r\n>... <size=200%><color=red>Open fire!</color></size>\r\n>... [gunfire erupts]",
            ">... Strikers!\r\n>... <size=200%><color=red>Lots of them!</color></size>\r\n>... [automatic fire]",
            ">... They're swarming!\r\n>... <size=200%><color=red>Backpedal!</color></size>\r\n>... [shooting while moving]",
            ">... Clear!\r\n>... Check ammo.\r\n>... <size=200%><color=red>Running low.</color></size>",
            ">... We all are.\r\n>... <size=200%><color=red>Conserve it.</color></size>\r\n>... [reloading]",
            ">... Next zone.\r\n>... <size=200%><color=red>Four to go.</color></size>\r\n>... Keep counting...",
            ">... Bioscan door.\r\n>... <size=200%><color=red>Everyone in!</color></size>\r\n>... [humming]",
            ">... Hold position...\r\n>... <size=200%><color=red>Stay in the scan...</color></size>\r\n>... [tense silence]",
            ">... Something's coming!\r\n>... <size=200%><color=red>Don't leave the scan!</color></size>\r\n>... [approaching sounds]",
            ">... Sleepers incoming!\r\n>... <size=200%><color=red>Shoot from scan zone!</color></size>\r\n>... [gunfire]",
            ">... Scan complete!\r\n>... <size=200%><color=red>Door's open!</color></size>\r\n>... Move! Move!",
            ">... Through!\r\n>... Three zones.\r\n>... <size=200%><color=red>Almost there.</color></size>",
            ">... I can feel it.\r\n>... <size=200%><color=red>We're close.</color></size>\r\n>... [determined footsteps]",
            ">... This is the second to last!\r\n>... <size=200%><color=red>One more after this!</color></size>\r\n>... [nervous laughter]",
            ">... Don't jinx it.\r\n>... <size=200%><color=red>Just saying...</color></size>\r\n>... [crash]",
            ">... What was that?!\r\n>... <size=200%><color=red>Big one!</color></size>\r\n>... [heavy footsteps]",
            ">... Giant!\r\n>... <size=200%><color=red>Don't wake it!</color></size>\r\n>... [thumping]",
            ">... It's following!\r\n>... <size=200%><color=red>Through the door!</color></size>\r\n>... [running]",
            ">... Door closing!\r\n>... <size=200%><color=red>It's stuck!</color></size>\r\n>... [hammering sounds]",
            ">... Shoot through the gap!\r\n>... <size=200%><color=red>FIRE!</color></size>\r\n>... [concentrated fire]",
            ">... It's down!\r\n>... [heavy thud]\r\n>... <size=200%><color=red>Last zone.</color></size>",
            ">... This is it.\r\n>... Extraction's in here.\r\n>... <size=200%><color=red>Let's finish this.</color></size>",
            ">... I see the elevator!\r\n>... <size=200%><color=red>Don't run to it yet!</color></size>\r\n>... Why not?!",
            ">... Setup first!\r\n>... <size=200%><color=red>Sentries! C-Foam!</color></size>\r\n>... Fine...",
            ">... Placing sentry here.\r\n>... <size=200%><color=red>Another one there.</color></size>\r\n>... [mechanical deploying]",
            ">... C-Foam these doors?\r\n>... <size=200%><color=red>All of them.</color></size>\r\n>... [spraying]",
            ">... Mines down.\r\n>... <size=200%><color=red>Everyone topped off?</color></size>\r\n>... Ready.",
            ">... This is it.\r\n>... <size=200%><color=red>Start the scan.</color></size>\r\n>... [deep breath]",
            ">... Scan initiated!\r\n>... <size=200%><color=red>[alarm blaring]</color></size>\r\n>... Here we go!",
            // ">... Error alarm?!\r\n>... <size=200%><color=red>Of course!</color></size>\r\n>... [klaxon wailing]",
            ">... First wave!\r\n>... <size=200%><color=red>Light them up!</color></size>\r\n>... [gunfire]",
            ">... Sentries firing!\r\n>... <size=200%><color=red>Good coverage!</color></size>\r\n>... [automated fire]",
            ">... Wave two incoming!\r\n>... <size=200%><color=red>From all sides!</color></size>\r\n>... [multiple directions]",
            ">... They're everywhere!\r\n>... <size=200%><color=red>Hold the line!</color></size>\r\n>... [intense combat]",
            ">... Scan's at 25%!\r\n>... <size=200%><color=red>Long way to go!</color></size>\r\n>... [continuous fire]",
            ">... Chargers!\r\n>... <size=200%><color=red>Focus them!</color></size>\r\n>... [rapid fire]",
            ">... Shadow teleporting!\r\n>... Where is it?!\r\n>... <size=200%><color=red>Behind!</color></size>",
            ">... Got it!\r\n>... <size=200%><color=red>Nice shot!</color></size>\r\n>... [reloading]",
            ">... 50% complete!\r\n>... Halfway there!\r\n>... <size=200%><color=red>Don't slow down!</color></size>",
            ">... Left sentry down!\r\n>... <size=200%><color=red>Cover that angle!</color></size>\r\n>... [shifting position]",
            ">... They broke through the foam!\r\n>... <size=200%><color=red>Fall back to scan!</color></size>\r\n>... [retreating]",
            ">... Stay in the zone!\r\n>... <size=200%><color=red>Don't step out!</color></size>\r\n>... [fighting]",
            ">... 60%!\r\n>... <size=200%><color=red>Keep going!</color></size>\r\n>... [gunfire]",
            ">... I'm dry!\r\n>... <size=200%><color=red>Switch weapons!</color></size>\r\n>... [swapping]",
            ">... Running low on everything!\r\n>... <size=200%><color=red>Make it count!</color></size>\r\n>... [aimed shots]",
            ">... Big wave!\r\n>... <size=200%><color=red>INCOMING!</color></size>\r\n>... [massive surge]",
            ">... Giants and Chargers!\r\n>... <size=200%><color=red>Prioritize!</color></size>\r\n>... [heavy fire]",
            ">... Can't hold them!\r\n>... <size=200%><color=red>You have to!</color></size>\r\n>... [screaming]",
            ">... 75%!\r\n>... <size=200%><color=red>Almost done!</color></size>\r\n>... [desperate fighting]",
            ">... Right sentry destroyed!\r\n>... <size=200%><color=red>No sentries left!</color></size>\r\n>... [panic]",
            ">... Just us now!\r\n>... <size=200%><color=red>We can do this!</color></size>\r\n>... [determined fire]",
            ">... 80%!\r\n>... <size=200%><color=red>Twenty more!</color></size>\r\n>... Come on!",
            ">... Woods is down!\r\n>... <size=200%><color=red>Keep scanning!</color></size>\r\n>... [continuing]",
            ">... Two of us left!\r\n>... <size=200%><color=red>Stay in the scan!</color></size>\r\n>... [fighting back-to-back]",
            ">... 85%!\r\n>... <size=200%><color=red>Don't give up!</color></size>\r\n>... [exhausted shooting]",
            ">... Out of primary ammo!\r\n>... <size=200%><color=red>Use secondary!</color></size>\r\n>... [pistol fire]",
            ">... 90%!\r\n>... <size=200%><color=red>Ten more seconds!</color></size>\r\n>... [frantic]",
            // ">... Tank incoming!\r\n>... <size=200%><color=red>Ignore it!</color></size>\r\n>... Shoot the scan!",
            ">... 95%!\r\n>... <size=200%><color=red>FIVE SECONDS!</color></size>\r\n>... [desperate]",
            ">... Four!\r\n>... Three!\r\n>... <size=200%><color=red>TWO!</color></size>",
            ">... ONE!\r\n>... <size=200%><color=red>DONE!</color></size>\r\n>... [door hiss]",
            ">... COMPLETE!\r\n>... <size=200%><color=red>GO! GO! GO!</color></size>\r\n>... [sprinting]",
            ">... Into the elevator!\r\n>... <size=200%><color=red>GET IN!</color></size>\r\n>... [scrambling]",
            // ">... Door closing!\r\n>... <size=200%><color=red>We made it!</color></size>\r\n>... [heavy breathing]",
            // ">... [gasping]\r\n>... [laughing]\r\n>... <size=200%><color=red>We actually fucking made it...</color></size>",
            ">... Extraction route is long.\r\n>... <size=200%><color=red>How long?</color></size>\r\n>... Don't ask.",
            ">... This path goes on forever.\r\n>... <size=200%><color=red>Keep walking.</color></size>\r\n>... [tired footsteps]",
            ">... Are we even going the right way?\r\n>... <size=200%><color=red>QUERY says yes.</color></size>\r\n>... If you say so...",
            ">... I don't trust that terminal.\r\n>... <size=200%><color=red>Got a better idea?</color></size>\r\n>... No...",
            ">... This is taking forever.\r\n>... <size=200%><color=red>Feels like it.</color></size>\r\n>... [exhausted sigh]",
            ">... My legs are killing me.\r\n>... <size=200%><color=red>Keep moving.</color></size>\r\n>... [limping]",
            ">... Need a break.\r\n>... <size=200%><color=red>No breaks.</color></size>\r\n>... Please...",
            ">... Can't stop now.\r\n>... <size=200%><color=red>Almost there.</color></size>\r\n>... You keep saying that!",
            ">... Because it's true!\r\n>... <size=200%><color=red>I hope...</color></size>\r\n>... [uncertain]",
            ">... Another zone transition.\r\n>... <size=200%><color=red>How many is that?</color></size>\r\n>... Lost count.",
            ">... This Complex is huge.\r\n>... <size=200%><color=red>Too huge.</color></size>\r\n>... [echoing footsteps]",
            ">... Extraction has to be close.\r\n>... <size=200%><color=red>It better be.</color></size>\r\n>... [hopeful]",
            ">... I see it!\r\n>... <size=200%><color=red>Where?!</color></size>\r\n>... There! The elevator!",
            // ">... That's it!\r\n>... <size=200%><color=red>Finally!</color></size>\r\n>... [relieved laughter]",
            ">... Don't celebrate yet.\r\n>... <size=200%><color=red>Right. Setup.</color></size>\r\n>... [serious tone]",
            ">... Sentries in position.\r\n>... <size=200%><color=red>C-Foam ready.</color></size>\r\n>... Let's do this.",
            ">... Starting extraction scan.\r\n>... <size=200%><color=red>Here we go again...</color></size>\r\n>... [bioscan starts]",
            ">... [alarm immediately]\r\n>... <size=200%><color=red>FUCK!</color></size>\r\n>... [klaxon]",
            ">... Every damn time!\r\n>... <size=200%><color=red>Just fight!</color></size>\r\n>... [gunfire]",
            ">... This scan better be quick!\r\n>... <size=200%><color=red>It's not!</color></size>\r\n>... [groaning]",
            ">... Long scan ahead!\r\n>... <size=200%><color=red>Conserve ammo!</color></size>\r\n>... [controlled fire]",
            ">... First contact!\r\n>... <size=200%><color=red>Strikers!</color></size>\r\n>... [shooting]",
            ">... More coming!\r\n>... <size=200%><color=red>Keep them back!</color></size>\r\n>... [continuous]",
            ">... They're not stopping!\r\n>... <size=200%><color=red>Neither are we!</color></size>\r\n>... [determined]",
            ">... Scan progress?\r\n>... <size=200%><color=red>15%!</color></size>\r\n>... That's it?!",
            ">... Long way to go!\r\n>... <size=200%><color=red>Pace yourself!</color></size>\r\n>... [measured shots]",
            ">... Shooter wave!\r\n>... <size=200%><color=red>Take cover!</color></size>\r\n>... [ducking]",
            ">... Can't hide in scan!\r\n>... <size=200%><color=red>Shoot back!</color></size>\r\n>... [return fire]",
            ">... Projectiles everywhere!\r\n>... <size=200%><color=red>Dodge!</color></size>\r\n>... [moving]",
            ">... Got one!\r\n>... <size=200%><color=red>More coming!</color></size>\r\n>... [continuing]",
            ">... 30% done!\r\n>... <size=200%><color=red>Still so much!</color></size>\r\n>... [fighting]",
            ">... This is intense!\r\n>... <size=200%><color=red>Focus!</color></size>\r\n>... [gunfire]",
            ">... Ammo check!\r\n>... <size=200%><color=red>Half!</color></size>\r\n>... Make it last!",
            ">... Conserving shots!\r\n>... <size=200%><color=red>Headshots only!</color></size>\r\n>... [precise fire]",
            ">... Big wave incoming!\r\n>... <size=200%><color=red>Brace!</color></size>\r\n>... [massive surge]",
            ">... So many!\r\n>... <size=200%><color=red>OPEN FIRE!</color></size>\r\n>... [uncontrolled shots]",
            ">... Can't stop them all!\r\n>... <size=200%><color=red>Try!</color></size>\r\n>... [desperate]",
            ">... Sentry's struggling!\r\n>... <size=200%><color=red>Support it!</color></size>\r\n>... [helping]",
            ">... Sentry's out!\r\n>... <size=200%><color=red>Damn!</color></size>\r\n>... [empty beep]",
            ">... Lost our sentries!\r\n>... <size=200%><color=red>Manual now!</color></size>\r\n>... [shooting]",
            ">... 45% complete!\r\n>... <size=200%><color=red>Past halfway!</color></size>\r\n>... Keep pushing!",
            ">... Charger rush!\r\n>... <size=200%><color=red>Multiple!</color></size>\r\n>... [rapid fire]",
            ">... They're fast!\r\n>... <size=200%><color=red>Stay in the scan!</color></size>\r\n>... [moving]",
            ">... Got one!\r\n>... Another!\r\n>... <size=200%><color=red>More behind!</color></size>",
            ">... No end to them!\r\n>... <size=200%><color=red>Keep shooting!</color></size>\r\n>... [continuing]",
            ">... 60% done!\r\n>... <size=200%><color=red>40 to go!</color></size>\r\n>... [panting]",
            ">... Getting tired!\r\n>... <size=200%><color=red>Push through!</color></size>\r\n>... [fighting fatigue]",
            ">... Arms are heavy!\r\n>... <size=200%><color=red>Don't stop!</color></size>\r\n>... [struggling]",
            ">... Shadow phase!\r\n>... <size=200%><color=red>Watch for teleport!</color></size>\r\n>... [alert]",
            ">... Where'd it go?!\r\n>... <size=200%><color=red>There!</color></size>\r\n>... [shooting]",
            ">... Got it!\r\n>... <size=200%><color=red>Another one!</color></size>\r\n>... [reacting]",
            ">... Multiple Shadows!\r\n>... <size=200%><color=red>Back to back!</color></size>\r\n>... [circular defense]",
            ">... 70% complete!\r\n>... <size=200%><color=red>30 left!</color></size>\r\n>... Almost there!",
            ">... Don't jinx it!\r\n>... <size=200%><color=red>Just fight!</color></size>\r\n>... [focused]",
            ">... Giant wave!\r\n>... <size=200%><color=red>Multiple Giants!</color></size>\r\n>... [heavy fire]",
            ">... They're tanky!\r\n>... <size=200%><color=red>Keep firing!</color></size>\r\n>... [sustained]",
            ">... First Giant down!\r\n>... <size=200%><color=red>Next one!</color></size>\r\n>... [continuing]",
            ">... This is exhausting!\r\n>... <size=200%><color=red>Almost done!</color></size>\r\n>... [tired]",
            ">... 80% complete!\r\n>... <size=200%><color=red>Twenty seconds!</color></size>\r\n>... [motivated]",
            ">... We got this!\r\n>... <size=200%><color=red>Don't stop now!</color></size>\r\n>... [pushing]",
            ">... Mixed wave!\r\n>... <size=200%><color=red>Everything at once!</color></size>\r\n>... [chaos]",
            ">... Strikers, Shooters, Giants!\r\n>... <size=200%><color=red>Kill them all!</color></size>\r\n>... [everything]",
            ">... 85%!\r\n>... <size=200%><color=red>15 seconds!</color></size>\r\n>... [intense]",
            ">... Running on fumes!\r\n>... <size=200%><color=red>Last magazine!</color></size>\r\n>... [depleted]",
            ">... Make every shot count!\r\n>... <size=200%><color=red>Precision!</color></size>\r\n>... [careful]",
            ">... 90%!\r\n>... <size=200%><color=red>TEN SECONDS!</color></size>\r\n>... [frantic]",
            ">... Final push!\r\n>... <size=200%><color=red>Give it everything!</color></size>\r\n>... [all out]",
            ">... 95%!\r\n>... <size=200%><color=red>FIVE!</color></size>\r\n>... FOUR!",
            ">... THREE!\r\n>... <size=200%><color=red>TWO!</color></size>\r\n>... ONE!",
            // ">... <size=200%><color=red>COMPLETE!</color></size>\r\n>... [success sound]\r\n>... YES!",
            ">... Into the elevator zone!\r\n>... <size=200%><color=red>MOVE!</color></size>\r\n>... [sprinting]",
            // ">... We did it!\r\n>... [door closing]\r\n>... <size=200%><color=red>We're out...</color></size>",
            ">... [heavy breathing]\r\n>... [relieved laughter]\r\n>... <size=200%><color=red>That was hell.</color></size>",
            // ">... But we made it.\r\n>... <size=200%><color=red>Yeah...</color></size>\r\n>... [exhausted smile]",
        })!));
        #endregion
    }
}
