using AutogenRundown.DataBlocks.Alarms;
using AutogenRundown.DataBlocks.Objectives;
using AutogenRundown.DataBlocks.Objectives.CentralGeneratorCluster;

namespace AutogenRundown.DataBlocks;

/**
 * Objective: CentralGeneratorCluster
 *
 *
 * Discord says getting the generator cluster to spawn can be tricky and require
 * re-rolls with the zone seed. Still waiting on seeing if this is a problem.
 */
public partial record WardenObjective
{
    private void PreBuild_CentralGeneratorCluster(BuildDirector director, Level level)
    {
        CentralGeneratorCluster_NumberOfGenerators = (level.Tier, director.Bulkhead) switch
        {
            ("A", Bulkhead.Main) => 3,
            ("A", _) => 2,

            ("B", Bulkhead.Main) => 3,
            ("B", _) => 2,

            ("C", Bulkhead.Main) => Generator.Between(3, 4),
            ("C", Bulkhead.Extreme) => 2,
            ("C", Bulkhead.Overload) => 3,

            ("D", Bulkhead.Main) => 4,
            ("D", Bulkhead.Extreme) => Generator.Between(3, 4),
            ("D", Bulkhead.Overload) => 3,

            ("E", Bulkhead.Main) => Generator.Between(4, 5),
            ("E", Bulkhead.Extreme) => Generator.Between(3, 4),
            ("E", Bulkhead.Overload) => 3,
        };
        CentralGeneratorCluster_NumberOfPowerCells = CentralGeneratorCluster_NumberOfGenerators;
    }

    private void Build_CentralGeneratorCluster(BuildDirector director, Level level)
    {
        var (dataLayer, layout) = GetObjectiveLayerAndLayout(director, level);

        MainObjective = new Text("Find [COUNT_REQUIRED] Power Cells and bring them to the Central Generator Cluster in [ITEM_ZONE]");
        FindLocationInfo = "Locate the Power Cells and use them to power up the Generator Cluster";
        FindLocationInfoHelp = "Generators Online: [COUNT_CURRENT] / [COUNT_REQUIRED]";
        // TODO: this key_map doesn't work?
        GoToWinConditionHelp_Elevator = "Use the navigational beacon and the floor map ([KEY_MAP]) to find the way back";
        GoToWinConditionHelp_CustomGeo = "Use the navigational beacon and the information in the surroundings to find the exit point";
        GoToWinCondition_ToMainLayer = "Malfunction in air purification system. Make your way for the forward emergency exit.";

        MidPuzzle = level.Tier switch
        {
            "A" => ChainedPuzzle.FindOrPersist(ChainedPuzzle.AlarmClass2 with { Settings = WaveSettings.Baseline_Easy }),
            "B" => ChainedPuzzle.FindOrPersist(ChainedPuzzle.AlarmClass3 with { Settings = WaveSettings.Baseline_Normal }),
            "C" => ChainedPuzzle.FindOrPersist(ChainedPuzzle.AlarmClass4 with { Settings = WaveSettings.Baseline_Hard }),
            "D" => ChainedPuzzle.FindOrPersist(ChainedPuzzle.AlarmClass5 with { Settings = WaveSettings.Baseline_Hard }),
            "E" => ChainedPuzzle.FindOrPersist(ChainedPuzzle.AlarmClass6 with { Settings = WaveSettings.Baseline_VeryHard })
        };

        AddCompletedObjectiveWaves(level, director);

        #region Warden Intel Messages
        level.ElevatorDropWardenIntel.Add((Generator.Between(1, 10), Generator.Draw(new List<string>
        {
            ">... Find the Power Cells.\r\n>... Bring them to the cluster.\r\n>... <size=200%><color=red>Don't insert the last one yet!</color></size>",
            ">... <size=200%><color=red>These cells are heavy!</color></size>\r\n>... [whispering] Keep it quiet.\r\n>... You'll wake them up.",
            ">... The fog is so thick...\r\n>... [coughing]\r\n>... <size=200%><color=red>Get those generators online!</color></size>",
            ">... Each cell clears the fog.\r\n>... <size=200%><color=red>Insert them as you find them!</color></size>\r\n>... Don't wait till the end.",
            ">... Check the terminal.\r\n>... It should show cell locations.\r\n>... <size=200%><color=red>Zone 45 has one!</color></size>",
            ">... <size=200%><color=red>Final cell triggered the alarm!</color></size>\r\n>... [alarm blaring]\r\n>... Get ready!",
            ">... I can barely see...\r\n>... This fog is killing me.\r\n>... <size=200%><color=red>Hurry with those cells!</color></size>",
            ">... Three cells left to find.\r\n>... <size=200%><color=red>Check every zone!</color></size>\r\n>... We're running out of time.",
            ">... [heavy breathing]\r\n>... This thing weighs a ton.\r\n>... <size=200%><color=red>Someone help me carry it!</color></size>",
            ">... The fog's clearing up!\r\n>... <size=200%><color=red>Keep inserting cells!</color></size>\r\n>... It's actually working.",
            ">... <size=200%><color=red>Don't trigger that last generator!</color></size>\r\n>... Not yet.\r\n>... We need to prepare first.",
            ">... Power Cell in Zone 32.\r\n>... I'll grab it.\r\n>... <size=200%><color=red>Cover me!</color></size>",
            ">... The cluster's in the center.\r\n>... <size=200%><color=red>Navigate back carefully!</color></size>\r\n>... Don't get lost in fog.",
            ">... [static]\r\n>... Cell secured.\r\n>... <size=200%><color=red>Heading back to cluster!</color></size>",
            ">... <size=200%><color=red>Watch for Sleepers!</color></size>\r\n>... The fog hides them.\r\n>... Stay alert.",
            ">... Two more generators to go.\r\n>... The fog's almost clear.\r\n>... <size=200%><color=red>One more cell!</color></size>",
            ">... [gunfire]\r\n>... They're on us!\r\n>... <size=200%><color=red>Drop the cell and fight!</color></size>",
            ">... <size=200%><color=red>Last cell triggers CLASS V!</color></size>\r\n>... Are we ready for that?\r\n>... Better prep defenses first.",
            ">... Use the LIST command.\r\n>... <size=200%><color=red>Find those Power Cells!</color></size>\r\n>... Terminal shows locations.",
            ">... The fog returned!\r\n>... <size=200%><color=red>After the final cell!</color></size>\r\n>... We're blind again!",
            ">... Carrying this through fog...\r\n>... Can't see anything.\r\n>... <size=200%><color=red>Follow my light!</color></size>",
            ">... <size=200%><color=red>Generator cluster located!</color></size>\r\n>... Mark it on your map.\r\n>... We'll need to return here.",
            ">... [coughing heavily]\r\n>... Infectious fog?\r\n>... <size=200%><color=red>Get to disinfection!</color></size>",
            ">... Three cells inserted.\r\n>... <size=200%><color=red>Fog's clearing nicely!</color></size>\r\n>... Keep it up.",
            ">... The last zone is far.\r\n>... Long carry back.\r\n>... <size=200%><color=red>Watch for ambushes!</color></size>",
            ">... <size=200%><color=red>Error Alarm incoming!</color></size>\r\n>... Final cell activated it.\r\n>... [alarm wailing]",
            ">... Split up to find cells?\r\n>... <size=200%><color=red>No, too dangerous!</color></size>\r\n>... Stay together.",
            ">... [panting]\r\n>... These cells are exhausting.\r\n>... <size=200%><color=red>How many left?!</color></size>",
            ">... The fog's so dense...\r\n>... <size=200%><color=red>I can't breathe!</color></size>\r\n>... [gasping]",
            ">... <size=200%><color=red>Cell located in Zone 67!</color></size>\r\n>... That's deep in the complex.\r\n>... We'll need to push through.",
            ">... Cluster needs five cells.\r\n>... We have three.\r\n>... <size=200%><color=red>Two more to find!</color></size>",
            ">... [whispering] Carry it slow.\r\n>... <size=200%><color=red>Don't drop it!</color></size>\r\n>... They'll hear the clatter.",
            ">... The fog parts as we insert.\r\n>... <size=200%><color=red>Keep going!</color></size>\r\n>... We can actually see now.",
            ">... <size=200%><color=red>Final generator ready!</color></size>\r\n>... Everyone stocked on ammo?\r\n>... This will get messy.",
            ">... Terminal says Zone 21.\r\n>... <size=200%><color=red>That's past the blood door!</color></size>\r\n>... We'll need to fight.",
            ">... [static crackling]\r\n>... Lost visual in fog.\r\n>... <size=200%><color=red>Regroup at cluster!</color></size>",
            ">... The weight of this thing...\r\n>... <size=200%><color=red>My arms are giving out!</color></size>\r\n>... [grunting]",
            ">... <size=200%><color=red>Fog's at waist level now!</color></size>\r\n>... Cells are working.\r\n>... Insert the next one.",
            ">... Five cells scattered.\r\n>... Five zones to search.\r\n>... <size=200%><color=red>Let's move out!</color></size>",
            ">... [alarm blaring]\r\n>... Last cell did this!\r\n>... <size=200%><color=red>They're spawning everywhere!</color></size>",
            ">... <size=200%><color=red>Don't save them all!</color></size>\r\n>... Insert as we collect.\r\n>... Fog clears progressively.",
            ">... Cell's in a locked room.\r\n>... Need to find the key.\r\n>... <size=200%><color=red>Check the terminals!</color></size>",
            ">... [heavy footsteps]\r\n>... Giant near the cluster!\r\n>... <size=200%><color=red>Clear it before inserting!</color></size>",
            ">... <size=200%><color=red>The fog returns after final cell!</color></size>\r\n>... Someone warned us.\r\n>... We didn't listen.",
            ">... Generator 1 online.\r\n>... Generator 2 online.\r\n>... <size=200%><color=red>Three more to go!</color></size>",
            ">... [panting heavily]\r\n>... Zone 88 has a cell.\r\n>... <size=200%><color=red>That's so far away!</color></size>",
            ">... <size=200%><color=red>Continuous spawns started!</color></size>\r\n>... Three Strikers every 10 seconds.\r\n>... This is endless!",
            ">... The cluster's surrounded.\r\n>... <size=200%><color=red>Clear the area first!</color></size>\r\n>... Then insert cells.",
            ">... Terminal query complete.\r\n>... <size=200%><color=red>All cell locations marked!</color></size>\r\n>... Let's collect them.",
            ">... [coughing]\r\n>... This fog is infectious!\r\n>... <size=200%><color=red>Find a disinfection station!</color></size>",
            ">... <size=200%><color=red>One cell left!</color></size>\r\n>... Everyone ready?\r\n>... This triggers the finale.",
            ">... Carrying through combat...\r\n>... [gunfire]\r\n>... <size=200%><color=red>I can't shoot back!</color></size>",
            ">... The fog's lifting!\r\n>... <size=200%><color=red>I can see the exit!</color></size>\r\n>... Keep inserting cells.",
            ">... <size=200%><color=red>Scout near the cluster!</color></size>\r\n>... Stay quiet.\r\n>... Don't wake it.",
            ">... Zone 45, Zone 32, Zone 67.\r\n>... <size=200%><color=red>Three cells confirmed!</color></size>\r\n>... Let's collect them.",
            ">... [metal clanging]\r\n>... Cell inserted.\r\n>... <size=200%><color=red>Generator powering up!</color></size>",
            ">... <size=200%><color=red>The alarm won't stop!</color></size>\r\n>... Final cell triggered it.\r\n>... We have to survive.",
            ">... My lungs are burning.\r\n>... This fog...\r\n>... <size=200%><color=red>Hurry with those generators!</color></size>",
            ">... [whispering] Cell's right there.\r\n>... <size=200%><color=red>Sleepers all around it!</color></size>\r\n>... Stealth approach.",
            ">... <size=200%><color=red>Fog's down to ankle level!</color></size>\r\n>... One more cell should clear it.\r\n>... Almost there!",
            ">... Terminal locked.\r\n>... Can't find cell locations.\r\n>... <size=200%><color=red>Hack it or search blind!</color></size>",
            ">... [grunting with effort]\r\n>... These stairs...\r\n>... <size=200%><color=red>Carrying this uphill!</color></size>",
            ">... <size=200%><color=red>Last generator activated!</color></size>\r\n>... [siren wailing]\r\n>... Here they come!",
            ">... Fog Repellers help.\r\n>... But generators clear it fully.\r\n>... <size=200%><color=red>Keep collecting cells!</color></size>",
            ">... [static]\r\n>... <size=200%><color=red>Lost in the fog!</color></size>\r\n>... Which way to cluster?",
            ">... The cells are spread out.\r\n>... <size=200%><color=red>This'll take multiple trips!</color></size>\r\n>... Let's get moving.",
            ">... <size=200%><color=red>Charger incoming!</color></size>\r\n>... Drop the cell!\r\n>... Fight or die!",
            ">... Generator cluster found.\r\n>... Now find the cells.\r\n>... <size=200%><color=red>Check terminals for locations!</color></size>",
            ">... [alarm blaring]\r\n>... <size=200%><color=red>CLASS V ALARM!</color></size>\r\n>... Final cell did this!",
            ">... Two cells left.\r\n>... <size=200%><color=red>Almost done!</color></size>\r\n>... Then we trigger finale.",
            ">... The fog hides everything.\r\n>... Can't see threats.\r\n>... <size=200%><color=red>Clear it with generators!</color></size>",
            ">... <size=200%><color=red>Cell in Zone 212!</color></size>\r\n>... That's the deepest zone.\r\n>... Long journey ahead.",
            ">... [breathing mask]\r\n>... Infectious fog confirmed.\r\n>... <size=200%><color=red>Don't stay in it long!</color></size>",
            ">... Generator 4 online.\r\n>... <size=200%><color=red>One more to go!</color></size>\r\n>... Then extraction opens.",
            ">... [heavy footsteps approaching]\r\n>... <size=200%><color=red>Something's coming!</color></size>\r\n>... Secure the cell!",
            ">... <size=200%><color=red>The cluster needs power!</color></size>\r\n>... Five cells scattered.\r\n>... Better start searching.",
            ">... Fog's clearing beautifully.\r\n>... Each cell helps.\r\n>... <size=200%><color=red>Keep them coming!</color></size>",
            ">... [panting]\r\n>... Zone 54 to cluster.\r\n>... <size=200%><color=red>That's a long haul!</color></size>",
            ">... <size=200%><color=red>Blood door blocks the cell!</color></size>\r\n>... We need to trigger it.\r\n>... Clear the wave first.",
            ">... Terminal shows four cells.\r\n>... <size=200%><color=red>Wait, the count says five!</color></size>\r\n>... One's hidden somewhere.",
            ">... [static]\r\n>... Cell secured from Zone 33.\r\n>... <size=200%><color=red>Returning to cluster now!</color></size>",
            ">... <size=200%><color=red>Fog's infectious here!</color></size>\r\n>... My vision's blurring.\r\n>... [coughing]",
            ">... The weight distribution's off.\r\n>... <size=200%><color=red>Help me balance this!</color></size>\r\n>... I'm gonna drop it.",
            ">... [alarm wailing]\r\n>... <size=200%><color=red>Error Alarm from final cell!</color></size>\r\n>... Can't turn it off!",
            ">... <size=200%><color=red>Generator cluster located!</color></size>\r\n>... Zone 41 central hub.\r\n>... Mark your maps.",
            ">... Three cells down.\r\n>... Fog's at knee level now.\r\n>... <size=200%><color=red>Progress!</color></size>",
            ">... [gunfire]\r\n>... Sleepers woke up!\r\n>... <size=200%><color=red>Protect the cell carrier!</color></size>",
            ">... <size=200%><color=red>The fog came back!</color></size>\r\n>... After final cell insertion.\r\n>... We're blind again!",
            ">... Terminal query: POWER_CELL.\r\n>... <size=200%><color=red>Five locations displayed!</color></size>\r\n>... Writing them down.",
            ">... [whispering] Giant sleeping.\r\n>... Cell's behind it.\r\n>... <size=200%><color=red>Go around quietly!</color></size>",
            ">... <size=200%><color=red>Last cell ready!</color></size>\r\n>... Everyone at full health?\r\n>... Check your ammo.",
            ">... The cluster hums with power.\r\n>... <size=200%><color=red>One more generator!</color></size>\r\n>... Then we're done.",
            ">... [coughing]\r\n>... Can barely breathe.\r\n>... <size=200%><color=red>These generators better clear the air!</color></size>",
            ">... <size=200%><color=red>Cell located!</color></size>\r\n>... It's in the flooded section.\r\n>... Watch your step.",
            ">... Four generators online.\r\n>... <size=200%><color=red>Final one triggers alarm!</color></size>\r\n>... Prepare yourselves.",
            ">... [metal scraping]\r\n>... Cell's stuck.\r\n>... <size=200%><color=red>Help me pull it free!</color></size>",
            ">... <size=200%><color=red>Continuous spawns active!</color></size>\r\n>... Strikers every few seconds.\r\n>... This is insane!",
            ">... The fog makes navigation hell.\r\n>... <size=200%><color=red>Insert cells to see!</color></size>\r\n>... Clear it up.",
            ">... [alarm blaring]\r\n>... <size=200%><color=red>Final generator online!</color></size>\r\n>... Get to extraction!",
            ">... <size=200%><color=red>Scout patrolling near cluster!</color></size>\r\n>... Wait for it to pass.\r\n>... Then insert the cell.",
            ">... Zone 99 has a cell.\r\n>... That's the opposite end.\r\n>... <size=200%><color=red>Long walk ahead!</color></size>",
            ">... [panting]\r\n>... My arms are shaking.\r\n>... <size=200%><color=red>This cell's so heavy!</color></size>",
            ">... <size=200%><color=red>The fog's clearing!</color></size>\r\n>... I can see corridors now.\r\n>... Keep it up!",
            ">... Terminal shows locked zone.\r\n>... Cell's inside.\r\n>... <size=200%><color=red>Find the zone key!</color></size>",
            ">... [static]\r\n>... Two cells remaining.\r\n>... <size=200%><color=red>Then we face the finale!</color></size>",
            ">... <size=200%><color=red>Giant blocking the cluster!</color></size>\r\n>... We need to clear it.\r\n>... [gunfire]",
            ">... The cluster's humming louder.\r\n>... <size=200%><color=red>More power with each cell!</color></size>\r\n>... It's working.",
            ">... [coughing fits]\r\n>... Infectious fog is spreading.\r\n>... <size=200%><color=red>Get those generators running!</color></size>",
            ">... <size=200%><color=red>Cell secured!</color></size>\r\n>... Now the long walk back.\r\n>... Stay together.",
            ">... Five cells, five zones.\r\n>... Simple math.\r\n>... <size=200%><color=red>Not simple execution!</color></size>",
            ">... [alarm wailing]\r\n>... <size=200%><color=red>Last cell triggered this!</color></size>\r\n>... Waves incoming!",
            ">... <size=200%><color=red>The fog's at ceiling level!</color></size>\r\n>... Can't see anything.\r\n>... Insert cells fast!",
            ">... Cell carrier down!\r\n>... <size=200%><color=red>Someone grab the cell!</color></size>\r\n>... Don't let it sit!",
            ">... [heavy breathing]\r\n>... Halfway to cluster.\r\n>... <size=200%><color=red>Keep pushing!</color></size>",
            ">... <size=200%><color=red>Terminal hacked!</color></size>\r\n>... Cell locations revealed.\r\n>... Zone 21, 34, 67, 82, 95.",
            ">... The cluster needs juice.\r\n>... <size=200%><color=red>Find those Power Cells!</color></size>\r\n>... Move out!",
            ">... [gunfire]\r\n>... Can't fight while carrying.\r\n>... <size=200%><color=red>Cover the carrier!</color></size>",
            ">... <size=200%><color=red>Fog's clearing nicely!</color></size>\r\n>... Three cells inserted.\r\n>... Two more to go.",
            ">... Zone 45 cell retrieved.\r\n>... <size=200%><color=red>Heading back now!</color></size>\r\n>... Watch for ambush.",
            ">... [alarm blaring]\r\n>... CLASS V from final cell!\r\n>... <size=200%><color=red>Defend the cluster!</color></size>",
            ">... <size=200%><color=red>The fog returns!</color></size>\r\n>... After final generator.\r\n>... Someone lied about this!",
            ">... Cell's in the vents.\r\n>... <size=200%><color=red>How do we get it?!</color></size>\r\n>... There must be access.",
            ">... [panting]\r\n>... Four cells done.\r\n>... <size=200%><color=red>One more!</color></size>",
            ">... <size=200%><color=red>Scout charging!</color></size>\r\n>... Drop the cell!\r\n>... Fight it off!",
            ">... The fog's so thick...\r\n>... Lost my bearings.\r\n>... <size=200%><color=red>Where's the cluster?!</color></size>",
            ">... [metal clanking]\r\n>... <size=200%><color=red>Generator activated!</color></size>\r\n>... Fog's lowering!",
            ">... <size=200%><color=red>Final cell in hand!</color></size>\r\n>... Everyone ready?\r\n>... This triggers everything.",
            ">... Terminal shows Zone 212.\r\n>... <size=200%><color=red>That's deep in the complex!</color></size>\r\n>... We'll need supplies.",
            ">... [coughing]\r\n>... This fog is poison.\r\n>... <size=200%><color=red>Hurry!</color></size>",
            ">... <size=200%><color=red>Two cells left to find!</color></size>\r\n>... Then we trigger finale.\r\n>... Get ready.",
            ">... The cluster's location is key.\r\n>... <size=200%><color=red>Mark it clearly!</color></size>\r\n>... We'll return often.",
            ">... [alarm blaring]\r\n>... <size=200%><color=red>Error Alarm won't stop!</color></size>\r\n>... Final cell did this!",
            ">... <size=200%><color=red>Charger near the cell!</color></size>\r\n>... Take it down first.\r\n>... Then grab the cell.",
            ">... Fog's at waist level.\r\n>... Getting better.\r\n>... <size=200%><color=red>Keep inserting cells!</color></size>",
            ">... [static]\r\n>... Cell location confirmed.\r\n>... <size=200%><color=red>Moving to retrieve!</color></size>",
            ">... <size=200%><color=red>The cluster's defended!</color></size>\r\n>... Clear Sleepers first.\r\n>... Then insert cells safely.",
            ">... Three more cells needed.\r\n>... Fog's still dense.\r\n>... <size=200%><color=red>This is taking forever!</color></size>",
            ">... [heavy footsteps]\r\n>... <size=200%><color=red>Tank approaching!</color></size>\r\n>... Secure the cell first!",
            ">... <size=200%><color=red>Generator 5 online!</color></size>\r\n>... [alarm wailing]\r\n>... Final alarm triggered!",
            ">... The fog hides the path.\r\n>... <size=200%><color=red>Follow the beacon!</color></size>\r\n>... Back to cluster.",
            ">... [gunfire]\r\n>... They're everywhere!\r\n>... <size=200%><color=red>Protect the cell carrier!</color></size>",
            ">... <size=200%><color=red>Cell's in a locked terminal room!</color></size>\r\n>... Need to hack the door.\r\n>... Someone get on it.",
            ">... One more generator.\r\n>... <size=200%><color=red>Then we extract!</color></size>\r\n>... Almost there!",
            ">... [coughing heavily]\r\n>... Fog's infectious.\r\n>... <size=200%><color=red>I need disinfection!</color></size>",
            ">... <size=200%><color=red>The fog's completely gone!</color></size>\r\n>... All cells inserted.\r\n>... Now survive the alarm.",
            ">... Terminal query complete.\r\n>... <size=200%><color=red>All five cells located!</color></size>\r\n>... Let's collect.",
            ">... [whispering] Shadow sleeping.\r\n>... Cell's next to it.\r\n>... <size=200%><color=red>Stealth grab!</color></size>",
            ">... <size=200%><color=red>Last cell triggers CLASS V!</color></size>\r\n>... Stock up on ammo.\r\n>... Check your tools.",
            ">... The weight of these...\r\n>... [grunting]\r\n>... <size=200%><color=red>My back's killing me!</color></size>",
            ">... [alarm blaring]\r\n>... <size=200%><color=red>Continuous spawns active!</color></size>\r\n>... They won't stop coming!",
            ">... <size=200%><color=red>Fog's lifting progressively!</color></size>\r\n>... Each cell helps.\r\n>... Keep it up.",
            ">... Cell in Zone 88.\r\n>... That's past security.\r\n>... <size=200%><color=red>We'll trigger sensors!</color></size>",
            ">... [static]\r\n>... <size=200%><color=red>Lost contact!</color></size>\r\n>... Fog's too thick.",
            ">... <size=200%><color=red>Generator cluster activated!</color></size>\r\n>... Fog clearing fast.\r\n>... We can see now!",
            ">... Four cells collected.\r\n>... <size=200%><color=red>One more to find!</color></size>\r\n>... Then finale.",
            ">... [panting]\r\n>... Carrying through combat.\r\n>... <size=200%><color=red>I'm defenseless!</color></size>",
            ">... <size=200%><color=red>The fog returns after final cell!</color></size>\r\n>... I told you!\r\n>... No one listened!",
            ">... Terminal locked behind bioscan.\r\n>... <size=200%><color=red>Someone stand in it!</color></size>\r\n>... Need cell locations.",
            ">... [alarm wailing]\r\n>... <size=200%><color=red>Final generator triggered it!</color></size>\r\n>... Get ready to fight!",
            ">... <size=200%><color=red>Mother near the cluster!</color></size>\r\n>... Kill it before inserting.\r\n>... Too dangerous.",
            ">... The fog's at ankle level.\r\n>... Almost clear.\r\n>... <size=200%><color=red>One more cell!</color></size>",
            ">... [heavy breathing]\r\n>... Zone 67 to 41.\r\n>... <size=200%><color=red>Long haul ahead!</color></size>",
            ">... <size=200%><color=red>Cell secured from deep zone!</color></size>\r\n>... Now the journey back.\r\n>... Stay alert.",
            ">... Five generators needed.\r\n>... <size=200%><color=red>Five cells to find!</color></size>\r\n>... Let's move.",
            ">... [gunfire]\r\n>... <size=200%><color=red>Giant blocking path!</color></size>\r\n>... Can't carry cell past it!",
            ">... <size=200%><color=red>The fog's completely cleared!</color></size>\r\n>... All generators online.\r\n>... Now run!",
            ">... Terminal shows Zone 21.\r\n>... <size=200%><color=red>That's behind blood door!</color></size>\r\n>... We'll need to fight.",
            ">... [coughing]\r\n>... Infectious fog confirmed.\r\n>... <size=200%><color=red>Get generators online fast!</color></size>",
            ">... <size=200%><color=red>Two cells remaining!</color></size>\r\n>... Then we face finale.\r\n>... Prep your gear.",
            ">... Cell carrier ambushed!\r\n>... <size=200%><color=red>Someone grab it!</color></size>\r\n>... Don't leave it!",
            ">... [alarm blaring]\r\n>... <size=200%><color=red>CLASS V ALARM!</color></size>\r\n>... Last cell triggered it!",
            ">... <size=200%><color=red>The cluster's right ahead!</color></size>\r\n>... Almost there.\r\n>... Stay focused.",
            ">... Fog Repellers aren't enough.\r\n>... <size=200%><color=red>Need those generators!</color></size>\r\n>... Find the cells.",
            ">... [static]\r\n>... Cell from Zone 45.\r\n>... <size=200%><color=red>Returning to cluster!</color></size>",
            ">... <size=200%><color=red>Scout near the cell!</color></size>\r\n>... Don't wake it.\r\n>... Stealth approach.",
            ">... Three cells down.\r\n>... <size=200%><color=red>Two to go!</color></size>\r\n>... Keep it up.",
            ">... [heavy footsteps]\r\n>... Something big near cluster.\r\n>... <size=200%><color=red>Clear it before inserting!</color></size>",
            ">... <size=200%><color=red>Final cell ready!</color></size>\r\n>... Everyone at cluster?\r\n>... Let's do this.",
            ">... The fog makes this impossible.\r\n>... <size=200%><color=red>Clear it with cells!</color></size>\r\n>... Progressive improvement.",
            ">... [panting]\r\n>... <size=200%><color=red>These cells are killing me!</color></size>\r\n>... How many left?",
            ">... <size=200%><color=red>Generator activated!</color></size>\r\n>... [humming power]\r\n>... Fog's lowering!",
            ">... Cell location: Zone 212.\r\n>... <size=200%><color=red>That's the deepest zone!</color></size>\r\n>... Long trip.",
            ">... [alarm wailing]\r\n>... <size=200%><color=red>Error Alarm from finale!</color></size>\r\n>... Can't shut it off!",
            ">... <size=200%><color=red>The fog's returning!</color></size>\r\n>... After final cell.\r\n>... This is bad!",
            ">... Terminal hacked successfully.\r\n>... <size=200%><color=red>All cell locations shown!</color></size>\r\n>... Writing coordinates.",
            ">... [gunfire]\r\n>... <size=200%><color=red>Charger incoming!</color></size>\r\n>... Drop the cell!",
            ">... <size=200%><color=red>One more generator!</color></size>\r\n>... Then extraction.\r\n>... Almost done!",
            ">... The cluster hums with power.\r\n>... <size=200%><color=red>Insert the final cell!</color></size>\r\n>... Here we go.",
            ">... [coughing fits]\r\n>... <size=200%><color=red>This fog is toxic!</color></size>\r\n>... Hurry with generators!",
            ">... <size=200%><color=red>Cell's behind security door!</color></size>\r\n>... Need keycard access.\r\n>... Check terminals.",
            ">... Four generators online.\r\n>... Fog's almost gone.\r\n>... <size=200%><color=red>One more cell!</color></size>",
            ">... [static]\r\n>... Lost in fog again.\r\n>... <size=200%><color=red>Which way?!</color></size>",
            ">... <size=200%><color=red>Continuous waves started!</color></size>\r\n>... Final cell triggered it.\r\n>... They won't stop!",
            ">... The fog clears beautifully.\r\n>... <size=200%><color=red>Each cell makes difference!</color></size>\r\n>... Keep going.",
            ">... [whispering] Sleepers everywhere.\r\n>... Cell's in the middle.\r\n>... <size=200%><color=red>Careful approach!</color></size>",
            ">... <size=200%><color=red>Last cell in hand!</color></size>\r\n>... To the cluster.\r\n>... Final push!",
            ">... Zone 54 has a cell.\r\n>... <size=200%><color=red>That's across the complex!</color></size>\r\n>... Long walk.",
            ">... [alarm blaring]\r\n>... <size=200%><color=red>Final generator online!</color></size>\r\n>... Run for extraction!",
            ">... <size=200%><color=red>Tank near the cluster!</color></size>\r\n>... Everyone focus fire.\r\n>... Take it down!",
            ">... Two cells left.\r\n>... <size=200%><color=red>Then we trigger finale!</color></size>\r\n>... Get ready.",
            ">... [heavy breathing]\r\n>... My arms are done.\r\n>... <size=200%><color=red>Someone else carry this!</color></size>",
            ">... <size=200%><color=red>The fog's at knee level!</color></size>\r\n>... Much better.\r\n>... Keep inserting cells.",
            ">... Terminal shows locked room.\r\n>... Cell's inside.\r\n>... <size=200%><color=red>Find the key!</color></size>",
            ">... [static]\r\n>... <size=200%><color=red>Cell secured!</color></size>\r\n>... Heading back.",
            ">... <size=200%><color=red>Shadow blocking the cluster!</color></size>\r\n>... Don't let it teleport.\r\n>... Kill it fast.",
            ">... Three cells inserted.\r\n>... Fog's lifting.\r\n>... <size=200%><color=red>Two more to go!</color></size>",
            ">... [gunfire]\r\n>... Can't defend while carrying.\r\n>... <size=200%><color=red>Team, cover me!</color></size>",
            ">... <size=200%><color=red>Final cell triggers alarm!</color></size>\r\n>... Ammo check.\r\n>... Tool check.",
            ">... The cluster's central location.\r\n>... <size=200%><color=red>Easy to find!</color></size>\r\n>... Mark your maps.",
            ">... [coughing]\r\n>... Infectious fog spreading.\r\n>... <size=200%><color=red>Get to disinfection!</color></size>",
            ">... <size=200%><color=red>All cells located!</color></size>\r\n>... Five zones marked.\r\n>... Let's collect them.",
            ">... Cell in flooded section.\r\n>... <size=200%><color=red>Watch your footing!</color></size>\r\n>... Don't drop it.",
            ">... [alarm wailing]\r\n>... <size=200%><color=red>CLASS V from finale!</color></size>\r\n>... Waves incoming!",
            ">... <size=200%><color=red>The fog's completely gone!</color></size>\r\n>... Perfect visibility.\r\n>... All cells inserted!",
            ">... Terminal query: POWER_CELL.\r\n>... <size=200%><color=red>Five results returned!</color></size>\r\n>... Note the zones.",
            ">... [whispering] Giant sleeping.\r\n>... <size=200%><color=red>Cell's right behind it!</color></size>\r\n>... Sneak around.",
            ">... <size=200%><color=red>One cell left!</color></size>\r\n>... Then finale.\r\n>... Everyone ready?",
            ">... The cluster needs power.\r\n>... <size=200%><color=red>Find those cells!</color></size>\r\n>... Move out now!",
            ">... [heavy footsteps]\r\n>... <size=200%><color=red>Something's approaching!</color></size>\r\n>... Secure the cell!",
            ">... <size=200%><color=red>Generator cluster activated!</color></size>\r\n>... Fog's clearing.\r\n>... We can see!",
            ">... Four cells done.\r\n>... <size=200%><color=red>Final one ahead!</color></size>\r\n>... Let's finish this.",
            ">... [panting]\r\n>... Carrying through fog.\r\n>... <size=200%><color=red>Can't see anything!</color></size>",
            ">... <size=200%><color=red>The fog returns!</color></size>\r\n>... Final cell triggered it.\r\n>... We're blind!",
            ">... Terminal behind blood door.\r\n>... <size=200%><color=red>Need to trigger alarm!</color></size>\r\n>... Then check locations.",
            ">... [alarm blaring]\r\n>... <size=200%><color=red>Final alarm triggered!</color></size>\r\n>... Defend and extract!",
            ">... <size=200%><color=red>Mother spawning children!</color></size>\r\n>... Near the cluster.\r\n>... Clear them all!",
            ">... The fog's at waist level.\r\n>... Getting better.\r\n>... <size=200%><color=red>One more cell!</color></size>",
            ">... [metal clanking]\r\n>... <size=200%><color=red>Cell inserted!</color></size>\r\n>... Generator powering up!",
            ">... <size=200%><color=red>Cell from Zone 99!</color></size>\r\n>... That's far.\r\n>... Long journey back.",
            ">... Five generators needed.\r\n>... <size=200%><color=red>Let's find those cells!</color></size>\r\n>... Check terminals first.",
            ">... [gunfire]\r\n>... <size=200%><color=red>Berserker incoming!</color></size>\r\n>... Drop the cell!",
            ">... <size=200%><color=red>Fog completely cleared!</color></size>\r\n>... All generators online.\r\n>... Extract now!",
            ">... Terminal shows Zone 45.\r\n>... <size=200%><color=red>That's past the Giant!</color></size>\r\n>... We'll have to fight.",
            ">... [coughing]\r\n>... This fog's killing me.\r\n>... <size=200%><color=red>Hurry with generators!</color></size>",
            ">... <size=200%><color=red>Three cells left!</color></size>\r\n>... Then finale.\r\n>... Stock up now.",
            ">... Cell carrier hit!\r\n>... <size=200%><color=red>Grab the cell!</color></size>\r\n>... Keep it moving!",
            ">... [alarm wailing]\r\n>... <size=200%><color=red>Error Alarm!</color></size>\r\n>... Final cell did this!",
            ">... <size=200%><color=red>The cluster's defended!</color></size>\r\n>... Clear area first.\r\n>... Then insert safely.",
            ">... Fog Repellers failing.\r\n>... <size=200%><color=red>Need generators online!</color></size>\r\n>... Find cells fast.",
            ">... [static]\r\n>... Cell from Zone 67.\r\n>... <size=200%><color=red>Returning now!</color></size>",
            ">... <size=200%><color=red>Charger near cell!</color></size>\r\n>... Kill it first.\r\n>... Then collect.",
            ">... Two cells done.\r\n>... <size=200%><color=red>Three to go!</color></size>\r\n>... Keep moving.",
            ">... [heavy breathing]\r\n>... Something big ahead.\r\n>... <size=200%><color=red>Clear before inserting!</color></size>",
        }))!);
        #endregion
    }
}
