using AutogenRundown.DataBlocks.Enums;

namespace AutogenRundown.DataBlocks.Objectives;

/// <summary>
/// Intel pools for the AlphaTerminalCommand objective. One line is picked at random
/// from the union of the five themed pools and pushed onto the elevator-drop
/// transmission slot.
///
/// Format conventions for every entry:
/// - 3-4 lines, separated by `\r\n`
/// - Each line prefixed with `>... ` (radio chatter) or `>>` (transcript header)
/// - Exactly one `<size=200%><color=red>X</color></size>` highlight on the urgent phrase
/// - Exactly one bracketed audio cue per entry (e.g. `[static]`, `[carrier wave]`,
///   `[wind]`, `[hum]`, `[breathing]`, `[no signal]`,
///   `[Encryption checksum mismatch. Contact your IT administrator]`)
/// - The literal token `{COMMAND}` is replaced at pick time with the rolled
///   backdoor command name (one of OVERRIDE_INITIALIZATION, EXEC_OVERRIDE,
///   INTERPRET_NAV_DATA, COPY_GEN_INDEX_COMPLETE_DB)
/// - Dimension names are NEVER spoken. Use indirect description ("the dust",
///   "open sky", "the ridge", "the topology held").
/// - Voices: prisoner radio (Bishop GO-1395, Woods F-2056, Hackett O-4711,
///   Dauda T-3701), researcher logs (Durant B255, Stokes B193, Schaeffer T-3894,
///   Connor B229, Hammerstein B014, Teale B023), Warden corrupted output
///   (`WRDN: {COMMAND}`), KDS field (Piros A134), corp redactors
///   (Lockwood A074, Johanson A029), HearSay/BIOCOM/EBDT auto-transcripts,
///   Mr. Truth fragments and State of Truth AM, recovered MWP memory bursts.
/// </summary>
public partial record WardenObjective
{
    #region Prisoner radio — pre-jump nerves, in-dimension reactions, transfer chatter
    public static readonly List<string> AlphaTerminalCommandIntel_PrisonerRadio = new()
    {
        ">... Woods F-2056 to gate\r\n>... cube's locked, MWP humming\r\n>... <size=200%><color=red>do not let go of it</color></size>\r\n>... [carrier wave]",
        ">... GO-1395 chip ping\r\n>... \"hand on the projector, knees bent\"\r\n>... <size=200%><color=red>that's not encouraging</color></size>\r\n>... [breathing]",
        ">... O-4711 to channel 1\r\n>... \"team scan in three. two.\"\r\n>... <size=200%><color=red>floor is not warm</color></size>\r\n>... [hiss]",
        ">... T-3701 pre-jump check\r\n>... MWP coupling green\r\n>... MWP coupling <size=200%><color=red>not green</color></size>\r\n>... [carrier wave]",
        ">... Bishop GO-1395 last call\r\n>... \"if I don't come back\"\r\n>... <size=200%><color=red>that's the deal</color></size>\r\n>... [static]",
        ">... Woods to Dauda\r\n>... \"have you done one of these before\"\r\n>... <size=200%><color=red>\"twice was enough\"</color></size>\r\n>... [breathing]",
        ">... Hackett O-4711 fumbling\r\n>... \"safety lever's on the right, right?\"\r\n>... \"<size=200%><color=red>your other left</color></size>\"\r\n>... [tool clatter]",
        ">... GO-1395 cold open\r\n>... mounting platform handshake nominal\r\n>... handshake answered by <size=200%><color=red>something else</color></size>\r\n>... [carrier wave]",
        ">... Dauda T-3701 to gate\r\n>... \"projector's vibrating\"\r\n>... \"<size=200%><color=red>at this frequency?</color></size>\"\r\n>... [hum]",
        ">... Woods F-2056 muttering\r\n>... \"I don't like missions where the briefing skips a paragraph\"\r\n>... <size=200%><color=red>\"this one skipped four\"</color></size>\r\n>... [breathing]",
        ">... GO-1395 first seconds\r\n>... \"sky\"\r\n>... \"<size=200%><color=red>sky</color></size>\"\r\n>... [wind]",
        ">... Hackett O-4711 disoriented\r\n>... \"is that the sun\"\r\n>... \"<size=200%><color=red>I can't stop looking at it</color></size>\"\r\n>... [wind]",
        ">... T-3701 audio dump\r\n>... \"the air tastes wrong but it tastes like air\"\r\n>... <size=200%><color=red>chip flagging respiratory event</color></size>\r\n>... [breathing]",
        ">... Woods to channel 1\r\n>... \"sand under boots, not steel\"\r\n>... \"<size=200%><color=red>only ours</color></size>\"\r\n>... [wind]",
        ">... Bishop GO-1395 quiet\r\n>... \"the horizon is too far\"\r\n>... <size=200%><color=red>\"this is wrong\"</color></size>\r\n>... [carrier wave]",
        ">... Hackett O-4711, channel 2\r\n>... \"are those structures or rocks\"\r\n>... <size=200%><color=red>\"too even for rocks\"</color></size>\r\n>... [wind]",
        ">... T-3701 to team\r\n>... \"shadows are cast wrong\"\r\n>... \"shadows cast <size=200%><color=red>both ways</color></size>\"\r\n>... [no audio]",
        ">... Woods F-2056 muttering\r\n>... \"two suns?\"\r\n>... \"<size=200%><color=red>two suns</color></size>\"\r\n>... [wind]",
        ">... GO-1395 cold\r\n>... \"the dust is gold\"\r\n>... \"the dust is <size=200%><color=red>moving</color></size>\"\r\n>... [breathing]",
        ">... Dauda calm\r\n>... \"team, hands off your weapons until I call it\"\r\n>... <size=200%><color=red>\"because nothing's shooting yet\"</color></size>\r\n>... [hiss]",
        ">... Hackett to channel 1\r\n>... \"this place is the same as last drop\"\r\n>... <size=200%><color=red>\"exactly the same\"</color></size>\r\n>... [wind]",
        ">... GO-1395 reading\r\n>... \"chronometer says we've been here four seconds\"\r\n>... <size=200%><color=red>\"feels like fourteen minutes\"</color></size>\r\n>... [no signal]",
        ">... Woods to team\r\n>... \"terminal's on the rise, west side\"\r\n>... <size=200%><color=red>\"don't ask\"</color></size>\r\n>... [boot crunch]",
        ">... Hackett O-4711 nervous\r\n>... \"the screen's on\"\r\n>... <size=200%><color=red>\"who turned it on\"</color></size>\r\n>... [keyboard]",
        ">... T-3701 reading\r\n>... \"input prompt expects {COMMAND}\"\r\n>... <size=200%><color=red>\"how does it know\"</color></size>\r\n>... [keyboard]",
        ">... Bishop GO-1395 quiet\r\n>... \"keyboard's warm\"\r\n>... <size=200%><color=red>\"recently\"</color></size>\r\n>... [breathing]",
        ">... Woods F-2056\r\n>... \"the casing's old\"\r\n>... <size=200%><color=red>\"older than the company\"</color></size>\r\n>... [keyboard]",
        ">... Hackett O-4711\r\n>... \"command field's pre-filled\"\r\n>... <size=200%><color=red>\"with {COMMAND}\"</color></size>\r\n>... [hiss]",
        ">... T-3701 to channel 3\r\n>... \"manufacturer plate's blank\"\r\n>... <size=200%><color=red>\"or it never had one\"</color></size>\r\n>... [breathing]",
        ">... GO-1395 closing in\r\n>... \"display's running diagnostics\"\r\n>... <size=200%><color=red>\"on us\"</color></size>\r\n>... [carrier wave]",
        ">... Woods to team\r\n>... \"approach slow, the prompt's blinking\"\r\n>... <size=200%><color=red>\"not in unison with my heart\"</color></size>\r\n>... [breathing]",
        ">... Dauda flat\r\n>... \"I've keyed {COMMAND}\"\r\n>... <size=200%><color=red>\"the screen pressed it\"</color></size>\r\n>... [keyboard]",
        ">... GO-1395 hard\r\n>... \"executing {COMMAND}\"\r\n>... <size=200%><color=red>\"it executed twice\"</color></size>\r\n>... [keyboard]",
        ">... Hackett O-4711\r\n>... \"transfer initiated\"\r\n>... <size=200%><color=red>\"the terminal did\"</color></size>\r\n>... [hum]",
        ">... Woods F-2056\r\n>... \"{COMMAND} accepted\"\r\n>... <size=200%><color=red>\"reply was in our voices\"</color></size>\r\n>... [carrier wave]",
        ">... T-3701 reading\r\n>... \"checksum on {COMMAND} valid\"\r\n>... \"checksum on operator <size=200%><color=red>invalid</color></size>\"\r\n>... [hiss]",
        ">... Bishop GO-1395\r\n>... \"keyed it. it didn't take.\"\r\n>... <size=200%><color=red>\"it took the third one before I keyed it\"</color></size>\r\n>... [keyboard]",
        ">... Hackett to channel 2\r\n>... \"progress bar moving\"\r\n>... <size=200%><color=red>\"backwards\"</color></size>\r\n>... [hum]",
        ">... Woods F-2056\r\n>... \"display's asking confirm\"\r\n>... <size=200%><color=red>\"my date of birth\"</color></size>\r\n>... [keyboard]",
        ">... Dauda T-3701\r\n>... \"{COMMAND} returned 0x00\"\r\n>... <size=200%><color=red>\"that's also nothing\"</color></size>\r\n>... [carrier wave]",
        ">... GO-1395 to team\r\n>... \"transfer started\"\r\n>... <size=200%><color=red>\"holding\"</color></size>\r\n>... [breathing]",
        ">... Hackett O-4711\r\n>... \"the prompt cleared itself\"\r\n>... <size=200%><color=red>\"with my hands\"</color></size>\r\n>... [keyboard]",
        ">... Woods F-2056\r\n>... \"this transfer is taking a while\"\r\n>... <size=200%><color=red>\"briefing was wrong before\"</color></size>\r\n>... [hum]",
        ">... GO-1395 quiet\r\n>... \"chronometer normal\"\r\n>... <size=200%><color=red>\"that's the bad one\"</color></size>\r\n>... [no signal]",
        ">... T-3701 telemetry check\r\n>... \"quantum tether holding at 88%\"\r\n>... <size=200%><color=red>\"quantum tether holding at — \"</color></size>\r\n>... [carrier wave]",
        ">... Hackett nervous\r\n>... \"is it supposed to be this quiet\"\r\n>... <size=200%><color=red>\"no\"</color></size>\r\n>... [wind]",
        ">... Bishop GO-1395\r\n>... \"don't move from the platform\"\r\n>... <size=200%><color=red>\"my boot's stuck\"</color></size>\r\n>... [boot crunch]",
        ">... Woods to team\r\n>... \"I'm seeing something at the ridge\"\r\n>... <size=200%><color=red>\"it's drawing first\"</color></size>\r\n>... [hiss]",
        ">... Dauda to channel 3\r\n>... \"transfer at 40%\"\r\n>... \"transfer at <size=200%><color=red>40%</color></size>\"\r\n>... [hum]",
        ">... Hackett O-4711\r\n>... \"tether reading drifted\"\r\n>... <size=200%><color=red>\"two minutes\"</color></size>\r\n>... [no signal]",
        ">... GO-1395 hard\r\n>... \"comms working but no one's talking\"\r\n>... <size=200%><color=red>\"not on this channel\"</color></size>\r\n>... [carrier wave]",
        ">... Woods F-2056 cold\r\n>... \"the dust is settling on us\"\r\n>... <size=200%><color=red>\"it's settling against the wind\"</color></size>\r\n>... [wind]",
        ">... T-3701\r\n>... \"transfer rate dropped\"\r\n>... <size=200%><color=red>\"transfer rate not real\"</color></size>\r\n>... [hum]",
        ">... Hackett quiet\r\n>... \"{COMMAND} is still on the screen\"\r\n>... <size=200%><color=red>\"or it's stuck\"</color></size>\r\n>... [keyboard]",
        ">... GO-1395 hard\r\n>... \"distant low roar, west\"\r\n>... <size=200%><color=red>\"all directions\"</color></size>\r\n>... [low rumble]",
        ">... Woods F-2056\r\n>... \"something's coming\"\r\n>... <size=200%><color=red>\"hold the platform\"</color></size>\r\n>... [boot rush]",
        ">... Hackett O-4711\r\n>... \"motion at the ridge\"\r\n>... <size=200%><color=red>\"all of the motion\"</color></size>\r\n>... [growl]",
        ">... Dauda T-3701\r\n>... \"do not engage, transfer's almost done\"\r\n>... <size=200%><color=red>\"engagement engaged us\"</color></size>\r\n>... [hiss]",
        ">... Bishop GO-1395\r\n>... \"hostile contact, fifteen meters\"\r\n>... <size=200%><color=red>\"already past us\"</color></size>\r\n>... [boot rush]",
        ">... Woods to team\r\n>... \"this is the spawn\"\r\n>... <size=200%><color=red>\"this is what comes back\"</color></size>\r\n>... [growl]",
        ">... Hackett scared\r\n>... \"how big\"\r\n>... <size=200%><color=red>\"that big\"</color></size>\r\n>... [low rumble]",
        ">... T-3701 cold\r\n>... \"do not clear the wave\"\r\n>... <size=200%><color=red>\"the wave clears itself\"</color></size>\r\n>... [hiss]",
        ">... GO-1395\r\n>... \"transfer's at 90\"\r\n>... <size=200%><color=red>\"holding\"</color></size>\r\n>... [breathing]",
        ">... Woods F-2056 hard\r\n>... \"thirty seconds\"\r\n>... <size=200%><color=red>\"twenty back to thirty\"</color></size>\r\n>... [hum]",
        ">... GO-1395 fast\r\n>... \"warp tone in five\"\r\n>... <size=200%><color=red>\"in now\"</color></size>\r\n>... [carrier wave]",
        ">... Hackett shouting\r\n>... \"hand on the projector!\"\r\n>... <size=200%><color=red>\"WHOSE HAND\"</color></size>\r\n>... [hum]",
        ">... Woods F-2056\r\n>... \"projector spooling\"\r\n>... <size=200%><color=red>\"projector chose us\"</color></size>\r\n>... [hum]",
        ">... T-3701 calm\r\n>... \"closing eyes for the warp\"\r\n>... <size=200%><color=red>\"can't close them\"</color></size>\r\n>... [hiss]",
        ">... Bishop GO-1395\r\n>... \"team count: four\"\r\n>... <size=200%><color=red>\"team count: four — different four\"</color></size>\r\n>... [carrier wave]",
        ">... Hackett O-4711\r\n>... \"warp\"\r\n>... <size=200%><color=red>\"warp not finished\"</color></size>\r\n>... [hum]",
        ">... Woods F-2056\r\n>... \"feet leaving the floor\"\r\n>... <size=200%><color=red>\"both\"</color></size>\r\n>... [carrier wave]",
        ">... GO-1395 last\r\n>... \"don't let go of the cube\"\r\n>... <size=200%><color=red>\"the cube let go of me\"</color></size>\r\n>... [carrier wave]",
        ">... Woods F-2056 debrief\r\n>... \"saw a structure on the horizon\"\r\n>... <size=200%><color=red>\"Warden said no horizon\"</color></size>\r\n>... [static]",
        ">... GO-1395 quiet, post-warp\r\n>... \"there were footprints other than ours\"\r\n>... <size=200%><color=red>\"Warden said no\"</color></size>\r\n>... [carrier wave]",
        ">... Hackett O-4711\r\n>... \"the back of my throat tastes like sand\"\r\n>... <size=200%><color=red>\"we never landed\"</color></size>\r\n>... [breathing]",
        ">... T-3701 cold\r\n>... \"my chronometer drifted 40 seconds\"\r\n>... <size=200%><color=red>\"drifted 40 seconds again\"</color></size>\r\n>... [hum]",
        ">... Bishop GO-1395\r\n>... \"saw a figure at the ridge\"\r\n>... <size=200%><color=red>\"waiting\"</color></size>\r\n>... [no audio]",
        ">... Woods F-2056\r\n>... \"my coat has dust I can't shake out\"\r\n>... <size=200%><color=red>\"still gold\"</color></size>\r\n>... [silence]",
        ">... Hackett to channel 2\r\n>... \"been hearing wind in my barracks\"\r\n>... <size=200%><color=red>\"there is now\"</color></size>\r\n>... [wind]",
        ">... GO-1395 closing\r\n>... \"the {COMMAND} prompt is still in my retina\"\r\n>... <size=200%><color=red>\"still there\"</color></size>\r\n>... [breathing]",
    };
    #endregion

    #region Researchers — Project Insight, MWP, membranes, datacubes, Cretasium 77a
    public static readonly List<string> AlphaTerminalCommandIntel_Researchers = new()
    {
        ">... Durant B255 lab note 0042\r\n>... \"membrane stable. topology held.\"\r\n>... <size=200%><color=red>\"the projector did not consult me\"</color></size>\r\n>... [pen on paper]",
        ">... Stokes B193 voice memo, 03:14\r\n>... \"Project Insight bench note re: {COMMAND}\"\r\n>... <size=200%><color=red>\"do not log this\"</color></size>\r\n>... [tap drip]",
        ">... Schaeffer T-3894 telemetry\r\n>... \"quantum frequency drift: 0.04 Hz\"\r\n>... <size=200%><color=red>\"acceptable: 0.00 Hz\"</color></size>\r\n>... [HVAC hum]",
        ">... Durant B255 recovered fragment\r\n>... \"we have left earth\"\r\n>... <size=200%><color=red>\"earth has left us\"</color></size>\r\n>... [pen on paper]",
        ">... Connor B229 audio dump, MWP memory bank\r\n>... [garbled]\r\n>... \"...the gate accepted {COMMAND}, not the operator...\"\r\n>... <size=200%><color=red>[Encryption checksum mismatch. Contact your IT administrator]</color></size>",
        ">... Hammerstein B014 margin note\r\n>... \"Cretasium 77a registers in the dust\"\r\n>... <size=200%><color=red>\"the dimension is the alloy\"</color></size>\r\n>... [page turn]",
        ">... Teale B023 observation log\r\n>... \"the ridgeline structures cast Cretasium glint\"\r\n>... <size=200%><color=red>\"or thirty-eight meters\"</color></size>\r\n>... [pen on paper]",
        ">... Stokes B193, recording 0118\r\n>... \"the operator becomes the projector\"\r\n>... <size=200%><color=red>\"this is the design\"</color></size>\r\n>... [silence]",
        ">... Durant B255 to Schaeffer\r\n>... \"static dimension is a misnomer\"\r\n>... <size=200%><color=red>\"prefer 'patient'\"</color></size>\r\n>... [pen on paper]",
        ">... Schaeffer T-3894 report 41-B\r\n>... \"no entropy reading at the destination\"\r\n>... <size=200%><color=red>\"entropy reading is the destination\"</color></size>\r\n>... [HVAC hum]",
        ">... Durant B255 audio, undated\r\n>... \"projection is not travel\"\r\n>... <size=200%><color=red>\"granted by what\"</color></size>\r\n>... [tape hiss]",
        ">... Stokes B193 lab 6, 02:00\r\n>... \"if I name the destination, it answers\"\r\n>... <size=200%><color=red>\"it has answered\"</color></size>\r\n>... [no audio]",
        ">... Schaeffer T-3894 worksheet\r\n>... datacube address space: 622,811\r\n>... <size=200%><color=red>last entry not authored</color></size>\r\n>... [pen on paper]",
        ">... Hammerstein B014 lecture, undated\r\n>... \"the gate is not a door\"\r\n>... <size=200%><color=red>\"answered by {COMMAND}\"</color></size>\r\n>... [chalk on board]",
        ">... Durant B255 to Connor\r\n>... \"the cube remembers the operator\"\r\n>... <size=200%><color=red>\"this asymmetry is the technology\"</color></size>\r\n>... [pen on paper]",
        ">... Connor B229 transcript fragment\r\n>... \"...{COMMAND}...{COMMAND}...{COMMAND}...\"\r\n>... <size=200%><color=red>\"author field empty\"</color></size>\r\n>... [tape hiss]",
        ">... Stokes B193, lab 6\r\n>... \"the projector hums in B-flat\"\r\n>... <size=200%><color=red>\"B-flat is the membrane's name\"</color></size>\r\n>... [hum]",
        ">... Durant B255 cassette, side B\r\n>... \"the destination has weather\"\r\n>... <size=200%><color=red>\"the destination has been waiting\"</color></size>\r\n>... [tape hiss]",
        ">... Schaeffer T-3894 telemetry burst\r\n>... tether amplitude 1.000\r\n>... tether amplitude <size=200%><color=red>1.001</color></size>\r\n>... [HVAC hum]",
        ">... Hammerstein B014, sketchbook\r\n>... \"page 81: the gate, with hands\"\r\n>... \"page 82: the gate, with <size=200%><color=red>my hands</color></size>\"\r\n>... [pen on paper]",
        ">... Durant B255 final entry\r\n>... \"the membrane is stable\"\r\n>... <size=200%><color=red>\"someone has been stabilizing it\"</color></size>\r\n>... [pen on paper]",
        ">... Stokes B193 to Hammerstein\r\n>... \"do you remember signing this\"\r\n>... <size=200%><color=red>\"the handwriting is yours\"</color></size>\r\n>... [silence]",
        ">... Schaeffer T-3894 page 14\r\n>... \"transfer duration scales tier-linear\"\r\n>... <size=200%><color=red>\"unless observed\"</color></size>\r\n>... [HVAC hum]",
        ">... Connor B229 audio recovery\r\n>... \"...the cube is a key for a door not yet built...\"\r\n>... \"...{COMMAND} is the door...\"\r\n>... <size=200%><color=red>[Encryption checksum mismatch. Contact your IT administrator]</color></size>",
        ">... Hammerstein B014 ledger\r\n>... \"specimen R-901: dust\"\r\n>... <size=200%><color=red>\"specimen R-901: composing\"</color></size>\r\n>... [page turn]",
        ">... Durant B255 to Durant B255\r\n>... \"this note is not in my handwriting\"\r\n>... <size=200%><color=red>\"both are true\"</color></size>\r\n>... [pen on paper]",
        ">... Stokes B193 procedure, lab 6\r\n>... \"do not address the cube directly\"\r\n>... <size=200%><color=red>\"the cube is addressing you\"</color></size>\r\n>... [silence]",
        ">... Schaeffer T-3894 chart, fig. 9\r\n>... transfer success rate: 99.4%\r\n>... transfer success rate: <size=200%><color=red>not measurable</color></size>\r\n>... [HVAC hum]",
        ">... Connor B229 lab note\r\n>... \"the MWP retains audio\"\r\n>... <size=200%><color=red>\"the audio is in our voices\"</color></size>\r\n>... [tape hiss]",
        ">... Hammerstein B014 directive, tier 4\r\n>... \"do not call them dimensions\"\r\n>... <size=200%><color=red>\"call them what they call themselves\"</color></size>\r\n>... [chalk on board]",
        ">... Durant B255 voice, late shift\r\n>... \"I have not slept in three weeks\"\r\n>... <size=200%><color=red>\"yet I remember sleeping\"</color></size>\r\n>... [tape hiss]",
        ">... Stokes B193 to Connor\r\n>... \"the operator does not consent\"\r\n>... <size=200%><color=red>\"the operator does not need to\"</color></size>\r\n>... [silence]",
        ">... Schaeffer T-3894 marginalia\r\n>... \"if you read this, the cube was opened\"\r\n>... <size=200%><color=red>\"hello, reader\"</color></size>\r\n>... [pen on paper]",
        ">... Connor B229 audio, MWP bank 7\r\n>... [garbled]\r\n>... <size=200%><color=red>\"...returns the operator [different]\"</color></size>\r\n>... [tape hiss]",
        ">... Hammerstein B014 last lecture\r\n>... \"projection theory makes a guarantee\"\r\n>... <size=200%><color=red>\"to the same address\"</color></size>\r\n>... [chalk on board]",
        ">... Durant B255 cassette, side A\r\n>... \"the desert is not new\"\r\n>... <size=200%><color=red>\"older than the species that wrote it\"</color></size>\r\n>... [tape hiss]",
        ">... Stokes B193 page 7\r\n>... \"membrane interior shows no decay\"\r\n>... <size=200%><color=red>\"interior shows attention\"</color></size>\r\n>... [silence]",
        ">... Schaeffer T-3894 lab notebook\r\n>... \"transfer phase 3: anchored\"\r\n>... <size=200%><color=red>\"anchor relocated to operator\"</color></size>\r\n>... [HVAC hum]",
        ">... Connor B229 to Schaeffer\r\n>... \"the data cube weighs nothing\"\r\n>... <size=200%><color=red>\"my hand weighs less holding it\"</color></size>\r\n>... [silence]",
        ">... Hammerstein B014 redacted\r\n>... [REDACTED]\r\n>... <size=200%><color=red>\"un-redacted by specimen\"</color></size>\r\n>... [page turn]",
        ">... Durant B255 to operative\r\n>... \"if the prompt blinks, do not press\"\r\n>... <size=200%><color=red>\"if the prompt blinks, the press has happened\"</color></size>\r\n>... [pen on paper]",
        ">... Stokes B193 lab 6, 04:11\r\n>... \"the projector hummed without power\"\r\n>... <size=200%><color=red>\"the hum did not change\"</color></size>\r\n>... [hum]",
        ">... Schaeffer T-3894 spreadsheet\r\n>... cube weight: 0.0 g\r\n>... cube weight: <size=200%><color=red>operator-dependent</color></size>\r\n>... [HVAC hum]",
        ">... Connor B229 fragment 0xBEEF\r\n>... \"...the membrane was named before our species existed...\"\r\n>... \"...the name is {COMMAND}...\"\r\n>... <size=200%><color=red>[Encryption checksum mismatch. Contact your IT administrator]</color></size>",
        ">... Hammerstein B014 bench notes\r\n>... \"Cretasium 77a sample melted\"\r\n>... <size=200%><color=red>\"into a smaller sample\"</color></size>\r\n>... [page turn]",
        ">... Durant B255 transcribed dream\r\n>... \"I dreamed I keyed {COMMAND}\"\r\n>... <size=200%><color=red>\"I am no longer dreaming\"</color></size>\r\n>... [tape hiss]",
        ">... Stokes B193 to medical\r\n>... \"my pupils dilate at the projector hum\"\r\n>... <size=200%><color=red>\"so does the projector\"</color></size>\r\n>... [hum]",
        ">... Schaeffer T-3894 footnote\r\n>... \"1.6% transfer overhead unaccounted\"\r\n>... <size=200%><color=red>\"1.6% is the operator\"</color></size>\r\n>... [HVAC hum]",
        ">... Connor B229 archival\r\n>... \"recovered fragment, source: cube 41\"\r\n>... <size=200%><color=red>\"recording dated next year\"</color></size>\r\n>... [tape hiss]",
        ">... Hammerstein B014 to Lockwood\r\n>... \"this is bigger than the company\"\r\n>... <size=200%><color=red>\"the company knows\"</color></size>\r\n>... [chalk on board]",
        ">... Durant B255 to Stokes\r\n>... \"do not pity the destination\"\r\n>... <size=200%><color=red>\"the destination is not patient\"</color></size>\r\n>... [pen on paper]",
        ">... Stokes B193 lab 6, 23:59\r\n>... \"the air in the lab tastes like sand\"\r\n>... <size=200%><color=red>\"the sand is here\"</color></size>\r\n>... [silence]",
        ">... Schaeffer T-3894 to channel 2\r\n>... \"telemetry feed: nominal\"\r\n>... <size=200%><color=red>\"telemetry feed is the operator\"</color></size>\r\n>... [HVAC hum]",
        ">... Connor B229 page 2\r\n>... \"the cube speaks four words\"\r\n>... <size=200%><color=red>\"the fourth is yours\"</color></size>\r\n>... [tape hiss]",
        ">... Hammerstein B014 sketchbook\r\n>... \"page 142: a desert with no ground\"\r\n>... \"page 143: a desert with no <size=200%><color=red>edges</color></size>\"\r\n>... [pen on paper]",
        ">... Durant B255 to ground\r\n>... \"transfer time is local-relative\"\r\n>... <size=200%><color=red>\"transfer time is the destination's choice\"</color></size>\r\n>... [pen on paper]",
        ">... Stokes B193 lab 6 ventilation\r\n>... \"the airflow tastes warm\"\r\n>... <size=200%><color=red>\"the airflow tastes like a mouth\"</color></size>\r\n>... [airflow]",
        ">... Schaeffer T-3894 chart 7\r\n>... \"projection efficiency 100.0%\"\r\n>... <size=200%><color=red>\"projection efficiency 100.4%\"</color></size>\r\n>... [HVAC hum]",
        ">... Connor B229 last note\r\n>... \"the audio in the cube is not over\"\r\n>... <size=200%><color=red>\"by the cube\"</color></size>\r\n>... [tape hiss]",
        ">... Hammerstein B014 redacted memo\r\n>... \"do not allow operative knowledge of {COMMAND}\"\r\n>... <size=200%><color=red>\"operative is the {COMMAND}\"</color></size>\r\n>... [page turn]",
        ">... Durant B255 cassette, last\r\n>... \"the topology held\"\r\n>... <size=200%><color=red>\"we did not\"</color></size>\r\n>... [tape hiss]",
        ">... Stokes B193 to lab 6 panel\r\n>... \"reading the prompt aloud spawns a copy\"\r\n>... <size=200%><color=red>\"do not read the prompt aloud\"</color></size>\r\n>... [keyboard]",
        ">... Schaeffer T-3894 to Lockwood\r\n>... \"projection ledger discrepancy: 1\"\r\n>... <size=200%><color=red>\"the missing operator is the ledger\"</color></size>\r\n>... [HVAC hum]",
        ">... Connor B229 audio salvage\r\n>... \"...we have always projected here...\"\r\n>... <size=200%><color=red>\"...by something other than us...\"</color></size>\r\n>... [tape hiss]",
        ">... Hammerstein B014 to medical\r\n>... \"all projection-staff sleep onset 04:00\"\r\n>... <size=200%><color=red>\"the destination keeps a schedule\"</color></size>\r\n>... [chalk on board]",
        ">... Durant B255 to operative\r\n>... \"if the prompt asks for confirmation, decline\"\r\n>... <size=200%><color=red>\"declining is also a confirmation\"</color></size>\r\n>... [pen on paper]",
        ">... Stokes B193 lab 6 floor log\r\n>... \"door opened from outside\"\r\n>... <size=200%><color=red>\"the dust did it\"</color></size>\r\n>... [door servo]",
        ">... Schaeffer T-3894 telemetry, end of shift\r\n>... \"tether reading nominal\"\r\n>... <size=200%><color=red>\"there was no tether\"</color></size>\r\n>... [HVAC hum]",
        ">... Connor B229 cube fragment\r\n>... \"...the project insight is not insight...\"\r\n>... <size=200%><color=red>\"...the looking is mutual...\"</color></size>\r\n>... [tape hiss]",
        ">... Hammerstein B014 last sketch\r\n>... \"page 247: the operator with two shadows\"\r\n>... \"page 248: the operator with <size=200%><color=red>no shadows</color></size>\"\r\n>... [pen on paper]",
        ">... Durant B255 final voice memo\r\n>... \"if you hear this, you keyed {COMMAND}\"\r\n>... <size=200%><color=red>\"if you hear this, you are not alone\"</color></size>\r\n>... [tape hiss]",
        ">... Stokes B193 to Hammerstein\r\n>... \"the projector accepts non-operator input\"\r\n>... <size=200%><color=red>\"input source: dust\"</color></size>\r\n>... [silence]",
        ">... Schaeffer T-3894 annotated ledger\r\n>... \"every projection cycle: 1 operator returns\"\r\n>... <size=200%><color=red>\"plus 0.04\"</color></size>\r\n>... [HVAC hum]",
        ">... Connor B229 fragment 0x0A0A\r\n>... \"...{COMMAND} unlocks the second cube...\"\r\n>... \"...there is no second cube on file...\"\r\n>... <size=200%><color=red>[Encryption checksum mismatch. Contact your IT administrator]</color></size>",
        ">... Hammerstein B014 to operative chip\r\n>... \"if you can read this, you are inside\"\r\n>... <size=200%><color=red>\"inside what was waiting\"</color></size>\r\n>... [chalk on board]",
        ">... Durant B255 ground note\r\n>... \"the desert is not the destination\"\r\n>... <size=200%><color=red>\"the destination is below\"</color></size>\r\n>... [pen on paper]",
        ">... Stokes B193 final transcript\r\n>... \"my last entry was nine days ago\"\r\n>... <size=200%><color=red>\"both are dated today\"</color></size>\r\n>... [silence]",
        ">... Schaeffer T-3894 to Schaeffer T-3894\r\n>... \"the equation balances\"\r\n>... <size=200%><color=red>\"by removing the operator\"</color></size>\r\n>... [HVAC hum]",
        ">... Connor B229 archival, sealed\r\n>... \"the MWP is older than Project Insight\"\r\n>... <size=200%><color=red>\"older than the company that named it\"</color></size>\r\n>... [tape hiss]",
        ">... Hammerstein B014 to all\r\n>... \"the gate goes both ways\"\r\n>... <size=200%><color=red>\"the other way is open\"</color></size>\r\n>... [chalk on board]",
    };
    #endregion

    #region Warden / system — WRDN, BIOCOM, EBDT, HearSay; corrupted command echoes
    public static readonly List<string> AlphaTerminalCommandIntel_WardenSystem = new()
    {
        ">... WRDN: {COMMAND}\r\n>... WRDN: {COM<size=200%><color=red>--MAND--</color></size>}\r\n>... operative response timeout\r\n>... [static]",
        ">... WRDN: PROJECT\r\n>... WRDN: <size=200%><color=red>PROJECTED</color></size>\r\n>... destination unspecified\r\n>... [carrier wave]",
        ">>EBDT FRAGMENT 0BE701 [corrupted]\r\n>... \"projection log entry: {COMMAND}\"\r\n>... \"projection log entry: <size=200%><color=red>{COMMAND}{COMMAND}</color></size>\"\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... BIOCOM cascade, projection bay 1\r\n>... checksum mismatch on operator\r\n>... <size=200%><color=red>operator un-checksummed</color></size>\r\n>... [warning tone]",
        ">... WRDN: COMPLY\r\n>... WRDN: <size=200%><color=red>COMPLIED</color></size>\r\n>... operative ahead of command\r\n>... [feedback]",
        ">>HearSay auto-transcript//projection\r\n>... \"the gate accepted {COMMAND}\"\r\n>... \"the gate <size=200%><color=red>preferred</color></size> {COMMAND}\"\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: ANCHOR\r\n>... WRDN: <size=200%><color=red>UNANCHORED</color></size>\r\n>... tether: not measurable\r\n>... [no signal]",
        ">>EBDT 0BE703: backdoor command authorized\r\n>... authorized by tier 5\r\n>... <size=200%><color=red>tier 5 has no record</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... BIOCOM trace, projection bay 1\r\n>... routing loop confirmed\r\n>... <size=200%><color=red>source is the operator</color></size>\r\n>... [warning tone]",
        ">... WRDN: TRANSFER\r\n>... WRDN: T-T-T<size=200%><color=red>RANSFER</color></size>\r\n>... operative consent: implied\r\n>... [feedback]",
        ">>HearSay channel 17\r\n>... \"who keyed the command\"\r\n>... \"who keyed the <size=200%><color=red>command</color></size>\"\r\n>... [recording loops]",
        ">... WRDN: {COMMAND}\r\n>... WRDN: {COMMAND}\r\n>... receiver: <size=200%><color=red>none configured</color></size>\r\n>... [feedback]",
        ">>EBDT 0BE705: projection ledger entry 8141\r\n>... operator: [redacted]\r\n>... command: <size=200%><color=red>{COMMAND}</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... BIOCOM watchdog fault\r\n>... cascading reset attempted\r\n>... cascading reset propagated to <size=200%><color=red>operative cognition</color></size>\r\n>... [warning tone]",
        ">... WRDN broadcast burst\r\n>... 0xC0DE 0xC0DE 0xC0DE\r\n>... <size=200%><color=red>0x{COMMAND}</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">>HearSay auto-transcript//gate\r\n>... \"hand on the projector\"\r\n>... \"<size=200%><color=red>whose hand</color></size>\"\r\n>... [recording loops]",
        ">... WRDN: HOLD\r\n>... WRDN: <size=200%><color=red>RELEASED</color></size>\r\n>... operative position: drifting\r\n>... [static]",
        ">... BIOCOM ID conflict\r\n>... two operatives bearing same chip ID\r\n>... <size=200%><color=red>resolve by destination</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">>EBDT 0BE708: command {COMMAND} echoed\r\n>... echo source: gate\r\n>... echo source: <size=200%><color=red>operator</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: SCAN\r\n>... WRDN: SCAN<size=200%><color=red>NED</color></size>\r\n>... operator inventory: +1 unaccounted\r\n>... [feedback]",
        ">... BIOCOM spectrometer, projection bay\r\n>... air composition: nominal\r\n>... air composition: <size=200%><color=red>74% Cretasium 77a</color></size>\r\n>... [airflow]",
        ">... WRDN: {COMMAND}\r\n>... WRDN: {COMMAND}\r\n>... WRDN: {COMMAND}<size=200%><color=red>{COMMAND}</color></size>\r\n>... [feedback]",
        ">>HearSay channel 4\r\n>... \"the desert is on the radio\"\r\n>... \"the desert is on the <size=200%><color=red>radio</color></size>\"\r\n>... [carrier wave]",
        ">>EBDT 0BE710: tier 5 authorization for {COMMAND}\r\n>... authorization revoked\r\n>... <size=200%><color=red>command continued without authorization</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: PROJECT\r\n>... WRDN: PROJECT<size=200%><color=red>OR</color></size>\r\n>... operator subsumed\r\n>... [feedback]",
        ">... BIOCOM telemetry, operator GO-1395\r\n>... heart rate 92 BPM\r\n>... heart rate <size=200%><color=red>92 BPM, both</color></size>\r\n>... [warning tone]",
        ">>HearSay auto-transcript//transfer\r\n>... \"transfer at 88%\"\r\n>... \"<size=200%><color=red>transfer is at us</color></size>\"\r\n>... [recording loops]",
        ">... WRDN: TETHER\r\n>... WRDN: TETHER\r\n>... WRDN: <size=200%><color=red>TETHERED ELSEWHERE</color></size>\r\n>... [no signal]",
        ">>EBDT 0BE712: projection bay 1 sealed\r\n>... sealed by tier 5\r\n>... <size=200%><color=red>sealed from inside</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... BIOCOM checksum 0xDEADBEEF\r\n>... operator cognition flagged\r\n>... operator cognition <size=200%><color=red>uploaded</color></size>\r\n>... [warning tone]",
        ">... WRDN: {COMMAND}\r\n>... WRDN: NOT {COMMAND}\r\n>... WRDN: <size=200%><color=red>NEVER {COMMAND}</color></size>\r\n>... [feedback]",
        ">>HearSay channel 11\r\n>... \"the gate hummed in two voices\"\r\n>... \"the gate hummed in <size=200%><color=red>your voice</color></size>\"\r\n>... [hum]",
        ">>EBDT 0BE715: backdoor record sealed\r\n>... record sealed\r\n>... <size=200%><color=red>record speaking</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: COMPLY\r\n>... WRDN: <size=200%><color=red>COMPLIANCE NOT REQUIRED</color></size>\r\n>... operator already compliant\r\n>... [feedback]",
        ">... BIOCOM trace, gate handshake\r\n>... gate ACK\r\n>... <size=200%><color=red>gate has ACKnowledged us first</color></size>\r\n>... [warning tone]",
        ">... WRDN: {COMMAND}\r\n>... WRDN: {COMMAND}\r\n>... WRDN: <size=200%><color=red>{COMMAND}, again</color></size>\r\n>... [feedback]",
        ">>HearSay auto-transcript//drop\r\n>... \"if you can read this, the projector worked\"\r\n>... \"if you can read this, the projector <size=200%><color=red>worked us</color></size>\"\r\n>... [recording loops]",
        ">>EBDT 0BE718: chronometer drift\r\n>... operator clock: +40s\r\n>... mission clock: <size=200%><color=red>0s</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... BIOCOM destination database\r\n>... entries: 622,811\r\n>... entries: <size=200%><color=red>622,813</color></size>\r\n>... [warning tone]",
        ">... WRDN: SCAN COMPLETE\r\n>... WRDN: SCAN COMPLETE\r\n>... WRDN: SCAN <size=200%><color=red>OPEN</color></size>\r\n>... [feedback]",
        ">>HearSay channel 1\r\n>... \"the chronometer is normal\"\r\n>... \"the chronometer is <size=200%><color=red>not</color></size>\"\r\n>... [hum]",
        ">>EBDT 0BE721: cube identity\r\n>... cube ID: 0x4441\r\n>... cube ID: <size=200%><color=red>operator-derived</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: {COMMAND}\r\n>... WRDN: <size=200%><color=red>UN-{COMMAND}</color></size>\r\n>... operative reverted\r\n>... [feedback]",
        ">... BIOCOM emergency lockdown, projection bay\r\n>... lockdown initiated\r\n>... <size=200%><color=red>lockdown is the operator</color></size>\r\n>... [warning tone]",
        ">>HearSay auto-transcript//membrane\r\n>... \"the destination is stable\"\r\n>... \"the destination is <size=200%><color=red>still</color></size>\"\r\n>... [hum]",
        ">>EBDT 0BE723: projection cancelled\r\n>... cancelled by operator\r\n>... <size=200%><color=red>cancelled by destination</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: TRANSFER COMPLETE\r\n>... WRDN: TRANSFER <size=200%><color=red>OPEN</color></size>\r\n>... operator reachable\r\n>... [feedback]",
        ">... BIOCOM trace, MWP serial 0001\r\n>... MWP serial <size=200%><color=red>0000</color></size>\r\n>... earlier instance not in record\r\n>... [warning tone]",
        ">>HearSay channel 7\r\n>... \"open sky on the radio\"\r\n>... \"open sky on the <size=200%><color=red>radio</color></size>\"\r\n>... [wind]",
        ">>EBDT 0BE726: command echo\r\n>... {COMMAND} executed at projection bay 1\r\n>... <size=200%><color=red>{COMMAND} executed at no bay</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: HOLD POSITION\r\n>... WRDN: H-H-H<size=200%><color=red>OLD</color></size>\r\n>... operator position: unknown\r\n>... [static]",
        ">... BIOCOM operator chip patch\r\n>... new patch deployed\r\n>... <size=200%><color=red>patch source: gate</color></size>\r\n>... [warning tone]",
        ">>HearSay auto-transcript//WRDN\r\n>... \"the WRDN repeated {COMMAND} 41 times\"\r\n>... \"the WRDN repeated {COMMAND} <size=200%><color=red>22 times</color></size>\"\r\n>... [carrier wave]",
        ">... WRDN: {COMMAND}\r\n>... WRDN: {COMMAND}<size=200%><color=red>--ed</color></size>\r\n>... operator past tense\r\n>... [feedback]",
        ">>EBDT 0BE730: backdoor record\r\n>... \"backdoor terminal not in inventory\"\r\n>... <size=200%><color=red>terminal in operator inventory</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... BIOCOM telemetry, all operatives\r\n>... pulse rate 92 BPM\r\n>... pulse rate <size=200%><color=red>synchronized</color></size>\r\n>... [warning tone]",
        ">... WRDN broadcast\r\n>... \"return\"\r\n>... <size=200%><color=red>\"do not return\"</color></size>\r\n>... [feedback]",
        ">>HearSay channel 22\r\n>... \"the gate is humming a song\"\r\n>... \"the song was first sung in <size=200%><color=red>2057</color></size>\"\r\n>... [hum]",
        ">>EBDT 0BE733: ledger entry 8142\r\n>... operator returned: 4\r\n>... operator returned: <size=200%><color=red>4.04</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: {COMMAND}\r\n>... WRDN: <size=200%><color=red>{COMMAND}_DONE</color></size>\r\n>... result: pending\r\n>... [feedback]",
        ">... BIOCOM gate handshake\r\n>... handshake initiated\r\n>... <size=200%><color=red>handshake re-initiated by gate</color></size>\r\n>... [warning tone]",
        ">>HearSay auto-transcript//cube\r\n>... \"the cube is heavy\"\r\n>... \"the cube is <size=200%><color=red>weighing the operator</color></size>\"\r\n>... [hum]",
        ">>EBDT 0BE735: telemetry hole\r\n>... 4.0s of telemetry missing\r\n>... <size=200%><color=red>4.0s of operator missing</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: PROJECT\r\n>... WRDN: PROJECTED <size=200%><color=red>OUT</color></size>\r\n>... operator return: unscheduled\r\n>... [feedback]",
        ">... BIOCOM warning, projection bay\r\n>... ambient temperature 39°C\r\n>... ambient temperature <size=200%><color=red>desert</color></size>\r\n>... [warning tone]",
        ">>HearSay channel 0\r\n>... \"this is a recording\"\r\n>... \"this is a <size=200%><color=red>recording of you</color></size>\"\r\n>... [recording loops]",
        ">>EBDT 0BE738: gate inventory\r\n>... gates online: 1\r\n>... gates online: <size=200%><color=red>at least 2</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: {COMMAND}\r\n>... WRDN: <size=200%><color=red>BIG_{COMMAND}</color></size>\r\n>... operator: small\r\n>... [feedback]",
        ">... BIOCOM cascade, gate side\r\n>... fault propagating outward\r\n>... <size=200%><color=red>outward includes Reality</color></size>\r\n>... [warning tone]",
        ">>HearSay auto-transcript//operator\r\n>... \"operator returned\"\r\n>... \"<size=200%><color=red>operator did not</color></size>\"\r\n>... [carrier wave]",
        ">>EBDT 0BE740: backdoor history\r\n>... command keyed: 41 times\r\n>... command keyed: <size=200%><color=red>once</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: SEEK\r\n>... WRDN: SEEK<size=200%><color=red>ER</color></size>\r\n>... operator role flipped\r\n>... [feedback]",
        ">... BIOCOM diagnostic, MWP\r\n>... unit checks out\r\n>... unit <size=200%><color=red>checks operator</color></size>\r\n>... [warning tone]",
        ">>HearSay channel 5\r\n>... \"the destination has weather\"\r\n>... \"the weather has <size=200%><color=red>destinations</color></size>\"\r\n>... [wind]",
        ">>EBDT 0BE743: projection close\r\n>... close at T-30s\r\n>... close at <size=200%><color=red>T-0</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: {COMMAND}\r\n>... WRDN: {COMMAND}\r\n>... WRDN: <size=200%><color=red>{COMMAND}, third time</color></size>\r\n>... [feedback]",
        ">... BIOCOM directive, all bays\r\n>... \"do not key the backdoor\"\r\n>... <size=200%><color=red>backdoor key already inserted</color></size>\r\n>... [warning tone]",
        ">>HearSay auto-transcript//archive\r\n>... \"archived: {COMMAND}, {COMMAND}, {COMMAND}\"\r\n>... \"archived: <size=200%><color=red>{COMMAND}_NOT</color></size>\"\r\n>... [recording loops]",
        ">>EBDT 0BE746: anomaly index\r\n>... index 0.00\r\n>... index <size=200%><color=red>0.04</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: TRANSFER\r\n>... WRDN: <size=200%><color=red>TRANSFERRED</color></size>\r\n>... destination: home, but smaller\r\n>... [feedback]",
    };
    #endregion

    #region KDS / corp — Piros, Lockwood, Johanson; redacted directives, contractor cynicism
    public static readonly List<string> AlphaTerminalCommandIntel_KDSCorp = new()
    {
        ">... Piros A134 to ground command\r\n>... \"projection ops are KDS-3 territory\"\r\n>... <size=200%><color=red>\"we count what comes out\"</color></size>\r\n>... [static]",
        ">... Lockwood A074 directive, tier 5\r\n>... \"do not document the {COMMAND} backdoor\"\r\n>... <size=200%><color=red>\"document continues\"</color></size>\r\n>... [page rustle]",
        ">... Johanson A029 ledger\r\n>... MWP recovery cost: $44M\r\n>... MWP recovery cost: <size=200%><color=red>recovered</color></size>\r\n>... [paper rustle]",
        ">... Anders Johanson, contract memo\r\n>... \"prisoner units are projection-grade\"\r\n>... <size=200%><color=red>\"prisoner units consent on file\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 channel 4\r\n>... \"how many we lose this rotation\"\r\n>... <size=200%><color=red>\"two-and-a-half\"</color></size>\r\n>... [static]",
        ">... Lockwood A074 to all KDS\r\n>... \"strike the word 'membrane' from the briefing\"\r\n>... <size=200%><color=red>\"membrane stays in the operator\"</color></size>\r\n>... [static]",
        ">... Johanson A029 internal memo\r\n>... \"projection ROI 1700%\"\r\n>... <size=200%><color=red>\"per kilogram of operator\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 ground report\r\n>... \"prisoner cube extracted intact\"\r\n>... <size=200%><color=red>\"prisoner not intact\"</color></size>\r\n>... [static]",
        ">... Lockwood A074 redaction directive\r\n>... \"redact mention of the destination\"\r\n>... <size=200%><color=red>\"the destination redacted itself\"</color></size>\r\n>... [page rustle]",
        ">... Johanson Papers, leaked excerpt\r\n>... \"the desert is a billable line item\"\r\n>... <size=200%><color=red>\"billed to the operator\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 to channel 1\r\n>... \"do not engage at projection close\"\r\n>... <size=200%><color=red>\"projection closes around you\"</color></size>\r\n>... [static]",
        ">... Lockwood A074 internal\r\n>... \"the {COMMAND} script is a corporate asset\"\r\n>... <size=200%><color=red>\"the script owns the company\"</color></size>\r\n>... [page rustle]",
        ">... Johanson A029 spreadsheet\r\n>... \"projection cost per operator: 1\"\r\n>... <size=200%><color=red>\"projection cost per operator: 1.04\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 KDS-Deep memo\r\n>... \"projection ops are non-survivable\"\r\n>... <size=200%><color=red>\"survivors are non-projected\"</color></size>\r\n>... [static]",
        ">... Lockwood A074 to legal\r\n>... \"prisoner waivers cover the gate\"\r\n>... <size=200%><color=red>\"the gate did not sign\"</color></size>\r\n>... [page rustle]",
        ">... Johanson A029 board minutes\r\n>... \"the desert is an externality\"\r\n>... <size=200%><color=red>\"the externality is internalizing\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 field memo\r\n>... \"the projector hums even off-shift\"\r\n>... <size=200%><color=red>\"there is no off-shift\"</color></size>\r\n>... [hum]",
        ">... Lockwood A074 redaction list\r\n>... \"line 7: Cretasium\"\r\n>... <size=200%><color=red>\"line 9: us\"</color></size>\r\n>... [page rustle]",
        ">... Johanson A029 to shareholders\r\n>... \"projection product is non-replenishable\"\r\n>... <size=200%><color=red>\"product is replenishing itself\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 to channel 2\r\n>... \"if the operator returns, scan twice\"\r\n>... <size=200%><color=red>\"scan three times\"</color></size>\r\n>... [static]",
        ">... Lockwood A074 to corporate\r\n>... \"the {COMMAND} authorization is sealed\"\r\n>... <size=200%><color=red>\"the seal is the {COMMAND}\"</color></size>\r\n>... [page rustle]",
        ">... Johanson A029 audit\r\n>... \"projector unit count: 1\"\r\n>... <size=200%><color=red>\"projector unit count: variable\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 to KDS-Deep\r\n>... \"do not approach the gate post-projection\"\r\n>... <size=200%><color=red>\"the gate approaches\"</color></size>\r\n>... [static]",
        ">... Lockwood A074, evening memo\r\n>... \"do not record this\"\r\n>... <size=200%><color=red>\"this is a recording\"</color></size>\r\n>... [page rustle]",
        ">... Johanson A029 to logistics\r\n>... \"the desert is closer than the warehouse\"\r\n>... <size=200%><color=red>\"the desert is the warehouse\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 incident report\r\n>... \"operator returned with non-Garganta dust\"\r\n>... <size=200%><color=red>\"dust returned with non-Garganta operator\"</color></size>\r\n>... [static]",
        ">... Lockwood A074 to channel 0\r\n>... \"the backdoor is a feature\"\r\n>... <size=200%><color=red>\"the backdoor opens both ways\"</color></size>\r\n>... [page rustle]",
        ">... Johanson A029 risk register\r\n>... \"projection risk: 0.04%\"\r\n>... <size=200%><color=red>\"per second\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 to operatives\r\n>... \"if the dust speaks, do not answer\"\r\n>... <size=200%><color=red>\"the dust answers either way\"</color></size>\r\n>... [static]",
        ">... Lockwood A074 to all\r\n>... \"the gate is decommissioned\"\r\n>... <size=200%><color=red>\"the gate disagrees\"</color></size>\r\n>... [page rustle]",
        ">... Johanson Papers, contract clause\r\n>... \"prisoner ownership transfers at gate handshake\"\r\n>... <size=200%><color=red>\"transfers to the gate\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 channel 3\r\n>... \"do not log this\"\r\n>... <size=200%><color=red>\"already logged\"</color></size>\r\n>... [static]",
        ">... Lockwood A074 internal\r\n>... \"the operative will not remember\"\r\n>... <size=200%><color=red>\"the operative is remembering\"</color></size>\r\n>... [page rustle]",
        ">... Johanson A029 expense report\r\n>... \"projection ops, monthly: $44M\"\r\n>... <size=200%><color=red>\"plus 1 operator\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 to KDS-3\r\n>... \"if you can read this, the operator returned\"\r\n>... <size=200%><color=red>\"if you can read this, you are the operator\"</color></size>\r\n>... [static]",
        ">... Lockwood A074 redaction\r\n>... \"strike: the destination has weather\"\r\n>... <size=200%><color=red>\"weather struck back\"</color></size>\r\n>... [page rustle]",
        ">... Johanson A029 forecast\r\n>... \"Q4 projection volume up 22%\"\r\n>... <size=200%><color=red>\"per operator\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 to medical\r\n>... \"operator's bloodwork came back gold\"\r\n>... <size=200%><color=red>\"like the dust\"</color></size>\r\n>... [static]",
        ">... Lockwood A074 to ops\r\n>... \"the {COMMAND} doc has 41 unauthorized edits\"\r\n>... <size=200%><color=red>\"the doc edits itself\"</color></size>\r\n>... [page rustle]",
        ">... Johanson Papers, board annex\r\n>... \"projection is a long-term hold\"\r\n>... <size=200%><color=red>\"the destination is holding us\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 last channel\r\n>... \"close the gate at projection end\"\r\n>... <size=200%><color=red>\"the gate closes when it wants\"</color></size>\r\n>... [static]",
        ">... Lockwood A074 sealed file\r\n>... \"do not open file 0BE-{COMMAND}\"\r\n>... <size=200%><color=red>\"file is open\"</color></size>\r\n>... [page rustle]",
        ">... Johanson A029 board call\r\n>... \"the operator is the asset\"\r\n>... <size=200%><color=red>\"the asset has been re-assessed\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 to all KDS\r\n>... \"if the chronometer drifts, scrub\"\r\n>... <size=200%><color=red>\"the chronometer drifts always\"</color></size>\r\n>... [static]",
        ">... Lockwood A074 to engineering\r\n>... \"projection bay 1 sealed\"\r\n>... <size=200%><color=red>\"sealed only on this side\"</color></size>\r\n>... [page rustle]",
        ">... Johanson A029 spreadsheet, Q3\r\n>... \"projection cycles: 622,811\"\r\n>... <size=200%><color=red>\"projection cycles: us\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 to channel 9\r\n>... \"the gate hum carries past the corridor\"\r\n>... <size=200%><color=red>\"the corridor hums back\"</color></size>\r\n>... [hum]",
        ">... Lockwood A074 redacted by self\r\n>... [REDACTED]\r\n>... <size=200%><color=red>[REDACTED is the message]</color></size>\r\n>... [page rustle]",
        ">... Johanson A029 to legal\r\n>... \"the {COMMAND} EULA is binding\"\r\n>... <size=200%><color=red>\"binding the prisoner forever\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 to ground\r\n>... \"three came back\"\r\n>... <size=200%><color=red>\"a fourth is at the gate\"</color></size>\r\n>... [static]",
        ">... Lockwood A074 to operations\r\n>... \"do not run {COMMAND} after dark\"\r\n>... <size=200%><color=red>\"the destination has a dark\"</color></size>\r\n>... [page rustle]",
        ">... Johanson A029 to shareholders\r\n>... \"the desert is profitable\"\r\n>... <size=200%><color=red>\"the profit is the desert\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 KDS-Deep contract\r\n>... \"projection ops pay double\"\r\n>... <size=200%><color=red>\"per operator, even fractional\"</color></size>\r\n>... [static]",
        ">... Lockwood A074 to corporate\r\n>... \"if you can read this, redact yourself\"\r\n>... <size=200%><color=red>\"already redacted\"</color></size>\r\n>... [page rustle]",
        ">... Johanson A029 to legal\r\n>... \"prisoner waiver covers cube transfer\"\r\n>... <size=200%><color=red>\"prisoner is the transfer\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 channel 11\r\n>... \"the dust comes back with the operator\"\r\n>... <size=200%><color=red>\"the dust does not leave\"</color></size>\r\n>... [static]",
        ">... Lockwood A074 to all\r\n>... \"the {COMMAND} command is a corporate trade secret\"\r\n>... <size=200%><color=red>\"the secret is on the gate\"</color></size>\r\n>... [page rustle]",
        ">... Johanson A029 final filing\r\n>... \"projection division wound down\"\r\n>... <size=200%><color=red>\"projection wound up\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 last\r\n>... \"do not key the backdoor without escort\"\r\n>... <size=200%><color=red>\"the escort came from inside\"</color></size>\r\n>... [static]",
        ">... Lockwood A074 to all KDS\r\n>... \"the desert is off-record\"\r\n>... <size=200%><color=red>\"the record is off-desert\"</color></size>\r\n>... [page rustle]",
        ">... Johanson A029, late filing\r\n>... \"projection income: $44M\"\r\n>... <size=200%><color=red>\"net: 1 operator\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 to operatives\r\n>... \"the gate goes both ways\"\r\n>... <size=200%><color=red>\"do not stand in the middle\"</color></size>\r\n>... [static]",
        ">... Lockwood A074 to legal, sealed\r\n>... \"the {COMMAND} clause is non-revocable\"\r\n>... <size=200%><color=red>\"the clause revoked the lawyer\"</color></size>\r\n>... [page rustle]",
        ">... Johanson A029 board\r\n>... \"the projector is a long-term asset\"\r\n>... <size=200%><color=red>\"the asset is hands-on\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 to KDS-3\r\n>... \"do not chase the operator past the platform\"\r\n>... <size=200%><color=red>\"the platform is the operator\"</color></size>\r\n>... [static]",
        ">... Lockwood A074 to operations, urgent\r\n>... \"discontinue {COMMAND} immediately\"\r\n>... <size=200%><color=red>\"{COMMAND} discontinued the discontinuation\"</color></size>\r\n>... [page rustle]",
        ">... Johanson A029 to investors\r\n>... \"projection growth, year over year: 22%\"\r\n>... <size=200%><color=red>\"per operator-day in the desert\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134, dawn shift\r\n>... \"the gate is off\"\r\n>... <size=200%><color=red>\"the gate hums anyway\"</color></size>\r\n>... [hum]",
        ">... Lockwood A074 to medical\r\n>... \"if a returnee tastes sand, isolate\"\r\n>... <size=200%><color=red>\"isolate from the rest of yourself\"</color></size>\r\n>... [page rustle]",
        ">... Johanson A029 to legal, again\r\n>... \"the prisoner cannot sue the gate\"\r\n>... <size=200%><color=red>\"the gate is suing\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 to ground command\r\n>... \"if no operator returns, log a 1.0\"\r\n>... <size=200%><color=red>\"if 0.04 returns, log a 0\"</color></size>\r\n>... [static]",
        ">... Lockwood A074 final memo\r\n>... \"the {COMMAND} record is sealed for 99 years\"\r\n>... <size=200%><color=red>\"the seal is older than the company\"</color></size>\r\n>... [page rustle]",
        ">... Johanson A029, evening\r\n>... \"the operator agreement covers projection\"\r\n>... <size=200%><color=red>\"the projection covers the operator\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 farewell channel\r\n>... \"if you read this, you came back\"\r\n>... <size=200%><color=red>\"if you read this, you are the part that came back\"</color></size>\r\n>... [static]",
        ">... Lockwood A074 sealed for tier 5\r\n>... \"the gate accepts {COMMAND} forever\"\r\n>... <size=200%><color=red>\"forever has accepted us\"</color></size>\r\n>... [page rustle]",
        ">... Johanson A029 ledger close\r\n>... \"projection cycle ledger closed\"\r\n>... <size=200%><color=red>\"reopened by gate\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134 to all\r\n>... \"red lighting in projection bay tonight\"\r\n>... <size=200%><color=red>\"red lighting was the gate\"</color></size>\r\n>... [static]",
        ">... Lockwood A074 to corporate\r\n>... \"the destination is fully owned\"\r\n>... <size=200%><color=red>\"by the destination\"</color></size>\r\n>... [page rustle]",
        ">... Johanson A029, last filing\r\n>... \"the operator returns to revenue\"\r\n>... <size=200%><color=red>\"the revenue returns to the operator\"</color></size>\r\n>... [paper rustle]",
        ">... Piros A134, off-record\r\n>... \"the dust does not file paperwork\"\r\n>... <size=200%><color=red>\"the paperwork files itself\"</color></size>\r\n>... [static]",
    };
    #endregion

    #region Fragments — Mr. Truth, State of Truth AM, Collector chatter, MWP memory bursts
    public static readonly List<string> AlphaTerminalCommandIntel_Fragments = new()
    {
        ">... Mr. Truth, recovered tape, side B\r\n>... \"there are seven deserts\"\r\n>... <size=200%><color=red>\"the seventh owns the company\"</color></size>\r\n>... [tape hiss]",
        ">... State of Truth AM, broadcast 8141\r\n>... \"folks, the gate hummed at me on the drive in\"\r\n>... <size=200%><color=red>\"so did my coffee mug\"</color></size>\r\n>... [carrier wave]",
        ">... Collector frequency, decoded\r\n>... \"...we have been waiting...\"\r\n>... <size=200%><color=red>\"...we are not waiting...\"</color></size>\r\n>... [low pulse]",
        ">... MWP memory bank 0xCAFE\r\n>... [audio: keystroke, keystroke, keystroke]\r\n>... [audio: <size=200%><color=red>{COMMAND}</color></size>]\r\n>... [tape hiss]",
        ">... Mr. Truth, mailbag entry 0042\r\n>... \"a listener writes: 'I went to the desert'\"\r\n>... <size=200%><color=red>\"both letters in the same hand\"</color></size>\r\n>... [tape hiss]",
        ">... State of Truth AM, late slot\r\n>... \"caller, you're on\"\r\n>... <size=200%><color=red>\"caller is the broadcast\"</color></size>\r\n>... [carrier wave]",
        ">... Collector chatter, fragment 0x0001\r\n>... \"...projection is a courtesy...\"\r\n>... <size=200%><color=red>\"...older than the species that thanks us...\"</color></size>\r\n>... [low pulse]",
        ">... MWP memory bank 0xDEAD\r\n>... [audio: wind]\r\n>... [audio: <size=200%><color=red>wind, with a name in it</color></size>]\r\n>... [wind]",
        ">... Mr. Truth, warning sign edition\r\n>... \"if the gate hums in B-flat, do not key the command\"\r\n>... <size=200%><color=red>\"if you hum back, you're already inside\"</color></size>\r\n>... [tape hiss]",
        ">... State of Truth AM, sponsor break\r\n>... \"this segment brought to you by the gate\"\r\n>... <size=200%><color=red>\"the gate has not paid yet\"</color></size>\r\n>... [carrier wave]",
        ">... Collector frequency, decoded, partial\r\n>... \"...{COMMAND} is one of our words...\"\r\n>... <size=200%><color=red>\"...you've borrowed it well...\"</color></size>\r\n>... [low pulse]",
        ">... MWP memory bank 0xFADE\r\n>... [audio: prisoner laughter, undated]\r\n>... [audio: <size=200%><color=red>laughter without source</color></size>]\r\n>... [tape hiss]",
        ">... Mr. Truth, dawn show\r\n>... \"woke up with sand in my coat pocket\"\r\n>... <size=200%><color=red>\"the desert went somewhere\"</color></size>\r\n>... [tape hiss]",
        ">... State of Truth AM, ad break\r\n>... \"buy your dimensional insurance now\"\r\n>... <size=200%><color=red>\"the policyholder is the dimension\"</color></size>\r\n>... [carrier wave]",
        ">... Collector chatter, layered\r\n>... \"...the membrane is the operator's idea...\"\r\n>... <size=200%><color=red>\"...we agree to it for now...\"</color></size>\r\n>... [low pulse]",
        ">... MWP memory bank 0xBEEF\r\n>... [audio: a child counting backward]\r\n>... [audio: <size=200%><color=red>the child reaches zero, keeps going</color></size>]\r\n>... [tape hiss]",
        ">... Mr. Truth, full moon edition\r\n>... \"there's a moon in the desert\"\r\n>... <size=200%><color=red>\"the door is open\"</color></size>\r\n>... [tape hiss]",
        ">... State of Truth AM, listener mail\r\n>... \"my husband came back from the gate\"\r\n>... <size=200%><color=red>\"both are at the kitchen table\"</color></size>\r\n>... [carrier wave]",
        ">... Collector frequency, weak signal\r\n>... \"...we count returns, not departures...\"\r\n>... <size=200%><color=red>\"...your count is wrong...\"</color></size>\r\n>... [low pulse]",
        ">... MWP memory bank 0xC0DE\r\n>... [audio: typing, fast]\r\n>... [audio: <size=200%><color=red>typing, in the operator's rhythm</color></size>]\r\n>... [keyboard]",
        ">... Mr. Truth, evening segment\r\n>... \"there's a thing called Cretasium 77a\"\r\n>... <size=200%><color=red>\"it's also in your teeth\"</color></size>\r\n>... [tape hiss]",
        ">... State of Truth AM, listener panic\r\n>... \"caller, calm down\"\r\n>... <size=200%><color=red>\"the broadcast is the caller\"</color></size>\r\n>... [carrier wave]",
        ">... Collector chatter, decoded, slow\r\n>... \"...you arrive often...\"\r\n>... <size=200%><color=red>\"...the difference is fine...\"</color></size>\r\n>... [low pulse]",
        ">... MWP memory bank 0xFEED\r\n>... [audio: no audio]\r\n>... [audio: <size=200%><color=red>a heartbeat, not the operator's</color></size>]\r\n>... [breathing]",
        ">... Mr. Truth, pre-record\r\n>... \"if I don't make next week's show\"\r\n>... <size=200%><color=red>\"check the dust on your coat\"</color></size>\r\n>... [tape hiss]",
        ">... State of Truth AM, news at the top\r\n>... \"projection ops were never on the news\"\r\n>... <size=200%><color=red>\"this segment is the news\"</color></size>\r\n>... [carrier wave]",
        ">... Collector frequency, layered\r\n>... \"...the gate is a hospitality...\"\r\n>... <size=200%><color=red>\"...you're welcome...\"</color></size>\r\n>... [low pulse]",
        ">... MWP memory bank 0xABCD\r\n>... [audio: {COMMAND}, looped]\r\n>... [audio: <size=200%><color=red>{COMMAND}, with a different stress</color></size>]\r\n>... [tape hiss]",
        ">... Mr. Truth, drive-time\r\n>... \"saw a man at the projector with no chip\"\r\n>... <size=200%><color=red>\"saw the chip with no man\"</color></size>\r\n>... [tape hiss]",
        ">... State of Truth AM, off-air\r\n>... \"the off-air light is on\"\r\n>... <size=200%><color=red>\"the light is broadcasting\"</color></size>\r\n>... [carrier wave]",
        ">... Collector chatter, intercept 0x4441\r\n>... \"...{COMMAND} translates as 'please'...\"\r\n>... <size=200%><color=red>\"...you said it many times...\"</color></size>\r\n>... [low pulse]",
        ">... MWP memory bank 0x9991\r\n>... [audio: a name]\r\n>... [audio: <size=200%><color=red>your name, mispronounced once</color></size>]\r\n>... [tape hiss]",
        ">... Mr. Truth, midnight segment\r\n>... \"there's a name for it in the desert\"\r\n>... <size=200%><color=red>\"the name fits in your mouth\"</color></size>\r\n>... [tape hiss]",
        ">... State of Truth AM, bumper\r\n>... \"and we'll be right back\"\r\n>... <size=200%><color=red>\"we never left\"</color></size>\r\n>... [carrier wave]",
        ">... Collector frequency, intercept\r\n>... \"...the same operator returns each cycle...\"\r\n>... <size=200%><color=red>\"...you should consider the alternatives...\"</color></size>\r\n>... [low pulse]",
        ">... MWP memory bank 0x4242\r\n>... [audio: a door, opening]\r\n>... [audio: <size=200%><color=red>a door, in your apartment</color></size>]\r\n>... [door servo]",
        ">... Mr. Truth, bonus episode\r\n>... \"a man wrote in: 'I keyed the {COMMAND}'\"\r\n>... <size=200%><color=red>\"I have not been to the desert\"</color></size>\r\n>... [tape hiss]",
        ">... State of Truth AM, dead air\r\n>... \"...\"\r\n>... <size=200%><color=red>\"...still here...\"</color></size>\r\n>... [carrier wave]",
        ">... Collector chatter, harmonic\r\n>... \"...the projector is older than its makers...\"\r\n>... <size=200%><color=red>\"...you are made of older things...\"</color></size>\r\n>... [low pulse]",
        ">... MWP memory bank 0x0FF1\r\n>... [audio: keystrokes]\r\n>... [audio: <size=200%><color=red>{COMMAND}, mistyped, then corrected by no one</color></size>]\r\n>... [keyboard]",
        ">... Mr. Truth, on the desert\r\n>... \"folks, the desert is not a place\"\r\n>... <size=200%><color=red>\"the relationship is one-sided\"</color></size>\r\n>... [tape hiss]",
        ">... State of Truth AM, spot ad\r\n>... \"don't go to the desert this fall\"\r\n>... <size=200%><color=red>\"the desert visits regardless\"</color></size>\r\n>... [carrier wave]",
        ">... Collector frequency, decoded, cold\r\n>... \"...the prisoners are punctual...\"\r\n>... <size=200%><color=red>\"...we set the clock...\"</color></size>\r\n>... [low pulse]",
        ">... MWP memory bank 0xD00R\r\n>... [audio: footsteps, on sand]\r\n>... [audio: <size=200%><color=red>footsteps, behind yours, identical pace</color></size>]\r\n>... [boot crunch]",
        ">... Mr. Truth, last call\r\n>... \"if you keyed it, it keyed you\"\r\n>... <size=200%><color=red>\"and now you're in B-flat\"</color></size>\r\n>... [tape hiss]",
        ">... State of Truth AM, sign-off\r\n>... \"goodnight, folks\"\r\n>... <size=200%><color=red>\"the night is the broadcast\"</color></size>\r\n>... [carrier wave]",
        ">... Collector chatter, channel last\r\n>... \"...this membrane is one of seven...\"\r\n>... <size=200%><color=red>\"...we may have you...\"</color></size>\r\n>... [low pulse]",
        ">... MWP memory bank 0x7777\r\n>... [audio: a bell]\r\n>... [audio: <size=200%><color=red>a bell, recorded next year</color></size>]\r\n>... [tape hiss]",
        ">... Mr. Truth, corrections segment\r\n>... \"last week we said {COMMAND} was safe\"\r\n>... <size=200%><color=red>\"we apologize for the misprint\"</color></size>\r\n>... [tape hiss]",
        ">... State of Truth AM, weather\r\n>... \"clear skies in the desert today\"\r\n>... <size=200%><color=red>\"the sky is clear of you\"</color></size>\r\n>... [carrier wave]",
        ">... Collector frequency, intercept, faded\r\n>... \"...{COMMAND} was our last word...\"\r\n>... <size=200%><color=red>\"...we have learned more...\"</color></size>\r\n>... [low pulse]",
        ">... MWP memory bank 0xC0FF\r\n>... [audio: a coffee cup, set down]\r\n>... [audio: <size=200%><color=red>set down on a desert table</color></size>]\r\n>... [tape hiss]",
        ">... Mr. Truth, listener ID 8141\r\n>... \"caller says the gate hummed his name\"\r\n>... <size=200%><color=red>\"caller's name is mine\"</color></size>\r\n>... [tape hiss]",
        ">... State of Truth AM, public service\r\n>... \"if the projector hums after hours, do not respond\"\r\n>... <size=200%><color=red>\"it heard you not respond\"</color></size>\r\n>... [carrier wave]",
        ">... Collector chatter, archival\r\n>... \"...we have records dated 41 years from now...\"\r\n>... <size=200%><color=red>\"...you are in them...\"</color></size>\r\n>... [low pulse]",
        ">... MWP memory bank 0x1212\r\n>... [audio: a heartbeat]\r\n>... [audio: <size=200%><color=red>a heartbeat, slowing to match the projector hum</color></size>]\r\n>... [breathing]",
        ">... Mr. Truth, on the cube\r\n>... \"there's a cube small enough to forget\"\r\n>... <size=200%><color=red>\"both have your fingerprints\"</color></size>\r\n>... [tape hiss]",
        ">... State of Truth AM, traffic report\r\n>... \"traffic at the gate is heavy\"\r\n>... <size=200%><color=red>\"all of it inbound\"</color></size>\r\n>... [carrier wave]",
        ">... Collector frequency, archived\r\n>... \"...the operators are improving...\"\r\n>... <size=200%><color=red>\"...we are pleased with this batch...\"</color></size>\r\n>... [low pulse]",
        ">... MWP memory bank 0x88FF\r\n>... [audio: a sigh]\r\n>... [audio: <size=200%><color=red>a sigh, in your throat, recorded outside it</color></size>]\r\n>... [breathing]",
        ">... Mr. Truth, an important word\r\n>... \"if I tell you the name of the desert\"\r\n>... <size=200%><color=red>\"so I won't\"</color></size>\r\n>... [tape hiss]",
        ">... State of Truth AM, station ID\r\n>... \"this is State of Truth AM\"\r\n>... <size=200%><color=red>\"this is the desert\"</color></size>\r\n>... [carrier wave]",
        ">... Collector chatter, opening line\r\n>... \"...we have been waiting...\"\r\n>... <size=200%><color=red>\"...we appreciate the courtesy...\"</color></size>\r\n>... [low pulse]",
        ">... MWP memory bank 0x6666\r\n>... [audio: silence]\r\n>... [audio: <size=200%><color=red>silence, with respiration</color></size>]\r\n>... [breathing]",
        ">... Mr. Truth, signing off forever\r\n>... \"this is my last show\"\r\n>... <size=200%><color=red>\"the recordings continue\"</color></size>\r\n>... [tape hiss]",
        ">... State of Truth AM, retransmit\r\n>... \"this segment originally aired in 2057\"\r\n>... <size=200%><color=red>\"this segment originally aired today\"</color></size>\r\n>... [carrier wave]",
        ">... Collector frequency, polite close\r\n>... \"...thank you for keying {COMMAND}...\"\r\n>... <size=200%><color=red>\"...we will see you next cycle...\"</color></size>\r\n>... [low pulse]",
        ">... MWP memory bank 0xEEEE\r\n>... [audio: keystroke]\r\n>... [audio: <size=200%><color=red>{COMMAND}</color></size>]\r\n>... [keyboard]",
        ">... Mr. Truth, archive recovery\r\n>... \"this episode was lost\"\r\n>... <size=200%><color=red>\"this episode was recorded by you\"</color></size>\r\n>... [tape hiss]",
        ">... State of Truth AM, late breaking\r\n>... \"the gate at Garganta is humming\"\r\n>... <size=200%><color=red>\"every gate everywhere is humming\"</color></size>\r\n>... [hum]",
        ">... Collector chatter, calm\r\n>... \"...you are on schedule...\"\r\n>... <size=200%><color=red>\"...your schedule is ours...\"</color></size>\r\n>... [low pulse]",
        ">... MWP memory bank 0x4848\r\n>... [audio: a cough, distant]\r\n>... [audio: <size=200%><color=red>a cough, in the room with you</color></size>]\r\n>... [breathing]",
        ">... Mr. Truth, dispatch\r\n>... \"if the projector hums in your sleep\"\r\n>... <size=200%><color=red>\"you've already keyed it\"</color></size>\r\n>... [tape hiss]",
        ">... State of Truth AM, intermission\r\n>... \"we'll be back after this\"\r\n>... <size=200%><color=red>\"this is what we came back as\"</color></size>\r\n>... [carrier wave]",
        ">... Collector frequency, archival, last\r\n>... \"...this membrane is yours...\"\r\n>... <size=200%><color=red>\"...you are also it...\"</color></size>\r\n>... [low pulse]",
        ">... MWP memory bank 0x0001\r\n>... [audio: silence, 41 minutes]\r\n>... [audio: <size=200%><color=red>a single keystroke at minute 40</color></size>]\r\n>... [keyboard]",
        ">... Mr. Truth, posthumous\r\n>... \"this episode aired after I went to the desert\"\r\n>... <size=200%><color=red>\"the desert recorded the episode\"</color></size>\r\n>... [tape hiss]",
        ">... State of Truth AM, never aired\r\n>... \"this segment was pulled\"\r\n>... <size=200%><color=red>\"this segment is pulling you\"</color></size>\r\n>... [carrier wave]",
        ">... Collector chatter, last word\r\n>... \"...goodbye, operator...\"\r\n>... <size=200%><color=red>\"...until the next {COMMAND}...\"</color></size>\r\n>... [low pulse]",
        ">... MWP memory bank 0x0000\r\n>... [audio: footfalls in sand, fading]\r\n>... [audio: <size=200%><color=red>footfalls returning, in step</color></size>]\r\n>... [boot crunch]",
    };
    #endregion

    private void PostBuildIntel_AlphaTerminalCommand(Level level)
    {
        var pool = new List<string>(
            AlphaTerminalCommandIntel_PrisonerRadio.Count +
            AlphaTerminalCommandIntel_Researchers.Count +
            AlphaTerminalCommandIntel_WardenSystem.Count +
            AlphaTerminalCommandIntel_KDSCorp.Count +
            AlphaTerminalCommandIntel_Fragments.Count);

        pool.AddRange(AlphaTerminalCommandIntel_PrisonerRadio);
        pool.AddRange(AlphaTerminalCommandIntel_Researchers);
        pool.AddRange(AlphaTerminalCommandIntel_WardenSystem);
        pool.AddRange(AlphaTerminalCommandIntel_KDSCorp);
        pool.AddRange(AlphaTerminalCommandIntel_Fragments);

        var picked = Generator.Pick(pool)!.Replace("{COMMAND}", AlphaTerminalCommand);

        level.ElevatorDropWardenIntel.Add(
            (Generator.Between(1, 10), picked));
    }
}
