using AutogenRundown.DataBlocks.Enums;

namespace AutogenRundown.DataBlocks.Objectives;

/// <summary>
/// Intel pools for the Cryptomnesia objective. Selected by the Reality theme of the
/// drop, with a 30% fallback to a neutral pool that draws on cube / Matter Wave
/// Projector / loop-of-cognition motifs that fit any theme.
///
/// Format conventions for every entry:
/// - 3-4 lines, separated by `\r\n`
/// - Each line prefixed with `>... ` (radio chatter) or `>` (transcript / log fragment)
/// - One `<size=200%><color=red>X</color></size>` highlight on the urgent phrase
/// - One bracketed audio/system cue per entry (e.g. `[static]`, `[siren]`)
/// - Voices: prisoner radio (Bishop GO-1395, Woods F-2056, Hackett O-4711, Dauda
///   T-3701), KDS field comms (Piros A134), researcher logs (Stokes B193, Hammerstein
///   B014, Teale B023, Stanovich C066, Connor B229, Durant B255, Schaeffer T-3894),
///   Warden corrupted output (`WRDN: COMMAND`), HearSay/BIOCOM auto-transcripts,
///   State of Truth AM, Mr. Truth fragments
/// </summary>
public partial record WardenObjective
{
    #region ErrorAlarm theme — comms shredded by sirens; BIOCOM cascade faults
    public static readonly List<string> CryptomnesiaIntel_ErrorAlarm = new()
    {
        ">... checksum mismatch on WRDN override\r\n>... EXTRACT EXTRACT EX<size=200%><color=red>--RETREAT--</color></size>\r\n>... [siren]",
        ">... alarm grid not isolating\r\n>... <size=200%><color=red>signal IS the alarm</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... quad reads four\r\n>... crypt reads <size=200%><color=red>five</color></size>\r\n>... BIOCOM: who is the fifth\r\n>... [siren]",
        ">... DISC failure level L37, ELG holding\r\n>... clock drift 230 seconds and climbing\r\n>... Lockwood A074: control the narrative\r\n>... <size=200%><color=red>narrative is screaming</color></size>\r\n>... [alarm blaring]",
        ">... WRDN: CO<size=200%><color=red>M-M-M</color></size>PLY\r\n>... operative response timeout\r\n>... operative response timeout\r\n>... [static]",
        ">... \"the siren is in the recording\"\r\n>... \"the siren was always in the <size=200%><color=red>recording</color></size>\"\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... incident count revised upward\r\n>... incident count revised <size=200%><color=red>upward</color></size>\r\n>... [siren cycling]",
        ">... silence the horn\r\n>... silence the horn\r\n>... <size=200%><color=red>nobody silenced it</color></size>\r\n>... [horn sustained]",
        ">... WRDN: <size=200%><color=red>RETREAT</color></size>\r\n>... WRDN: RETREAT\r\n>... destination unspecified\r\n>... [dead air]",
        ">... cascading reset attempted\r\n>... reset propagated to <size=200%><color=red>operative cognition</color></size>\r\n>... [siren]",
        ">... Lockwood A074 escalation declined by tier 5\r\n>... declined by tier 5\r\n>... <size=200%><color=red>declined by self</color></size>\r\n>... [static]",
        ">... DISC at 12%, ELG at 8%, CMS dark\r\n>... emergency beacon active in Z-32\r\n>... emergency beacon <size=200%><color=red>not requested</color></size>\r\n>... [siren]",
        ">... commands queueing\r\n>... commands resolving in <size=200%><color=red>reverse order</color></size>\r\n>... [warning tone]",
        ">... 0xFFEE 0xFFEE 0xFFEE\r\n>... <size=200%><color=red>0xDEAD</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... \"unscheduled klaxon at 03:14\"\r\n>... \"klaxon predates installed hardware\"\r\n>... <size=200%><color=red>install date pending</color></size>\r\n>... [siren]",
        ">... red-amber alarm mismatch\r\n>... per protocol the lower wins\r\n>... <size=200%><color=red>both are louder</color></size>\r\n>... [alarm blaring]",
        ">... no answer\r\n>... no answer\r\n>... <size=200%><color=red>no KDS-ground</color></size>\r\n>... [static]",
        ">... routing loop confirmed\r\n>... loop is the corridor\r\n>... <size=200%><color=red>corridor is the loop</color></size>\r\n>... [siren]",
        ">... WRDN: SIREN OFF\r\n>... WRDN: <size=200%><color=red>SIREN ON</color></size>\r\n>... [siren]",
        ">... emergency lighting cycling amber-red\r\n>... amber-red\r\n>... amber-<size=200%><color=red>black</color></size>\r\n>... [generator stutter]",
        ">... klaxon transcript: thirty-one minutes\r\n>... klaxon was <size=200%><color=red>two seconds</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... cannot hear myself\r\n>... cannot hear <size=200%><color=red>myself</color></size>\r\n>... [siren]",
        ">... fault on alarm bus 12\r\n>... fault on alarm bus 12\r\n>... fault on alarm bus 12\r\n>... fault propagating to <size=200%><color=red>cognition bus</color></size>\r\n>... [warning tone]",
        ">... \"the alarm was always running\"\r\n>... \"do not log this directive\"\r\n>... <size=200%><color=red>logged</color></size>\r\n>... [system chime]",
        ">... WRDN: EX<size=200%><color=red>--TRACT--</color></size>\r\n>... destination: Z-44\r\n>... [static]",
        ">... two operatives bearing GO-1395\r\n>... <size=200%><color=red>resolve manually</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... heart rate 142 BPM\r\n>... heart rate <size=200%><color=red>0 BPM</color></size>\r\n>... operative still moving\r\n>... [siren]",
        ">... \"who triggered the alarm\"\r\n>... \"who triggered the <size=200%><color=red>alarm</color></size>\"\r\n>... [recording loops]",
        ">... \"114 incidents is the floor\"\r\n>... \"114 incidents is the <size=200%><color=red>floor</color></size>\"\r\n>... [siren]",
        ">... operative offline\r\n>... operative offline\r\n>... operative <size=200%><color=red>compliant</color></size>\r\n>... [dead air]",
        ">... klaxon sweep beginning at L37\r\n>... wave reaches L0 in 230 seconds\r\n>... wave reaches operative in <size=200%><color=red>0 seconds</color></size>\r\n>... [pre-echo]",
        ">... source field empty\r\n>... source field <size=200%><color=red>filled with operative ID</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... emergency lockdown initiated\r\n>... emergency lockdown initiated\r\n>... emergency lockdown <size=200%><color=red>not initiated</color></size>\r\n>... operative inside\r\n>... [siren]",
        ">... reset the alarm\r\n>... reset the alarm\r\n>... <size=200%><color=red>reset the operative</color></size>\r\n>... [static burst]",
        ">... WRDN broadcast\r\n>... receiver: <size=200%><color=red>none configured</color></size>\r\n>... [siren]",
        ">... \"call it a malfunction\"\r\n>... \"do not call it a <size=200%><color=red>warning</color></size>\"\r\n>... [system chime]",
        ">... operative cognition flagged\r\n>... operative cognition <size=200%><color=red>flagged</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... red light, red light, <size=200%><color=red>red light</color></size>\r\n>... no green this cycle\r\n>... no green next cycle\r\n>... [siren]",
        ">... WRDN: H-H-H<size=200%><color=red>OLD</color></size>\r\n>... operative position: unknown\r\n>... [static]",
    };
    #endregion

    #region Giants theme — Project Insight clinical voice; "trees, not branches"
    public static readonly List<string> CryptomnesiaIntel_Giants = new()
    {
        ">... specimen exceeds Gallus Reptus baseline by 340%\r\n>... \"trees, not branches\" -- Hammerstein\r\n>... <size=200%><color=red>still has a wedding ring</color></size>\r\n>... [HVAC hum]",
        ">... \"the human DNA fraction is not a contaminant\"\r\n>... \"the human DNA fraction is the <size=200%><color=red>architecture</color></size>\"\r\n>... [lights cycle]",
        ">... twelve units returned empty\r\n>... twelve units returned <size=200%><color=red>larger</color></size>\r\n>... [pneumatic seal]",
        ">... subject S-072 exhibits Capreolatus skeletal frame\r\n>... subject S-072 was Capreolatus skeletal frame\r\n>... subject S-072 is <size=200%><color=red>sitting up</color></size>\r\n>... [no audio]",
        ">... \"Non ducor, duco\"\r\n>... handwriting is not Hammerstein's\r\n>... Hammerstein died in <size=200%><color=red>Shaft 17b</color></size>\r\n>... [page turn]",
        ">... do not refer to specimens by former designation\r\n>... do not refer to specimens by former <size=200%><color=red>name</color></size>\r\n>... they remember their name\r\n>... [HVAC hum]",
        ">... \"Gallus Capreolatus is structurally human\"\r\n>... \"with corrections\"\r\n>... <size=200%><color=red>my corrections</color></size>\r\n>... [pen on paper]",
        ">... bench scale exceeded\r\n>... bench scale <size=200%><color=red>destroyed</color></size>\r\n>... specimen weight: pending\r\n>... [load cell crack]",
        ">... \"not Reptus, not Jaculus, not Capreolatus\"\r\n>... \"a fourth genus, dormant\"\r\n>... <size=200%><color=red>or a first</color></size>\r\n>... [HVAC hum]",
        ">... 28 units in, 16 units out\r\n>... 12 units re-categorized\r\n>... 12 units <size=200%><color=red>walked</color></size>\r\n>... [pneumatic seal]",
        ">... \"the size is not the horror\"\r\n>... \"the <size=200%><color=red>composure</color></size> is the horror\"\r\n>... [lights cycle]",
        ">... white only\r\n>... white only\r\n>... white preserves <size=200%><color=red>the shape</color></size>\r\n>... [fluorescent buzz]",
        ">... CT slice 0042: ribcage 3x baseline\r\n>... CT slice 0042: ribcage <size=200%><color=red>occupied</color></size>\r\n>... [scanner cycling]",
        ">... \"the Gallus is not the Sleeper\"\r\n>... \"the Gallus is what the Sleeper <size=200%><color=red>becomes</color></size>\"\r\n>... [pen on paper]",
        ">... \"this one is wearing my coat\"\r\n>... \"this one is <size=200%><color=red>wearing my coat</color></size>\"\r\n>... [breathing]",
        ">... reclassification halted by tier 5\r\n>... reclassification halted by <size=200%><color=red>specimen</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... \"if I name it, it answers\"\r\n>... \"I have not named it\"\r\n>... \"it has <size=200%><color=red>answered</color></size>\"\r\n>... [no audio]",
        ">... \"do not feed the standing one\"\r\n>... \"the standing one is <size=200%><color=red>feeding</color></size>\"\r\n>... [HVAC hum]",
        ">... \"my ring fits a finger that is not mine\"\r\n>... \"my ring fits a finger that is <size=200%><color=red>larger</color></size>\"\r\n>... [page turn]",
        ">... 3 units verified at intake\r\n>... 4 units verified at <size=200%><color=red>discharge</color></size>\r\n>... [pneumatic seal]",
        ">... white light protocol active\r\n>... white light protocol <size=200%><color=red>insufficient</color></size>\r\n>... [fluorescent buzz]",
        ">... \"do you remember my face\"\r\n>... \"I do not remember <size=200%><color=red>your face</color></size>\"\r\n>... [silence]",
        ">... \"specimen S-072 has not eaten\"\r\n>... \"specimen S-072 has not <size=200%><color=red>blinked</color></size>\"\r\n>... 14 days observation\r\n>... [HVAC hum]",
        ">... activated by hand at 03:14\r\n>... no hand on the panel\r\n>... no hand on the <size=200%><color=red>panel</color></size>\r\n>... [airflow surge]",
        ">... a Gallus with hands\r\n>... a Gallus with <size=200%><color=red>my hands</color></size>\r\n>... [pen on paper]",
        ">... \"this one held the door for me\"\r\n>... \"this one held the door for <size=200%><color=red>me</color></size>\"\r\n>... [door servo]",
        ">... \"Gallus tissue resists fixation\"\r\n>... \"Gallus tissue resists <size=200%><color=red>identification</color></size>\"\r\n>... [microscope click]",
        ">... \"never address a specimen by name\"\r\n>... \"a specimen has <size=200%><color=red>memorized yours</color></size>\"\r\n>... [HVAC hum]",
        ">... -187.4°C → -94.1°C → 36.9°C\r\n>... <size=200%><color=red>internal heat source</color></size>\r\n>... [coolant alarm]",
        ">... \"the Gallus is composed\"\r\n>... \"the Gallus is <size=200%><color=red>composing</color></size>\"\r\n>... [pen on paper]",
        ">... \"my hands are not my hands\"\r\n>... \"my hands are not my hands\"\r\n>... \"my hands are <size=200%><color=red>not</color></size>\"\r\n>... [silence]",
        ">... door opened from inside, 04:41\r\n>... no operative inside at 04:40\r\n>... no operative <size=200%><color=red>inside</color></size>\r\n>... [door servo]",
        ">... \"trees, not branches\"\r\n>... \"the tree is <size=200%><color=red>standing in the corridor</color></size>\"\r\n>... [chalk on board]",
        ">... \"it is wearing a face I half-remember\"\r\n>... \"it is wearing a <size=200%><color=red>face I half-remember</color></size>\"\r\n>... [breathing]",
        ">... \"specimen S-072 reclassified\"\r\n>... \"specimen S-072 reclassified as <size=200%><color=red>Stokes</color></size>\"\r\n>... [no audio]",
        ">... \"do not open the crate alone\"\r\n>... \"do not open the crate <size=200%><color=red>at all</color></size>\"\r\n>... [crate hiss]",
        ">... lab 6 sealed by tier 5\r\n>... lab 6 sealed by <size=200%><color=red>specimen</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... \"Non ducor, duco\"\r\n>... \"I am not led, I lead\"\r\n>... \"this time I am <size=200%><color=red>led</color></size>\"\r\n>... [chalk on board]",
        ">... 100% white, no spectral drift\r\n>... 100% white, no spectral drift\r\n>... shadow cast: <size=200%><color=red>nineteen meters</color></size>\r\n>... [fluorescent buzz]",
    };
    #endregion

    #region Chargers theme — KDS field-comms; truncated declaratives; red-light protocol
    public static readonly List<string> CryptomnesiaIntel_Chargers = new()
    {
        ">... contact, contact, Z-32, fast movers\r\n>... quad B452 hold position\r\n>... quad B452 <size=200%><color=red>does not hold</color></size>\r\n>... [gunfire]",
        ">... aggression spike, source external\r\n>... source external\r\n>... source is the <size=200%><color=red>room</color></size>\r\n>... [growl]",
        ">... \"contractors call it the kill floor\"\r\n>... McCallister asked, McCallister was dismissed\r\n>... red light, red light, red <size=200%><color=red>light</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... \"they're in the corridor and the corridor is in <size=200%><color=red>me</color></size>\"\r\n>... [KSO entry]\r\n>... log terminated by tier 5 authority",
        ">... \"product runs hot, product runs faster\"\r\n>... Sigma generation outpacing chip latency\r\n>... they are <size=200%><color=red>deciding, sir</color></size>\r\n>... [static]",
        ">... Z-32 cleared\r\n>... Z-32 not cleared\r\n>... Z-32 <size=200%><color=red>louder</color></size>\r\n>... [gunfire]",
        ">... pulse 188 BPM\r\n>... pulse 188 BPM\r\n>... pulse <size=200%><color=red>flat</color></size>\r\n>... [breathing]",
        ">... no surface contact\r\n>... no surface contact\r\n>... <size=200%><color=red>contact behind you</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... \"the corridor is shorter on the way out\"\r\n>... \"the corridor is shorter every <size=200%><color=red>cycle</color></size>\"\r\n>... [pen on paper]",
        ">... three movers, four movers, six movers\r\n>... ammunition assessment: <size=200%><color=red>insufficient</color></size>\r\n>... [magazine click]",
        ">... \"red light is the briefing\"\r\n>... \"red light is the <size=200%><color=red>contract</color></size>\"\r\n>... [static]",
        ">... \"my chip is firing on its own\"\r\n>... \"my chip is firing <size=200%><color=red>on its own</color></size>\"\r\n>... [Sec-B-M tone]",
        ">... operative aim: not configured\r\n>... operative aim <size=200%><color=red>configured by chip</color></size>\r\n>... [feedback]",
        ">... \"new aggression curve deployed\"\r\n>... \"do not consult operative\"\r\n>... operative is <size=200%><color=red>already running</color></size>\r\n>... [boot thud]",
        ">... red light cycle 33\r\n>... red light cycle <size=200%><color=red>32</color></size>\r\n>... [light buzz]",
        ">... entry suppressed by Lockwood A074\r\n>... entry resurfaced by <size=200%><color=red>specimen</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... \"the corridor smells like copper\"\r\n>... \"the corridor smells like <size=200%><color=red>me</color></size>\"\r\n>... [breathing]",
        ">... \"shoot first\"\r\n>... \"shoot first\"\r\n>... \"shoot <size=200%><color=red>last</color></size>\"\r\n>... [gunfire]",
        ">... \"they took my badge before they shot me\"\r\n>... \"they took my badge before they <size=200%><color=red>shot me</color></size>\"\r\n>... [silence]",
        ">... no flares\r\n>... no flares\r\n>... <size=200%><color=red>they see in red</color></size>\r\n>... [static]",
        ">... Sec-B-M chip latency 22ms\r\n>... Sec-B-M chip latency <size=200%><color=red>0ms</color></size>\r\n>... operative ahead of command\r\n>... [Sec-B-M tone]",
        ">... WRDN: <size=200%><color=red>SEEK</color></size>\r\n>... WRDN: SEEK\r\n>... WRDN: SEEK\r\n>... target: operative\r\n>... [feedback]",
        ">... \"reload\"\r\n>... \"reload\"\r\n>... \"<size=200%><color=red>nothing to reload into</color></size>\"\r\n>... [magazine click]",
        ">... \"the contract pays per body\"\r\n>... \"the contract pays per body\"\r\n>... \"the contract pays per <size=200%><color=red>your</color></size> body\"\r\n>... [paper rustle]",
        ">... \"red is the only color the corridor takes\"\r\n>... \"red is the only color the corridor <size=200%><color=red>has taken</color></size>\"\r\n>... [static]",
        ">... muscle fatigue 4%\r\n>... muscle fatigue 4%\r\n>... muscle fatigue <size=200%><color=red>0%</color></size>\r\n>... [breathing]",
        ">... \"contact\"\r\n>... \"contact\"\r\n>... \"<size=200%><color=red>contact in front and behind</color></size>\"\r\n>... [gunfire]",
        ">... red lighting cannot fail\r\n>... red lighting was <size=200%><color=red>never lit</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... \"the room is faster than I am\"\r\n>... \"the room has been faster than I am for <size=200%><color=red>seven years</color></size>\"\r\n>... [pen on paper]",
        ">... \"two left\"\r\n>... \"one left\"\r\n>... \"<size=200%><color=red>none left</color></size>\"\r\n>... [static]",
        ">... operative did not consent\r\n>... operative did not <size=200%><color=red>need to</color></size>\r\n>... [Sec-B-M tone]",
        ">... WRDN: PURSUE\r\n>... target: <size=200%><color=red>operative</color></size>\r\n>... [feedback]",
        ">... \"I am pulling my own trigger\"\r\n>... \"I am pulling my own <size=200%><color=red>trigger</color></size>\"\r\n>... [gunshot]",
        ">... \"red lighting is a kindness\"\r\n>... \"you do not have to see <size=200%><color=red>their faces</color></size>\"\r\n>... [boot thud]",
        ">... \"casualty rate at red is below KDS-Deep\"\r\n>... \"casualty rate at red is <size=200%><color=red>not yours to query</color></size>\"\r\n>... [paper rustle]",
        ">... \"forward, forward, forward\"\r\n>... \"forward into the <size=200%><color=red>door that is closed</color></size>\"\r\n>... [Sec-B-M tone]",
        ">... \"I have run out of corridor\"\r\n>... \"I have not run out of <size=200%><color=red>direction</color></size>\"\r\n>... [breathing]",
    };
    #endregion

    #region InfectionFog theme — WHO/Stanovich epidemiology; NAM-V; "the Stoops"
    public static readonly List<string> CryptomnesiaIntel_InfectionFog = new()
    {
        ">... NAM-V case count revised upward\r\n>... 4.8 billion. 4.8 billion. 4.8 [inaudible]\r\n>... survives 4+ weeks <size=200%><color=red>outside host</color></size>\r\n>... [hiss]",
        ">... 34.4% workforce psychological disturbance\r\n>... no physical etiology\r\n>... workers are calling it <size=200%><color=red>the Stoops</color></size>\r\n>... [pen on paper]",
        ">... \"the virus is perfectly designed\"\r\n>... \"perfectly designed implies a designer\"\r\n>... <size=200%><color=red>do not transmit this line</color></size>\r\n>... [silence]",
        ">... target escaped Garganta with hazardous material\r\n>... target escaped Garganta\r\n>... target <size=200%><color=red>is</color></size> the hazardous material\r\n>... [hiss]",
        ">... mass cremation site grid 12\r\n>... fog reads positive for NAM-V\r\n>... fog reads positive for <size=200%><color=red>cognition</color></size>\r\n>... [Geiger click]",
        ">... \"the host is improving the virus\"\r\n>... \"the host is <size=200%><color=red>thanking</color></size> the virus\"\r\n>... [pen on paper]",
        ">... \"NAM-V is not airborne\"\r\n>... \"NAM-V is <size=200%><color=red>thoughtborne</color></size>\"\r\n>... line stricken by tier 5\r\n>... [silence]",
        ">... \"Progreso is a fog the size of a city\"\r\n>... \"Progreso is a city the size of a <size=200%><color=red>fog</color></size>\"\r\n>... [wind]",
        ">... new label: insufficient\r\n>... new label: insufficient\r\n>... new label: <size=200%><color=red>insufficient</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... \"I have stopped washing my hands\"\r\n>... \"the virus and I have an <size=200%><color=red>understanding</color></size>\"\r\n>... [tap drip]",
        ">... fog density Z-44: 88%\r\n>... fog density Z-44: 88%\r\n>... fog density Z-44: <size=200%><color=red>112%</color></size>\r\n>... [airflow surge]",
        ">... \"the Stoops is not a posture\"\r\n>... \"the Stoops is a <size=200%><color=red>listening</color></size>\"\r\n>... [pen on paper]",
        ">... \"my disinfectant is empty\"\r\n>... \"my disinfectant is full\"\r\n>... \"my disinfectant is <size=200%><color=red>warm</color></size>\"\r\n>... [hiss]",
        ">... \"do not approach the fog\"\r\n>... \"the fog is approaching\"\r\n>... \"the fog is <size=200%><color=red>familiar</color></size>\"\r\n>... [wind]",
        ">... \"NAM-V iteration 7 is not iteration 6\"\r\n>... \"iteration 7 is <size=200%><color=red>asking questions</color></size>\"\r\n>... [silence]",
        ">... \"don't breathe through the cloth\"\r\n>... \"breathe <size=200%><color=red>with</color></size> it\"\r\n>... [voice deepening]",
        ">... \"114 incidents do not include the fog\"\r\n>... \"the fog is the <size=200%><color=red>incident</color></size>\"\r\n>... [pen on paper]",
        ">... \"the virus is not contagious\"\r\n>... \"the virus is <size=200%><color=red>conversational</color></size>\"\r\n>... [chalk on board]",
        ">... 4 of 4 turbines online\r\n>... 5 of 4 turbines online\r\n>... <size=200%><color=red>5 of 4 turbines online</color></size>\r\n>... [turbine hum]",
        ">... \"I am not stooped\"\r\n>... \"I am not stooped\"\r\n>... \"I am <size=200%><color=red>listening</color></size>\"\r\n>... [hiss]",
        ">... vector: airborne\r\n>... vector: <size=200%><color=red>memorial</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... \"sample S-901 reproduces in disinfectant\"\r\n>... \"sample S-901 <size=200%><color=red>prefers</color></size> disinfectant\"\r\n>... [tap drip]",
        ">... \"the Stoops is not contagious by air\"\r\n>... \"the Stoops is contagious by <size=200%><color=red>schedule</color></size>\"\r\n>... [pen on paper]",
        ">... [garbled]\r\n>... [garbled]\r\n>... \"<size=200%><color=red>Don't touch that dial</color></size>\"\r\n>... [static]",
        ">... \"I have not coughed once\"\r\n>... \"I have not coughed <size=200%><color=red>at all</color></size>\"\r\n>... [silence]",
        ">... bodies counted: 14,000\r\n>... bodies counted: 14,000\r\n>... bodies counted: <size=200%><color=red>14,001</color></size>\r\n>... [wind]",
        ">... \"my workforce is not sick\"\r\n>... \"my workforce is <size=200%><color=red>concentrating</color></size>\"\r\n>... [hiss]",
        ">... composition: 22% NAM-V, 76% air\r\n>... composition: 22% NAM-V, 76% <size=200%><color=red>cretasium</color></size>\r\n>... [hiss]",
        ">... \"the fog is humming\"\r\n>... \"the fog is humming\"\r\n>... \"the fog is humming <size=200%><color=red>my song</color></size>\"\r\n>... [wind]",
        ">... \"I have been writing this report for nine days\"\r\n>... \"I have been writing this report for <size=200%><color=red>one minute</color></size>\"\r\n>... [pen on paper]",
        ">... \"smile for the lens\"\r\n>... \"smile for the lens\"\r\n>... \"the lens is <size=200%><color=red>smiling back</color></size>\"\r\n>... [shutter]",
        ">... cordon redrawn\r\n>... cordon redrawn around the <size=200%><color=red>operative</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... \"sweat composition: NAM-V positive\"\r\n>... \"sweat composition: NAM-V <size=200%><color=red>productive</color></size>\"\r\n>... [hiss]",
        ">... transmission ends\r\n>... transmission ends\r\n>... <size=200%><color=red>transmission resumes</color></size>\r\n>... [static]",
        ">... \"I do not miss anyone\"\r\n>... \"I do not miss anyone\"\r\n>... \"I do not miss <size=200%><color=red>anyone</color></size>\"\r\n>... [tap drip]",
        ">... turbine 3 reversing\r\n>... turbine 3 reversing\r\n>... turbine 3 <size=200%><color=red>swallowing</color></size>\r\n>... [turbine groan]",
        ">... \"label this report 'routine'\"\r\n>... \"label this report 'routine'\"\r\n>... \"label this report <size=200%><color=red>'final'</color></size>\"\r\n>... [pen on paper]",
    };
    #endregion

    #region Shadows theme — Teale dissociation; HearSay surveillance bleed; "I can hear you"
    public static readonly List<string> CryptomnesiaIntel_Shadows = new()
    {
        ">... \"I can hear you out there\"\r\n>... \"I can hear you in here\"\r\n>... <size=200%><color=red>recording predates installation date</color></size>\r\n>... [tape hiss]",
        ">... breathing\r\n>... breathing\r\n>... breathing <size=200%><color=red>in time with mine</color></size>\r\n>... [breathing]",
        ">... \"my files have been altered\"\r\n>... \"my files alter while I read them\"\r\n>... \"the file is reading <size=200%><color=red>me</color></size>\"\r\n>... [pen on paper]",
        ">... 1,000,000,000+ entries\r\n>... one entry returns the operative's name\r\n>... operative did <size=200%><color=red>not submit a name</color></size>\r\n>... [keyboard click]",
        ">... \"the visions are not hallucinations\"\r\n>... \"the hallucinations are not mine\"\r\n>... \"someone else is having them <size=200%><color=red>through me</color></size>\"\r\n>... [silence]",
        ">... \"who is recording this\"\r\n>... \"who is recording <size=200%><color=red>this</color></size>\"\r\n>... //transcript begins",
        ">... \"my reflection is delayed\"\r\n>... \"my reflection is <size=200%><color=red>ahead</color></size>\"\r\n>... [pen on paper]",
        ">... \"the door is locked from inside\"\r\n>... \"I am inside\"\r\n>... \"I am also <size=200%><color=red>locking it</color></size>\"\r\n>... [tape hiss]",
        ">... footsteps\r\n>... footsteps\r\n>... <size=200%><color=red>footsteps continue when operative stops</color></size>\r\n>... [boot scrape]",
        ">... \"discharge granted, signed Soweta\"\r\n>... \"signed Soweta\"\r\n>... \"signed <size=200%><color=red>twice</color></size>\"\r\n>... [pen on paper]",
        ">... \"my notes contain instructions\"\r\n>... \"the instructions are not <size=200%><color=red>mine</color></size>\"\r\n>... [keyboard click]",
        ">... empty\r\n>... empty\r\n>... contains <size=200%><color=red>your voice</color></size>\r\n>... [keyboard click]",
        ">... \"there is a footstep behind every footstep\"\r\n>... \"there is a footstep behind <size=200%><color=red>every</color></size>\"\r\n>... [boot scrape]",
        ">... \"the surveillance is the surveilled\"\r\n>... \"the surveillance is <size=200%><color=red>filming itself</color></size>\"\r\n>... [tape hiss]",
        ">... \"I have already met today\"\r\n>... \"I have already <size=200%><color=red>finished today</color></size>\"\r\n>... [pen on paper]",
        ">... \"do not turn around\"\r\n>... \"do not turn around\"\r\n>... \"<size=200%><color=red>thank you</color></size>\"\r\n>... [whisper]",
        ">... operative's name appears 412 times\r\n>... 411 are misspelled\r\n>... 1 is <size=200%><color=red>correct</color></size>\r\n>... [keyboard click]",
        ">... \"there are too many of me\"\r\n>... \"none of them are <size=200%><color=red>too many</color></size>\"\r\n>... [silence]",
        ">... \"the dark holds\"\r\n>... \"the dark holds <size=200%><color=red>still</color></size>\"\r\n>... [tape hiss]",
        ">... \"prisoner T-3701 inhales\"\r\n>... \"prisoner T-3701 inhales\"\r\n>... \"prisoner T-3701 has not been <size=200%><color=red>deployed</color></size>\"\r\n>... [breathing]",
        ">... \"I have run out of names for the patient\"\r\n>... \"the patient has <size=200%><color=red>my name</color></size>\"\r\n>... [pen on paper]",
        ">... 1,247 archive entries\r\n>... operative born <size=200%><color=red>this morning</color></size>\r\n>... [keyboard click]",
        ">... \"the green light is the witness\"\r\n>... \"the green light is the <size=200%><color=red>second witness</color></size>\"\r\n>... [tape hiss]",
        ">... \"my breathing is not local\"\r\n>... \"my breathing is <size=200%><color=red>shared</color></size>\"\r\n>... [breathing]",
        ">... \"two Sowetas left the facility\"\r\n>... \"one Soweta arrived <size=200%><color=red>home</color></size>\"\r\n>... [door close]",
        ">... \"you are being watched\"\r\n>... \"you are being watched\"\r\n>... \"<size=200%><color=red>you are watching back</color></size>\"\r\n>... [whisper]",
        ">... operative's last command: 'cancel'\r\n>... operative's last command: <size=200%><color=red>'observe'</color></size>\r\n>... [keyboard click]",
        ">... \"the recorder is the recorded\"\r\n>... \"the recorder is the <size=200%><color=red>recordee</color></size>\"\r\n>... [tape hiss]",
        ">... \"there is light in the corridor\"\r\n>... \"there is light <size=200%><color=red>behind</color></size> the corridor\"\r\n>... [pen on paper]",
        ">... \"operative said\"\r\n>... \"operative said\"\r\n>... \"operative had <size=200%><color=red>not yet spoken</color></size>\"\r\n>... [keyboard click]",
        ">... \"my voice is in the channel before I speak\"\r\n>... \"my voice is in the channel <size=200%><color=red>after I stop</color></size>\"\r\n>... [echo]",
        ">... \"the visions ended\"\r\n>... \"the visions ended\"\r\n>... \"the visions <size=200%><color=red>did not</color></size>\"\r\n>... [silence]",
        ">... self\r\n>... self\r\n>... <size=200%><color=red>self (other)</color></size>\r\n>... [pen on paper]",
        ">... \"do not erase this\"\r\n>... \"do not erase this\"\r\n>... \"<size=200%><color=red>too late</color></size>\"\r\n>... [tape hiss]",
        ">... \"there is a shadow on the camera\"\r\n>... \"the camera is <size=200%><color=red>the shadow</color></size>\"\r\n>... [keyboard click]",
        ">... \"footfall pattern matched 1 of 1\"\r\n>... \"matched to file: <size=200%><color=red>operative</color></size>\"\r\n>... [boot scrape]",
        ">... \"my speech delay is six seconds\"\r\n>... \"my speech delay is <size=200%><color=red>before</color></size>\"\r\n>... [silence]",
        ">... \"sealed by tier 5\"\r\n>... \"sealed by tier 5\"\r\n>... \"sealed by <size=200%><color=red>operative</color></size>\"\r\n>... [keyboard click]",
        ">... \"the door is open\"\r\n>... \"the door is open\"\r\n>... \"the door is <size=200%><color=red>watching</color></size>\"\r\n>... [tape hiss]",
        ">... \"are you still here\"\r\n>... \"are you still here\"\r\n>... \"are you <size=200%><color=red>still</color></size>\"\r\n>... [silence]",
    };
    #endregion

    #region Nightmares theme — State of Truth AM; Mr. Truth; EF-01; "the corridor remembers"
    public static readonly List<string> CryptomnesiaIntel_Nightmares = new()
    {
        ">... \"the Merida quake was on a date that didn't exist yet\"\r\n>... \"you remember it. so do I.\"\r\n>... <size=200%><color=red>Don't touch that dial</color></size>\r\n>... [static]",
        ">... sealed chamber, biomass exceeds chamber volume\r\n>... final expedition tomorrow\r\n>... final expedition <size=200%><color=red>was yesterday</color></size>\r\n>... [pen on paper]",
        ">... \"we have been here ten months\"\r\n>... Garganta clock: 4 hours 12 minutes\r\n>... Bishop returned with <size=200%><color=red>two masks</color></size>\r\n>... [static]",
        ">... \"Mrs. Truth is not here\"\r\n>... \"Mr. Truth is not here either\"\r\n>... \"the dial turned <size=200%><color=red>itself</color></size>\"\r\n>... [wind]",
        ">... you have walked this corridor\r\n>... you have walked this corridor\r\n>... the corridor remembers you. <size=200%><color=red>you do not</color></size>\r\n>... [boot scrape]",
        ">... \"the dreamer is the door\"\r\n>... \"the door has been opened from the <size=200%><color=red>other side</color></size>\"\r\n>... [low hum]",
        ">... quad B452 deployment count <size=200%><color=red>unknown</color></size>\r\n>... you are not the first you\r\n>... [silence]",
        ">... \"if you remember a place you've never been\"\r\n>... \"someone has been there <size=200%><color=red>as you</color></size>\"\r\n>... [static]",
        ">... \"the dust is not falling\"\r\n>... \"the dust is <size=200%><color=red>arriving</color></size>\"\r\n>... [wind]",
        ">... \"I am writing this twice\"\r\n>... \"I am writing this <size=200%><color=red>again</color></size>\"\r\n>... [pen on paper]",
        ">... \"a dream is a deployment\"\r\n>... \"a deployment is a <size=200%><color=red>dream</color></size>\"\r\n>... [static]",
        ">... \"I have aged\"\r\n>... \"I have aged\"\r\n>... \"I have <size=200%><color=red>met myself</color></size>\"\r\n>... [tape hiss]",
        ">... 14% iron oxide\r\n>... 14% cretasium\r\n>... 72% <size=200%><color=red>not measured</color></size>\r\n>... [wind]",
        ">... \"the chamber is bigger inside\"\r\n>... \"the chamber is <size=200%><color=red>older</color></size> inside\"\r\n>... [silence]",
        ">... \"my call letters are not my call letters\"\r\n>... \"my call letters belong to <size=200%><color=red>you</color></size>\"\r\n>... [static]",
        ">... a forgotten memory returning as new\r\n>... operative reading this entry\r\n>... has read this entry <size=200%><color=red>before</color></size>\r\n>... [page turn]",
        ">... \"the corridor is open at both ends\"\r\n>... \"the corridor is open at <size=200%><color=red>three</color></size>\"\r\n>... [wind]",
        ">... \"I have signed off\"\r\n>... \"I have signed off\"\r\n>... \"I am <size=200%><color=red>still here</color></size>\"\r\n>... [static]",
        ">... \"I dreamed this corridor\"\r\n>... \"I dreamed this corridor\"\r\n>... \"the corridor <size=200%><color=red>dreamed back</color></size>\"\r\n>... [boot scrape]",
        ">... 4 prisoners deployed\r\n>... 4 prisoners returned\r\n>... 5 prisoners <size=200%><color=red>recovered</color></size>\r\n>... [Geiger click]",
        ">... figure A: Connor\r\n>... figure B: Connor\r\n>... figure C: <size=200%><color=red>not Connor</color></size>\r\n>... [pen on paper]",
        ">... \"I think I dreamed your station\"\r\n>... \"I think you dreamed <size=200%><color=red>me</color></size>\"\r\n>... [static]",
        ">... \"I do not remember thawing\"\r\n>... \"I do not remember <size=200%><color=red>freezing</color></size>\"\r\n>... [coolant hiss]",
        ">... orange light L37 pre-deployment\r\n>... orange light L37 pre-deployment\r\n>... orange light L37 <size=200%><color=red>post-extraction</color></size>\r\n>... [low hum]",
        ">... \"the rations have multiplied\"\r\n>... \"the rations have <size=200%><color=red>aged</color></size>\"\r\n>... [tape hiss]",
        ">... \"I am not coming back\"\r\n>... \"I am <size=200%><color=red>already back</color></size>\"\r\n>... [silence]",
        ">... \"the dust is not from here\"\r\n>... \"the dust is from <size=200%><color=red>when</color></size>\"\r\n>... [wind]",
        ">... \"the loop is not the symptom\"\r\n>... \"the loop is the <size=200%><color=red>diagnosis</color></size>\"\r\n>... [page turn]",
        ">... \"my orders are familiar\"\r\n>... \"my orders are <size=200%><color=red>completed</color></size>\"\r\n>... not yet executed\r\n>... [breathing]",
        ">... \"good night, Pahrump\"\r\n>... \"good night, <size=200%><color=red>Garganta</color></size>\"\r\n>... [static]",
        ">... \"the door home is not the door home\"\r\n>... \"the door home is <size=200%><color=red>another door</color></size>\"\r\n>... [latch]",
        ">... \"I returned with my own face\"\r\n>... \"I returned with <size=200%><color=red>two</color></size>\"\r\n>... [silence]",
        ">... \"the chamber wall has my handwriting\"\r\n>... \"the chamber wall has <size=200%><color=red>better</color></size> handwriting\"\r\n>... [pen on paper]",
        ">... origin: Yucatan, Chicxulub\r\n>... origin: Yucatan, <size=200%><color=red>future</color></size>\r\n>... [wind]",
        ">... \"my crypt is not where I left it\"\r\n>... \"my crypt is where I will <size=200%><color=red>leave it</color></size>\"\r\n>... [coolant hiss]",
        ">... operative cognition: novel\r\n>... operative cognition: <size=200%><color=red>recurrent</color></size>\r\n>... rerunning\r\n>... [keyboard click]",
        ">... [no audio]\r\n>... [no audio]\r\n>... \"<size=200%><color=red>still here</color></size>\"\r\n>... [static resumes]",
        ">... \"the corridor smells like a dream\"\r\n>... \"the dream <size=200%><color=red>smells like the corridor</color></size>\"\r\n>... [boot scrape]",
    };
    #endregion

    #region Neutral — cube / Matter Wave Projector / loop / cretasium / hydrostasis memory
    public static readonly List<string> CryptomnesiaIntel_Neutral = new()
    {
        ">... We're... back...\r\n>... This will go quick then!\r\n>... No, <size=200%><color=red>wait-</color></size>\r\n>... [screeching, gunfire]",
        ">... cretasium signature 24% unidentified\r\n>... matches Chicxulub meteorite spectrum\r\n>... matches the operative's <size=200%><color=red>blood</color></size>\r\n>... [Geiger click]",
        ">... silicon resin coating: nominal\r\n>... do not contact the surface unshielded\r\n>... previous quads who did: 7. recovered: <size=200%><color=red>0</color></size>\r\n>... [transformer hum]",
        ">... destination: Reality\r\n>... destination: <size=200%><color=red>Reality?</color></size>\r\n>... [chamber pressurize]",
        ">... memory continuity flagged as forgery\r\n>... memory continuity flagged as forgery\r\n>... flag dismissed by <size=200%><color=red>tier 5 authority</color></size>\r\n>... [system chime]",
        ">... artifact integrity: unbreakable\r\n>... artifact contents: a corridor you've walked\r\n>... artifact contents: <size=200%><color=red>this corridor</color></size>\r\n>... [low hum]",
        ">... clock anomaly L37: +230s/24h\r\n>... quad clock: -230s/24h\r\n>... net drift across drop: zero\r\n>... net drift across <size=200%><color=red>you</color></size>: unknown\r\n>... [tick]",
        ">... \"do not call it a dimension\"\r\n>... \"do not call it a memory either\"\r\n>... \"call it a <size=200%><color=red>recovery operation</color></size>\"\r\n>... [paper rustle]",
        ">... two matches. one operative.\r\n>... <size=200%><color=red>EF-01 anomaly persists</color></size>\r\n>... [scanner click]",
        ">... operative status: deployed\r\n>... operative status: <size=200%><color=red>re-</color></size>deployed\r\n>... cube count rising\r\n>... [page turn]",
        ">... \"if you remember a place you've never been --\"\r\n>... \"-- someone has been there <size=200%><color=red>as you</color></size>\"\r\n>... Don't touch that dial. Mr. Truth out.\r\n>... [static]",
        ">... 4 of 4 operatives sealed\r\n>... 4 of 4 operatives sealed\r\n>... 4 of 4 operatives <size=200%><color=red>not yet entered</color></size>\r\n>... [chamber pressurize]",
        ">... requested: 4\r\n>... received: 4\r\n>... archived: <size=200%><color=red>5</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... \"I do not know whose voice this is\"\r\n>... \"the voice is <size=200%><color=red>signing off as me</color></size>\"\r\n>... [coolant hiss]",
        ">... \"deployment count: 1\"\r\n>... \"deployment count: 1\"\r\n>... \"deployment count: <size=200%><color=red>not displayed</color></size>\"\r\n>... [Sec-B-M tone]",
        ">... cycle 0042 complete\r\n>... cycle 0042 complete\r\n>... cycle 0042 <size=200%><color=red>still running</color></size>\r\n>... [transformer hum]",
        ">... cretasium reading L37: anomalous\r\n>... cretasium reading L37: anomalous\r\n>... cretasium reading <size=200%><color=red>follows operative</color></size>\r\n>... [Geiger click]",
        ">... data cube serial <size=200%><color=red>RK-0042-Y</color></size>\r\n>... different alphabet\r\n>... [low hum]",
        ">... \"COMPLY\"\r\n>... \"EXTRACT\"\r\n>... \"<size=200%><color=red>RECALL</color></size>\"\r\n>... [feedback]",
        ">... \"I remember this elevator\"\r\n>... \"I remember <size=200%><color=red>not remembering</color></size> this elevator\"\r\n>... [chamber pressurize]",
        ">... \"the dimension is a misfiled report\"\r\n>... \"the misfiled report is the <size=200%><color=red>only true file</color></size>\"\r\n>... [paper rustle]",
        ">... 14 cycles this hour\r\n>... 14 cycles this hour\r\n>... <size=200%><color=red>operative arrived 13 times</color></size>\r\n>... [system chime]",
        ">... patient describes a vivid first deployment\r\n>... patient is on deployment <size=200%><color=red>114</color></size>\r\n>... [pen on paper]",
        ">... carbon-12 signature: nominal\r\n>... cretasium signature: <size=200%><color=red>elevated</color></size>\r\n>... operative signature: present\r\n>... [Geiger click]",
        ">... \"this map is wrong\"\r\n>... \"this map is wrong\"\r\n>... \"this map is <size=200%><color=red>tomorrow's</color></size>\"\r\n>... [paper rustle]",
        ">... operative consciousness: continuous\r\n>... operative consciousness: continuous\r\n>... operative consciousness: <size=200%><color=red>continuous (revised)</color></size>\r\n>... [system chime]",
        ">... \"Non ducor, duco\"\r\n>... \"a corridor leads its walker\"\r\n>... \"the walker has been <size=200%><color=red>led before</color></size>\"\r\n>... [chalk on board]",
        ">... percentage of recall: 92%\r\n>... percentage of recall: 92%\r\n>... percentage of recall: <size=200%><color=red>0%</color></size>\r\n>... [coolant hiss]",
        ">... \"a memory you do not have\"\r\n>... \"is a memory <size=200%><color=red>someone else has of you</color></size>\"\r\n>... [static]",
        ">... \"my notes contain my future notes\"\r\n>... \"my future notes are <size=200%><color=red>illegible</color></size>\"\r\n>... [pen on paper]",
        ">... seal integrity: 100%\r\n>... seal integrity: 100%\r\n>... seal integrity: <size=200%><color=red>not the right seal</color></size>\r\n>... [chamber pressurize]",
        ">... contents: 'do not'\r\n>... contents: 'do not'\r\n>... contents: '<size=200%><color=red>do not turn around</color></size>'\r\n>... [low hum]",
        ">... operative cognition: novel\r\n>... operative cognition: novel\r\n>... operative cognition: <size=200%><color=red>recurrent (1142)</color></size>\r\n>... [keyboard click]",
        ">... \"the loop is not the failure\"\r\n>... \"the loop is the <size=200%><color=red>product</color></size>\"\r\n>... [pen on paper]",
        ">... heart rate: 88 BPM\r\n>... heart rate: 88 BPM\r\n>... heart rate: <size=200%><color=red>88 BPM (not yours)</color></size>\r\n>... [Sec-B-M tone]",
        ">... \"we have been here before\"\r\n>... \"we have been here before\"\r\n>... \"we have <size=200%><color=red>not yet left</color></size>\"\r\n>... [feedback]",
        ">... \"strike all references to recurrence\"\r\n>... \"strike all references to <size=200%><color=red>recurrence</color></size>\"\r\n>... line preserved by automation\r\n>... [paper rustle]",
        ">... cretasium drift observed at L37\r\n>... drift vector: north-northwest\r\n>... drift vector: <size=200%><color=red>operative-shaped</color></size>\r\n>... [Geiger click]",
        ">... \"the elevator door has opened twice\"\r\n>... \"I have entered <size=200%><color=red>once</color></size>\"\r\n>... [chamber pressurize]",
        ">... \"I am not who I was\"\r\n>... \"I was not <size=200%><color=red>who I was either</color></size>\"\r\n>... [coolant hiss]",
        ">... cube weight stable\r\n>... cube count stable\r\n>... cube count <size=200%><color=red>increasing while observed</color></size>\r\n>... [low hum]",
        ">... \"I left a marker last cycle\"\r\n>... \"the marker is <size=200%><color=red>here</color></size>\"\r\n>... \"this is cycle one\"\r\n>... [chalk on wall]",
        ">... 4 in, 4 out\r\n>... 4 in, 4 out\r\n>... 4 in, <size=200%><color=red>5 out</color></size>\r\n>... [chamber pressurize]",
        ">... \"the dial does not exist\"\r\n>... \"the dial does not exist\"\r\n>... \"<size=200%><color=red>you turned it</color></size>\"\r\n>... [static]",
        ">... \"this objective is familiar\"\r\n>... \"this objective is <size=200%><color=red>completed</color></size>\"\r\n>... not yet started\r\n>... [breathing]",
        ">... cube emits at 4.2 kHz\r\n>... cube emits at 4.2 kHz\r\n>... cube emits the <size=200%><color=red>operative's name</color></size>\r\n>... [low hum]",
        ">... \"a memory mistaken for a thought\"\r\n>... \"a thought mistaken for a <size=200%><color=red>place</color></size>\"\r\n>... [page turn]",
        ">... \"call it a recovery operation\"\r\n>... \"call it a recovery operation\"\r\n>... \"call <size=200%><color=red>them</color></size> recovered\"\r\n>... [paper rustle]",
        ">... 4\r\n>... 4\r\n>... <size=200%><color=red>4 (different)</color></size>\r\n>... [chamber pressurize]",
        ">... operative recall: <size=200%><color=red>not configured</color></size>\r\n>... operative is the recall\r\n>... [feedback]",
        ">... \"114 incidents and rising\"\r\n>... \"114 incidents and <size=200%><color=red>this one</color></size>\"\r\n>... [pen on paper]",
        ">... \"the corridor is the report\"\r\n>... \"the report is the <size=200%><color=red>corridor</color></size>\"\r\n>... [chalk on board]",
        ">... slot 1: occupied\r\n>... slot 2: occupied\r\n>... slot 3: <size=200%><color=red>occupied</color></size>\r\n>... [scanner click]",
        ">... \"I am here\"\r\n>... \"I was here\"\r\n>... \"I will be <size=200%><color=red>here</color></size>\"\r\n>... [Sec-B-M tone]",
        ">... extract, then forget\r\n>... extract, then forget\r\n>... extract, then <size=200%><color=red>extract again</color></size>\r\n>... [chamber pressurize]",
        ">... \"goodnight\"\r\n>... \"goodnight\"\r\n>... \"<size=200%><color=red>tomorrow's listeners</color></size>\"\r\n>... [static]",
        ">... \"the elevator has dropped\"\r\n>... \"the elevator has <size=200%><color=red>not stopped</color></size>\"\r\n>... [chamber pressurize]",
        ">... cretasium 24% unidentified\r\n>... cretasium 24% <size=200%><color=red>uninvented</color></size>\r\n>... [Geiger click]",
        ">... operative status: extracting\r\n>... operative status: extracting\r\n>... operative status: <size=200%><color=red>extracted (again)</color></size>\r\n>... [system chime]",
        ">... \"good work\"\r\n>... \"good work\"\r\n>... \"good <size=200%><color=red>work</color></size>\"\r\n>... [feedback]",
    };
    #endregion
}
