using AutogenRundown.DataBlocks.Alarms;
using AutogenRundown.DataBlocks.Objectives;
using AutogenRundown.Extensions;

namespace AutogenRundown.DataBlocks;

/**
 * Objective: CentralGeneratorCluster
 *
 *
 * Discord says getting the generator cluster to spawn can be tricky and require
 * re-rolls with the zone seed. Still waiting on seeing if this is a problem.
 */
public partial record WardenObjective
{
    private void PreBuild_CentralGeneratorCluster(BuildDirector director, Level level)
    {
        CentralGeneratorCluster_NumberOfGenerators = (level.Tier, director.Bulkhead) switch
        {
            ("A", Bulkhead.Main) => 3,
            ("A", _) => 2,

            ("B", Bulkhead.Main) => 3,
            ("B", _) => 2,

            ("C", Bulkhead.Main) => Generator.Between(3, 4),
            ("C", Bulkhead.Extreme) => 2,
            ("C", Bulkhead.Overload) => 3,

            ("D", Bulkhead.Main) => 4,
            ("D", Bulkhead.Extreme) => Generator.Between(3, 4),
            ("D", Bulkhead.Overload) => 3,

            ("E", Bulkhead.Main) => Generator.Between(4, 5),
            ("E", Bulkhead.Extreme) => Generator.Between(3, 4),
            ("E", Bulkhead.Overload) => 3,
        };
        CentralGeneratorCluster_NumberOfPowerCells = CentralGeneratorCluster_NumberOfGenerators;
    }

    private void Build_CentralGeneratorCluster(BuildDirector director, Level level)
    {
        var (dataLayer, layout) = GetObjectiveLayerAndLayout(director, level);

        MainObjective = new Text("Find [COUNT_REQUIRED] Power Cells and bring them to the Central Generator Cluster in [ITEM_ZONE]");
        FindLocationInfo = "Locate the Power Cells and use them to power up the Generator Cluster";
        FindLocationInfoHelp = "Generators Online: [COUNT_CURRENT] / [COUNT_REQUIRED]";
        // TODO: this key_map doesn't work?
        GoToWinConditionHelp_Elevator = "Use the navigational beacon and the floor map ([KEY_MAP]) to find the way back";
        GoToWinConditionHelp_CustomGeo = "Use the navigational beacon and the information in the surroundings to find the exit point";
        GoToWinCondition_ToMainLayer = "Malfunction in air purification system. Make your way for the forward emergency exit.";

        MidPuzzle = level.Tier switch
        {
            "A" => ChainedPuzzle.FindOrPersist(ChainedPuzzle.AlarmClass2 with { Settings = WaveSettings.Baseline_Easy }),
            "B" => ChainedPuzzle.FindOrPersist(ChainedPuzzle.AlarmClass3 with { Settings = WaveSettings.Baseline_Normal }),
            "C" => ChainedPuzzle.FindOrPersist(ChainedPuzzle.AlarmClass4 with { Settings = WaveSettings.Baseline_Hard }),
            "D" => ChainedPuzzle.FindOrPersist(ChainedPuzzle.AlarmClass5 with { Settings = WaveSettings.Baseline_Hard }),
            "E" => ChainedPuzzle.FindOrPersist(ChainedPuzzle.AlarmClass6 with { Settings = WaveSettings.Baseline_VeryHard })
        };

        AddCompletedObjectiveWaves(level, director);

        #region Warden Intel Messages
        level.ElevatorDropWardenIntel.Add((Generator.Between(1, 5), Generator.Draw(new List<string>
        {
            $">... How many cells do we need?\r\n>... <size=200%><color=red>{Intel.Number(CentralGeneratorCluster_NumberOfGenerators).ToTitleCase()}!</color></size>\r\n>... [breathing heavily] These things are heavy...",
            ">... Found another one.\r\n>... <size=200%><color=red>Grab it!</color></size>\r\n>... Already carrying one...",
            ">... The fog's so thick...\r\n>... Insert the cells, it'll clear.\r\n>... <size=200%><color=red>I hope you're right.</color></size>",
            ">... Generator cluster's in that zone.\r\n>... <size=200%><color=red>How many cells?</color></size>\r\n>... Too many.",
            ">... [panting] This cell is killing my back.\r\n>... Just get it to the cluster.\r\n>... <size=200%><color=red>Easy for you to say!</color></size>",
            ">... Use the terminal to find them.\r\n>... LIST command?\r\n>... <size=200%><color=red>Yes, now hurry!</color></size>",
            $">... One cell down, {Intel.Number(CentralGeneratorCluster_NumberOfGenerators - 1)} to go.\r\n>... <size=200%><color=red>Fog's clearing!</color></size>\r\n>... Keep moving!",
            ">... Don't insert the last cell yet!\r\n>... Why not?\r\n>... <size=200%><color=red>It'll trigger the alarm!</color></size>",
            ">... [static]\r\n>... Power Cell located.\r\n>... <size=200%><color=red>Bring it back!</color></size>",
            ">... How do we find all these cells?\r\n>... <size=200%><color=red>Check the terminals!</color></size>\r\n>... Right, terminals...",
            ">... Generator 258 is online.\r\n>... <size=200%><color=red>One more!</color></size>\r\n>... [groaning]",
            // ">... Zone 24 has a cell.\r\n>... That's on the other side!\r\n>... <size=200%><color=red>Start walking.</color></size>",
            ">... Insert it here?\r\n>... Yeah, the generator cluster.\r\n>... <size=200%><color=red>It's working!</color></size>",
            ">... This fog is killing me...\r\n>... [coughing]\r\n>... <size=200%><color=red>Get those generators online!</color></size>",
            ">... Final cell ready?\r\n>... <size=200%><color=red>Wait!</color></size>\r\n>... [alarm blaring]",
            ">... They're scattered everywhere.\r\n>... <size=200%><color=red>Split up and search!</color></size>\r\n>... Bad idea...",
            // ">... One in Zone 8, one in Zone 15.\r\n>... <size=200%><color=red>Mark them all!</color></size>\r\n>... Working on it!",
            ">... [heavy breathing] Almost there...\r\n>... Insert it!\r\n>... <size=200%><color=red>Generator online!</color></size>",
            ">... How many left?\r\n>... Two more cells.\r\n>... <size=200%><color=red>The fog's getting worse!</color></size>",
            // ">... Found it!\r\n>... <size=200%><color=red>Bring it to Zone 12!</color></size>\r\n>... On my way!",
            ">... Cell's too heavy!\r\n>... <size=200%><color=red>Suck it up!</color></size>\r\n>... [grunting]",
            // ">... Three down, two to go!\r\n>... I can actually see now.\r\n>... <size=200%><color=red>Keep inserting!</color></size>",
            // ">... Terminal says Zone 31.\r\n>... <size=200%><color=red>That's deep.</color></size>\r\n>... Let's move.",
            // ">... [panting] Zone 12, where's the cluster?\r\n>... Should be central.\r\n>... <size=200%><color=red>There!</color></size>",
            ">... Don't do the last one yet!\r\n>... <size=200%><color=red>Why?!</color></size>\r\n>... [alarm blaring]",
            ">... This'll clear the fog?\r\n>... Gradually, yes.\r\n>... <size=200%><color=red>Insert them as we find them!</color></size>",
            ">... Found one in the storage room.\r\n>... <size=200%><color=red>Grab it!</color></size>\r\n>... [grunting] Got it.",
            // ">... Where's the generator cluster?\r\n>... Zone 12, central area.\r\n>... <size=200%><color=red>Mark it on the map!</color></size>",
            ">... [coughing] Can't breathe...\r\n>... Power the generators!\r\n>... <size=200%><color=red>It'll clear the air!</color></size>",
            // ">... Last cell is in Zone 45.\r\n>... <size=200%><color=red>That's past the fog!</color></size>\r\n>... Great...",
            ">... One more generator online.\r\n>... Fog's lifting!\r\n>... <size=200%><color=red>Finally!</color></size>",
            $">... How many generators total?\r\n>... <size=200%><color=red>{Intel.Number(CentralGeneratorCluster_NumberOfGenerators).ToTitleCase()}!</color></size>\r\n>... Fuck...",
            ">... Cell secured.\r\n>... <size=200%><color=red>Return to cluster!</color></size>\r\n>... [breathing heavily]",
            $">... Terminal query: LIST CELL\r\n>... <size=200%><color=red>{Intel.Number(CentralGeneratorCluster_NumberOfPowerCells).ToTitleCase()} locations!</color></size>\r\n>... Let's get moving.",
            ">... Don't insert the last one!\r\n>... Too late!\r\n>... <size=200%><color=red>[alarm blaring]</color></size>",
            ">... Generator cluster located.\r\n>... <size=200%><color=red>Now find the cells!</color></size>\r\n>... Working on it!",
            ">... Two cells left!\r\n>... Fog's almost gone!\r\n>... <size=200%><color=red>Keep going!</color></size>",
            // ">... [static]\r\n>... <size=200%><color=red>Cell in Zone 28!</color></size>\r\n>... Copy that.",
            ">... This is the last one.\r\n>... Everyone ready?\r\n>... <size=200%><color=red>Do it!</color></size>",
            ">... [grunting] So... heavy...\r\n>... Almost at the cluster!\r\n>... <size=200%><color=red>Keep moving!</color></size>",
            // ">... Terminal shows three cells.\r\n>... We need five!\r\n>... <size=200%><color=red>Keep searching!</color></size>",
            $">... Generator one online!\r\n>... <size=200%><color=red>{Intel.Number(CentralGeneratorCluster_NumberOfGenerators - 1).ToTitleCase()} to go!</color></size>\r\n>... [groaning]",
            ">... The fog is clearing!\r\n>... Insert another!\r\n>... <size=200%><color=red>On it!</color></size>",
            // ">... Where's Zone 12?\r\n>... <size=200%><color=red>Check the map!</color></size>\r\n>... Right...",
            ">... Power Cell acquired.\r\n>... <size=200%><color=red>Bring it back!</color></size>\r\n>... [panting]",
            ">... Last generator!\r\n>... Wait for my signal!\r\n>... <size=200%><color=red>Ready!</color></size>",
            ">... [coughing] This fog...\r\n>... Get the generators running!\r\n>... <size=200%><color=red>Trying!</color></size>",
            // ">... Found it in Zone 19.\r\n>... <size=200%><color=red>Secure it!</color></size>\r\n>... [grunting]",
            ">... How many more?\r\n>... Two cells.\r\n>... <size=200%><color=red>Let's split up!</color></size>",
            ">... Generator cluster powered!\r\n>... <size=200%><color=red>Not fully!</color></size>\r\n>... Keep going!",
            ">... This one's in the hub.\r\n>... <size=200%><color=red>Grab it!</color></size>\r\n>... Got it!",
            // ">... [breathing heavily] Zone 12...\r\n>... There's the cluster!\r\n>... <size=200%><color=red>Drop it in!</color></size>",
            // ">... Terminal location: Zone 24.\r\n>... <size=200%><color=red>Mark it!</color></size>\r\n>... Marked.",
            $">... {Intel.Number(CentralGeneratorCluster_NumberOfGenerators - 1).ToTitleCase()} {"generator".Pluralize(CentralGeneratorCluster_NumberOfGenerators - 1)} online!\r\n>... One more!\r\n>... <size=200%><color=red>Everyone ready?</color></size>",
            ">... [static]\r\n>... Power Cell sighted.\r\n>... <size=200%><color=red>Secure and return!</color></size>",
            ">... The final cell triggers the alarm!\r\n>... <size=200%><color=red>Then we wait!</color></size>\r\n>... [breathing heavily]",
            ">... Fog's thick here.\r\n>... Insert another cell.\r\n>... <size=200%><color=red>It'll help!</color></size>",
            ">... [grunting] These cells...\r\n>... Keep moving!\r\n>... <size=200%><color=red>I'm trying!</color></size>",
            ">... Three cells down!\r\n>... <size=200%><color=red>Two to go!</color></size>\r\n>... [panting]",
            ">... Terminal query complete.\r\n>... <size=200%><color=red>Five cells located!</color></size>\r\n>... Let's move out!",
            // ">... Zone 12 is central.\r\n>... <size=200%><color=red>That's the cluster!</color></size>\r\n>... Perfect location.",
            ">... [alarm blaring]\r\n>... You inserted the last one?!\r\n>... <size=200%><color=red>My bad!</color></size>",
            ">... Can't see through this fog!\r\n>... [coughing]\r\n>... <size=200%><color=red>Power the generators!</color></size>",
            // ">... Cell in Zone 8.\r\n>... <size=200%><color=red>I'll get it!</color></size>\r\n>... Hurry!",
            ">... Two more cells!\r\n>... Then the alarm triggers?\r\n>... <size=200%><color=red>On the last one!</color></size>",
            ">... [breathing heavily] Almost there...\r\n>... <size=200%><color=red>Drop it!</color></size>\r\n>... [mechanical whirring]",
            ">... How do we find them all?\r\n>... Terminal.\r\n>... <size=200%><color=red>Use LIST command!</color></size>",
            ">... Generator two online!\r\n>... <size=200%><color=red>Keep going!</color></size>\r\n>... [grunting]",
            ">... Fog's clearing up!\r\n>... I can see!\r\n>... <size=200%><color=red>Insert more cells!</color></size>",
            ">... Where's this cluster?\r\n>... Central zone.\r\n>... <size=200%><color=red>Let's find it!</color></size>",
            ">... [static]\r\n>... <size=200%><color=red>Power Cell located!</color></size>\r\n>... Coordinates?",
            ">... Last one ready?\r\n>... Not yet!\r\n>... <size=200%><color=red>Hold position!</color></size>",
            ">... [coughing] The air...\r\n>... Get those generators running!\r\n>... <size=200%><color=red>Working on it!</color></size>",
            ">... This cell is so heavy!\r\n>... <size=200%><color=red>Just carry it!</color></size>\r\n>... [grunting]",
            ">... Four down, one to go.\r\n>... <size=200%><color=red>Prep for the alarm!</color></size>\r\n>... Ready.",
            // ">... Terminal shows Zone 31.\r\n>... <size=200%><color=red>That's far!</color></size>\r\n>... Let's move!",
            ">... Generator cluster found!\r\n>... <size=200%><color=red>Now the cells!</color></size>\r\n>... Searching...",
            // ">... [panting] Zone 12...\r\n>... <size=200%><color=red>There!</color></size>\r\n>... [mechanical whirring]",
            ">... Three cells inserted.\r\n>... Fog's lifting!\r\n>... <size=200%><color=red>It's working!</color></size>",
            ">... Don't trigger the alarm yet!\r\n>... <size=200%><color=red>I know!</color></size>\r\n>... Just checking...",
            // ">... Cell secured in Zone 15.\r\n>... <size=200%><color=red>Return to cluster!</color></size>\r\n>... On my way!",
            ">... [breathing heavily] How many more?\r\n>... Two.\r\n>... <size=200%><color=red>I can't feel my arms!</color></size>",
            ">... Terminal list complete.\r\n>... <size=200%><color=red>All cells marked!</color></size>\r\n>... Let's go!",
            ">... This is the fifth one.\r\n>... Everyone ready?\r\n>... <size=200%><color=red>Do it!</color></size>",
            ">... [alarm blaring]\r\n>... <size=200%><color=red>They're coming!</color></size>\r\n>... [gunfire]",
            ">... Fog's too thick!\r\n>... Insert more cells!\r\n>... <size=200%><color=red>It'll clear!</color></size>",
            // ">... Zone 24 cell located.\r\n>... <size=200%><color=red>Grab it!</color></size>\r\n>... [grunting] Got it!",
            ">... One more generator!\r\n>... <size=200%><color=red>Hold!</color></size>\r\n>... Why?!",
            ">... [coughing] Can't breathe...\r\n>... <size=200%><color=red>Power the cluster!</color></size>\r\n>... Trying!",
            ">... Generator online!\r\n>... Fog's clearing!\r\n>... <size=200%><color=red>Keep going!</color></size>",
            ">... This cell is killing me...\r\n>... <size=200%><color=red>Almost there!</color></size>\r\n>... [panting]",
            // ">... Terminal query: Zone 19.\r\n>... <size=200%><color=red>Mark it!</color></size>\r\n>... Marked!",
            ">... Last cell triggers alarm.\r\n>... <size=200%><color=red>Then we prep first!</color></size>\r\n>... Good idea...",
            ">... [static]\r\n>... Power Cell found!\r\n>... <size=200%><color=red>Secure it!</color></size>",
            ">... Two cells left!\r\n>... <size=200%><color=red>Keep moving!</color></size>\r\n>... [breathing heavily]",
            // ">... Zone 12 cluster location.\r\n>... There it is!\r\n>... <size=200%><color=red>Drop the cell!</color></size>",
            ">... [grunting] So heavy...\r\n>... You got this!\r\n>... <size=200%><color=red>Almost there!</color></size>",
            ">... Four generators powered!\r\n>... One more!\r\n>... <size=200%><color=red>Wait for signal!</color></size>",
            ">... Fog's lifting!\r\n>... <size=200%><color=red>I can see!</color></size>\r\n>... Keep inserting!",
            // ">... Cell in Zone 8.\r\n>... <size=200%><color=red>I'll get it!</color></size>\r\n>... Be quick!",
            ">... [alarm blaring]\r\n>... The final cell!\r\n>... <size=200%><color=red>Here they come!</color></size>",
            ">... Terminal shows five cells.\r\n>... <size=200%><color=red>All marked!</color></size>\r\n>... Let's collect them!",
            ">... This is too heavy!\r\n>... <size=200%><color=red>Keep going!</color></size>\r\n>... [grunting]",
            ">... Three down!\r\n>... Two to go!\r\n>... <size=200%><color=red>Fog's clearing!</color></size>",
            ">... Don't insert the last one!\r\n>... <size=200%><color=red>Why not?!</color></size>\r\n>... Alarm!",
            // ">... [breathing heavily] Zone 12...\r\n>... <size=200%><color=red>There's the cluster!</color></size>\r\n>... [mechanical whirring]",
            ">... Power Cell secured.\r\n>... <size=200%><color=red>Return now!</color></size>\r\n>... On it!",
            ">... Final generator ready.\r\n>... Everyone in position?\r\n>... <size=200%><color=red>Ready!</color></size>",
            ">... [coughing] This fog...\r\n>... <size=200%><color=red>Get the power on!</color></size>\r\n>... Working!",
            ">... Cell located in hub.\r\n>... <size=200%><color=red>Grab it!</color></size>\r\n>... [grunting]",
            ">... Two more cells!\r\n>... <size=200%><color=red>Almost done!</color></size>\r\n>... [panting]",
            ">... Generator cluster found!\r\n>... <size=200%><color=red>Mark it!</color></size>\r\n>... Marked!",
            // ">... [static]\r\n>... Zone 31 has a cell.\r\n>... <size=200%><color=red>That's deep!</color></size>",
            ">... Last one triggers alarm!\r\n>... <size=200%><color=red>Prep first!</color></size>\r\n>... Good call.",
            ">... [breathing heavily] Almost...\r\n>... Drop it in!\r\n>... <size=200%><color=red>Done!</color></size>",
            ">... Fog's thick here!\r\n>... Insert another cell!\r\n>... <size=200%><color=red>It'll help!</color></size>",
            ">... Terminal list ready.\r\n>... <size=200%><color=red>Five cells total!</color></size>\r\n>... Let's move!",
            ">... Four cells done!\r\n>... One left!\r\n>... <size=200%><color=red>Wait for signal!</color></size>",
            ">... [grunting] This weight...\r\n>... <size=200%><color=red>Keep moving!</color></size>\r\n>... Trying!",
            ">... Generator two online!\r\n>... <size=200%><color=red>Keep going!</color></size>\r\n>... [mechanical whirring]",
            // ">... Where's the cluster?\r\n>... Zone 12, central!\r\n>... <size=200%><color=red>Got it!</color></size>",
            ">... [alarm blaring]\r\n>... <size=200%><color=red>Contact!</color></size>\r\n>... [gunfire]",
            // ">... Cell in Zone 15.\r\n>... <size=200%><color=red>Secure it!</color></size>\r\n>... On my way!",
            ">... Three cells left!\r\n>... <size=200%><color=red>Split up!</color></size>\r\n>... Bad idea...",
            ">... [coughing] Can't see...\r\n>... Power the generators!\r\n>... <size=200%><color=red>It'll clear!</color></size>",
            ">... Generator online!\r\n>... Fog's lifting!\r\n>... <size=200%><color=red>It's working!</color></size>",
            ">... [breathing heavily] So heavy...\r\n>... <size=200%><color=red>Almost there!</color></size>\r\n>... [grunting]",
            // ">... Terminal shows Zone 24.\r\n>... <size=200%><color=red>Mark it!</color></size>\r\n>... Done!",
            ">... Last cell ready?\r\n>... Not yet!\r\n>... <size=200%><color=red>Prep first!</color></size>",
            ">... [static]\r\n>... Power Cell found!\r\n>... <size=200%><color=red>Bring it back!</color></size>",
            ">... Two more generators!\r\n>... <size=200%><color=red>Keep inserting!</color></size>\r\n>... Working on it!",
            // ">... Zone 12 located.\r\n>... There's the cluster!\r\n>... <size=200%><color=red>Perfect!</color></size>",
            ">... [grunting] Can't drop it...\r\n>... <size=200%><color=red>Keep going!</color></size>\r\n>... [panting]",
            ">... Five cells total.\r\n>... <size=200%><color=red>All marked!</color></size>\r\n>... Let's collect!",
            ">... Final generator!\r\n>... Everyone ready?\r\n>... <size=200%><color=red>Do it!</color></size>",
            ">... [alarm blaring]\r\n>... They're here!\r\n>... <size=200%><color=red>Hold position!</color></size>",
            ">... Fog's clearing up!\r\n>... <size=200%><color=red>I can breathe!</color></size>\r\n>... Keep going!",
            ">... Cell in the storage.\r\n>... <size=200%><color=red>Get it!</color></size>\r\n>... [grunting]",
            ">... Three down, two left!\r\n>... <size=200%><color=red>Almost done!</color></size>\r\n>... [breathing heavily]",
            ">... Don't trigger alarm yet!\r\n>... <size=200%><color=red>I know!</color></size>\r\n>... Just saying...",
            ">... [coughing] The air...\r\n>... <size=200%><color=red>Power up!</color></size>\r\n>... Working!",
            ">... Generator cluster here.\r\n>... <size=200%><color=red>Drop it in!</color></size>\r\n>... [mechanical whirring]",
            ">... Terminal query done.\r\n>... Five cells located!\r\n>... <size=200%><color=red>Let's move!</color></size>",
            ">... Last one triggers it.\r\n>... <size=200%><color=red>Prep first!</color></size>\r\n>... Agreed.",
            // ">... [breathing heavily] Zone 12...\r\n>... <size=200%><color=red>There!</color></size>\r\n>... Drop it!",
            ">... Four generators powered!\r\n>... <size=200%><color=red>One more!</color></size>\r\n>... [panting]",
            ">... Fog's too thick!\r\n>... Insert more cells!\r\n>... <size=200%><color=red>On it!</color></size>",
            // ">... Zone 19 cell located.\r\n>... <size=200%><color=red>Grab it!</color></size>\r\n>... Got it!",
            ">... [grunting] So heavy...\r\n>... <size=200%><color=red>You got this!</color></size>\r\n>... [panting]",
            ">... Two cells left!\r\n>... <size=200%><color=red>Keep moving!</color></size>\r\n>... Trying!",
            ">... Generator online!\r\n>... <size=200%><color=red>Fog's lifting!</color></size>\r\n>... Finally!",
            // ">... [static]\r\n>... Cell in Zone 8.\r\n>... <size=200%><color=red>Mark it!</color></size>",
            ">... Final cell ready.\r\n>... Everyone in position?\r\n>... <size=200%><color=red>Ready!</color></size>",
            ">... [alarm blaring]\r\n>... <size=200%><color=red>Here they come!</color></size>\r\n>... [gunfire]",
            ">... Terminal shows all cells.\r\n>... <size=200%><color=red>Five total!</color></size>\r\n>... Let's go!",
            ">... This cell is killing me!\r\n>... <size=200%><color=red>Almost there!</color></size>\r\n>... [grunting]",
            ">... Three cells done!\r\n>... Two to go!\r\n>... <size=200%><color=red>Fog's clearing!</color></size>",
            // ">... Zone 12 cluster.\r\n>... <size=200%><color=red>There it is!</color></size>\r\n>... Drop it!",
            ">... [coughing] Can't breathe...\r\n>... <size=200%><color=red>Power up!</color></size>\r\n>... Working!",
            ">... Last one triggers alarm!\r\n>... <size=200%><color=red>Prep first!</color></size>\r\n>... Good idea.",
            ">... [breathing heavily] Almost...\r\n>... <size=200%><color=red>Drop it!</color></size>\r\n>... Done!",
            ">... Generator two online!\r\n>... <size=200%><color=red>Keep going!</color></size>\r\n>... [mechanical whirring]",
            // ">... Cell in Zone 24.\r\n>... <size=200%><color=red>I'll get it!</color></size>\r\n>... Hurry!",
            ">... Four down, one left!\r\n>... <size=200%><color=red>Wait for signal!</color></size>\r\n>... Ready.",
            ">... [static]\r\n>... Power Cell located!\r\n>... <size=200%><color=red>Coordinates?</color></size>",
            ">... Fog's lifting!\r\n>... I can see!\r\n>... <size=200%><color=red>Insert more!</color></size>",
            ">... [grunting] This weight...\r\n>... <size=200%><color=red>Keep moving!</color></size>\r\n>... Trying!",
            ">... Terminal list complete.\r\n>... <size=200%><color=red>All marked!</color></size>\r\n>... Let's collect!",
            ">... Last generator!\r\n>... Everyone ready?\r\n>... <size=200%><color=red>Do it!</color></size>",
            ">... [alarm blaring]\r\n>... <size=200%><color=red>Contact!</color></size>\r\n>... [gunfire]",
            ">... Cell secured.\r\n>... <size=200%><color=red>Return now!</color></size>\r\n>... On my way!",
            ">... Three cells left!\r\n>... <size=200%><color=red>Split up!</color></size>\r\n>... Bad idea...",
            ">... [coughing] The fog...\r\n>... <size=200%><color=red>Power the cluster!</color></size>\r\n>... Working!",
            ">... Generator online!\r\n>... <size=200%><color=red>Fog's clearing!</color></size>\r\n>... It's working!",
            // ">... [breathing heavily] Zone 12...\r\n>... <size=200%><color=red>There's the cluster!</color></size>\r\n>... [mechanical whirring]",
            // ">... Terminal shows Zone 31.\r\n>... <size=200%><color=red>That's far!</color></size>\r\n>... Let's move!",
            ">... Two more cells!\r\n>... <size=200%><color=red>Almost done!</color></size>\r\n>... [panting]",
            ">... Final cell triggers it.\r\n>... <size=200%><color=red>Prep first!</color></size>\r\n>... Agreed.",
            ">... [grunting] So heavy...\r\n>... <size=200%><color=red>You got this!</color></size>\r\n>... [panting]",
            ">... Five cells total.\r\n>... <size=200%><color=red>All located!</color></size>\r\n>... Let's go!",
            ">... Generator cluster found!\r\n>... <size=200%><color=red>Drop it in!</color></size>\r\n>... [mechanical whirring]",
            // ">... [static]\r\n>... Cell in Zone 15.\r\n>... <size=200%><color=red>Mark it!</color></size>",
            ">... Four generators powered!\r\n>... <size=200%><color=red>One more!</color></size>\r\n>... [breathing heavily]",
            ">... Fog's too thick!\r\n>... <size=200%><color=red>Insert more cells!</color></size>\r\n>... On it!",
            ">... [alarm blaring]\r\n>... They're here!\r\n>... <size=200%><color=red>Hold position!</color></size>",
            ">... Cell in the hub.\r\n>... <size=200%><color=red>Get it!</color></size>\r\n>... [grunting]",
            ">... Three down!\r\n>... <size=200%><color=red>Two to go!</color></size>\r\n>... [panting]",
            ">... Don't trigger alarm!\r\n>... <size=200%><color=red>I know!</color></size>\r\n>... Just checking...",
            ">... [coughing] Can't see...\r\n>... <size=200%><color=red>Power up!</color></size>\r\n>... Working!",
            // ">... Zone 12 located.\r\n>... <size=200%><color=red>There's the cluster!</color></size>\r\n>... Perfect!",
            ">... Terminal query done.\r\n>... <size=200%><color=red>Five cells!</color></size>\r\n>... Let's move!",
            ">... Last one ready.\r\n>... <size=200%><color=red>Prep first!</color></size>\r\n>... Good call.",
            ">... [breathing heavily] Almost...\r\n>... <size=200%><color=red>Drop it!</color></size>\r\n>... Done!",
            ">... Generator online!\r\n>... <size=200%><color=red>Fog's lifting!</color></size>\r\n>... Finally!",
            ">... [grunting] This cell...\r\n>... <size=200%><color=red>Keep going!</color></size>\r\n>... Trying!",
            ">... Two cells left!\r\n>... <size=200%><color=red>Almost there!</color></size>\r\n>... [panting]",
            // ">... Cell in Zone 19.\r\n>... <size=200%><color=red>Grab it!</color></size>\r\n>... Got it!",
            ">... Final generator!\r\n>... <size=200%><color=red>Everyone ready?</color></size>\r\n>... Ready!",
            ">... [alarm blaring]\r\n>... <size=200%><color=red>Here they come!</color></size>\r\n>... [gunfire]",
            ">... Terminal shows all cells.\r\n>... <size=200%><color=red>All marked!</color></size>\r\n>... Let's collect!",
            ">... This is too heavy!\r\n>... <size=200%><color=red>Almost there!</color></size>\r\n>... [grunting]",
            ">... Four cells done!\r\n>... <size=200%><color=red>One left!</color></size>\r\n>... [breathing heavily]",
            // ">... Zone 12 cluster.\r\n>... <size=200%><color=red>There!</color></size>\r\n>... Drop it!",
            ">... [coughing] The air...\r\n>... <size=200%><color=red>Power the cluster!</color></size>\r\n>... Working!",
            ">... Last cell triggers alarm.\r\n>... <size=200%><color=red>Prep first!</color></size>\r\n>... Agreed.",
            // ">... [breathing heavily] Zone 12...\r\n>... <size=200%><color=red>There's the cluster!</color></size>\r\n>... [mechanical whirring]",
            ">... Generator two online!\r\n>... <size=200%><color=red>Keep going!</color></size>\r\n>... [mechanical whirring]",
            // ">... Cell in Zone 8.\r\n>... <size=200%><color=red>I'll get it!</color></size>\r\n>... Be quick!",
            ">... Three cells left!\r\n>... <size=200%><color=red>Split up!</color></size>\r\n>... Bad idea...",
            ">... [static]\r\n>... <size=200%><color=red>Power Cell found!</color></size>\r\n>... Location?",
            ">... Fog's clearing!\r\n>... <size=200%><color=red>I can see!</color></size>\r\n>... Keep inserting!",
            ">... [grunting] So heavy...\r\n>... <size=200%><color=red>You got this!</color></size>\r\n>... [panting]",
            ">... Terminal list ready.\r\n>... <size=200%><color=red>Five cells total!</color></size>\r\n>... Let's go!",
            ">... Last generator ready.\r\n>... <size=200%><color=red>Everyone in position?</color></size>\r\n>... Ready!",
            ">... [alarm blaring]\r\n>... <size=200%><color=red>Contact!</color></size>\r\n>... [gunfire]",
            ">... Cell secured.\r\n>... <size=200%><color=red>Return to cluster!</color></size>\r\n>... On it!",
            ">... Two more cells!\r\n>... <size=200%><color=red>Almost done!</color></size>\r\n>... [breathing heavily]",
            ">... Final cell triggers it.\r\n>... <size=200%><color=red>Prep first!</color></size>\r\n>... Good idea.",
            ">... [coughing] Can't breathe...\r\n>... <size=200%><color=red>Power up!</color></size>\r\n>... Working!",
            ">... Generator cluster here.\r\n>... <size=200%><color=red>Drop it in!</color></size>\r\n>... [mechanical whirring]",
            ">... [breathing heavily] Almost there...\r\n>... <size=200%><color=red>Keep moving!</color></size>\r\n>... [grunting]",
            // ">... Terminal shows Zone 24.\r\n>... <size=200%><color=red>Mark it!</color></size>\r\n>... Done!",
            ">... Four generators powered!\r\n>... <size=200%><color=red>One more!</color></size>\r\n>... [panting]",
            ">... Fog's too thick!\r\n>... <size=200%><color=red>Insert more cells!</color></size>\r\n>... On it!",
            // ">... Zone 15 cell located.\r\n>... <size=200%><color=red>Grab it!</color></size>\r\n>... Got it!",
            ">... [grunting] This weight...\r\n>... <size=200%><color=red>Almost there!</color></size>\r\n>... [panting]",
            ">... Three cells done!\r\n>... <size=200%><color=red>Two to go!</color></size>\r\n>... [breathing heavily]",
            ">... Generator online!\r\n>... <size=200%><color=red>Fog's lifting!</color></size>\r\n>... It's working!",
            // ">... [static]\r\n>... Cell in Zone 31.\r\n>... <size=200%><color=red>That's deep!</color></size>",
            ">... Last one ready.\r\n>... <size=200%><color=red>Everyone in position?</color></size>\r\n>... Ready!",
            ">... [alarm blaring]\r\n>... <size=200%><color=red>Here they come!</color></size>\r\n>... [gunfire]",
            ">... Terminal query complete.\r\n>... <size=200%><color=red>All cells located!</color></size>\r\n>... Let's move!",
            ">... This cell is killing me!\r\n>... <size=200%><color=red>Keep going!</color></size>\r\n>... [grunting]",
            ">... Two cells left!\r\n>... <size=200%><color=red>Almost done!</color></size>\r\n>... [panting]",
            // ">... Zone 12 cluster.\r\n>... <size=200%><color=red>There it is!</color></size>\r\n>... Drop it!",
            ">... [coughing] The fog...\r\n>... <size=200%><color=red>Power the cluster!</color></size>\r\n>... Working!",
            ">... Final cell triggers alarm.\r\n>... <size=200%><color=red>Prep first!</color></size>\r\n>... Agreed.",
            // ">... [breathing heavily] Zone 12...\r\n>... <size=200%><color=red>There's the cluster!</color></size>\r\n>... [mechanical whirring]",
            ">... Generator two online!\r\n>... <size=200%><color=red>Keep going!</color></size>\r\n>... [mechanical whirring]",
            // ">... Cell in Zone 19.\r\n>... <size=200%><color=red>I'll get it!</color></size>\r\n>... Hurry!",
            ">... Four down, one left!\r\n>... <size=200%><color=red>Wait for signal!</color></size>\r\n>... Ready.",
            ">... [static]\r\n>... <size=200%><color=red>Power Cell located!</color></size>\r\n>... Coordinates?",
            ">... Fog's clearing up!\r\n>... <size=200%><color=red>I can breathe!</color></size>\r\n>... Keep going!",
            ">... [grunting] So heavy...\r\n>... <size=200%><color=red>You got this!</color></size>\r\n>... [panting]",
            ">... Terminal list complete.\r\n>... <size=200%><color=red>Five cells total!</color></size>\r\n>... Let's go!",
            ">... Last generator!\r\n>... <size=200%><color=red>Everyone ready?</color></size>\r\n>... Do it!",
            ">... [alarm blaring]\r\n>... <size=200%><color=red>Contact!</color></size>\r\n>... [gunfire]",
            ">... Cell secured.\r\n>... <size=200%><color=red>Return now!</color></size>\r\n>... On my way!",
            ">... Three cells left!\r\n>... <size=200%><color=red>Split up!</color></size>\r\n>... Bad idea...",
            ">... [coughing] Can't see...\r\n>... <size=200%><color=red>Power up!</color></size>\r\n>... Working!",
            ">... Generator online!\r\n>... <size=200%><color=red>Fog's lifting!</color></size>\r\n>... Finally!",
        }))!);
        #endregion
    }
}
