using AutogenRundown.DataBlocks.Enums;

namespace AutogenRundown.DataBlocks.Objectives;

/// <summary>
/// Intel pools for the Cryptomnesia objective. Selected by the Reality theme of the
/// drop, with a 30% fallback to a neutral pool that draws on cube / Matter Wave
/// Projector / loop-of-cognition motifs that fit any theme.
///
/// Format conventions for every entry:
/// - 3-5 lines, separated by `\r\n`
/// - Each line prefixed with `>... ` (radio chatter) or `>` (transcript / log fragment)
/// - One `<size=200%><color=red>X</color></size>` highlight on the urgent phrase
/// - One bracketed audio/system cue per entry (e.g. `[static]`, `[siren]`)
/// - Voices: prisoner radio (Bishop GO-1395, Woods F-2056, Hackett O-4711, Dauda
///   T-3701), KDS field comms (Piros A134), researcher logs (Stokes B193, Hammerstein
///   B014, Teale B023, Stanovich C066, Connor B229, Durant B255, Schaeffer T-3894),
///   Warden corrupted output (`WRDN: COMMAND`), HearSay/BIOCOM auto-transcripts,
///   State of Truth AM, Mr. Truth fragments
/// </summary>
public partial record WardenObjective
{
    #region ErrorAlarm theme — comms shredded by sirens; BIOCOM cascade faults
    public static readonly List<string> CryptomnesiaIntel_ErrorAlarm = new()
    {
        ">... BIOCOM fault cascade Z-44 area C\r\n>... checksum mismatch on WRDN override\r\n>... EXTRACT EXTRACT EX<size=200%><color=red>--RETREAT--</color></size>\r\n>... [siren]",
        ">>EBDT FRAGMENT 0BE204 [corrupted]\r\n>... alarm grid not isolating\r\n>... <size=200%><color=red>signal IS the alarm</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... Sec-B-M 2.7.4 upload spike sustained\r\n>... quad reads four\r\n>... crypt reads <size=200%><color=red>five</color></size>\r\n>... BIOCOM: who is the fifth\r\n>... [siren]",
        ">... DISC failure level L37, ELG holding\r\n>... clock drift 230 seconds and climbing\r\n>... Lockwood A074: control the narrative\r\n>... <size=200%><color=red>narrative is screaming</color></size>\r\n>... [alarm blaring]",
        ">... WRDN: COMPLY\r\n>... WRDN: CO<size=200%><color=red>M-M-M</color></size>PLY\r\n>... operative response timeout\r\n>... operative response timeout\r\n>... [static]",
        ">>HearSay auto-transcript//error\r\n>... \"the siren is in the recording\"\r\n>... \"the siren was always in the <size=200%><color=red>recording</color></size>\"\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... Stanovich C066 amend report 114\r\n>... incident count revised upward\r\n>... incident count revised <size=200%><color=red>upward</color></size>\r\n>... [siren cycling]",
        ">... Piros A134 to channel 3\r\n>... silence the horn\r\n>... silence the horn\r\n>... <size=200%><color=red>nobody silenced it</color></size>\r\n>... [horn sustained]",
        ">... WRDN: <size=200%><color=red>RETREAT</color></size>\r\n>... WRDN: RETREAT\r\n>... destination unspecified\r\n>... [dead air]",
        ">... BIOCOM watchdog fault\r\n>... cascading reset attempted\r\n>... reset propagated to <size=200%><color=red>operative cognition</color></size>\r\n>... [siren]",
        ">>EBDT 0BE207: alarm matrix unbinding\r\n>... Lockwood A074 escalation declined by tier 5\r\n>... declined by tier 5\r\n>... <size=200%><color=red>declined by self</color></size>\r\n>... [static]",
        ">... DISC at 12%, ELG at 8%, CMS dark\r\n>... emergency beacon spawned in Z-32\r\n>... emergency beacon <size=200%><color=red>not requested</color></size>\r\n>... [siren]",
        ">... operative chip latency 480ms and rising\r\n>... commands queueing\r\n>... commands resolving in <size=200%><color=red>reverse order</color></size>\r\n>... [warning tone]",
        ">... WRDN broadcast burst\r\n>... 0xFFEE 0xFFEE 0xFFEE\r\n>... <size=200%><color=red>0xDEAD</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... Stanovich C066 report SAMD-C043-08\r\n>... \"unscheduled klaxon at 03:14\"\r\n>... \"klaxon predates installed hardware\"\r\n>... <size=200%><color=red>install date pending</color></size>\r\n>... [siren]",
        ">... operative GO-1395 chip echo\r\n>... operative GO-1395 chip echo\r\n>... operative GO-1395 chip <size=200%><color=red>echo</color></size>\r\n>... [feedback loop]",
        ">... red-amber alarm mismatch\r\n>... per protocol the lower wins\r\n>... <size=200%><color=red>both are louder</color></size>\r\n>... [alarm blaring]",
        ">... Piros A134 calling KDS-ground\r\n>... no answer\r\n>... no answer\r\n>... <size=200%><color=red>no KDS-ground</color></size>\r\n>... [static]",
        ">>BIOCOM trace: Z-44 → Z-44 → Z-44\r\n>... routing loop confirmed\r\n>... loop is the corridor\r\n>... <size=200%><color=red>corridor is the loop</color></size>\r\n>... [siren]",
        ">... WRDN: SIREN OFF\r\n>... WRDN: SIREN OFF\r\n>... WRDN: <size=200%><color=red>SIREN ON</color></size>\r\n>... [siren]",
        ">... emergency lighting cycling amber-red\r\n>... amber-red\r\n>... amber-<size=200%><color=red>black</color></size>\r\n>... [generator stutter]",
        ">>EBDT 0BE211 [redacted by Lockwood A074]\r\n>... klaxon transcript: thirty-one minutes\r\n>... klaxon was <size=200%><color=red>two seconds</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... operative T-3701 reporting in\r\n>... cannot hear myself\r\n>... cannot hear <size=200%><color=red>myself</color></size>\r\n>... [siren]",
        ">... fault on alarm bus 12\r\n>... fault on alarm bus 12\r\n>... fault on alarm bus 12\r\n>... fault propagating to <size=200%><color=red>cognition bus</color></size>\r\n>... [warning tone]",
        ">... Lockwood A074 directive\r\n>... \"the alarm was always running\"\r\n>... \"do not log this directive\"\r\n>... <size=200%><color=red>logged</color></size>\r\n>... [system chime]",
        ">... WRDN: EXTRACT\r\n>... WRDN: EXTRACT\r\n>... WRDN: EX<size=200%><color=red>--TRACT--</color></size>\r\n>... destination: Z-44\r\n>... [static]",
        ">... BIOCOM ID conflict\r\n>... two operatives bearing GO-1395\r\n>... <size=200%><color=red>resolve manually</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... Sec-B-M chip telemetry\r\n>... heart rate 142 BPM\r\n>... heart rate <size=200%><color=red>0 BPM</color></size>\r\n>... operative still moving\r\n>... [siren]",
        ">>HearSay channel 7\r\n>... \"who triggered the alarm\"\r\n>... \"who triggered the <size=200%><color=red>alarm</color></size>\"\r\n>... [recording loops]",
        ">... Stanovich C066 footnote\r\n>... \"114 incidents is the floor\"\r\n>... \"114 incidents is the <size=200%><color=red>floor</color></size>\"\r\n>... [siren]",
        ">... WRDN: COMPLY\r\n>... operative offline\r\n>... operative offline\r\n>... operative <size=200%><color=red>compliant</color></size>\r\n>... [dead air]",
        ">... klaxon sweep beginning at L37\r\n>... wave reaches L0 in 230 seconds\r\n>... wave reaches operative in <size=200%><color=red>0 seconds</color></size>\r\n>... [pre-echo]",
        ">>EBDT 0BE218: alarm without source\r\n>... source field empty\r\n>... source field <size=200%><color=red>filled with operative ID</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... emergency lockdown initiated\r\n>... emergency lockdown initiated\r\n>... emergency lockdown <size=200%><color=red>not initiated</color></size>\r\n>... operative inside\r\n>... [siren]",
        ">... Piros A134 to all KDS\r\n>... reset the alarm\r\n>... reset the alarm\r\n>... <size=200%><color=red>reset the level</color></size>\r\n>... [static burst]",
        ">... WRDN broadcast\r\n>... WRDN broadcast\r\n>... WRDN broadcast\r\n>... receiver: <size=200%><color=red>none configured</color></size>\r\n>... [siren]",
        ">... Lockwood A074 tier 5 memo\r\n>... \"call it a malfunction\"\r\n>... \"do not call it a <size=200%><color=red>warning</color></size>\"\r\n>... [system chime]",
        ">... BIOCOM checksum error 0xDEADBEEF\r\n>... operative cognition flagged\r\n>... operative cognition <size=200%><color=red>flagged</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... red light, red light, <size=200%><color=red>red light</color></size>\r\n>... no green this cycle\r\n>... no green next cycle\r\n>... [siren]",
        ">... WRDN: HOLD POSITION\r\n>... WRDN: HOLD POSITION\r\n>... WRDN: H-H-H<size=200%><color=red>OLD</color></size>\r\n>... operative position: unknown\r\n>... [static]",
    };
    #endregion

    #region Giants theme — Project Insight clinical voice; "trees, not branches"
    public static readonly List<string> CryptomnesiaIntel_Giants = new()
    {
        ">... Project Insight bench note B-014\r\n>... specimen exceeds Gallus Reptus baseline by 340%\r\n>... \"trees, not branches\" -- Hammerstein\r\n>... <size=200%><color=red>still has a wedding ring</color></size>\r\n>... [HVAC hum]",
        ">... Stokes B193 audio, lab 6\r\n>... \"the human DNA fraction is not a contaminant\"\r\n>... \"the human DNA fraction is the <size=200%><color=red>architecture</color></size>\"\r\n>... [lights cycle]",
        ">... Neonate HSU shipment, 28x, Nyxos\r\n>... received Z-44 area C, KDS rep #00118-G\r\n>... twelve units returned empty\r\n>... twelve units returned <size=200%><color=red>larger</color></size>\r\n>... [pneumatic seal]",
        ">... autopsy floor 3, sterile, no movement\r\n>... subject S-072 exhibits Capreolatus skeletal frame\r\n>... subject S-072 was Capreolatus skeletal frame\r\n>... subject S-072 is <size=200%><color=red>sitting up</color></size>\r\n>... [no audio]",
        ">... Hammerstein B014 margin note\r\n>... \"Non ducor, duco\"\r\n>... handwriting is not Hammerstein's\r\n>... Hammerstein died in <size=200%><color=red>Shaft 17b</color></size>\r\n>... [page turn]",
        ">... Project Insight memo, tier 4 only\r\n>... do not refer to specimens by former designation\r\n>... do not refer to specimens by former <size=200%><color=red>name</color></size>\r\n>... they remember their name\r\n>... [HVAC hum]",
        ">... Stokes B193, lab 6, 04:11\r\n>... \"Gallus Capreolatus is structurally human\"\r\n>... \"with corrections\"\r\n>... <size=200%><color=red>my corrections</color></size>\r\n>... [pen on paper]",
        ">... bench scale exceeded\r\n>... bench scale exceeded\r\n>... bench scale <size=200%><color=red>destroyed</color></size>\r\n>... specimen weight: pending\r\n>... [load cell crack]",
        ">... Hammerstein taxonomy note\r\n>... \"not Reptus, not Jaculus, not Capreolatus\"\r\n>... \"a fourth genus, dormant\"\r\n>... <size=200%><color=red>or a first</color></size>\r\n>... [HVAC hum]",
        ">... shipment manifest, Project Insight\r\n>... 28 units in, 16 units out\r\n>... 12 units re-categorized\r\n>... 12 units <size=200%><color=red>walked</color></size>\r\n>... [pneumatic seal]",
        ">... Stokes B193 voice memo\r\n>... \"the size is not the horror\"\r\n>... \"the <size=200%><color=red>composure</color></size> is the horror\"\r\n>... [lights cycle]",
        ">... lab 6 lighting protocol\r\n>... white only\r\n>... white only\r\n>... white preserves <size=200%><color=red>the shape</color></size>\r\n>... [fluorescent buzz]",
        ">... Project Insight imaging\r\n>... CT slice 0042: ribcage 3x baseline\r\n>... CT slice 0042: ribcage <size=200%><color=red>occupied</color></size>\r\n>... [scanner cycling]",
        ">... Hammerstein B014, undated\r\n>... \"the Gallus is not the Sleeper\"\r\n>... \"the Gallus is what the Sleeper <size=200%><color=red>becomes</color></size>\"\r\n>... [pen on paper]",
        ">... operative GO-1395 to channel 2\r\n>... \"this one is wearing my coat\"\r\n>... \"this one is <size=200%><color=red>wearing my coat</color></size>\"\r\n>... [breathing]",
        ">>EBDT 0BE301: Gallus reclassification halted\r\n>... reclassification halted by tier 5\r\n>... reclassification halted by <size=200%><color=red>specimen</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... Stokes B193, lab 6, 02:00\r\n>... \"if I name it, it answers\"\r\n>... \"I have not named it\"\r\n>... \"it has <size=200%><color=red>answered</color></size>\"\r\n>... [no audio]",
        ">... Project Insight ledger\r\n>... line 1142: \"do not feed the standing one\"\r\n>... line 1143: \"the standing one is <size=200%><color=red>feeding</color></size>\"\r\n>... [HVAC hum]",
        ">... Hammerstein B014 final note\r\n>... \"my ring fits a finger that is not mine\"\r\n>... \"my ring fits a finger that is <size=200%><color=red>larger</color></size>\"\r\n>... [page turn]",
        ">... ShooterGiant manifest, 3 units\r\n>... 3 units verified at intake\r\n>... 4 units verified at <size=200%><color=red>discharge</color></size>\r\n>... [pneumatic seal]",
        ">... white light protocol active\r\n>... white light protocol active\r\n>... white light protocol <size=200%><color=red>insufficient</color></size>\r\n>... [fluorescent buzz]",
        ">... Stokes B193 to Hammerstein B014\r\n>... \"do you remember my face\"\r\n>... \"I do not remember <size=200%><color=red>your face</color></size>\"\r\n>... [silence]",
        ">... Project Insight specimen log\r\n>... \"specimen S-072 has not eaten\"\r\n>... \"specimen S-072 has not <size=200%><color=red>blinked</color></size>\"\r\n>... 14 days observation\r\n>... [HVAC hum]",
        ">... lab 6 emergency ventilation\r\n>... activated by hand at 03:14\r\n>... no hand on the panel\r\n>... no hand on the <size=200%><color=red>panel</color></size>\r\n>... [airflow surge]",
        ">... Hammerstein B014 sketchbook\r\n>... page 42: a Gallus with hands\r\n>... page 43: a Gallus with <size=200%><color=red>my hands</color></size>\r\n>... [pen on paper]",
        ">... operative F-2056 on channel 1\r\n>... \"this one held the door for me\"\r\n>... \"this one held the door for <size=200%><color=red>me</color></size>\"\r\n>... [door servo]",
        ">... Stokes B193 procedure note\r\n>... \"Gallus tissue resists fixation\"\r\n>... \"Gallus tissue resists <size=200%><color=red>identification</color></size>\"\r\n>... [microscope click]",
        ">... Project Insight directive\r\n>... \"never address a specimen by name\"\r\n>... \"a specimen has <size=200%><color=red>memorized yours</color></size>\"\r\n>... [HVAC hum]",
        ">... Neonate HSU temperature drift\r\n>... -187.4°C → -94.1°C → 36.9°C\r\n>... <size=200%><color=red>internal heat source</color></size>\r\n>... [coolant alarm]",
        ">... Hammerstein B014 lab transcript\r\n>... \"the Gallus is composed\"\r\n>... \"the Gallus is <size=200%><color=red>composing</color></size>\"\r\n>... [pen on paper]",
        ">... Stokes B193, recording 0118\r\n>... \"my hands are not my hands\"\r\n>... \"my hands are not my hands\"\r\n>... \"my hands are <size=200%><color=red>not</color></size>\"\r\n>... [silence]",
        ">... Project Insight intake form\r\n>... weight: 412kg\r\n>... weight: 412kg\r\n>... weight: <size=200%><color=red>0kg</color></size>\r\n>... specimen still on scale\r\n>... [load cell hum]",
        ">... lab 6 door log\r\n>... door opened from inside, 04:41\r\n>... no operative inside at 04:40\r\n>... no operative <size=200%><color=red>inside</color></size>\r\n>... [door servo]",
        ">... Hammerstein B014 lecture notes\r\n>... \"trees, not branches\"\r\n>... \"the tree is <size=200%><color=red>standing in the corridor</color></size>\"\r\n>... [chalk on board]",
        ">... operative T-3701 to channel 3\r\n>... \"it is wearing a face I half-remember\"\r\n>... \"it is wearing a <size=200%><color=red>face I half-remember</color></size>\"\r\n>... [breathing]",
        ">... Stokes B193 final entry\r\n>... \"specimen S-072 reclassified\"\r\n>... \"specimen S-072 reclassified as <size=200%><color=red>Stokes</color></size>\"\r\n>... [no audio]",
        ">... Project Insight courier note\r\n>... \"do not open the crate alone\"\r\n>... \"do not open the crate <size=200%><color=red>at all</color></size>\"\r\n>... [crate hiss]",
        ">>EBDT 0BE324: lab 6 sealed\r\n>... lab 6 sealed by tier 5\r\n>... lab 6 sealed by <size=200%><color=red>specimen</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... Hammerstein B014 last lecture\r\n>... \"Non ducor, duco\"\r\n>... \"I am not led, I lead\"\r\n>... \"this time I am <size=200%><color=red>led</color></size>\"\r\n>... [chalk on board]",
        ">... Project Insight floor lighting\r\n>... 100% white, no spectral drift\r\n>... 100% white, no spectral drift\r\n>... shadow cast: <size=200%><color=red>nineteen meters</color></size>\r\n>... [fluorescent buzz]",
    };
    #endregion

    #region Chargers theme — KDS field-comms; truncated declaratives; red-light protocol
    public static readonly List<string> CryptomnesiaIntel_Chargers = new()
    {
        ">... KDS field, Piros A134\r\n>... contact, contact, Z-32, fast movers\r\n>... quad B452 hold position\r\n>... quad B452 <size=200%><color=red>does not hold</color></size>\r\n>... [gunfire]",
        ">... Sec-B-M chip readout, GO-1395\r\n>... aggression spike, source external\r\n>... source external\r\n>... source is the <size=200%><color=red>room</color></size>\r\n>... [growl]",
        ">>EBDT 0BE401: red lighting protocol confirmed\r\n>... \"contractors call it the kill floor\"\r\n>... McCallister asked, McCallister was dismissed\r\n>... red light, red light, red <size=200%><color=red>light</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... Igor Rostok C122 last log\r\n>... \"they're in the corridor and the corridor is in <size=200%><color=red>me</color></size>\"\r\n>... [KSO entry]\r\n>... log terminated by tier 5 authority",
        ">... WRDN: SEEK\r\n>... WRDN: SEEK\r\n>... WRDN: DESTROY\r\n>... operative compliance 100%\r\n>... operative compliance <size=200%><color=red>not yours</color></size>\r\n>... [feedback]",
        ">... Anders Johanson A029 directive\r\n>... \"product runs hot, product runs faster\"\r\n>... Sigma generation outpacing chip latency\r\n>... they are <size=200%><color=red>deciding, sir</color></size>\r\n>... [static]",
        ">... Piros A134 to ground command\r\n>... Z-32 cleared\r\n>... Z-32 not cleared\r\n>... Z-32 <size=200%><color=red>louder</color></size>\r\n>... [gunfire]",
        ">... operative chip telemetry\r\n>... pulse 188 BPM\r\n>... pulse 188 BPM\r\n>... pulse <size=200%><color=red>flat</color></size>\r\n>... [breathing]",
        ">>EBDT 0BE403: red rotation, sweep 4\r\n>... no surface contact\r\n>... no surface contact\r\n>... <size=200%><color=red>contact behind you</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... Rostok C122 margin note\r\n>... \"the corridor is shorter on the way out\"\r\n>... \"the corridor is shorter every <size=200%><color=red>cycle</color></size>\"\r\n>... [pen on paper]",
        ">... KDS field channel 4\r\n>... three movers, four movers, six movers\r\n>... ammunition assessment: <size=200%><color=red>insufficient</color></size>\r\n>... [magazine click]",
        ">... Piros A134 to channel 1\r\n>... \"red light is the briefing\"\r\n>... \"red light is the <size=200%><color=red>contract</color></size>\"\r\n>... [static]",
        ">... operative T-3701 to channel 3\r\n>... \"my chip is firing on its own\"\r\n>... \"my chip is firing <size=200%><color=red>on its own</color></size>\"\r\n>... [Sec-B-M tone]",
        ">... WRDN: ENGAGE\r\n>... WRDN: ENGAGE\r\n>... operative aim: not configured\r\n>... operative aim <size=200%><color=red>configured by chip</color></size>\r\n>... [feedback]",
        ">... Johanson A029 ledger\r\n>... ChargerGiant unit cost: $4.4M\r\n>... ChargerGiant unit cost: <size=200%><color=red>recovered</color></size>\r\n>... [paper rustle]",
        ">... Sec-B-M chip update bulletin\r\n>... \"new aggression curve deployed\"\r\n>... \"do not consult operative\"\r\n>... operative is <size=200%><color=red>already running</color></size>\r\n>... [boot thud]",
        ">... red light cycle 32\r\n>... red light cycle 33\r\n>... red light cycle <size=200%><color=red>32</color></size>\r\n>... [light buzz]",
        ">... Piros A134 ground report\r\n>... three down\r\n>... three down\r\n>... <size=200%><color=red>four down</color></size>\r\n>... mine\r\n>... [static]",
        ">>EBDT 0BE409: ChargerGiant subspecies log\r\n>... entry suppressed by Lockwood A074\r\n>... entry resurfaced by <size=200%><color=red>specimen</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... operative F-2056 on channel 2\r\n>... \"the corridor smells like copper\"\r\n>... \"the corridor smells like <size=200%><color=red>me</color></size>\"\r\n>... [breathing]",
        ">... KDS rules of engagement, red\r\n>... \"shoot first\"\r\n>... \"shoot first\"\r\n>... \"shoot <size=200%><color=red>last</color></size>\"\r\n>... [gunfire]",
        ">... Rostok C122 cell transcript\r\n>... \"they took my badge before they shot me\"\r\n>... \"they took my badge before they <size=200%><color=red>shot me</color></size>\"\r\n>... [silence]",
        ">... Piros A134 to all KDS\r\n>... no flares\r\n>... no flares\r\n>... <size=200%><color=red>they see in red</color></size>\r\n>... [static]",
        ">... Sec-B-M chip latency 22ms\r\n>... Sec-B-M chip latency 22ms\r\n>... Sec-B-M chip latency <size=200%><color=red>0ms</color></size>\r\n>... operative ahead of command\r\n>... [Sec-B-M tone]",
        ">... WRDN: <size=200%><color=red>SEEK</color></size>\r\n>... WRDN: SEEK\r\n>... WRDN: SEEK\r\n>... target: operative\r\n>... [feedback]",
        ">... KDS dispatch, channel 4\r\n>... \"reload\"\r\n>... \"reload\"\r\n>... \"<size=200%><color=red>nothing to reload into</color></size>\"\r\n>... [magazine click]",
        ">... Johanson Papers, redacted line\r\n>... \"the contract pays per body\"\r\n>... \"the contract pays per body\"\r\n>... \"the contract pays per <size=200%><color=red>your</color></size> body\"\r\n>... [paper rustle]",
        ">... Piros A134 final report\r\n>... \"red is the only color the corridor takes\"\r\n>... \"red is the only color the corridor <size=200%><color=red>has taken</color></size>\"\r\n>... [static]",
        ">... operative GO-1395 chip telemetry\r\n>... muscle fatigue 4%\r\n>... muscle fatigue 4%\r\n>... muscle fatigue <size=200%><color=red>0%</color></size>\r\n>... [breathing]",
        ">... KDS field channel 7\r\n>... \"contact\"\r\n>... \"contact\"\r\n>... \"<size=200%><color=red>contact in front and behind</color></size>\"\r\n>... [gunfire]",
        ">>EBDT 0BE415: red lighting failure\r\n>... red lighting cannot fail\r\n>... red lighting was <size=200%><color=red>never lit</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... Rostok C122 ledger margin\r\n>... \"the room is faster than I am\"\r\n>... \"the room has been faster than I am for <size=200%><color=red>seven years</color></size>\"\r\n>... [pen on paper]",
        ">... Piros A134 to ground\r\n>... \"two left\"\r\n>... \"one left\"\r\n>... \"<size=200%><color=red>none left</color></size>\"\r\n>... [static]",
        ">... Sec-B-M update applied mid-deployment\r\n>... operative did not consent\r\n>... operative did not <size=200%><color=red>need to</color></size>\r\n>... [Sec-B-M tone]",
        ">... WRDN: PURSUE\r\n>... WRDN: PURSUE\r\n>... target: <size=200%><color=red>operative</color></size>\r\n>... [feedback]",
        ">... operative T-3701 chip dump\r\n>... \"I am pulling my own trigger\"\r\n>... \"I am pulling my own <size=200%><color=red>trigger</color></size>\"\r\n>... [gunshot]",
        ">... KDS field, Piros A134\r\n>... \"red lighting is a kindness\"\r\n>... \"you do not have to see <size=200%><color=red>their faces</color></size>\"\r\n>... [boot thud]",
        ">... Johanson Papers, leaked excerpt\r\n>... \"casualty rate at red is below KDS-Deep\"\r\n>... \"casualty rate at red is <size=200%><color=red>not yours to query</color></size>\"\r\n>... [paper rustle]",
        ">... Sec-B-M chip override, all units\r\n>... \"forward, forward, forward\"\r\n>... \"forward into the <size=200%><color=red>door that is closed</color></size>\"\r\n>... [Sec-B-M tone]",
        ">... operative chip log\r\n>... \"I have run out of corridor\"\r\n>... \"I have not run out of <size=200%><color=red>direction</color></size>\"\r\n>... [breathing]",
    };
    #endregion

    #region InfectionFog theme — WHO/Stanovich epidemiology; NAM-V; "the Stoops"
    public static readonly List<string> CryptomnesiaIntel_InfectionFog = new()
    {
        ">... WHO bulletin, Geneva, [inaudible]\r\n>... NAM-V case count revised upward\r\n>... 4.8 billion. 4.8 billion. 4.8 [inaudible]\r\n>... survives 4+ weeks <size=200%><color=red>outside host</color></size>\r\n>... [hiss]",
        ">... Stanovich C066 report SAMD-C043-07\r\n>... 34.4% workforce psychological disturbance\r\n>... no physical etiology\r\n>... workers are calling it <size=200%><color=red>the Stoops</color></size>\r\n>... [pen on paper]",
        ">... Dauda A153 lab note\r\n>... \"the virus is perfectly designed\"\r\n>... \"perfectly designed implies a designer\"\r\n>... <size=200%><color=red>do not transmit this line</color></size>\r\n>... [silence]",
        ">... Patient Zero, Naples FL, Dec 28 2052\r\n>... target escaped Garganta with hazardous material\r\n>... target escaped Garganta\r\n>... target <size=200%><color=red>is</color></size> the hazardous material\r\n>... [hiss]",
        ">... Daylight Mission, Progreso, April 2057\r\n>... mass cremation site grid 12\r\n>... fog reads positive for NAM-V\r\n>... fog reads positive for <size=200%><color=red>cognition</color></size>\r\n>... [Geiger click]",
        ">... incubation analysis: 46% asymptomatic\r\n>... 18 days to 12 months\r\n>... quad B452 cleared at deployment\r\n>... quad B452 cleared at deployment\r\n>... quad B452 <size=200%><color=red>cleared at deployment</color></size>\r\n>... [hiss]",
        ">... Dauda A153 voice memo\r\n>... \"the host is improving the virus\"\r\n>... \"the host is <size=200%><color=red>thanking</color></size> the virus\"\r\n>... [pen on paper]",
        ">... Stanovich C066 footnote, redacted\r\n>... \"NAM-V is not airborne\"\r\n>... \"NAM-V is <size=200%><color=red>thoughtborne</color></size>\"\r\n>... line stricken by tier 5\r\n>... [silence]",
        ">... operative chip readout\r\n>... lung capacity 92%\r\n>... lung capacity 92%\r\n>... lung capacity <size=200%><color=red>not measured</color></size>\r\n>... operative not breathing\r\n>... [hiss]",
        ">... WHO Daylight Mission log\r\n>... \"Progreso is a fog the size of a city\"\r\n>... \"Progreso is a city the size of a <size=200%><color=red>fog</color></size>\"\r\n>... [wind]",
        ">>EBDT 0BE501: Garganta Flu reclassified\r\n>... new label: insufficient\r\n>... new label: insufficient\r\n>... new label: <size=200%><color=red>insufficient</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... Dauda A153 isolation entry\r\n>... \"I have stopped washing my hands\"\r\n>... \"the virus and I have an <size=200%><color=red>understanding</color></size>\"\r\n>... [tap drip]",
        ">... fog density Z-44: 88%\r\n>... fog density Z-44: 88%\r\n>... fog density Z-44: <size=200%><color=red>112%</color></size>\r\n>... [airflow surge]",
        ">... Stanovich C066 to medical\r\n>... \"the Stoops is not a posture\"\r\n>... \"the Stoops is a <size=200%><color=red>listening</color></size>\"\r\n>... [pen on paper]",
        ">... operative F-2056 on channel 2\r\n>... \"my disinfectant is empty\"\r\n>... \"my disinfectant is full\"\r\n>... \"my disinfectant is <size=200%><color=red>warm</color></size>\"\r\n>... [hiss]",
        ">... WHO emergency bulletin\r\n>... \"do not approach the fog\"\r\n>... \"the fog is approaching\"\r\n>... \"the fog is <size=200%><color=red>familiar</color></size>\"\r\n>... [wind]",
        ">... Dauda A153 specimen log\r\n>... \"NAM-V iteration 7 is not iteration 6\"\r\n>... \"iteration 7 is <size=200%><color=red>asking questions</color></size>\"\r\n>... [silence]",
        ">... operative chip telemetry\r\n>... O2 saturation 96%\r\n>... O2 saturation 96%\r\n>... O2 saturation <size=200%><color=red>0%</color></size>\r\n>... operative still talking\r\n>... [breathing]",
        ">>HearSay channel 11, fog overlay\r\n>... \"don't breathe through the cloth\"\r\n>... \"breathe <size=200%><color=red>with</color></size> it\"\r\n>... [voice deepening]",
        ">... Stanovich C066 amend, page 14\r\n>... \"114 incidents do not include the fog\"\r\n>... \"the fog is the <size=200%><color=red>incident</color></size>\"\r\n>... [pen on paper]",
        ">... Dauda A153 lecture notes\r\n>... \"the virus is not contagious\"\r\n>... \"the virus is <size=200%><color=red>conversational</color></size>\"\r\n>... [chalk on board]",
        ">... fog turbine status, Z-44 area C\r\n>... 4 of 4 turbines online\r\n>... 5 of 4 turbines online\r\n>... <size=200%><color=red>5 of 4 turbines online</color></size>\r\n>... [turbine hum]",
        ">... operative GO-1395 to channel 1\r\n>... \"I am not stooped\"\r\n>... \"I am not stooped\"\r\n>... \"I am <size=200%><color=red>listening</color></size>\"\r\n>... [hiss]",
        ">>EBDT 0BE508: Naples FL outbreak\r\n>... source: Garganta\r\n>... vector: airborne\r\n>... vector: <size=200%><color=red>memorial</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... Dauda A153 procedure note\r\n>... \"sample S-901 reproduces in disinfectant\"\r\n>... \"sample S-901 <size=200%><color=red>prefers</color></size> disinfectant\"\r\n>... [tap drip]",
        ">... Stanovich C066 footnote\r\n>... \"the Stoops is not contagious by air\"\r\n>... \"the Stoops is contagious by <size=200%><color=red>schedule</color></size>\"\r\n>... [pen on paper]",
        ">... WHO Geneva, broadcast 226-CAQ-PLK\r\n>... [garbled]\r\n>... [garbled]\r\n>... \"<size=200%><color=red>Don't touch that dial</color></size>\"\r\n>... [static]",
        ">... operative T-3701 chip dump\r\n>... \"I have not coughed once\"\r\n>... \"I have not coughed <size=200%><color=red>at all</color></size>\"\r\n>... [silence]",
        ">... Daylight Mission grid 12 bulletin\r\n>... bodies counted: 14,000\r\n>... bodies counted: 14,000\r\n>... bodies counted: <size=200%><color=red>14,001</color></size>\r\n>... [wind]",
        ">... Dauda A153 to medical\r\n>... \"my workforce is not sick\"\r\n>... \"my workforce is <size=200%><color=red>concentrating</color></size>\"\r\n>... [hiss]",
        ">... fog spectrometer Z-44\r\n>... composition: 22% NAM-V, 76% air\r\n>... composition: 22% NAM-V, 76% <size=200%><color=red>cretasium</color></size>\r\n>... [hiss]",
        ">... operative F-2056 on channel 2\r\n>... \"the fog is humming\"\r\n>... \"the fog is humming\"\r\n>... \"the fog is humming <size=200%><color=red>my song</color></size>\"\r\n>... [wind]",
        ">... Stanovich C066 final entry, fog\r\n>... \"I have been writing this report for nine days\"\r\n>... \"I have been writing this report for <size=200%><color=red>one minute</color></size>\"\r\n>... [pen on paper]",
        ">... Dauda A153 video recording\r\n>... \"smile for the lens\"\r\n>... \"smile for the lens\"\r\n>... \"the lens is <size=200%><color=red>smiling back</color></size>\"\r\n>... [shutter]",
        ">>EBDT 0BE515: Naples cordon broken\r\n>... cordon redrawn\r\n>... cordon redrawn around the <size=200%><color=red>operative</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... operative chip readout\r\n>... \"sweat composition: NAM-V positive\"\r\n>... \"sweat composition: NAM-V <size=200%><color=red>productive</color></size>\"\r\n>... [hiss]",
        ">... WHO Geneva, transmission ends\r\n>... transmission ends\r\n>... transmission ends\r\n>... <size=200%><color=red>transmission resumes</color></size>\r\n>... [static]",
        ">... Dauda A153 isolation diary\r\n>... \"I do not miss anyone\"\r\n>... \"I do not miss anyone\"\r\n>... \"I do not miss <size=200%><color=red>anyone</color></size>\"\r\n>... [tap drip]",
        ">... fog turbine fault, Z-44\r\n>... turbine 3 reversing\r\n>... turbine 3 reversing\r\n>... turbine 3 <size=200%><color=red>swallowing</color></size>\r\n>... [turbine groan]",
        ">... Stanovich C066, dictation\r\n>... \"label this report 'routine'\"\r\n>... \"label this report 'routine'\"\r\n>... \"label this report <size=200%><color=red>'final'</color></size>\"\r\n>... [pen on paper]",
    };
    #endregion

    #region Shadows theme — Teale dissociation; HearSay surveillance bleed; "I can hear you"
    public static readonly List<string> CryptomnesiaIntel_Shadows = new()
    {
        ">... Stokes B193, 03:14 vault recording\r\n>... \"I can hear you out there\"\r\n>... \"I can hear you in here\"\r\n>... <size=200%><color=red>recording predates installation date</color></size>\r\n>... [tape hiss]",
        ">... HearSay channel 7, no source assigned\r\n>... breathing\r\n>... breathing\r\n>... breathing <size=200%><color=red>in time with mine</color></size>\r\n>... [breathing]",
        ">... Teale B023 session notes, patient: self\r\n>... \"my files have been altered\"\r\n>... \"my files alter while I read them\"\r\n>... \"the file is reading <size=200%><color=red>me</color></size>\"\r\n>... [pen on paper]",
        ">... BIOCOM membrane database query\r\n>... 1,000,000,000+ entries\r\n>... one entry returns the operative's name\r\n>... operative did <size=200%><color=red>not submit a name</color></size>\r\n>... [keyboard click]",
        ">... Edgar Soweta, released by KDS\r\n>... \"the visions are not hallucinations\"\r\n>... \"the hallucinations are not mine\"\r\n>... \"someone else is having them <size=200%><color=red>through me</color></size>\"\r\n>... [silence]",
        ">>HearSay auto-transcript begins//\r\n>... \"who is recording this\"\r\n>... \"who is recording <size=200%><color=red>this</color></size>\"\r\n>... //transcript begins",
        ">... Teale B023, undated entry\r\n>... \"my reflection is delayed\"\r\n>... \"my reflection is <size=200%><color=red>ahead</color></size>\"\r\n>... [pen on paper]",
        ">... Stokes B193 vault tape, side B\r\n>... \"the door is locked from inside\"\r\n>... \"I am inside\"\r\n>... \"I am also <size=200%><color=red>locking it</color></size>\"\r\n>... [tape hiss]",
        ">>HearSay channel 14, ambient\r\n>... footsteps\r\n>... footsteps\r\n>... <size=200%><color=red>footsteps continue when operative stops</color></size>\r\n>... [boot scrape]",
        ">... Soweta release transcript\r\n>... \"discharge granted, signed Soweta\"\r\n>... \"signed Soweta\"\r\n>... \"signed <size=200%><color=red>twice</color></size>\"\r\n>... [pen on paper]",
        ">... Teale B023 dictation, lab 4\r\n>... \"my notes contain instructions\"\r\n>... \"the instructions are not <size=200%><color=red>mine</color></size>\"\r\n>... [keyboard click]",
        ">... HearSay archive, file 0001\r\n>... empty\r\n>... empty\r\n>... contains <size=200%><color=red>your voice</color></size>\r\n>... [keyboard click]",
        ">... operative GO-1395 chip log\r\n>... \"there is a footstep behind every footstep\"\r\n>... \"there is a footstep behind <size=200%><color=red>every</color></size>\"\r\n>... [boot scrape]",
        ">... Stokes B193, lab 6, 03:14\r\n>... \"the surveillance is the surveilled\"\r\n>... \"the surveillance is <size=200%><color=red>filming itself</color></size>\"\r\n>... [tape hiss]",
        ">... Teale B023 to himself\r\n>... \"I have already met today\"\r\n>... \"I have already <size=200%><color=red>finished today</color></size>\"\r\n>... [pen on paper]",
        ">>HearSay channel 22, rebroadcast\r\n>... \"do not turn around\"\r\n>... \"do not turn around\"\r\n>... \"<size=200%><color=red>thank you</color></size>\"\r\n>... [whisper]",
        ">... BIOCOM cross-reference\r\n>... operative's name appears 412 times\r\n>... 411 are misspelled\r\n>... 1 is <size=200%><color=red>correct</color></size>\r\n>... [keyboard click]",
        ">... Soweta, untranscribed session\r\n>... \"there are too many of me\"\r\n>... \"none of them are <size=200%><color=red>too many</color></size>\"\r\n>... [silence]",
        ">... Stokes B193, vault recording 0042\r\n>... \"the dark holds\"\r\n>... \"the dark holds <size=200%><color=red>still</color></size>\"\r\n>... [tape hiss]",
        ">>HearSay archive, no metadata\r\n>... \"prisoner T-3701 inhales\"\r\n>... \"prisoner T-3701 inhales\"\r\n>... \"prisoner T-3701 has not been <size=200%><color=red>deployed</color></size>\"\r\n>... [breathing]",
        ">... Teale B023 evening note\r\n>... \"I have run out of names for the patient\"\r\n>... \"the patient has <size=200%><color=red>my name</color></size>\"\r\n>... [pen on paper]",
        ">... HearSay correlation engine\r\n>... operative voice patterns matched\r\n>... 1,247 archive entries\r\n>... operative born <size=200%><color=red>this morning</color></size>\r\n>... [keyboard click]",
        ">... Stokes B193 vault, side A\r\n>... \"the green light is the witness\"\r\n>... \"the green light is the <size=200%><color=red>second witness</color></size>\"\r\n>... [tape hiss]",
        ">... Teale B023 marginalia\r\n>... \"my breathing is not local\"\r\n>... \"my breathing is <size=200%><color=red>shared</color></size>\"\r\n>... [breathing]",
        ">... Soweta retrieval log\r\n>... \"two Sowetas left the facility\"\r\n>... \"one Soweta arrived <size=200%><color=red>home</color></size>\"\r\n>... [door close]",
        ">>HearSay alert, priority high\r\n>... \"you are being watched\"\r\n>... \"you are being watched\"\r\n>... \"<size=200%><color=red>you are watching back</color></size>\"\r\n>... [whisper]",
        ">... BIOCOM ID lookup\r\n>... operative's last command: 'cancel'\r\n>... operative's last command: <size=200%><color=red>'observe'</color></size>\r\n>... [keyboard click]",
        ">... Stokes B193 vault, last side\r\n>... \"the recorder is the recorded\"\r\n>... \"the recorder is the <size=200%><color=red>recordee</color></size>\"\r\n>... [tape hiss]",
        ">... Teale B023, dawn\r\n>... \"there is light in the corridor\"\r\n>... \"there is light <size=200%><color=red>behind</color></size> the corridor\"\r\n>... [pen on paper]",
        ">>HearSay anomaly: file appended in past tense\r\n>... \"operative said\"\r\n>... \"operative said\"\r\n>... \"operative had <size=200%><color=red>not yet spoken</color></size>\"\r\n>... [keyboard click]",
        ">... operative F-2056 on channel 2\r\n>... \"my voice is in the channel before I speak\"\r\n>... \"my voice is in the channel <size=200%><color=red>after I stop</color></size>\"\r\n>... [echo]",
        ">... Soweta clinical note\r\n>... \"the visions ended\"\r\n>... \"the visions ended\"\r\n>... \"the visions <size=200%><color=red>did not</color></size>\"\r\n>... [silence]",
        ">... Teale B023 patient roster\r\n>... self\r\n>... self\r\n>... <size=200%><color=red>self (other)</color></size>\r\n>... [pen on paper]",
        ">... Stokes B193 vault, taped over\r\n>... \"do not erase this\"\r\n>... \"do not erase this\"\r\n>... \"<size=200%><color=red>too late</color></size>\"\r\n>... [tape hiss]",
        ">>HearSay channel 33\r\n>... \"there is a shadow on the camera\"\r\n>... \"the camera is <size=200%><color=red>the shadow</color></size>\"\r\n>... [keyboard click]",
        ">... operative chip telemetry\r\n>... \"footfall pattern matched 1 of 1\"\r\n>... \"matched to file: <size=200%><color=red>operative</color></size>\"\r\n>... [boot scrape]",
        ">... Teale B023 to channel 9\r\n>... \"my speech delay is six seconds\"\r\n>... \"my speech delay is <size=200%><color=red>before</color></size>\"\r\n>... [silence]",
        ">>HearSay archive, sealed\r\n>... \"sealed by tier 5\"\r\n>... \"sealed by tier 5\"\r\n>... \"sealed by <size=200%><color=red>operative</color></size>\"\r\n>... [keyboard click]",
        ">... Stokes B193, lab 6, 03:14\r\n>... \"the door is open\"\r\n>... \"the door is open\"\r\n>... \"the door is <size=200%><color=red>watching</color></size>\"\r\n>... [tape hiss]",
        ">... Soweta last interview\r\n>... \"are you still here\"\r\n>... \"are you still here\"\r\n>... \"are you <size=200%><color=red>still</color></size>\"\r\n>... [silence]",
    };
    #endregion

    #region Nightmares theme — State of Truth AM; Mr. Truth; EF-01; "the corridor remembers"
    public static readonly List<string> CryptomnesiaIntel_Nightmares = new()
    {
        ">... State of Truth AM, frequency unstable\r\n>... \"the Merida quake was on a date that didn't exist yet\"\r\n>... \"you remember it. so do I.\"\r\n>... <size=200%><color=red>Don't touch that dial</color></size>\r\n>... [static]",
        ">... Connor B229 final journal, Nov 2056\r\n>... sealed chamber, biomass exceeds chamber volume\r\n>... final expedition tomorrow\r\n>... final expedition <size=200%><color=red>was yesterday</color></size>\r\n>... [pen on paper]",
        ">... EF-01 telemetry, time dilation 115x\r\n>... Durant B255: \"we have been here ten months\"\r\n>... Garganta clock: 4 hours 12 minutes\r\n>... Bishop returned with <size=200%><color=red>two masks</color></size>\r\n>... [static]",
        ">... Mr. Truth, Pahrump dust storm\r\n>... \"Mrs. Truth is not here\"\r\n>... \"Mr. Truth is not here either\"\r\n>... \"the dial turned <size=200%><color=red>itself</color></size>\"\r\n>... [wind]",
        ">... Cryptomnesia note, source unknown\r\n>... you have walked this corridor\r\n>... you have walked this corridor\r\n>... the corridor remembers you. <size=200%><color=red>you do not</color></size>\r\n>... [boot scrape]",
        ">... The Fossil, Gallery section\r\n>... Collector inscription, partial decode\r\n>... \"the dreamer is the door\"\r\n>... \"the door has been opened from the <size=200%><color=red>other side</color></size>\"\r\n>... [low hum]",
        ">... hydrostasis memory loss confirmed (Johanson Papers)\r\n>... Schaeffer T-3894: seven years frozen\r\n>... quad B452 deployment count <size=200%><color=red>unknown</color></size>\r\n>... you are not the first you\r\n>... [silence]",
        ">... State of Truth AM\r\n>... \"if you remember a place you've never been\"\r\n>... \"someone has been there <size=200%><color=red>as you</color></size>\"\r\n>... [static]",
        ">... Durant B255 EF-01 tape\r\n>... \"the dust is not falling\"\r\n>... \"the dust is <size=200%><color=red>arriving</color></size>\"\r\n>... [wind]",
        ">... Connor B229 sealed-chamber note\r\n>... \"I am writing this twice\"\r\n>... \"I am writing this <size=200%><color=red>again</color></size>\"\r\n>... [pen on paper]",
        ">... Bishop GO-1395 mask scan\r\n>... match\r\n>... match\r\n>... match\r\n>... <size=200%><color=red>three masks</color></size>\r\n>... [scanner click]",
        ">... Mr. Truth, Pahrump rebroadcast\r\n>... \"a dream is a deployment\"\r\n>... \"a deployment is a <size=200%><color=red>dream</color></size>\"\r\n>... [static]",
        ">... EF-01 audio fragment\r\n>... Durant B255: \"I have aged\"\r\n>... Durant B255: \"I have aged\"\r\n>... Durant B255: \"I have <size=200%><color=red>met myself</color></size>\"\r\n>... [tape hiss]",
        ">... orange dust composition\r\n>... 14% iron oxide\r\n>... 14% cretasium\r\n>... 72% <size=200%><color=red>not measured</color></size>\r\n>... [wind]",
        ">... Connor B229 last sealed entry\r\n>... \"the chamber is bigger inside\"\r\n>... \"the chamber is <size=200%><color=red>older</color></size> inside\"\r\n>... [silence]",
        ">... State of Truth AM, frequency drift\r\n>... \"my call letters are not my call letters\"\r\n>... \"my call letters belong to <size=200%><color=red>you</color></size>\"\r\n>... [static]",
        ">... cryptomnesia (n.)\r\n>... a forgotten memory returning as new\r\n>... operative reading this entry\r\n>... has read this entry <size=200%><color=red>before</color></size>\r\n>... [page turn]",
        ">... Durant B255 voice memo, EF-01\r\n>... \"the corridor is open at both ends\"\r\n>... \"the corridor is open at <size=200%><color=red>three</color></size>\"\r\n>... [wind]",
        ">... Mr. Truth final broadcast, Pahrump\r\n>... \"I have signed off\"\r\n>... \"I have signed off\"\r\n>... \"I am <size=200%><color=red>still here</color></size>\"\r\n>... [static]",
        ">... operative chip dump\r\n>... \"I dreamed this corridor\"\r\n>... \"I dreamed this corridor\"\r\n>... \"the corridor <size=200%><color=red>dreamed back</color></size>\"\r\n>... [boot scrape]",
        ">... EF-01 expedition manifest\r\n>... 4 prisoners deployed\r\n>... 4 prisoners returned\r\n>... 5 prisoners <size=200%><color=red>recovered</color></size>\r\n>... [Geiger click]",
        ">... Connor B229 sealed-chamber sketch\r\n>... figure A: Connor\r\n>... figure B: Connor\r\n>... figure C: <size=200%><color=red>not Connor</color></size>\r\n>... [pen on paper]",
        ">... State of Truth AM, listener call-in\r\n>... \"I think I dreamed your station\"\r\n>... \"I think you dreamed <size=200%><color=red>me</color></size>\"\r\n>... [static]",
        ">... Schaeffer T-3894 hydrostasis log\r\n>... \"I do not remember thawing\"\r\n>... \"I do not remember <size=200%><color=red>freezing</color></size>\"\r\n>... [coolant hiss]",
        ">... Bishop GO-1395 mask anomaly\r\n>... mask 1: orbital socket impression\r\n>... mask 2: orbital socket impression\r\n>... <size=200%><color=red>different operative</color></size>\r\n>... same DNA\r\n>... [scanner click]",
        ">... orange light L37 pre-deployment\r\n>... orange light L37 pre-deployment\r\n>... orange light L37 <size=200%><color=red>post-extraction</color></size>\r\n>... [low hum]",
        ">... Durant B255 dispatch, EF-01\r\n>... \"the rations have multiplied\"\r\n>... \"the rations have <size=200%><color=red>aged</color></size>\"\r\n>... [tape hiss]",
        ">... Connor B229 final transmission\r\n>... \"I am not coming back\"\r\n>... \"I am <size=200%><color=red>already back</color></size>\"\r\n>... [silence]",
        ">... Mr. Truth, Pahrump 2049\r\n>... \"the dust is not from here\"\r\n>... \"the dust is from <size=200%><color=red>when</color></size>\"\r\n>... [wind]",
        ">... cryptomnesia (n.) appendix\r\n>... \"the loop is not the symptom\"\r\n>... \"the loop is the <size=200%><color=red>diagnosis</color></size>\"\r\n>... [page turn]",
        ">... operative T-3701 chip dump\r\n>... \"my orders are familiar\"\r\n>... \"my orders are <size=200%><color=red>completed</color></size>\"\r\n>... not yet executed\r\n>... [breathing]",
        ">... State of Truth AM, sign-off\r\n>... \"good night, Pahrump\"\r\n>... \"good night, <size=200%><color=red>Garganta</color></size>\"\r\n>... [static]",
        ">... Durant B255 EF-01 final\r\n>... \"the door home is not the door home\"\r\n>... \"the door home is <size=200%><color=red>another door</color></size>\"\r\n>... [latch]",
        ">... Bishop GO-1395 voice memo\r\n>... \"I returned with my own face\"\r\n>... \"I returned with <size=200%><color=red>two</color></size>\"\r\n>... [silence]",
        ">... Connor B229 page 88\r\n>... \"the chamber wall has my handwriting\"\r\n>... \"the chamber wall has <size=200%><color=red>better</color></size> handwriting\"\r\n>... [pen on paper]",
        ">... orange dust spectrometer\r\n>... origin: Yucatan, Chicxulub\r\n>... origin: Yucatan, <size=200%><color=red>future</color></size>\r\n>... [wind]",
        ">... Schaeffer T-3894 dispatch\r\n>... \"my crypt is not where I left it\"\r\n>... \"my crypt is where I will <size=200%><color=red>leave it</color></size>\"\r\n>... [coolant hiss]",
        ">... cryptomnesia diagnostic\r\n>... operative cognition: novel\r\n>... operative cognition: <size=200%><color=red>recurrent</color></size>\r\n>... rerunning\r\n>... [keyboard click]",
        ">... State of Truth AM, dead air\r\n>... [no audio]\r\n>... [no audio]\r\n>... \"<size=200%><color=red>still here</color></size>\"\r\n>... [static resumes]",
        ">... operative GO-1395 to channel 1\r\n>... \"the corridor smells like a dream\"\r\n>... \"the dream <size=200%><color=red>smells like the corridor</color></size>\"\r\n>... [boot scrape]",
    };
    #endregion

    #region Neutral — cube / Matter Wave Projector / loop / cretasium / hydrostasis memory
    public static readonly List<string> CryptomnesiaIntel_Neutral = new()
    {
        ">... We're... back...\r\n>... This will go quick then!\r\n>... No, <size=200%><color=red>wait-</color></size>\r\n>... [screeching, gunfire]",
        ">... Tampered Data Cube recovered, Z-? area ?\r\n>... cretasium signature 24% unidentified\r\n>... matches Chicxulub meteorite spectrum\r\n>... matches the operative's <size=200%><color=red>blood</color></size>\r\n>... [Geiger click]",
        ">... Matter Wave Projector cycle initiated\r\n>... silicon resin coating: nominal\r\n>... do not contact the surface unshielded\r\n>... previous quads who did: 7. recovered: <size=200%><color=red>0</color></size>\r\n>... [transformer hum]",
        ">... WRDN: TRANSLOCATE\r\n>... WRDN: TRANSLOCATE\r\n>... destination: Reality\r\n>... destination: <size=200%><color=red>Reality?</color></size>\r\n>... [chamber pressurize]",
        ">... BIOCOM checksum on operative cognition\r\n>... memory continuity flagged as forgery\r\n>... memory continuity flagged as forgery\r\n>... flag dismissed by <size=200%><color=red>tier 5 authority</color></size>\r\n>... [system chime]",
        ">... data block index L18-AT06 et seq.\r\n>... artifact integrity: unbreakable\r\n>... artifact contents: a corridor you've walked\r\n>... artifact contents: <size=200%><color=red>this corridor</color></size>\r\n>... [low hum]",
        ">... clock anomaly L37: +230s/24h\r\n>... quad clock: -230s/24h\r\n>... net drift across drop: zero\r\n>... net drift across <size=200%><color=red>you</color></size>: unknown\r\n>... [tick]",
        ">... Lockwood A074 directive, tier 5\r\n>... \"do not call it a dimension\"\r\n>... \"do not call it a memory either\"\r\n>... \"call it a <size=200%><color=red>recovery operation</color></size>\"\r\n>... [paper rustle]",
        ">... Bishop GO-1395 mask scan: match\r\n>... Bishop GO-1395 mask scan: match\r\n>... two matches. one operative.\r\n>... <size=200%><color=red>EF-01 anomaly persists</color></size>\r\n>... [scanner click]",
        ">... cryptomnesia (n.): a memory mistaken for a new thought\r\n>... operative status: deployed\r\n>... operative status: <size=200%><color=red>re-</color></size>deployed\r\n>... cube count rising\r\n>... [page turn]",
        ">... State of Truth AM, last clean broadcast\r\n>... \"if you remember a place you've never been --\"\r\n>... \"-- someone has been there <size=200%><color=red>as you</color></size>\"\r\n>... Don't touch that dial. Mr. Truth out.\r\n>... [static]",
        ">... Translocation Chamber pressure check\r\n>... 4 of 4 operatives sealed\r\n>... 4 of 4 operatives sealed\r\n>... 4 of 4 operatives <size=200%><color=red>not yet entered</color></size>\r\n>... [chamber pressurize]",
        ">>EBDT 0BE701: cube count anomaly\r\n>... requested: 4\r\n>... received: 4\r\n>... archived: <size=200%><color=red>5</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... Schaeffer T-3894 dispatch\r\n>... \"I do not know whose voice this is\"\r\n>... \"the voice is <size=200%><color=red>signing off as me</color></size>\"\r\n>... [coolant hiss]",
        ">... operative chip telemetry\r\n>... \"deployment count: 1\"\r\n>... \"deployment count: 1\"\r\n>... \"deployment count: <size=200%><color=red>not displayed</color></size>\"\r\n>... [Sec-B-M tone]",
        ">... Matter Wave Projector log\r\n>... cycle 0042 complete\r\n>... cycle 0042 complete\r\n>... cycle 0042 <size=200%><color=red>still running</color></size>\r\n>... [transformer hum]",
        ">... cretasium reading L37: anomalous\r\n>... cretasium reading L37: anomalous\r\n>... cretasium reading <size=200%><color=red>follows operative</color></size>\r\n>... [Geiger click]",
        ">... data cube serial RK-0042-A\r\n>... data cube serial RK-0042-A\r\n>... data cube serial <size=200%><color=red>RK-0042-Y</color></size>\r\n>... different alphabet\r\n>... [low hum]",
        ">... WRDN broadcast burst\r\n>... \"COMPLY\"\r\n>... \"EXTRACT\"\r\n>... \"<size=200%><color=red>RECALL</color></size>\"\r\n>... [feedback]",
        ">... operative GO-1395 internal note\r\n>... \"I remember this elevator\"\r\n>... \"I remember <size=200%><color=red>not remembering</color></size> this elevator\"\r\n>... [chamber pressurize]",
        ">... Lockwood A074 talking points\r\n>... \"the dimension is a misfiled report\"\r\n>... \"the misfiled report is the <size=200%><color=red>only true file</color></size>\"\r\n>... [paper rustle]",
        ">... Translocation Chamber audit\r\n>... 14 cycles this hour\r\n>... 14 cycles this hour\r\n>... <size=200%><color=red>operative arrived 13 times</color></size>\r\n>... [system chime]",
        ">... cryptomnesia clinical note\r\n>... patient describes a vivid first deployment\r\n>... patient is on deployment <size=200%><color=red>114</color></size>\r\n>... [pen on paper]",
        ">... data cube assay\r\n>... carbon-12 signature: nominal\r\n>... cretasium signature: <size=200%><color=red>elevated</color></size>\r\n>... operative signature: present\r\n>... [Geiger click]",
        ">... operative F-2056 to channel 2\r\n>... \"this map is wrong\"\r\n>... \"this map is wrong\"\r\n>... \"this map is <size=200%><color=red>tomorrow's</color></size>\"\r\n>... [paper rustle]",
        ">... BIOCOM continuity check\r\n>... operative consciousness: continuous\r\n>... operative consciousness: continuous\r\n>... operative consciousness: <size=200%><color=red>continuous (revised)</color></size>\r\n>... [system chime]",
        ">... Hammerstein B014 quoted, posthumous\r\n>... \"Non ducor, duco\"\r\n>... \"a corridor leads its walker\"\r\n>... \"the walker has been <size=200%><color=red>led before</color></size>\"\r\n>... [chalk on board]",
        ">>EBDT 0BE713: hydrostasis memory loss escalation\r\n>... percentage of recall: 92%\r\n>... percentage of recall: 92%\r\n>... percentage of recall: <size=200%><color=red>0%</color></size>\r\n>... [coolant hiss]",
        ">... Mr. Truth dispatch, replay\r\n>... \"a memory you do not have\"\r\n>... \"is a memory <size=200%><color=red>someone else has of you</color></size>\"\r\n>... [static]",
        ">... operative T-3701 logbook\r\n>... \"my notes contain my future notes\"\r\n>... \"my future notes are <size=200%><color=red>illegible</color></size>\"\r\n>... [pen on paper]",
        ">... Matter Wave Projector compliance\r\n>... seal integrity: 100%\r\n>... seal integrity: 100%\r\n>... seal integrity: <size=200%><color=red>not the right seal</color></size>\r\n>... [chamber pressurize]",
        ">... data cube fragment, RK-0042-G\r\n>... contents: 'do not'\r\n>... contents: 'do not'\r\n>... contents: '<size=200%><color=red>do not turn around</color></size>'\r\n>... [low hum]",
        ">... cryptomnesia second-pass diagnostic\r\n>... operative cognition: novel\r\n>... operative cognition: novel\r\n>... operative cognition: <size=200%><color=red>recurrent (1142)</color></size>\r\n>... [keyboard click]",
        ">... Stanovich C066 amend, page 22\r\n>... \"the loop is not the failure\"\r\n>... \"the loop is the <size=200%><color=red>product</color></size>\"\r\n>... [pen on paper]",
        ">... operative chip telemetry, post-warp\r\n>... heart rate: 88 BPM\r\n>... heart rate: 88 BPM\r\n>... heart rate: <size=200%><color=red>88 BPM (not yours)</color></size>\r\n>... [Sec-B-M tone]",
        ">... WRDN address, all operatives\r\n>... \"we have been here before\"\r\n>... \"we have been here before\"\r\n>... \"we have <size=200%><color=red>not yet left</color></size>\"\r\n>... [feedback]",
        ">... Lockwood A074 redaction note\r\n>... \"strike all references to recurrence\"\r\n>... \"strike all references to <size=200%><color=red>recurrence</color></size>\"\r\n>... line preserved by automation\r\n>... [paper rustle]",
        ">... cretasium drift observed at L37\r\n>... drift vector: north-northwest\r\n>... drift vector: <size=200%><color=red>operative-shaped</color></size>\r\n>... [Geiger click]",
        ">... operative GO-1395 chip dump\r\n>... \"the elevator door has opened twice\"\r\n>... \"I have entered <size=200%><color=red>once</color></size>\"\r\n>... [chamber pressurize]",
        ">>HearSay archive request\r\n>... query: 'first deployment'\r\n>... results: 0\r\n>... results: 0\r\n>... results: <size=200%><color=red>none</color></size>\r\n>... [keyboard click]",
        ">... Schaeffer T-3894 voice memo, undated\r\n>... \"I am not who I was\"\r\n>... \"I was not <size=200%><color=red>who I was either</color></size>\"\r\n>... [coolant hiss]",
        ">... data cube assay continued\r\n>... cube weight stable\r\n>... cube count stable\r\n>... cube count <size=200%><color=red>increasing while observed</color></size>\r\n>... [low hum]",
        ">... operative F-2056 final note this drop\r\n>... \"I left a marker last cycle\"\r\n>... \"the marker is <size=200%><color=red>here</color></size>\"\r\n>... \"this is cycle one\"\r\n>... [chalk on wall]",
        ">... Translocation Chamber telemetry\r\n>... 4 in, 4 out\r\n>... 4 in, 4 out\r\n>... 4 in, <size=200%><color=red>5 out</color></size>\r\n>... [chamber pressurize]",
        ">... Mr. Truth, off-air channel\r\n>... \"the dial does not exist\"\r\n>... \"the dial does not exist\"\r\n>... \"<size=200%><color=red>you turned it</color></size>\"\r\n>... [static]",
        ">... operative T-3701 dictation\r\n>... \"this objective is familiar\"\r\n>... \"this objective is <size=200%><color=red>completed</color></size>\"\r\n>... not yet started\r\n>... [breathing]",
        ">... cretasium-cube interaction\r\n>... cube emits at 4.2 kHz\r\n>... cube emits at 4.2 kHz\r\n>... cube emits the <size=200%><color=red>operative's name</color></size>\r\n>... [low hum]",
        ">... cryptomnesia (n.) revised\r\n>... \"a memory mistaken for a thought\"\r\n>... \"a thought mistaken for a <size=200%><color=red>place</color></size>\"\r\n>... [page turn]",
        ">... Lockwood A074 final talking point\r\n>... \"call it a recovery operation\"\r\n>... \"call it a recovery operation\"\r\n>... \"call <size=200%><color=red>them</color></size> recovered\"\r\n>... [paper rustle]",
        ">... data cube count, post-extraction\r\n>... 4\r\n>... 4\r\n>... <size=200%><color=red>4 (different)</color></size>\r\n>... [chamber pressurize]",
        ">... WRDN: RECALL\r\n>... WRDN: RECALL\r\n>... operative recall: <size=200%><color=red>not configured</color></size>\r\n>... operative is the recall\r\n>... [feedback]",
        ">... Stanovich C066 closing line\r\n>... \"114 incidents and rising\"\r\n>... \"114 incidents and <size=200%><color=red>this one</color></size>\"\r\n>... [pen on paper]",
        ">... Hammerstein B014 footnote\r\n>... \"the corridor is the report\"\r\n>... \"the report is the <size=200%><color=red>corridor</color></size>\"\r\n>... [chalk on board]",
        ">... Bishop GO-1395 mask shelf\r\n>... slot 1: occupied\r\n>... slot 2: occupied\r\n>... slot 3: <size=200%><color=red>occupied</color></size>\r\n>... [scanner click]",
        ">... operative chip dump, post-warp\r\n>... \"I am here\"\r\n>... \"I was here\"\r\n>... \"I will be <size=200%><color=red>here</color></size>\"\r\n>... [Sec-B-M tone]",
        ">... cryptomnesia operational note\r\n>... extract, then forget\r\n>... extract, then forget\r\n>... extract, then <size=200%><color=red>extract again</color></size>\r\n>... [chamber pressurize]",
        ">... Mr. Truth, broadcast end\r\n>... \"goodnight\"\r\n>... \"goodnight\"\r\n>... \"<size=200%><color=red>tomorrow's listeners</color></size>\"\r\n>... [static]",
        ">... operative GO-1395 final note\r\n>... \"the elevator has dropped\"\r\n>... \"the elevator has <size=200%><color=red>not stopped</color></size>\"\r\n>... [chamber pressurize]",
        ">... data cube reading, summary\r\n>... cretasium 24% unidentified\r\n>... cretasium 24% <size=200%><color=red>uninvented</color></size>\r\n>... [Geiger click]",
        ">... cryptomnesia closing diagnostic\r\n>... operative status: extracting\r\n>... operative status: extracting\r\n>... operative status: <size=200%><color=red>extracted (again)</color></size>\r\n>... [system chime]",
        ">... WRDN address, sign-off\r\n>... \"good work\"\r\n>... \"good work\"\r\n>... \"good <size=200%><color=red>work</color></size>\"\r\n>... [feedback]",
    };
    #endregion
}
