using AutogenRundown.DataBlocks.Enums;

namespace AutogenRundown.DataBlocks.Objectives;

/// <summary>
/// Intel pools for the AlphaTerminalCommand objective. One line is picked at random
/// from the union of the three themed pools and pushed onto the elevator-drop
/// transmission slot.
///
/// Format conventions for every entry:
/// - 2-3 lines, separated by `\r\n`
/// - Each line prefixed with `>... ` (radio chatter) or `>>` (transcript header)
/// - Exactly one `<size=200%><color=red>X</color></size>` highlight on the urgent phrase
/// - Exactly one bracketed audio cue per entry (e.g. `[static]`, `[carrier wave]`,
///   `[wind]`, `[hum]`, `[breathing]`, `[no signal]`,
///   `[Encryption checksum mismatch. Contact your IT administrator]`)
/// - The literal token `{COMMAND}` is replaced at pick time with the rolled
///   backdoor command name (one of OVERRIDE_INITIALIZATION, EXEC_OVERRIDE,
///   INTERPRET_NAV_DATA, COPY_GEN_INDEX_COMPLETE_DB)
/// - Dimension names are NEVER spoken. Use indirect description ("the dust",
///   "open sky", "the ridge", "the topology held").
/// - Voices: prisoner radio (Bishop GO-1395, Woods F-2056, Hackett O-4711,
///   Dauda T-3701), researcher logs (Durant B255, Stokes B193, Schaeffer T-3894,
///   Connor B229, Hammerstein B014, Teale B023), Warden corrupted output
///   (`WRDN: {COMMAND}`), HearSay/BIOCOM/EBDT auto-transcripts.
/// </summary>
public partial record WardenObjective
{
    #region Prisoner radio — pre-jump nerves, in-dimension reactions, transfer chatter
    public static readonly List<string> AlphaTerminalCommandIntel_PrisonerRadio = new()
    {
        ">... cube's locked, MWP humming\r\n>... <size=200%><color=red>do not let go of it</color></size>\r\n>... [carrier wave]",
        ">... \"hand on the projector, knees bent\"\r\n>... <size=200%><color=red>that's not encouraging</color></size>\r\n>... [breathing]",
        ">... \"team scan in three. two.\"\r\n>... <size=200%><color=red>floor is not warm</color></size>\r\n>... [hiss]",
        ">... MWP coupling green\r\n>... MWP coupling <size=200%><color=red>not green</color></size>\r\n>... [carrier wave]",
        ">... \"if I don't come back\"\r\n>... <size=200%><color=red>that's the deal</color></size>\r\n>... [static]",
        ">... \"have you done one of these before\"\r\n>... <size=200%><color=red>\"twice was enough\"</color></size>\r\n>... [breathing]",
        ">... \"safety lever's on the right, right?\"\r\n>... \"<size=200%><color=red>your other left</color></size>\"\r\n>... [tool clatter]",
        ">... mounting platform handshake nominal\r\n>... handshake answered by <size=200%><color=red>something else</color></size>\r\n>... [carrier wave]",
        ">... \"projector's vibrating\"\r\n>... \"<size=200%><color=red>at this frequency?</color></size>\"\r\n>... [hum]",
        ">... \"I don't like missions where the briefing skips a paragraph\"\r\n>... <size=200%><color=red>\"this one skipped four\"</color></size>\r\n>... [breathing]",
        ">... \"sky\"\r\n>... \"<size=200%><color=red>sky</color></size>\"\r\n>... [wind]",
        ">... \"is that the sun\"\r\n>... \"<size=200%><color=red>I can't stop looking at it</color></size>\"\r\n>... [wind]",
        ">... \"the air tastes wrong but it tastes like air\"\r\n>... <size=200%><color=red>chip flagging respiratory event</color></size>\r\n>... [breathing]",
        ">... \"sand under boots, not steel\"\r\n>... \"<size=200%><color=red>only ours</color></size>\"\r\n>... [wind]",
        ">... \"the horizon is too far\"\r\n>... <size=200%><color=red>\"this is wrong\"</color></size>\r\n>... [carrier wave]",
        ">... \"are those structures or rocks\"\r\n>... <size=200%><color=red>\"too even for rocks\"</color></size>\r\n>... [wind]",
        ">... \"shadows are cast wrong\"\r\n>... \"shadows cast <size=200%><color=red>both ways</color></size>\"\r\n>... [no audio]",
        ">... \"two suns?\"\r\n>... \"<size=200%><color=red>two suns</color></size>\"\r\n>... [wind]",
        ">... \"the dust is gold\"\r\n>... \"the dust is <size=200%><color=red>moving</color></size>\"\r\n>... [breathing]",
        ">... \"team, hands off your weapons until I call it\"\r\n>... <size=200%><color=red>\"because nothing's shooting yet\"</color></size>\r\n>... [hiss]",
        ">... \"this place is the same as last drop\"\r\n>... <size=200%><color=red>\"exactly the same\"</color></size>\r\n>... [wind]",
        ">... \"chronometer says we've been here four seconds\"\r\n>... <size=200%><color=red>\"feels like fourteen minutes\"</color></size>\r\n>... [no signal]",
        ">... \"terminal's on the rise, west side\"\r\n>... <size=200%><color=red>\"don't ask\"</color></size>\r\n>... [boot crunch]",
        ">... \"the screen's on\"\r\n>... <size=200%><color=red>\"who turned it on\"</color></size>\r\n>... [keyboard]",
        ">... \"input prompt expects {COMMAND}\"\r\n>... <size=200%><color=red>\"how does it know\"</color></size>\r\n>... [keyboard]",
        ">... \"keyboard's warm\"\r\n>... <size=200%><color=red>\"recently\"</color></size>\r\n>... [breathing]",
        ">... \"the casing's old\"\r\n>... <size=200%><color=red>\"older than the company\"</color></size>\r\n>... [keyboard]",
        ">... \"command field's pre-filled\"\r\n>... <size=200%><color=red>\"with {COMMAND}\"</color></size>\r\n>... [hiss]",
        ">... \"manufacturer plate's blank\"\r\n>... <size=200%><color=red>\"or it never had one\"</color></size>\r\n>... [breathing]",
        ">... \"display's running diagnostics\"\r\n>... <size=200%><color=red>\"on us\"</color></size>\r\n>... [carrier wave]",
        ">... \"approach slow, the prompt's blinking\"\r\n>... <size=200%><color=red>\"not in unison with my heart\"</color></size>\r\n>... [breathing]",
        ">... \"I've keyed {COMMAND}\"\r\n>... <size=200%><color=red>\"the screen pressed it\"</color></size>\r\n>... [keyboard]",
        ">... \"executing {COMMAND}\"\r\n>... <size=200%><color=red>\"it executed twice\"</color></size>\r\n>... [keyboard]",
        ">... \"transfer initiated\"\r\n>... <size=200%><color=red>\"the terminal did\"</color></size>\r\n>... [hum]",
        ">... \"{COMMAND} accepted\"\r\n>... <size=200%><color=red>\"reply was in our voices\"</color></size>\r\n>... [carrier wave]",
        ">... \"checksum on {COMMAND} valid\"\r\n>... \"checksum on operator <size=200%><color=red>invalid</color></size>\"\r\n>... [hiss]",
        ">... \"keyed it. it didn't take.\"\r\n>... <size=200%><color=red>\"it took the third one before I keyed it\"</color></size>\r\n>... [keyboard]",
        ">... \"progress bar moving\"\r\n>... <size=200%><color=red>\"backwards\"</color></size>\r\n>... [hum]",
        ">... \"display's asking confirm\"\r\n>... <size=200%><color=red>\"my date of birth\"</color></size>\r\n>... [keyboard]",
        ">... \"{COMMAND} returned 0x00\"\r\n>... <size=200%><color=red>\"that's also nothing\"</color></size>\r\n>... [carrier wave]",
        ">... \"transfer started\"\r\n>... <size=200%><color=red>\"holding\"</color></size>\r\n>... [breathing]",
        ">... \"the prompt cleared itself\"\r\n>... <size=200%><color=red>\"with my hands\"</color></size>\r\n>... [keyboard]",
        ">... \"this transfer is taking a while\"\r\n>... <size=200%><color=red>\"briefing was wrong before\"</color></size>\r\n>... [hum]",
        ">... \"chronometer normal\"\r\n>... <size=200%><color=red>\"that's the bad one\"</color></size>\r\n>... [no signal]",
        ">... \"quantum tether holding at 88%\"\r\n>... <size=200%><color=red>\"quantum tether holding at — \"</color></size>\r\n>... [carrier wave]",
        ">... \"is it supposed to be this quiet\"\r\n>... <size=200%><color=red>\"no\"</color></size>\r\n>... [wind]",
        ">... \"don't move from the platform\"\r\n>... <size=200%><color=red>\"my boot's stuck\"</color></size>\r\n>... [boot crunch]",
        ">... \"I'm seeing something at the ridge\"\r\n>... <size=200%><color=red>\"it's drawing first\"</color></size>\r\n>... [hiss]",
        ">... \"transfer at 40%\"\r\n>... \"transfer at <size=200%><color=red>40%</color></size>\"\r\n>... [hum]",
        ">... \"tether reading drifted\"\r\n>... <size=200%><color=red>\"two minutes\"</color></size>\r\n>... [no signal]",
        ">... \"comms working but no one's talking\"\r\n>... <size=200%><color=red>\"not on this channel\"</color></size>\r\n>... [carrier wave]",
        ">... \"the dust is settling on us\"\r\n>... <size=200%><color=red>\"it's settling against the wind\"</color></size>\r\n>... [wind]",
        ">... \"transfer rate dropped\"\r\n>... <size=200%><color=red>\"transfer rate not real\"</color></size>\r\n>... [hum]",
        ">... \"{COMMAND} is still on the screen\"\r\n>... <size=200%><color=red>\"or it's stuck\"</color></size>\r\n>... [keyboard]",
        ">... \"distant low roar, west\"\r\n>... <size=200%><color=red>\"all directions\"</color></size>\r\n>... [low rumble]",
        ">... \"something's coming\"\r\n>... <size=200%><color=red>\"hold the platform\"</color></size>\r\n>... [boot rush]",
        ">... \"motion at the ridge\"\r\n>... <size=200%><color=red>\"all of the motion\"</color></size>\r\n>... [growl]",
        ">... \"do not engage, transfer's almost done\"\r\n>... <size=200%><color=red>\"engagement engaged us\"</color></size>\r\n>... [hiss]",
        ">... \"hostile contact, fifteen meters\"\r\n>... <size=200%><color=red>\"already past us\"</color></size>\r\n>... [boot rush]",
        ">... \"this is what's coming through\"\r\n>... <size=200%><color=red>\"this is what came back\"</color></size>\r\n>... [growl]",
        ">... \"how big\"\r\n>... <size=200%><color=red>\"that big\"</color></size>\r\n>... [low rumble]",
        ">... \"do not engage the contacts\"\r\n>... <size=200%><color=red>\"contacts engage themselves\"</color></size>\r\n>... [hiss]",
        ">... \"transfer's at 90\"\r\n>... <size=200%><color=red>\"holding\"</color></size>\r\n>... [breathing]",
        ">... \"thirty seconds\"\r\n>... <size=200%><color=red>\"twenty back to thirty\"</color></size>\r\n>... [hum]",
        ">... \"warp tone in five\"\r\n>... <size=200%><color=red>\"in now\"</color></size>\r\n>... [carrier wave]",
        ">... \"hand on the projector!\"\r\n>... <size=200%><color=red>\"WHOSE HAND\"</color></size>\r\n>... [hum]",
        ">... \"projector spooling\"\r\n>... <size=200%><color=red>\"projector chose us\"</color></size>\r\n>... [hum]",
        ">... \"closing eyes for the warp\"\r\n>... <size=200%><color=red>\"can't close them\"</color></size>\r\n>... [hiss]",
        ">... \"team count: four\"\r\n>... <size=200%><color=red>\"team count: four — different four\"</color></size>\r\n>... [carrier wave]",
        ">... \"warp\"\r\n>... <size=200%><color=red>\"warp not finished\"</color></size>\r\n>... [hum]",
        ">... \"feet leaving the floor\"\r\n>... <size=200%><color=red>\"both\"</color></size>\r\n>... [carrier wave]",
        ">... \"don't let go of the cube\"\r\n>... <size=200%><color=red>\"the cube let go of me\"</color></size>\r\n>... [carrier wave]",
        ">... \"saw a structure on the horizon\"\r\n>... <size=200%><color=red>\"Warden said no horizon\"</color></size>\r\n>... [static]",
        ">... \"there were footprints other than ours\"\r\n>... <size=200%><color=red>\"Warden said no\"</color></size>\r\n>... [carrier wave]",
        ">... \"the back of my throat tastes like sand\"\r\n>... <size=200%><color=red>\"we never landed\"</color></size>\r\n>... [breathing]",
        ">... \"my chronometer drifted 40 seconds\"\r\n>... <size=200%><color=red>\"drifted 40 seconds again\"</color></size>\r\n>... [hum]",
        ">... \"saw a figure at the ridge\"\r\n>... <size=200%><color=red>\"waiting\"</color></size>\r\n>... [no audio]",
        ">... \"my coat has dust I can't shake out\"\r\n>... <size=200%><color=red>\"still gold\"</color></size>\r\n>... [silence]",
        ">... \"been hearing wind in my barracks\"\r\n>... <size=200%><color=red>\"there is now\"</color></size>\r\n>... [wind]",
        ">... \"the {COMMAND} prompt is still in my retina\"\r\n>... <size=200%><color=red>\"still there\"</color></size>\r\n>... [breathing]",
        ">... \"strapping the helm\"\r\n>... <size=200%><color=red>\"it's already strapped\"</color></size>\r\n>... [tool clatter]",
        ">... \"cube's reading hot\"\r\n>... <size=200%><color=red>\"hot to the touch, cold to the meter\"</color></size>\r\n>... [hum]",
        ">... \"gate alignment, ready\"\r\n>... <size=200%><color=red>\"gate aligned without us\"</color></size>\r\n>... [carrier wave]",
        ">... \"final check on the projector\"\r\n>... <size=200%><color=red>\"projector finished checking us\"</color></size>\r\n>... [hum]",
        ">... \"breather seal nominal\"\r\n>... <size=200%><color=red>\"seal nominal but I'm not breathing yet\"</color></size>\r\n>... [breathing]",
        ">... \"who briefed us on this\"\r\n>... <size=200%><color=red>\"there was no briefing\"</color></size>\r\n>... [carrier wave]",
        ">... \"chip says I'm calm\"\r\n>... <size=200%><color=red>\"chip is lying\"</color></size>\r\n>... [breathing]",
        ">... \"glove's tight\"\r\n>... <size=200%><color=red>\"by the second\"</color></size>\r\n>... [tool clatter]",
        ">... \"my pulse is a hundred and four\"\r\n>... <size=200%><color=red>\"a hundred and four exactly\"</color></size>\r\n>... [breathing]",
        ">... \"running diagnostics on the harness\"\r\n>... <size=200%><color=red>\"the harness is running diagnostics back\"</color></size>\r\n>... [keyboard]",
        ">... \"locking into the platform\"\r\n>... <size=200%><color=red>\"the platform locked first\"</color></size>\r\n>... [tool clatter]",
        ">... \"projector cycle in twenty\"\r\n>... <size=200%><color=red>\"cycle started before the count\"</color></size>\r\n>... [hum]",
        ">... \"cube secured\"\r\n>... <size=200%><color=red>\"by whom\"</color></size>\r\n>... [carrier wave]",
        ">... \"the briefing said three minutes\"\r\n>... <size=200%><color=red>\"the briefing was three minutes ago\"</color></size>\r\n>... [breathing]",
        ">... \"last call before warp\"\r\n>... <size=200%><color=red>\"there are more calls\"</color></size>\r\n>... [static]",
        ">... \"the air weighs more here\"\r\n>... <size=200%><color=red>\"by exactly one of us\"</color></size>\r\n>... [wind]",
        ">... \"the ground gives wrong\"\r\n>... <size=200%><color=red>\"gives like a tongue\"</color></size>\r\n>... [boot crunch]",
        ">... \"no birds\"\r\n>... <size=200%><color=red>\"no anything\"</color></size>\r\n>... [wind]",
        ">... \"this place has a smell\"\r\n>... <size=200%><color=red>\"like a room someone just left\"</color></size>\r\n>... [breathing]",
        ">... \"the wind has a direction\"\r\n>... <size=200%><color=red>\"toward us, only\"</color></size>\r\n>... [wind]",
        ">... \"sun's at noon\"\r\n>... <size=200%><color=red>\"it was at noon when we got here\"</color></size>\r\n>... [wind]",
        ">... \"the horizon line is too high\"\r\n>... <size=200%><color=red>\"the horizon is below the platform\"</color></size>\r\n>... [no signal]",
        ">... \"my boots are dusty\"\r\n>... <size=200%><color=red>\"I haven't moved\"</color></size>\r\n>... [breathing]",
        ">... \"footprints, four\"\r\n>... <size=200%><color=red>\"five\"</color></size>\r\n>... [boot crunch]",
        ">... \"the ridges look man-made\"\r\n>... <size=200%><color=red>\"not by men\"</color></size>\r\n>... [wind]",
        ">... \"my shadow is the wrong length\"\r\n>... <size=200%><color=red>\"my shadow is reading something\"</color></size>\r\n>... [no audio]",
        ">... \"gravity feels low\"\r\n>... <size=200%><color=red>\"only on me\"</color></size>\r\n>... [breathing]",
        ">... \"the temperature is dropping\"\r\n>... <size=200%><color=red>\"my chip says it's rising\"</color></size>\r\n>... [hiss]",
        ">... \"I can see a long way\"\r\n>... <size=200%><color=red>\"too long\"</color></size>\r\n>... [wind]",
        ">... \"the dust is warm\"\r\n>... <size=200%><color=red>\"the dust knows my name\"</color></size>\r\n>... [silence]",
        ">... \"there's a glint on the ridge\"\r\n>... <size=200%><color=red>\"it's looking back\"</color></size>\r\n>... [wind]",
        ">... \"the sky has no clouds\"\r\n>... <size=200%><color=red>\"the sky has no top\"</color></size>\r\n>... [wind]",
        ">... \"no sound carries here\"\r\n>... <size=200%><color=red>\"except mine, back to me\"</color></size>\r\n>... [no audio]",
        ">... \"the colors are off\"\r\n>... <size=200%><color=red>\"the colors are right, my eyes are off\"</color></size>\r\n>... [breathing]",
        ">... \"I can hear my heart\"\r\n>... <size=200%><color=red>\"and someone else's\"</color></size>\r\n>... [breathing]",
        ">... \"my radio's clear\"\r\n>... <size=200%><color=red>\"too clear\"</color></size>\r\n>... [carrier wave]",
        ">... \"the wind's blowing through me\"\r\n>... <size=200%><color=red>\"not around\"</color></size>\r\n>... [wind]",
        ">... \"I taste copper\"\r\n>... <size=200%><color=red>\"I am not bleeding\"</color></size>\r\n>... [breathing]",
        ">... \"the chip's silent\"\r\n>... <size=200%><color=red>\"first time ever\"</color></size>\r\n>... [hiss]",
        ">... \"I can smell rain\"\r\n>... <size=200%><color=red>\"the desert has not rained\"</color></size>\r\n>... [wind]",
        ">... \"my eyes are adjusting too slow\"\r\n>... <size=200%><color=red>\"adjusting to what\"</color></size>\r\n>... [breathing]",
        ">... \"my comms are echoing\"\r\n>... <size=200%><color=red>\"before I speak\"</color></size>\r\n>... [carrier wave]",
        ">... \"the visor's fogging\"\r\n>... <size=200%><color=red>\"on the outside\"</color></size>\r\n>... [hiss]",
        ">... \"a tone in my ear\"\r\n>... <size=200%><color=red>\"my chip says my ear is fine\"</color></size>\r\n>... [hum]",
        ">... \"my mouth's dry\"\r\n>... <size=200%><color=red>\"only on one side\"</color></size>\r\n>... [breathing]",
        ">... \"the projector's hum is in my teeth\"\r\n>... <size=200%><color=red>\"my teeth hum back\"</color></size>\r\n>... [hum]",
        ">... \"there's static in my visor\"\r\n>... <size=200%><color=red>\"the visor's off\"</color></size>\r\n>... [static]",
        ">... \"smell of ozone, west\"\r\n>... <size=200%><color=red>\"smell of ozone in my throat\"</color></size>\r\n>... [breathing]",
        ">... \"the suit's cooling too well\"\r\n>... <size=200%><color=red>\"the suit's not on\"</color></size>\r\n>... [hiss]",
        ">... \"my legs feel wrong\"\r\n>... <size=200%><color=red>\"the dust feels them too\"</color></size>\r\n>... [boot crunch]",
        ">... \"prompt's blinking faster than my heart\"\r\n>... <size=200%><color=red>\"now in step\"</color></size>\r\n>... [keyboard]",
        ">... \"keying {COMMAND}\"\r\n>... <size=200%><color=red>\"keyed it before I keyed it\"</color></size>\r\n>... [keyboard]",
        ">... \"the cursor's blinking\"\r\n>... <size=200%><color=red>\"the cursor knows the next letter\"</color></size>\r\n>... [keyboard]",
        ">... \"display's flickering\"\r\n>... <size=200%><color=red>\"between {COMMAND} and a name\"</color></size>\r\n>... [hiss]",
        ">... \"command field's grayed out\"\r\n>... <size=200%><color=red>\"still accepting\"</color></size>\r\n>... [keyboard]",
        ">... \"there's no enter key\"\r\n>... <size=200%><color=red>\"there's been no enter all along\"</color></size>\r\n>... [keyboard]",
        ">... \"the terminal's asking for my name\"\r\n>... <size=200%><color=red>\"it spelled it first\"</color></size>\r\n>... [keyboard]",
        ">... \"completed {COMMAND}\"\r\n>... <size=200%><color=red>\"the screen says I haven't started\"</color></size>\r\n>... [keyboard]",
        ">... \"the prompt's listening\"\r\n>... <size=200%><color=red>\"to my chip, not my hands\"</color></size>\r\n>... [breathing]",
        ">... \"keystroke registered\"\r\n>... <size=200%><color=red>\"by which keyboard\"</color></size>\r\n>... [keyboard]",
        ">... \"the screen's mirrored\"\r\n>... <size=200%><color=red>\"my reflection's typing different\"</color></size>\r\n>... [keyboard]",
        ">... \"backspace doesn't work\"\r\n>... <size=200%><color=red>\"nothing can be unkeyed here\"</color></size>\r\n>... [keyboard]",
        ">... \"the keyboard's not connected\"\r\n>... <size=200%><color=red>\"input still accepted\"</color></size>\r\n>... [keyboard]",
        ">... \"{COMMAND} typed itself\"\r\n>... <size=200%><color=red>\"in my keystroke pattern\"</color></size>\r\n>... [keyboard]",
        ">... \"the prompt has my name on it\"\r\n>... <size=200%><color=red>\"with a different spelling\"</color></size>\r\n>... [breathing]",
        ">... \"transfer at 12\"\r\n>... <size=200%><color=red>\"transfer was at 18 a moment ago\"</color></size>\r\n>... [hum]",
        ">... \"countdown desynced\"\r\n>... <size=200%><color=red>\"between the two clocks on my arm\"</color></size>\r\n>... [no signal]",
        ">... \"transfer rate stable\"\r\n>... <size=200%><color=red>\"stable at the wrong number\"</color></size>\r\n>... [hum]",
        ">... \"thirty seconds left\"\r\n>... <size=200%><color=red>\"forty seconds ago\"</color></size>\r\n>... [breathing]",
        ">... \"tether reads 0%\"\r\n>... <size=200%><color=red>\"still here\"</color></size>\r\n>... [no signal]",
        ">... \"transfer phase three\"\r\n>... <size=200%><color=red>\"phase three of five\"</color></size>\r\n>... [hum]",
        ">... \"the clock's frozen\"\r\n>... <size=200%><color=red>\"so are my hands\"</color></size>\r\n>... [hiss]",
        ">... \"final stretch\"\r\n>... <size=200%><color=red>\"the stretch is what's final\"</color></size>\r\n>... [breathing]",
        ">... \"tether tone steady\"\r\n>... <size=200%><color=red>\"steady at B-flat\"</color></size>\r\n>... [hum]",
        ">... \"transfer overhead 1.6%\"\r\n>... <size=200%><color=red>\"the 1.6% has a voice\"</color></size>\r\n>... [carrier wave]",
        ">... \"clock at 4 seconds and counting\"\r\n>... <size=200%><color=red>\"counting in the wrong direction\"</color></size>\r\n>... [hum]",
        ">... \"transfer pause\"\r\n>... <size=200%><color=red>\"requested by destination\"</color></size>\r\n>... [hiss]",
        ">... \"warp window opening\"\r\n>... <size=200%><color=red>\"on the wrong side\"</color></size>\r\n>... [hum]",
        ">... \"warp window closed\"\r\n>... <size=200%><color=red>\"we're still inside\"</color></size>\r\n>... [carrier wave]",
        ">... \"tether jolted\"\r\n>... <size=200%><color=red>\"by something with hands\"</color></size>\r\n>... [hum]",
        ">... \"contact, ridge\"\r\n>... <size=200%><color=red>\"contact, all ridges\"</color></size>\r\n>... [growl]",
        ">... \"hold formation\"\r\n>... <size=200%><color=red>\"formation already broken\"</color></size>\r\n>... [boot rush]",
        ">... \"I see one\"\r\n>... <size=200%><color=red>\"I see all of them\"</color></size>\r\n>... [low rumble]",
        ">... \"silhouette, north\"\r\n>... <size=200%><color=red>\"silhouette wearing me\"</color></size>\r\n>... [hiss]",
        ">... \"open fire on the ridge\"\r\n>... <size=200%><color=red>\"the ridge fires first\"</color></size>\r\n>... [growl]",
        ">... \"down to three mags\"\r\n>... <size=200%><color=red>\"down to two\"</color></size>\r\n>... [tool clatter]",
        ">... \"target dropped\"\r\n>... <size=200%><color=red>\"target was nothing\"</color></size>\r\n>... [hiss]",
        ">... \"they're coming uphill\"\r\n>... <size=200%><color=red>\"uphill in every direction\"</color></size>\r\n>... [boot rush]",
        ">... \"they're slowing\"\r\n>... <size=200%><color=red>\"because we're slowing\"</color></size>\r\n>... [hiss]",
        ">... \"hostile down\"\r\n>... <size=200%><color=red>\"got back up wearing my coat\"</color></size>\r\n>... [growl]",
        ">... \"reloading\"\r\n>... <size=200%><color=red>\"into a chamber with no mag\"</color></size>\r\n>... [tool clatter]",
        ">... \"the gunfire echoes\"\r\n>... <size=200%><color=red>\"before each shot\"</color></size>\r\n>... [hiss]",
        ">... \"perimeter clear\"\r\n>... <size=200%><color=red>\"perimeter is a wall\"</color></size>\r\n>... [breathing]",
        ">... \"down, one of ours\"\r\n>... <size=200%><color=red>\"who\"</color></size>\r\n>... [breathing]",
        ">... \"contact close\"\r\n>... <size=200%><color=red>\"on the platform\"</color></size>\r\n>... [boot rush]",
        ">... \"final hand on the projector\"\r\n>... <size=200%><color=red>\"a fifth hand\"</color></size>\r\n>... [hum]",
        ">... \"warp engaged\"\r\n>... <size=200%><color=red>\"not by us\"</color></size>\r\n>... [carrier wave]",
        ">... \"extracting\"\r\n>... <size=200%><color=red>\"to a different drop point\"</color></size>\r\n>... [hum]",
        ">... \"warp tone in two\"\r\n>... <size=200%><color=red>\"in negative two\"</color></size>\r\n>... [hum]",
        ">... \"the projector is shaking\"\r\n>... <size=200%><color=red>\"the projector is laughing\"</color></size>\r\n>... [hum]",
        ">... \"hands count: four\"\r\n>... <size=200%><color=red>\"hands count: nine\"</color></size>\r\n>... [breathing]",
        ">... \"extraction in five\"\r\n>... <size=200%><color=red>\"extraction in always\"</color></size>\r\n>... [hum]",
        ">... \"team status: green\"\r\n>... <size=200%><color=red>\"team status: gold, like the dust\"</color></size>\r\n>... [breathing]",
        ">... \"warping in\"\r\n>... <size=200%><color=red>\"in\"</color></size>\r\n>... [hum]",
        ">... \"closing eyes for the snap\"\r\n>... <size=200%><color=red>\"my eyes don't close anymore\"</color></size>\r\n>... [hiss]",
        ">... \"feet under me\"\r\n>... <size=200%><color=red>\"feet still in the desert\"</color></size>\r\n>... [carrier wave]",
        ">... \"the warp pulled\"\r\n>... <size=200%><color=red>\"toward the wrong side of the gate\"</color></size>\r\n>... [hum]",
        ">... \"counting four masks\"\r\n>... <size=200%><color=red>\"five faces under them\"</color></size>\r\n>... [breathing]",
        ">... \"the platform's letting us go\"\r\n>... <size=200%><color=red>\"letting go of one of us\"</color></size>\r\n>... [carrier wave]",
        ">... \"warp complete\"\r\n>... <size=200%><color=red>\"complete is the wrong word\"</color></size>\r\n>... [hum]",
        ">... \"who packed the rations\"\r\n>... <size=200%><color=red>\"there's an extra packet\"</color></size>\r\n>... [breathing]",
        ">... \"first time?\"\r\n>... \"first time. <size=200%><color=red>and the second\"</color></size>\r\n>... [breathing]",
        ">... \"who's on point\"\r\n>... <size=200%><color=red>\"the platform decided\"</color></size>\r\n>... [boot crunch]",
        ">... \"after this we're on leave\"\r\n>... <size=200%><color=red>\"we're never quite back\"</color></size>\r\n>... [breathing]",
        ">... \"team count: four\"\r\n>... <size=200%><color=red>\"team count: three plus the platform\"</color></size>\r\n>... [carrier wave]",
        ">... \"my coat still has the dust\"\r\n>... <size=200%><color=red>\"my coat is the dust\"</color></size>\r\n>... [silence]",
        ">... \"dreamed the {COMMAND} prompt\"\r\n>... <size=200%><color=red>\"woke up keying it\"</color></size>\r\n>... [breathing]",
        ">... \"didn't sleep last night\"\r\n>... <size=200%><color=red>\"my chip says I did, eight hours\"</color></size>\r\n>... [breathing]",
        ">... \"can't remember dropping\"\r\n>... <size=200%><color=red>\"can remember coming back\"</color></size>\r\n>... [silence]",
        ">... \"the briefing said one terminal\"\r\n>... <size=200%><color=red>\"there's one on every drop\"</color></size>\r\n>... [carrier wave]",
    };
    #endregion

    #region Researchers — Project Insight, MWP, membranes, datacubes, Cretasium 77a
    public static readonly List<string> AlphaTerminalCommandIntel_Researchers = new()
    {
        ">... \"membrane stable. topology held.\"\r\n>... <size=200%><color=red>\"the projector did not consult me\"</color></size>\r\n>... [pen on paper]",
        ">... \"Project Insight bench note re: {COMMAND}\"\r\n>... <size=200%><color=red>\"do not log this\"</color></size>\r\n>... [tap drip]",
        ">... \"quantum frequency drift: 0.04 Hz\"\r\n>... <size=200%><color=red>\"acceptable: 0.00 Hz\"</color></size>\r\n>... [HVAC hum]",
        ">... \"we have left earth\"\r\n>... <size=200%><color=red>\"earth has left us\"</color></size>\r\n>... [pen on paper]",
        ">... [garbled]\r\n>... \"...the gate accepted {COMMAND}, not the operator...\"\r\n>... <size=200%><color=red>[Encryption checksum mismatch. Contact your IT administrator]</color></size>",
        ">... \"Cretasium 77a registers in the dust\"\r\n>... <size=200%><color=red>\"the dimension is the alloy\"</color></size>\r\n>... [page turn]",
        ">... \"the ridgeline structures cast Cretasium glint\"\r\n>... <size=200%><color=red>\"or thirty-eight meters\"</color></size>\r\n>... [pen on paper]",
        ">... \"the operator becomes the projector\"\r\n>... <size=200%><color=red>\"this is the design\"</color></size>\r\n>... [silence]",
        ">... \"static dimension is a misnomer\"\r\n>... <size=200%><color=red>\"prefer 'patient'\"</color></size>\r\n>... [pen on paper]",
        ">... \"no entropy reading at the destination\"\r\n>... <size=200%><color=red>\"entropy reading is the destination\"</color></size>\r\n>... [HVAC hum]",
        ">... \"projection is not travel\"\r\n>... <size=200%><color=red>\"granted by what\"</color></size>\r\n>... [tape hiss]",
        ">... \"if I name the destination, it answers\"\r\n>... <size=200%><color=red>\"it has answered\"</color></size>\r\n>... [no audio]",
        ">... datacube address space: 622,811\r\n>... <size=200%><color=red>last entry not authored</color></size>\r\n>... [pen on paper]",
        ">... \"the gate is not a door\"\r\n>... <size=200%><color=red>\"answered by {COMMAND}\"</color></size>\r\n>... [chalk on board]",
        ">... \"the cube remembers the operator\"\r\n>... <size=200%><color=red>\"this asymmetry is the technology\"</color></size>\r\n>... [pen on paper]",
        ">... \"...{COMMAND}...{COMMAND}...{COMMAND}...\"\r\n>... <size=200%><color=red>\"author field empty\"</color></size>\r\n>... [tape hiss]",
        ">... \"the projector hums in B-flat\"\r\n>... <size=200%><color=red>\"B-flat is the membrane's name\"</color></size>\r\n>... [hum]",
        ">... \"the destination has weather\"\r\n>... <size=200%><color=red>\"the destination has been waiting\"</color></size>\r\n>... [tape hiss]",
        ">... tether amplitude 1.000\r\n>... tether amplitude <size=200%><color=red>1.001</color></size>\r\n>... [HVAC hum]",
        ">... \"page 81: the gate, with hands\"\r\n>... \"page 82: the gate, with <size=200%><color=red>my hands</color></size>\"\r\n>... [pen on paper]",
        ">... \"the membrane is stable\"\r\n>... <size=200%><color=red>\"someone has been stabilizing it\"</color></size>\r\n>... [pen on paper]",
        ">... \"do you remember signing this\"\r\n>... <size=200%><color=red>\"the handwriting is yours\"</color></size>\r\n>... [silence]",
        ">... \"transfer duration scales tier-linear\"\r\n>... <size=200%><color=red>\"unless observed\"</color></size>\r\n>... [HVAC hum]",
        ">... \"...the cube is a key for a door not yet built...\"\r\n>... \"...{COMMAND} is the door...\"\r\n>... <size=200%><color=red>[Encryption checksum mismatch. Contact your IT administrator]</color></size>",
        ">... \"specimen R-901: dust\"\r\n>... <size=200%><color=red>\"specimen R-901: composing\"</color></size>\r\n>... [page turn]",
        ">... \"this note is not in my handwriting\"\r\n>... <size=200%><color=red>\"both are true\"</color></size>\r\n>... [pen on paper]",
        ">... \"do not address the cube directly\"\r\n>... <size=200%><color=red>\"the cube is addressing you\"</color></size>\r\n>... [silence]",
        ">... transfer success rate: 99.4%\r\n>... transfer success rate: <size=200%><color=red>not measurable</color></size>\r\n>... [HVAC hum]",
        ">... \"the MWP retains audio\"\r\n>... <size=200%><color=red>\"the audio is in our voices\"</color></size>\r\n>... [tape hiss]",
        ">... \"do not call them dimensions\"\r\n>... <size=200%><color=red>\"call them what they call themselves\"</color></size>\r\n>... [chalk on board]",
        ">... \"I have not slept in three weeks\"\r\n>... <size=200%><color=red>\"yet I remember sleeping\"</color></size>\r\n>... [tape hiss]",
        ">... \"the operator does not consent\"\r\n>... <size=200%><color=red>\"the operator does not need to\"</color></size>\r\n>... [silence]",
        ">... \"if you read this, the cube was opened\"\r\n>... <size=200%><color=red>\"hello, reader\"</color></size>\r\n>... [pen on paper]",
        ">... [garbled]\r\n>... <size=200%><color=red>\"...returns the operator [different]\"</color></size>\r\n>... [tape hiss]",
        ">... \"projection theory makes a guarantee\"\r\n>... <size=200%><color=red>\"to the same address\"</color></size>\r\n>... [chalk on board]",
        ">... \"the desert is not new\"\r\n>... <size=200%><color=red>\"older than the species that wrote it\"</color></size>\r\n>... [tape hiss]",
        ">... \"membrane interior shows no decay\"\r\n>... <size=200%><color=red>\"interior shows attention\"</color></size>\r\n>... [silence]",
        ">... \"transfer phase 3: anchored\"\r\n>... <size=200%><color=red>\"anchor relocated to operator\"</color></size>\r\n>... [HVAC hum]",
        ">... \"the data cube weighs nothing\"\r\n>... <size=200%><color=red>\"my hand weighs less holding it\"</color></size>\r\n>... [silence]",
        ">... [REDACTED]\r\n>... <size=200%><color=red>\"un-redacted by specimen\"</color></size>\r\n>... [page turn]",
        ">... \"if the prompt blinks, do not press\"\r\n>... <size=200%><color=red>\"if the prompt blinks, the press has happened\"</color></size>\r\n>... [pen on paper]",
        ">... \"the projector hummed without power\"\r\n>... <size=200%><color=red>\"the hum did not change\"</color></size>\r\n>... [hum]",
        ">... cube weight: 0.0 g\r\n>... cube weight: <size=200%><color=red>operator-dependent</color></size>\r\n>... [HVAC hum]",
        ">... \"...the membrane was named before our species existed...\"\r\n>... \"...the name is {COMMAND}...\"\r\n>... <size=200%><color=red>[Encryption checksum mismatch. Contact your IT administrator]</color></size>",
        ">... \"Cretasium 77a sample melted\"\r\n>... <size=200%><color=red>\"into a smaller sample\"</color></size>\r\n>... [page turn]",
        ">... \"I dreamed I keyed {COMMAND}\"\r\n>... <size=200%><color=red>\"I am no longer dreaming\"</color></size>\r\n>... [tape hiss]",
        ">... \"my pupils dilate at the projector hum\"\r\n>... <size=200%><color=red>\"so does the projector\"</color></size>\r\n>... [hum]",
        ">... \"1.6% transfer overhead unaccounted\"\r\n>... <size=200%><color=red>\"1.6% is the operator\"</color></size>\r\n>... [HVAC hum]",
        ">... \"recovered fragment, source: cube 41\"\r\n>... <size=200%><color=red>\"recording dated next year\"</color></size>\r\n>... [tape hiss]",
        ">... \"this is bigger than the company\"\r\n>... <size=200%><color=red>\"the company knows\"</color></size>\r\n>... [chalk on board]",
        ">... \"do not pity the destination\"\r\n>... <size=200%><color=red>\"the destination is not patient\"</color></size>\r\n>... [pen on paper]",
        ">... \"the air in the lab tastes like sand\"\r\n>... <size=200%><color=red>\"the sand is here\"</color></size>\r\n>... [silence]",
        ">... \"telemetry feed: nominal\"\r\n>... <size=200%><color=red>\"telemetry feed is the operator\"</color></size>\r\n>... [HVAC hum]",
        ">... \"the cube speaks four words\"\r\n>... <size=200%><color=red>\"the fourth is yours\"</color></size>\r\n>... [tape hiss]",
        ">... \"page 142: a desert with no ground\"\r\n>... \"page 143: a desert with no <size=200%><color=red>edges</color></size>\"\r\n>... [pen on paper]",
        ">... \"transfer time is local-relative\"\r\n>... <size=200%><color=red>\"transfer time is the destination's choice\"</color></size>\r\n>... [pen on paper]",
        ">... \"the airflow tastes warm\"\r\n>... <size=200%><color=red>\"the airflow tastes like a mouth\"</color></size>\r\n>... [airflow]",
        ">... \"projection efficiency 100.0%\"\r\n>... <size=200%><color=red>\"projection efficiency 100.4%\"</color></size>\r\n>... [HVAC hum]",
        ">... \"the audio in the cube is not over\"\r\n>... <size=200%><color=red>\"by the cube\"</color></size>\r\n>... [tape hiss]",
        ">... \"do not allow operative knowledge of {COMMAND}\"\r\n>... <size=200%><color=red>\"operative is the {COMMAND}\"</color></size>\r\n>... [page turn]",
        ">... \"the topology held\"\r\n>... <size=200%><color=red>\"we did not\"</color></size>\r\n>... [tape hiss]",
        ">... \"reading the prompt aloud produces a copy\"\r\n>... <size=200%><color=red>\"do not read the prompt aloud\"</color></size>\r\n>... [keyboard]",
        ">... \"projection ledger discrepancy: 1\"\r\n>... <size=200%><color=red>\"the missing operator is the ledger\"</color></size>\r\n>... [HVAC hum]",
        ">... \"...we have always projected here...\"\r\n>... <size=200%><color=red>\"...by something other than us...\"</color></size>\r\n>... [tape hiss]",
        ">... \"all projection-staff sleep onset 04:00\"\r\n>... <size=200%><color=red>\"the destination keeps a schedule\"</color></size>\r\n>... [chalk on board]",
        ">... \"if the prompt asks for confirmation, decline\"\r\n>... <size=200%><color=red>\"declining is also a confirmation\"</color></size>\r\n>... [pen on paper]",
        ">... \"door opened from outside\"\r\n>... <size=200%><color=red>\"the dust did it\"</color></size>\r\n>... [door servo]",
        ">... \"tether reading nominal\"\r\n>... <size=200%><color=red>\"there was no tether\"</color></size>\r\n>... [HVAC hum]",
        ">... \"...the project insight is not insight...\"\r\n>... <size=200%><color=red>\"...the looking is mutual...\"</color></size>\r\n>... [tape hiss]",
        ">... \"page 247: the operator with two shadows\"\r\n>... \"page 248: the operator with <size=200%><color=red>no shadows</color></size>\"\r\n>... [pen on paper]",
        ">... \"if you hear this, you keyed {COMMAND}\"\r\n>... <size=200%><color=red>\"if you hear this, you are not alone\"</color></size>\r\n>... [tape hiss]",
        ">... \"the projector accepts non-operator input\"\r\n>... <size=200%><color=red>\"input source: dust\"</color></size>\r\n>... [silence]",
        ">... \"every projection cycle: 1 operator returns\"\r\n>... <size=200%><color=red>\"plus 0.04\"</color></size>\r\n>... [HVAC hum]",
        ">... \"...{COMMAND} unlocks the second cube...\"\r\n>... \"...there is no second cube on file...\"\r\n>... <size=200%><color=red>[Encryption checksum mismatch. Contact your IT administrator]</color></size>",
        ">... \"if you can read this, you are inside\"\r\n>... <size=200%><color=red>\"inside what was waiting\"</color></size>\r\n>... [chalk on board]",
        ">... \"the desert is not the destination\"\r\n>... <size=200%><color=red>\"the destination is below\"</color></size>\r\n>... [pen on paper]",
        ">... \"my last entry was nine days ago\"\r\n>... <size=200%><color=red>\"both are dated today\"</color></size>\r\n>... [silence]",
        ">... \"the equation balances\"\r\n>... <size=200%><color=red>\"by removing the operator\"</color></size>\r\n>... [HVAC hum]",
        ">... \"the MWP is older than Project Insight\"\r\n>... <size=200%><color=red>\"older than the company that named it\"</color></size>\r\n>... [tape hiss]",
        ">... \"the gate goes both ways\"\r\n>... <size=200%><color=red>\"the other way is open\"</color></size>\r\n>... [chalk on board]",
        ">... \"projector resonance: 4.41 Hz\"\r\n>... <size=200%><color=red>\"resonance authored elsewhere\"</color></size>\r\n>... [HVAC hum]",
        ">... \"the MWP has a serial number\"\r\n>... <size=200%><color=red>\"older than serialization\"</color></size>\r\n>... [pen on paper]",
        ">... \"projector log shows no idle period\"\r\n>... <size=200%><color=red>\"the projector does not idle\"</color></size>\r\n>... [HVAC hum]",
        ">... \"the projector cools on warp engage\"\r\n>... <size=200%><color=red>\"because the operator warms\"</color></size>\r\n>... [hum]",
        ">... \"projector vibration spectrum, 18 peaks\"\r\n>... <size=200%><color=red>\"19 if you stand near\"</color></size>\r\n>... [HVAC hum]",
        ">... \"the MWP refused a calibration cycle\"\r\n>... <size=200%><color=red>\"by name\"</color></size>\r\n>... [silence]",
        ">... \"projector schematic, page 41: missing\"\r\n>... <size=200%><color=red>\"page 41 is the dimension\"</color></size>\r\n>... [page turn]",
        ">... \"the projector predicts the operator\"\r\n>... <size=200%><color=red>\"the operator becomes the prediction\"</color></size>\r\n>... [HVAC hum]",
        ">... \"membrane scan: smooth\"\r\n>... <size=200%><color=red>\"smooth has a texture\"</color></size>\r\n>... [pen on paper]",
        ">... \"the topology is closed\"\r\n>... <size=200%><color=red>\"closed around the operator\"</color></size>\r\n>... [chalk on board]",
        ">... \"membrane shows a seam\"\r\n>... <size=200%><color=red>\"seam stitched from the other side\"</color></size>\r\n>... [pen on paper]",
        ">... \"projection geometry: euclidean\"\r\n>... <size=200%><color=red>\"only on our side\"</color></size>\r\n>... [HVAC hum]",
        ">... \"the membrane stores audio\"\r\n>... <size=200%><color=red>\"the audio is older than the operator\"</color></size>\r\n>... [tape hiss]",
        ">... \"topology held this drop\"\r\n>... <size=200%><color=red>\"held us, not the projection\"</color></size>\r\n>... [silence]",
        ">... \"Cretasium 77a in operator hair samples\"\r\n>... <size=200%><color=red>\"prior to deployment\"</color></size>\r\n>... [pen on paper]",
        ">... \"the dust accepts no preservation\"\r\n>... <size=200%><color=red>\"the dust prefers to be in the operator\"</color></size>\r\n>... [page turn]",
        ">... \"Cretasium 77a, weight: 0.04 g\"\r\n>... <size=200%><color=red>\"per operator-cycle\"</color></size>\r\n>... [HVAC hum]",
        ">... \"sample 0042: dust\"\r\n>... <size=200%><color=red>\"sample 0042: speaking\"</color></size>\r\n>... [tape hiss]",
        ">... \"dust melts to dust\"\r\n>... <size=200%><color=red>\"smaller, warmer, ours\"</color></size>\r\n>... [silence]",
        ">... \"Cretasium 77a in the air filters\"\r\n>... <size=200%><color=red>\"the filters are upstream of the desert\"</color></size>\r\n>... [HVAC hum]",
        ">... \"cube 41 catalogued\"\r\n>... <size=200%><color=red>\"by the cube\"</color></size>\r\n>... [pen on paper]",
        ">... \"cube weight drifts with temperature\"\r\n>... <size=200%><color=red>\"with the operator's temperature\"</color></size>\r\n>... [HVAC hum]",
        ">... \"data cube contents: empty\"\r\n>... <size=200%><color=red>\"empty of us\"</color></size>\r\n>... [page turn]",
        ">... \"cube is unbreakable\"\r\n>... <size=200%><color=red>\"because it broke us\"</color></size>\r\n>... [silence]",
        ">... \"datacube archive index unstable\"\r\n>... <size=200%><color=red>\"the index writes us\"</color></size>\r\n>... [HVAC hum]",
        ">... \"...cube 79 returned a second cube...\"\r\n>... \"...the second cube returned the operator...\"\r\n>... <size=200%><color=red>[Encryption checksum mismatch. Contact your IT administrator]</color></size>",
        ">... \"third night without sleep\"\r\n>... <size=200%><color=red>\"yet I remember dreaming the desert\"</color></size>\r\n>... [pen on paper]",
        ">... \"the lab clock drifts when I look\"\r\n>... <size=200%><color=red>\"when I do not, more\"</color></size>\r\n>... [HVAC hum]",
        ">... \"my notes have hours I did not work\"\r\n>... <size=200%><color=red>\"and entries I do not remember writing\"</color></size>\r\n>... [pen on paper]",
        ">... \"coffee no longer wakes me\"\r\n>... <size=200%><color=red>\"the projector hum does\"</color></size>\r\n>... [hum]",
        ">... \"my reflection is delayed by a beat\"\r\n>... <size=200%><color=red>\"by a beat of the projector\"</color></size>\r\n>... [silence]",
        ">... \"the operator goes nowhere\"\r\n>... <size=200%><color=red>\"the destination comes here\"</color></size>\r\n>... [pen on paper]",
        ">... \"we built the projector\"\r\n>... <size=200%><color=red>\"the projector built us back\"</color></size>\r\n>... [chalk on board]",
        ">... \"the gate has two sides\"\r\n>... <size=200%><color=red>\"both are this side\"</color></size>\r\n>... [silence]",
        ">... \"the operator chooses the destination\"\r\n>... <size=200%><color=red>\"the destination chooses the operator\"</color></size>\r\n>... [pen on paper]",
        ">... \"membrane has a single side\"\r\n>... <size=200%><color=red>\"we are that side\"</color></size>\r\n>... [chalk on board]",
        ">... \"...the gate spoke {COMMAND} before our records...\"\r\n>... \"...records updated retroactively...\"\r\n>... <size=200%><color=red>[Encryption checksum mismatch. Contact your IT administrator]</color></size>",
        ">... \"key {COMMAND} once\"\r\n>... <size=200%><color=red>\"the second key is the operator\"</color></size>\r\n>... [pen on paper]",
        ">... \"do not write {COMMAND} in full\"\r\n>... <size=200%><color=red>\"writing it shortens us\"</color></size>\r\n>... [page turn]",
        ">... \"{COMMAND} is not a command\"\r\n>... <size=200%><color=red>\"it is a recognition\"</color></size>\r\n>... [silence]",
    };
    #endregion

    #region Warden / system — WRDN, BIOCOM, EBDT, HearSay; corrupted command echoes
    public static readonly List<string> AlphaTerminalCommandIntel_WardenSystem = new()
    {
        ">... WRDN: {COM<size=200%><color=red>--MAND--</color></size>}\r\n>... operative response timeout\r\n>... [static]",
        ">... WRDN: <size=200%><color=red>PROJECTED</color></size>\r\n>... destination unspecified\r\n>... [carrier wave]",
        ">... \"projection log entry: {COMMAND}\"\r\n>... \"projection log entry: <size=200%><color=red>{COMMAND}{COMMAND}</color></size>\"\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... checksum mismatch on operator\r\n>... <size=200%><color=red>operator un-checksummed</color></size>\r\n>... [warning tone]",
        ">... WRDN: <size=200%><color=red>COMPLIED</color></size>\r\n>... operative ahead of command\r\n>... [feedback]",
        ">... \"the gate accepted {COMMAND}\"\r\n>... \"the gate <size=200%><color=red>preferred</color></size> {COMMAND}\"\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: <size=200%><color=red>UNANCHORED</color></size>\r\n>... tether: not measurable\r\n>... [no signal]",
        ">... authorized by tier 5\r\n>... <size=200%><color=red>tier 5 has no record</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... routing loop confirmed\r\n>... <size=200%><color=red>source is the operator</color></size>\r\n>... [warning tone]",
        ">... WRDN: T-T-T<size=200%><color=red>RANSFER</color></size>\r\n>... operative consent: implied\r\n>... [feedback]",
        ">... \"who keyed the command\"\r\n>... \"who keyed the <size=200%><color=red>command</color></size>\"\r\n>... [recording loops]",
        ">... WRDN: {COMMAND}\r\n>... receiver: <size=200%><color=red>none configured</color></size>\r\n>... [feedback]",
        ">... operator: [redacted]\r\n>... command: <size=200%><color=red>{COMMAND}</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... cascading reset attempted\r\n>... cascading reset propagated to <size=200%><color=red>operative cognition</color></size>\r\n>... [warning tone]",
        ">... 0xC0DE 0xC0DE 0xC0DE\r\n>... <size=200%><color=red>0x{COMMAND}</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... \"hand on the projector\"\r\n>... \"<size=200%><color=red>whose hand</color></size>\"\r\n>... [recording loops]",
        ">... WRDN: <size=200%><color=red>RELEASED</color></size>\r\n>... operative position: drifting\r\n>... [static]",
        ">... two operatives bearing same chip ID\r\n>... <size=200%><color=red>resolve by destination</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... echo source: gate\r\n>... echo source: <size=200%><color=red>operator</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: SCAN<size=200%><color=red>NED</color></size>\r\n>... operator inventory: +1 unaccounted\r\n>... [feedback]",
        ">... air composition: nominal\r\n>... air composition: <size=200%><color=red>74% Cretasium 77a</color></size>\r\n>... [airflow]",
        ">... WRDN: {COMMAND}\r\n>... WRDN: {COMMAND}<size=200%><color=red>{COMMAND}</color></size>\r\n>... [feedback]",
        ">... \"the desert is on the radio\"\r\n>... \"the desert is on the <size=200%><color=red>radio</color></size>\"\r\n>... [carrier wave]",
        ">... authorization revoked\r\n>... <size=200%><color=red>command continued without authorization</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: PROJECT<size=200%><color=red>OR</color></size>\r\n>... operator subsumed\r\n>... [feedback]",
        ">... heart rate 92 BPM\r\n>... heart rate <size=200%><color=red>92 BPM, both</color></size>\r\n>... [warning tone]",
        ">... \"transfer at 88%\"\r\n>... \"<size=200%><color=red>transfer is at us</color></size>\"\r\n>... [recording loops]",
        ">... WRDN: TETHER\r\n>... WRDN: <size=200%><color=red>TETHERED ELSEWHERE</color></size>\r\n>... [no signal]",
        ">... sealed by tier 5\r\n>... <size=200%><color=red>sealed from inside</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... operator cognition flagged\r\n>... operator cognition <size=200%><color=red>uploaded</color></size>\r\n>... [warning tone]",
        ">... WRDN: NOT {COMMAND}\r\n>... WRDN: <size=200%><color=red>NEVER {COMMAND}</color></size>\r\n>... [feedback]",
        ">... \"the gate hummed in two voices\"\r\n>... \"the gate hummed in <size=200%><color=red>your voice</color></size>\"\r\n>... [hum]",
        ">... record sealed\r\n>... <size=200%><color=red>record speaking</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: <size=200%><color=red>COMPLIANCE NOT REQUIRED</color></size>\r\n>... operator already compliant\r\n>... [feedback]",
        ">... gate ACK\r\n>... <size=200%><color=red>gate has ACKnowledged us first</color></size>\r\n>... [warning tone]",
        ">... WRDN: {COMMAND}\r\n>... WRDN: <size=200%><color=red>{COMMAND}, again</color></size>\r\n>... [feedback]",
        ">... \"if you can read this, the projector worked\"\r\n>... \"if you can read this, the projector <size=200%><color=red>worked us</color></size>\"\r\n>... [recording loops]",
        ">... operator clock: +40s\r\n>... mission clock: <size=200%><color=red>0s</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... entries: 622,811\r\n>... entries: <size=200%><color=red>622,813</color></size>\r\n>... [warning tone]",
        ">... WRDN: SCAN COMPLETE\r\n>... WRDN: SCAN <size=200%><color=red>OPEN</color></size>\r\n>... [feedback]",
        ">... \"the chronometer is normal\"\r\n>... \"the chronometer is <size=200%><color=red>not</color></size>\"\r\n>... [hum]",
        ">... cube ID: 0x4441\r\n>... cube ID: <size=200%><color=red>operator-derived</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: <size=200%><color=red>UN-{COMMAND}</color></size>\r\n>... operative reverted\r\n>... [feedback]",
        ">... lockdown initiated\r\n>... <size=200%><color=red>lockdown is the operator</color></size>\r\n>... [warning tone]",
        ">... \"the destination is stable\"\r\n>... \"the destination is <size=200%><color=red>still</color></size>\"\r\n>... [hum]",
        ">... cancelled by operator\r\n>... <size=200%><color=red>cancelled by destination</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: TRANSFER <size=200%><color=red>OPEN</color></size>\r\n>... operator reachable\r\n>... [feedback]",
        ">... MWP serial <size=200%><color=red>0000</color></size>\r\n>... earlier instance not in record\r\n>... [warning tone]",
        ">... \"open sky on the radio\"\r\n>... \"open sky on the <size=200%><color=red>radio</color></size>\"\r\n>... [wind]",
        ">... {COMMAND} executed at projection bay 1\r\n>... <size=200%><color=red>{COMMAND} executed at no bay</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: H-H-H<size=200%><color=red>OLD</color></size>\r\n>... operator position: unknown\r\n>... [static]",
        ">... new patch deployed\r\n>... <size=200%><color=red>patch source: gate</color></size>\r\n>... [warning tone]",
        ">... \"the WRDN repeated {COMMAND} 41 times\"\r\n>... \"the WRDN repeated {COMMAND} <size=200%><color=red>22 times</color></size>\"\r\n>... [carrier wave]",
        ">... WRDN: {COMMAND}<size=200%><color=red>--ed</color></size>\r\n>... operator past tense\r\n>... [feedback]",
        ">... \"backdoor terminal not in inventory\"\r\n>... <size=200%><color=red>terminal in operator inventory</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... pulse rate 92 BPM\r\n>... pulse rate <size=200%><color=red>synchronized</color></size>\r\n>... [warning tone]",
        ">... \"return\"\r\n>... <size=200%><color=red>\"do not return\"</color></size>\r\n>... [feedback]",
        ">... \"the gate is humming a song\"\r\n>... \"the song was first sung in <size=200%><color=red>2057</color></size>\"\r\n>... [hum]",
        ">... operator returned: 4\r\n>... operator returned: <size=200%><color=red>4.04</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: <size=200%><color=red>{COMMAND}_DONE</color></size>\r\n>... result: pending\r\n>... [feedback]",
        ">... handshake initiated\r\n>... <size=200%><color=red>handshake re-initiated by gate</color></size>\r\n>... [warning tone]",
        ">... \"the cube is heavy\"\r\n>... \"the cube is <size=200%><color=red>weighing the operator</color></size>\"\r\n>... [hum]",
        ">... 4.0s of telemetry missing\r\n>... <size=200%><color=red>4.0s of operator missing</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: PROJECTED <size=200%><color=red>OUT</color></size>\r\n>... operator return: unscheduled\r\n>... [feedback]",
        ">... ambient temperature 39°C\r\n>... ambient temperature <size=200%><color=red>desert</color></size>\r\n>... [warning tone]",
        ">... \"this is a recording\"\r\n>... \"this is a <size=200%><color=red>recording of you</color></size>\"\r\n>... [recording loops]",
        ">... gates online: 1\r\n>... gates online: <size=200%><color=red>at least 2</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: <size=200%><color=red>BIG_{COMMAND}</color></size>\r\n>... operator: small\r\n>... [feedback]",
        ">... fault propagating outward\r\n>... <size=200%><color=red>outward includes Reality</color></size>\r\n>... [warning tone]",
        ">... \"operator returned\"\r\n>... \"<size=200%><color=red>operator did not</color></size>\"\r\n>... [carrier wave]",
        ">... command keyed: 41 times\r\n>... command keyed: <size=200%><color=red>once</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: SEEK<size=200%><color=red>ER</color></size>\r\n>... operator role flipped\r\n>... [feedback]",
        ">... unit checks out\r\n>... unit <size=200%><color=red>checks operator</color></size>\r\n>... [warning tone]",
        ">... \"the destination has weather\"\r\n>... \"the weather has <size=200%><color=red>destinations</color></size>\"\r\n>... [wind]",
        ">... close at T-30s\r\n>... close at <size=200%><color=red>T-0</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: {COMMAND}\r\n>... WRDN: <size=200%><color=red>{COMMAND}, third time</color></size>\r\n>... [feedback]",
        ">... \"do not key the backdoor\"\r\n>... <size=200%><color=red>backdoor key already inserted</color></size>\r\n>... [warning tone]",
        ">... \"archived: {COMMAND}, {COMMAND}, {COMMAND}\"\r\n>... \"archived: <size=200%><color=red>{COMMAND}_NOT</color></size>\"\r\n>... [recording loops]",
        ">... index 0.00\r\n>... index <size=200%><color=red>0.04</color></size>\r\n>... [Encryption checksum mismatch. Contact your IT administrator]",
        ">... WRDN: <size=200%><color=red>TRANSFERRED</color></size>\r\n>... destination: home, but smaller\r\n>... [feedback]",
    };
    #endregion

    private void PostBuildIntel_AlphaTerminalCommand(Level level)
    {
        var pool = new List<string>(
            AlphaTerminalCommandIntel_PrisonerRadio.Count +
            AlphaTerminalCommandIntel_Researchers.Count +
            AlphaTerminalCommandIntel_WardenSystem.Count);

        pool.AddRange(AlphaTerminalCommandIntel_PrisonerRadio);
        pool.AddRange(AlphaTerminalCommandIntel_Researchers);
        pool.AddRange(AlphaTerminalCommandIntel_WardenSystem);

        var picked = Generator.Pick(pool)!.Replace("{COMMAND}", AlphaTerminalCommand);

        level.ElevatorDropWardenIntel.Add(
            (Generator.Between(1, 10), picked));
    }
}
