using AutogenRundown.Extensions;

namespace AutogenRundown.DataBlocks.Objectives;

/**
 * Objective: Gather Terminal
 *
 *
 * TBD
 */
public partial record WardenObjective
{
    private void PreBuild_GatherTerminal(BuildDirector director, Level level)
    {
        // Fast version of this objective
        if (level.MainDirector.Objective is WardenObjectiveType.ReachKdsDeep)
        {
            GatherTerminal_SpawnCount = GatherTerminal_RequiredCount = level.Tier switch
            {
                "E" => 3,
                _ => 2
            };

            return;
        }

        GatherTerminal_SpawnCount = (level.Tier, director.Bulkhead) switch
        {
            ("A", _) => 2,

            ("B", Bulkhead.Main) => 3,
            ("B", _) => 2,

            ("C", Bulkhead.Main) => 4,
            ("C", _) => 2,

            ("D", Bulkhead.Main) => 4,
            ("D", Bulkhead.Extreme) => 2,
            ("D", Bulkhead.Overload) => 3,

            ("E", Bulkhead.Main) => 6,
            ("E", Bulkhead.Extreme) => 3,
            ("E", Bulkhead.Overload) => 4,

            (_, _) => 2,
        };
        GatherTerminal_RequiredCount = Math.Min(GatherTerminal_SpawnCount, (level.Tier, director.Bulkhead) switch
        {
            ("A", _) => 2,

            ("B", Bulkhead.Main) => Generator.Between(2, 3),
            ("B", _) => 2,

            ("C", Bulkhead.Main) => Generator.Between(3, 4),
            ("C", _) => 2,

            ("D", Bulkhead.Main) => Generator.Between(3, 4),
            ("D", Bulkhead.Extreme) => 2,
            ("D", Bulkhead.Overload) => 3,

            ("E", Bulkhead.Main) => Generator.Between(4, 5),
            ("E", Bulkhead.Extreme) => 3,
            ("E", Bulkhead.Overload) => Generator.Between(3, 4),

            (_) => 2,
        });
    }

    private void Build_GatherTerminal(BuildDirector director, Level level)
    {
        MainObjective = new Text("Download <color=orange>Decryption Keys</color> on <u>terminals</u> in the sector and then proceed to the exit point.");
        SolveItem = "Use <color=orange>\"EXTRACT_DECRYPTION_KEY\"</color> command to transfer data to portable unit.";
        SolveItemHelp = "Current progress: [COUNT_CURRENT] / [COUNT_REQUIRED]";
        GoToWinCondition_ToMainLayer = "Go back to the main objective and complete the expedition.";

        GatherTerminal_Command = "EXTRACT_DECRYPTION_KEY";
        GatherTerminal_CommandHelp = "Extract decryption key on local system and transfer to portable unit";
        GatherTerminal_DownloadingText = "";
        GatherTerminal_DownloadCompleteText = "";
        GatherTerminal_DownloadTime = level.Tier switch
        {
            "A" => Generator.Between(2, 4),
            "B" => Generator.Between(3, 6),
            "C" => Generator.Between(5, 8),
            "D" => Generator.Between(6, 10),
            "E" => Generator.Between(8, 14),
        };
    }

    private void PostBuildIntel_GatherTerminal(Level level)
    {
        #region Warden Intel Messages

        // Intel variables
        var totalTerminals = GatherTerminal_RequiredCount.ToCardinal();
        var doneTerminals = Math.Min(Math.Max(1, GatherTerminal_RequiredCount / 2), GatherTerminal_RequiredCount - 1).ToCardinal();

        level.ElevatorDropWardenIntel.Add((Generator.Between(1, 10), Generator.Draw(new List<string>
        {
            // Terminal progress tracking (with totalTerminals and doneTerminals)
            $">... This is terminal {doneTerminals}!\r\n>... <size=200%><color=red>How many total?!</color></size>\r\n>... {totalTerminals.ToTitleCase()}!",
            $">... We've accessed {doneTerminals} terminals!\r\n>... <size=200%><color=red>{totalTerminals.ToTitleCase()} in total!</color></size>\r\n>... [exhausted sigh]",
            $">... {doneTerminals.ToTitleCase()} down!\r\n>... <size=200%><color=red>Still {totalTerminals} to find!</color></size>\r\n>... [breathing heavily]",
            $">... This is {doneTerminals} of {totalTerminals}!\r\n>... <size=200%><color=red>Halfway there!</color></size>\r\n>... [panting]",
            $">... We're at terminal {doneTerminals}!\r\n>... {totalTerminals.ToTitleCase()} total!\r\n>... <size=200%><color=red>Keep going!</color></size>",
            $">... {doneTerminals.ToTitleCase()} terminals accessed!\r\n>... <size=200%><color=red>Out of {totalTerminals}!</color></size>\r\n>... [alarm blaring]",
            $">... This is number {doneTerminals}!\r\n>... <size=200%><color=red>{totalTerminals.ToTitleCase()} required!</color></size>\r\n>... [gunfire]",
            $">... {doneTerminals.ToTitleCase()} so far!\r\n>... We need {totalTerminals}!\r\n>... <size=200%><color=red>Where are the rest?!</color></size>",
            $">... Terminal {doneTerminals} complete!\r\n>... <size=200%><color=red>{totalTerminals.ToTitleCase()} total!</color></size>\r\n>... [creatures approaching]",
            $">... We've done {doneTerminals}!\r\n>... <size=200%><color=red>Only {totalTerminals}?!</color></size>\r\n>... [sobbing]",
            $">... This is {doneTerminals} of how many?!\r\n>... <size=200%><color=red>{totalTerminals.ToTitleCase()}!</color></size>\r\n>... [panic]",
            $">... {doneTerminals.ToTitleCase()} terminals down!\r\n>... {totalTerminals.ToTitleCase()} needed!\r\n>... <size=200%><color=red>I'm exhausted!</color></size>",
            $">... We're on terminal {doneTerminals}!\r\n>... <size=200%><color=red>Out of {totalTerminals}!</color></size>\r\n>... [typing]",
            $">... {doneTerminals.ToTitleCase()} accessed!\r\n>... <size=200%><color=red>Need {totalTerminals}!</color></size>\r\n>... [alarm]",
            $">... Terminal {doneTerminals} done!\r\n>... <size=200%><color=red>{totalTerminals.ToTitleCase()} total!</color></size>\r\n>... [breathing hard]",
            $">... This is {doneTerminals}!\r\n>... {totalTerminals.ToTitleCase()} terminals!\r\n>... <size=200%><color=red>Too many!</color></size>",
            $">... We've hit {doneTerminals}!\r\n>... <size=200%><color=red>Out of {totalTerminals}!</color></size>\r\n>... [creatures shrieking]",
            $">... {doneTerminals.ToTitleCase()} complete!\r\n>... {totalTerminals.ToTitleCase()} required!\r\n>... <size=200%><color=red>Keep moving!</color></size>",
            $">... This is terminal {doneTerminals}!\r\n>... <size=200%><color=red>{totalTerminals.ToTitleCase()} in all!</color></size>\r\n>... [gunfire]",
            $">... {doneTerminals.ToTitleCase()} down!\r\n>... <size=200%><color=red>More to go!</color></size>\r\n>... We need {totalTerminals}!",
            $">... We're at {doneTerminals}!\r\n>... Total is {totalTerminals}!\r\n>... <size=200%><color=red>Where are they?!</color></size>",
            $">... Terminal {doneTerminals}!\r\n>... <size=200%><color=red>{totalTerminals.ToTitleCase()} needed!</color></size>\r\n>... [alarm blaring]",
            $">... {doneTerminals.ToTitleCase()} accessed so far!\r\n>... <size=200%><color=red>{totalTerminals.ToTitleCase()} total!</color></size>\r\n>... [panting]",
            $">... This is {doneTerminals} of {totalTerminals}!\r\n>... <size=200%><color=red>Halfway!</color></size>\r\n>... [exhausted]",
            $">... We've done {doneTerminals} terminals!\r\n>... {totalTerminals.ToTitleCase()} in total!\r\n>... <size=200%><color=red>I can't do this!</color></size>",
            $">... {doneTerminals.ToTitleCase()} complete!\r\n>... <size=200%><color=red>Out of {totalTerminals}!</color></size>\r\n>... [creatures roaring]",
            $">... Terminal {doneTerminals} done!\r\n>... {totalTerminals.ToTitleCase()} required!\r\n>... <size=200%><color=red>Keep going!</color></size>",
            $">... This is {doneTerminals}!\r\n>... <size=200%><color=red>Need {totalTerminals}!</color></size>\r\n>... [typing frantically]",
            $">... {doneTerminals.ToTitleCase()} terminals!\r\n>... {totalTerminals.ToTitleCase()} total!\r\n>... <size=200%><color=red>Almost there!</color></size>",
            $">... We're on {doneTerminals}!\r\n>... <size=200%><color=red>{totalTerminals.ToTitleCase()} needed!</color></size>\r\n>... [alarm]",
            $">... {doneTerminals.ToTitleCase()} so far!\r\n>... <size=200%><color=red>Out of {totalTerminals}!</color></size>\r\n>... [gunfire]",
            $">... Terminal {doneTerminals} accessed!\r\n>... {totalTerminals.ToTitleCase()} in total!\r\n>... <size=200%><color=red>More left!</color></size>",
            $">... This is {doneTerminals} of how many?!\r\n>... <size=200%><color=red>{totalTerminals.ToTitleCase()} terminals!</color></size>\r\n>... [sobbing]",
            $">... We've hit {doneTerminals}!\r\n>... {totalTerminals.ToTitleCase()} required!\r\n>... <size=200%><color=red>Keep searching!</color></size>",
            $">... {doneTerminals.ToTitleCase()} done!\r\n>... <size=200%><color=red>Need {totalTerminals}!</color></size>\r\n>... [breathing heavily]",
            $">... Terminal {doneTerminals} complete!\r\n>... <size=200%><color=red>Out of {totalTerminals}!</color></size>\r\n>... [creatures approaching]",
            $">... This is {doneTerminals}!\r\n>... {totalTerminals.ToTitleCase()} total!\r\n>... <size=200%><color=red>I'm done!</color></size>",
            $">... We're at terminal {doneTerminals}!\r\n>... <size=200%><color=red>{totalTerminals.ToTitleCase()} needed!</color></size>\r\n>... [panic]",
            $">... {doneTerminals.ToTitleCase()} terminals accessed!\r\n>... {totalTerminals.ToTitleCase()} in all!\r\n>... <size=200%><color=red>Keep moving!</color></size>",
            $">... Terminal {doneTerminals}!\r\n>... <size=200%><color=red>Out of {totalTerminals}!</color></size>\r\n>... [alarm blaring]",
            $">... This is {doneTerminals} of {totalTerminals}!\r\n>... <size=200%><color=red>So many!</color></size>\r\n>... [crying]",
            $">... {doneTerminals.ToTitleCase()} down!\r\n>... {totalTerminals.ToTitleCase()} required!\r\n>... <size=200%><color=red>Where are they?!</color></size>",
            $">... We've done {doneTerminals}!\r\n>... <size=200%><color=red>{totalTerminals.ToTitleCase()} total!</color></size>\r\n>... [gunfire]",
            $">... Terminal {doneTerminals} accessed!\r\n>... {totalTerminals.ToTitleCase()} needed!\r\n>... <size=200%><color=red>Still searching!</color></size>",
            $">... This is {doneTerminals}!\r\n>... <size=200%><color=red>Need {totalTerminals}!</color></size>\r\n>... [exhausted sigh]",
            $">... {doneTerminals.ToTitleCase()} complete!\r\n>... {totalTerminals.ToTitleCase()} in total!\r\n>... <size=200%><color=red>Keep going!</color></size>",
            $">... We're on terminal {doneTerminals}!\r\n>... <size=200%><color=red>Out of {totalTerminals}!</color></size>\r\n>... [panting]",
            $">... {doneTerminals.ToTitleCase()} terminals!\r\n>... {totalTerminals.ToTitleCase()} required!\r\n>... <size=200%><color=red>I can't!</color></size>",
            $">... Terminal {doneTerminals} done!\r\n>... <size=200%><color=red>{totalTerminals.ToTitleCase()} needed!</color></size>\r\n>... [creatures shrieking]",
            $">... This is {doneTerminals} of {totalTerminals}!\r\n>... <size=200%><color=red>Halfway point!</color></size>\r\n>... [alarm]",
            $">... We've accessed {doneTerminals}!\r\n>... {totalTerminals.ToTitleCase()} total!\r\n>... <size=200%><color=red>More to find!</color></size>",
            $">... {doneTerminals.ToTitleCase()} so far!\r\n>... <size=200%><color=red>Out of {totalTerminals}!</color></size>\r\n>... [breathing hard]",
            $">... Terminal {doneTerminals} complete!\r\n>... {totalTerminals.ToTitleCase()} in all!\r\n>... <size=200%><color=red>Keep searching!</color></size>",
            $">... This is {doneTerminals}!\r\n>... <size=200%><color=red>{totalTerminals.ToTitleCase()} terminals!</color></size>\r\n>... [sobbing]",
            $">... {doneTerminals.ToTitleCase()} terminals accessed!\r\n>... {totalTerminals.ToTitleCase()} needed!\r\n>... <size=200%><color=red>Almost there!</color></size>",
            $">... We're at {doneTerminals}!\r\n>... <size=200%><color=red>Need {totalTerminals}!</color></size>\r\n>... [gunfire]",
            $">... Terminal {doneTerminals}!\r\n>... {totalTerminals.ToTitleCase()} required!\r\n>... <size=200%><color=red>Keep moving!</color></size>",
            $">... {doneTerminals.ToTitleCase()} complete!\r\n>... <size=200%><color=red>{totalTerminals.ToTitleCase()} total!</color></size>\r\n>... [alarm blaring]",
            $">... This is terminal {doneTerminals}!\r\n>... {totalTerminals.ToTitleCase()} in total!\r\n>... <size=200%><color=red>I'm exhausted!</color></size>",
            $">... We've done {doneTerminals} terminals!\r\n>... <size=200%><color=red>Out of {totalTerminals}!</color></size>\r\n>... [panting]",
            $">... {doneTerminals.ToTitleCase()} down!\r\n>... {totalTerminals.ToTitleCase()} needed!\r\n>... <size=200%><color=red>Where are they?!</color></size>",
            $">... Terminal {doneTerminals} accessed!\r\n>... <size=200%><color=red>{totalTerminals.ToTitleCase()} required!</color></size>\r\n>... [creatures approaching]",
            $">... This is {doneTerminals} of {totalTerminals}!\r\n>... <size=200%><color=red>So many left!</color></size>\r\n>... [crying]",
            $">... We're on terminal {doneTerminals}!\r\n>... {totalTerminals.ToTitleCase()} in all!\r\n>... <size=200%><color=red>Keep going!</color></size>",
            $">... {doneTerminals.ToTitleCase()} terminals!\r\n>... <size=200%><color=red>Need {totalTerminals}!</color></size>\r\n>... [exhausted]",
            $">... Terminal {doneTerminals} complete!\r\n>... {totalTerminals.ToTitleCase()} total!\r\n>... <size=200%><color=red>More to find!</color></size>",
            $">... This is {doneTerminals}!\r\n>... <size=200%><color=red>Out of {totalTerminals}!</color></size>\r\n>... [alarm]",
            $">... {doneTerminals.ToTitleCase()} accessed!\r\n>... {totalTerminals.ToTitleCase()} required!\r\n>... <size=200%><color=red>I'm done!</color></size>",
            $">... We've hit {doneTerminals}!\r\n>... <size=200%><color=red>{totalTerminals.ToTitleCase()} needed!</color></size>\r\n>... [gunfire]",
            $">... Terminal {doneTerminals} done!\r\n>... {totalTerminals.ToTitleCase()} in total!\r\n>... <size=200%><color=red>Keep searching!</color></size>",

            // Log file hints (60 messages - these help players find terminal locations)
            ">... Check the logs!\r\n>... <size=200%><color=red>There's a file with terminal locations!</color></size>\r\n>... [typing]",
            ">... Use LOGS command!\r\n>... <size=200%><color=red>There's a zone map!</color></size>\r\n>... [frantic typing]",
            ">... READ the location file!\r\n>... <size=200%><color=red>It lists the zones!</color></size>\r\n>... [alarm]",
            ">... There's a log file!\r\n>... <size=200%><color=red>Shows terminal zones!</color></size>\r\n>... [typing frantically]",
            ">... LOGS shows a map!\r\n>... <size=200%><color=red>Terminal locations!</color></size>\r\n>... [gunfire]",
            ">... Check the terminal logs!\r\n>... <size=200%><color=red>Zone information!</color></size>\r\n>... [breathing heavily]",
            ">... There's a file!\r\n>... <size=200%><color=red>Lists terminal zones!</color></size>\r\n>... [creatures approaching]",
            ">... READ the zone file!\r\n>... <size=200%><color=red>Terminal locations!</color></size>\r\n>... [alarm blaring]",
            ">... Use LOGS!\r\n>... <size=200%><color=red>There's a location map!</color></size>\r\n>... [typing]",
            ">... Check for logs!\r\n>... <size=200%><color=red>Zone data!</color></size>\r\n>... [panic]",
            ">... The logs have a map!\r\n>... <size=200%><color=red>Terminal zones!</color></size>\r\n>... [frantic]",
            ">... READ the map file!\r\n>... <size=200%><color=red>Shows terminal locations!</color></size>\r\n>... [gunfire]",
            ">... There's a zone log!\r\n>... <size=200%><color=red>Terminal data!</color></size>\r\n>... [typing frantically]",
            ">... Use LOGS command!\r\n>... <size=200%><color=red>Zone information file!</color></size>\r\n>... [alarm]",
            ">... Check the logs!\r\n>... <size=200%><color=red>Terminal zone map!</color></size>\r\n>... [creatures shrieking]",
            ">... READ the location log!\r\n>... <size=200%><color=red>Lists all zones!</color></size>\r\n>... [breathing hard]",
            ">... There's a file!\r\n>... <size=200%><color=red>Terminal locations!</color></size>\r\n>... [alarm blaring]",
            ">... LOGS shows zones!\r\n>... <size=200%><color=red>Terminal data!</color></size>\r\n>... [typing]",
            ">... Check for a map file!\r\n>... <size=200%><color=red>Zone information!</color></size>\r\n>... [gunfire]",
            ">... The logs!\r\n>... <size=200%><color=red>Terminal zone list!</color></size>\r\n>... [panting]",
            ">... READ the zone map!\r\n>... <size=200%><color=red>Terminal locations!</color></size>\r\n>... [alarm]",
            ">... There's a location file!\r\n>... <size=200%><color=red>Shows terminal zones!</color></size>\r\n>... [creatures approaching]",
            ">... Use LOGS!\r\n>... <size=200%><color=red>Zone data file!</color></size>\r\n>... [typing frantically]",
            ">... Check the terminal!\r\n>... <size=200%><color=red>Logs have zone info!</color></size>\r\n>... [frantic]",
            ">... READ the file!\r\n>... <size=200%><color=red>Terminal zone map!</color></size>\r\n>... [gunfire]",
            ">... There's a zone list!\r\n>... <size=200%><color=red>In the logs!</color></size>\r\n>... [alarm blaring]",
            ">... LOGS command!\r\n>... <size=200%><color=red>Terminal location file!</color></size>\r\n>... [breathing heavily]",
            ">... Check for a zone file!\r\n>... <size=200%><color=red>Terminal data!</color></size>\r\n>... [typing]",
            ">... The logs show zones!\r\n>... <size=200%><color=red>Terminal locations!</color></size>\r\n>... [creatures shrieking]",
            ">... READ the location data!\r\n>... <size=200%><color=red>Zone information!</color></size>\r\n>... [alarm]",
            ">... There's a map!\r\n>... <size=200%><color=red>In the log files!</color></size>\r\n>... [gunfire]",
            ">... Use LOGS!\r\n>... <size=200%><color=red>Shows terminal zones!</color></size>\r\n>... [panting]",
            ">... Check the logs!\r\n>... <size=200%><color=red>Zone map file!</color></size>\r\n>... [typing frantically]",
            ">... READ the zone data!\r\n>... <size=200%><color=red>Terminal locations!</color></size>\r\n>... [alarm blaring]",
            ">... There's a file!\r\n>... <size=200%><color=red>Lists terminal zones!</color></size>\r\n>... [creatures approaching]",
            ">... LOGS shows a map!\r\n>... <size=200%><color=red>Zone information!</color></size>\r\n>... [frantic]",
            ">... Check for zone logs!\r\n>... <size=200%><color=red>Terminal data!</color></size>\r\n>... [gunfire]",
            ">... The logs have locations!\r\n>... <size=200%><color=red>Terminal zones!</color></size>\r\n>... [typing]",
            ">... READ the map!\r\n>... <size=200%><color=red>Shows all zones!</color></size>\r\n>... [alarm]",
            ">... There's a location log!\r\n>... <size=200%><color=red>Terminal information!</color></size>\r\n>... [breathing heavily]",
            ">... Use LOGS command!\r\n>... <size=200%><color=red>Zone map data!</color></size>\r\n>... [creatures shrieking]",
            ">... Check the terminal!\r\n>... <size=200%><color=red>Logs show zones!</color></size>\r\n>... [alarm blaring]",
            ">... READ the zone file!\r\n>... <size=200%><color=red>Terminal locations!</color></size>\r\n>... [gunfire]",
            ">... There's a map file!\r\n>... <size=200%><color=red>Zone data!</color></size>\r\n>... [typing frantically]",
            ">... LOGS shows zones!\r\n>... <size=200%><color=red>Terminal information!</color></size>\r\n>... [panting]",
            ">... Check for a location file!\r\n>... <size=200%><color=red>Terminal zones!</color></size>\r\n>... [alarm]",
            ">... The logs!\r\n>... <size=200%><color=red>Zone map!</color></size>\r\n>... [creatures approaching]",
            ">... READ the data!\r\n>... <size=200%><color=red>Terminal zone list!</color></size>\r\n>... [frantic]",
            ">... There's a zone file!\r\n>... <size=200%><color=red>Shows terminals!</color></size>\r\n>... [gunfire]",
            ">... Use LOGS!\r\n>... <size=200%><color=red>Location information!</color></size>\r\n>... [typing]",
            ">... Check the logs!\r\n>... <size=200%><color=red>Terminal zone data!</color></size>\r\n>... [alarm blaring]",
            ">... READ the zone map!\r\n>... <size=200%><color=red>Terminal locations!</color></size>\r\n>... [breathing heavily]",
            ">... There's a file!\r\n>... <size=200%><color=red>Zone information!</color></size>\r\n>... [creatures shrieking]",
            ">... LOGS command!\r\n>... <size=200%><color=red>Shows terminal zones!</color></size>\r\n>... [alarm]",
            ">... Check for zone data!\r\n>... <size=200%><color=red>Terminal map!</color></size>\r\n>... [gunfire]",
            ">... The logs show a map!\r\n>... <size=200%><color=red>Zone locations!</color></size>\r\n>... [typing frantically]",
            ">... READ the location file!\r\n>... <size=200%><color=red>Terminal zones!</color></size>\r\n>... [panting]",
            ">... There's a zone log!\r\n>... <size=200%><color=red>Terminal information!</color></size>\r\n>... [alarm blaring]",
            ">... Use LOGS!\r\n>... <size=200%><color=red>Zone map file!</color></size>\r\n>... [creatures approaching]",

            // Command usage & extraction (with GatherTerminal_Command)
            $">... Type {GatherTerminal_Command}!\r\n>... <size=200%><color=red>Extract the data!</color></size>\r\n>... [typing]",
            $">... {GatherTerminal_Command}...\r\n>... <size=200%><color=red>Command entered!</color></size>\r\n>... [downloading]",
            $">... Use {GatherTerminal_Command}!\r\n>... <size=200%><color=red>Extracting now!</color></size>\r\n>... [alarm]",
            $">... {GatherTerminal_Command} command!\r\n>... <size=200%><color=red>It's downloading!</color></size>\r\n>... [gunfire]",
            $">... Type {GatherTerminal_Command}!\r\n>... <size=200%><color=red>Hurry!</color></size>\r\n>... [creatures approaching]",
            $">... {GatherTerminal_Command}...\r\n>... <size=200%><color=red>Extraction started!</color></size>\r\n>... [typing frantically]",
            $">... Use the {GatherTerminal_Command} command!\r\n>... <size=200%><color=red>Download in progress!</color></size>\r\n>... [alarm blaring]",
            $">... {GatherTerminal_Command}!\r\n>... <size=200%><color=red>It's working!</color></size>\r\n>... [breathing heavily]",
            $">... Type {GatherTerminal_Command} now!\r\n>... <size=200%><color=red>Extract the key!</color></size>\r\n>... [creatures shrieking]",
            $">... {GatherTerminal_Command}...\r\n>... <size=200%><color=red>Extraction failed!</color></size>\r\n>... [panic]",
            $">... Use {GatherTerminal_Command}!\r\n>... <size=200%><color=red>Download interrupted!</color></size>\r\n>... [gunfire]",
            $">... {GatherTerminal_Command} command!\r\n>... <size=200%><color=red>Almost done!</color></size>\r\n>... [alarm]",
            $">... Type {GatherTerminal_Command}!\r\n>... <size=200%><color=red>Extracting data!</color></size>\r\n>... [typing]",
            $">... {GatherTerminal_Command}...\r\n>... <size=200%><color=red>It's downloading!</color></size>\r\n>... [panting]",
            $">... Use {GatherTerminal_Command} command!\r\n>... <size=200%><color=red>Download started!</color></size>\r\n>... [creatures approaching]",
            $">... {GatherTerminal_Command}!\r\n>... <size=200%><color=red>Extraction complete!</color></size>\r\n>... [alarm blaring]",
            $">... Type {GatherTerminal_Command} now!\r\n>... <size=200%><color=red>Hurry up!</color></size>\r\n>... [gunfire]",
            $">... {GatherTerminal_Command}...\r\n>... <size=200%><color=red>Command failed!</color></size>\r\n>... [screaming]",
            $">... Use the {GatherTerminal_Command}!\r\n>... <size=200%><color=red>Extracting now!</color></size>\r\n>... [typing frantically]",
            $">... {GatherTerminal_Command} command!\r\n>... <size=200%><color=red>Download in progress!</color></size>\r\n>... [alarm]",
            $">... Type {GatherTerminal_Command}!\r\n>... <size=200%><color=red>It's working!</color></size>\r\n>... [breathing heavily]",
            $">... {GatherTerminal_Command}...\r\n>... <size=200%><color=red>Extraction interrupted!</color></size>\r\n>... [creatures shrieking]",
            $">... Use {GatherTerminal_Command}!\r\n>... <size=200%><color=red>Download failed!</color></size>\r\n>... [panic]",
            $">... {GatherTerminal_Command} now!\r\n>... <size=200%><color=red>Extract the data!</color></size>\r\n>... [gunfire]",
            $">... Type {GatherTerminal_Command}!\r\n>... <size=200%><color=red>Downloading!</color></size>\r\n>... [typing]",
            $">... {GatherTerminal_Command}...\r\n>... <size=200%><color=red>Almost there!</color></size>\r\n>... [alarm blaring]",
            $">... Use {GatherTerminal_Command} command!\r\n>... <size=200%><color=red>Extraction started!</color></size>\r\n>... [creatures approaching]",
            $">... {GatherTerminal_Command}!\r\n>... <size=200%><color=red>It's downloading!</color></size>\r\n>... [panting]",
            $">... Type {GatherTerminal_Command} now!\r\n>... <size=200%><color=red>Hurry!</color></size>\r\n>... [alarm]",
            $">... {GatherTerminal_Command}...\r\n>... <size=200%><color=red>Download complete!</color></size>\r\n>... [gunfire]",
            $">... Use the {GatherTerminal_Command}!\r\n>... <size=200%><color=red>Extracting data!</color></size>\r\n>... [typing frantically]",
            $">... {GatherTerminal_Command} command!\r\n>... <size=200%><color=red>It's working!</color></size>\r\n>... [breathing heavily]",
            $">... Type {GatherTerminal_Command}!\r\n>... <size=200%><color=red>Extraction in progress!</color></size>\r\n>... [creatures shrieking]",
            $">... {GatherTerminal_Command}...\r\n>... <size=200%><color=red>Download interrupted!</color></size>\r\n>... [alarm blaring]",
            $">... Use {GatherTerminal_Command}!\r\n>... <size=200%><color=red>Extract now!</color></size>\r\n>... [panic]",
            $">... {GatherTerminal_Command} now!\r\n>... <size=200%><color=red>Downloading!</color></size>\r\n>... [gunfire]",
            $">... Type {GatherTerminal_Command}!\r\n>... <size=200%><color=red>Almost done!</color></size>\r\n>... [typing]",
            $">... {GatherTerminal_Command}...\r\n>... <size=200%><color=red>Extraction failed!</color></size>\r\n>... [screaming]",
            $">... Use {GatherTerminal_Command} command!\r\n>... <size=200%><color=red>Download started!</color></size>\r\n>... [alarm]",
            $">... {GatherTerminal_Command}!\r\n>... <size=200%><color=red>It's extracting!</color></size>\r\n>... [creatures approaching]",
            $">... Type {GatherTerminal_Command} now!\r\n>... <size=200%><color=red>Hurry up!</color></size>\r\n>... [panting]",
            $">... {GatherTerminal_Command}...\r\n>... <size=200%><color=red>Download in progress!</color></size>\r\n>... [alarm blaring]",
            $">... Use the {GatherTerminal_Command}!\r\n>... <size=200%><color=red>Extracting now!</color></size>\r\n>... [gunfire]",
            $">... {GatherTerminal_Command} command!\r\n>... <size=200%><color=red>It's working!</color></size>\r\n>... [typing frantically]",
            $">... Type {GatherTerminal_Command}!\r\n>... <size=200%><color=red>Extraction complete!</color></size>\r\n>... [breathing heavily]",
            $">... {GatherTerminal_Command}...\r\n>... <size=200%><color=red>Download failed!</color></size>\r\n>... [creatures shrieking]",
            $">... Use {GatherTerminal_Command}!\r\n>... <size=200%><color=red>Extract the data!</color></size>\r\n>... [alarm]",
            $">... {GatherTerminal_Command} now!\r\n>... <size=200%><color=red>Downloading!</color></size>\r\n>... [panic]",
            $">... Type {GatherTerminal_Command}!\r\n>... <size=200%><color=red>Almost there!</color></size>\r\n>... [gunfire]",
            $">... {GatherTerminal_Command}...\r\n>... <size=200%><color=red>Extraction interrupted!</color></size>\r\n>... [typing]",
            $">... Use {GatherTerminal_Command} command!\r\n>... <size=200%><color=red>Download started!</color></size>\r\n>... [alarm blaring]",
            $">... {GatherTerminal_Command}!\r\n>... <size=200%><color=red>It's downloading!</color></size>\r\n>... [creatures approaching]",
            $">... Type {GatherTerminal_Command} now!\r\n>... <size=200%><color=red>Hurry!</color></size>\r\n>... [panting]",
            $">... {GatherTerminal_Command}...\r\n>... <size=200%><color=red>Extraction in progress!</color></size>\r\n>... [alarm]",
            $">... Use the {GatherTerminal_Command}!\r\n>... <size=200%><color=red>Extract now!</color></size>\r\n>... [gunfire]",
            $">... {GatherTerminal_Command} command!\r\n>... <size=200%><color=red>It's working!</color></size>\r\n>... [typing frantically]",
            $">... Type {GatherTerminal_Command}!\r\n>... <size=200%><color=red>Download complete!</color></size>\r\n>... [breathing heavily]",
            $">... {GatherTerminal_Command}...\r\n>... <size=200%><color=red>Extraction failed!</color></size>\r\n>... [creatures shrieking]",
            $">... Use {GatherTerminal_Command}!\r\n>... <size=200%><color=red>Extracting data!</color></size>\r\n>... [alarm blaring]",

            // Terminal count stress (with totalTerminals)
            $">... {totalTerminals.ToTitleCase()} terminals?!\r\n>... <size=200%><color=red>That's too many!</color></size>\r\n>... [exhausted sigh]",
            $">... We need {totalTerminals}!\r\n>... <size=200%><color=red>I can't find them all!</color></size>\r\n>... [panic]",
            $">... {totalTerminals.ToTitleCase()} terminals total!\r\n>... <size=200%><color=red>Where are they?!</color></size>\r\n>... [breathing heavily]",
            $">... {totalTerminals.ToTitleCase()} to access!\r\n>... <size=200%><color=red>We'll never make it!</color></size>\r\n>... [sobbing]",
            $">... We need {totalTerminals} terminals!\r\n>... <size=200%><color=red>Too many!</color></size>\r\n>... [alarm blaring]",
            $">... {totalTerminals.ToTitleCase()} terminals?!\r\n>... <size=200%><color=red>That's impossible!</color></size>\r\n>... [gunfire]",
            $">... {totalTerminals.ToTitleCase()} in total!\r\n>... <size=200%><color=red>I'm exhausted!</color></size>\r\n>... [panting]",
            $">... We need {totalTerminals}!\r\n>... <size=200%><color=red>Can't find them!</color></size>\r\n>... [creatures approaching]",
            $">... {totalTerminals.ToTitleCase()} terminals!\r\n>... <size=200%><color=red>I'm done!</color></size>\r\n>... [crying]",
            $">... {totalTerminals.ToTitleCase()} to find!\r\n>... <size=200%><color=red>We're lost!</color></size>\r\n>... [alarm]",
            $">... We need {totalTerminals} terminals!\r\n>... <size=200%><color=red>Too much!</color></size>\r\n>... [breathing hard]",
            $">... {totalTerminals.ToTitleCase()} terminals?!\r\n>... <size=200%><color=red>That's madness!</color></size>\r\n>... [creatures shrieking]",
            $">... {totalTerminals.ToTitleCase()} in all!\r\n>... <size=200%><color=red>I can't do this!</color></size>\r\n>... [gunfire]",
            $">... We need {totalTerminals}!\r\n>... <size=200%><color=red>Where are they?!</color></size>\r\n>... [typing frantically]",
            $">... {totalTerminals.ToTitleCase()} terminals!\r\n>... <size=200%><color=red>We'll die first!</color></size>\r\n>... [alarm blaring]",
            $">... {totalTerminals.ToTitleCase()} to access!\r\n>... <size=200%><color=red>Too many!</color></size>\r\n>... [panting]",
            $">... We need {totalTerminals} terminals!\r\n>... <size=200%><color=red>I'm out of ammo!</color></size>\r\n>... [creatures approaching]",
            $">... {totalTerminals.ToTitleCase()} terminals?!\r\n>... <size=200%><color=red>That's insane!</color></size>\r\n>... [sobbing]",
            $">... {totalTerminals.ToTitleCase()} in total!\r\n>... <size=200%><color=red>Can't find them all!</color></size>\r\n>... [alarm]",
            $">... We need {totalTerminals}!\r\n>... <size=200%><color=red>Too many zones!</color></size>\r\n>... [gunfire]",
            $">... {totalTerminals.ToTitleCase()} terminals!\r\n>... <size=200%><color=red>I'm exhausted!</color></size>\r\n>... [breathing heavily]",
            $">... {totalTerminals.ToTitleCase()} to find!\r\n>... <size=200%><color=red>We're scattered!</color></size>\r\n>... [creatures shrieking]",
            $">... We need {totalTerminals} terminals!\r\n>... <size=200%><color=red>That's too much!</color></size>\r\n>... [alarm blaring]",
            $">... {totalTerminals.ToTitleCase()} terminals?!\r\n>... <size=200%><color=red>We'll never finish!</color></size>\r\n>... [crying]",
            $">... {totalTerminals.ToTitleCase()} in all!\r\n>... <size=200%><color=red>I'm done!</color></size>\r\n>... [panting]",
            $">... We need {totalTerminals}!\r\n>... <size=200%><color=red>Where are they?!</color></size>\r\n>... [gunfire]",
            $">... {totalTerminals.ToTitleCase()} terminals!\r\n>... <size=200%><color=red>Too many!</color></size>\r\n>... [alarm]",
            $">... {totalTerminals.ToTitleCase()} to access!\r\n>... <size=200%><color=red>We can't!</color></size>\r\n>... [creatures approaching]",
            $">... We need {totalTerminals} terminals!\r\n>... <size=200%><color=red>I'm lost!</color></size>\r\n>... [breathing hard]",
            $">... {totalTerminals.ToTitleCase()} terminals?!\r\n>... <size=200%><color=red>That's impossible!</color></size>\r\n>... [sobbing]",
            $">... {totalTerminals.ToTitleCase()} in total!\r\n>... <size=200%><color=red>We're doomed!</color></size>\r\n>... [alarm blaring]",
            $">... We need {totalTerminals}!\r\n>... <size=200%><color=red>Can't find them!</color></size>\r\n>... [gunfire]",
            $">... {totalTerminals.ToTitleCase()} terminals!\r\n>... <size=200%><color=red>I can't!</color></size>\r\n>... [creatures shrieking]",
            $">... {totalTerminals.ToTitleCase()} to find!\r\n>... <size=200%><color=red>Too much!</color></size>\r\n>... [panting]",
            $">... We need {totalTerminals} terminals!\r\n>... <size=200%><color=red>We're exhausted!</color></size>\r\n>... [alarm]",
            $">... {totalTerminals.ToTitleCase()} terminals?!\r\n>... <size=200%><color=red>That's too many!</color></size>\r\n>... [breathing heavily]",
            $">... {totalTerminals.ToTitleCase()} in all!\r\n>... <size=200%><color=red>Where are they?!</color></size>\r\n>... [gunfire]",
            $">... We need {totalTerminals}!\r\n>... <size=200%><color=red>I'm done!</color></size>\r\n>... [crying]",
            $">... {totalTerminals.ToTitleCase()} terminals!\r\n>... <size=200%><color=red>We'll never make it!</color></size>\r\n>... [alarm blaring]",
            $">... {totalTerminals.ToTitleCase()} to access!\r\n>... <size=200%><color=red>Too many!</color></size>\r\n>... [creatures approaching]",
            $">... We need {totalTerminals} terminals!\r\n>... <size=200%><color=red>I can't do this!</color></size>\r\n>... [panting]",
            $">... {totalTerminals.ToTitleCase()} terminals?!\r\n>... <size=200%><color=red>That's insane!</color></size>\r\n>... [alarm]",
            $">... {totalTerminals.ToTitleCase()} in total!\r\n>... <size=200%><color=red>We're lost!</color></size>\r\n>... [gunfire]",
            $">... We need {totalTerminals}!\r\n>... <size=200%><color=red>Can't find them all!</color></size>\r\n>... [breathing heavily]",
            $">... {totalTerminals.ToTitleCase()} terminals!\r\n>... <size=200%><color=red>I'm exhausted!</color></size>\r\n>... [creatures shrieking]",
            $">... {totalTerminals.ToTitleCase()} to find!\r\n>... <size=200%><color=red>We can't!</color></size>\r\n>... [sobbing]",
            $">... We need {totalTerminals} terminals!\r\n>... <size=200%><color=red>Too much!</color></size>\r\n>... [alarm blaring]",
            $">... {totalTerminals.ToTitleCase()} terminals?!\r\n>... <size=200%><color=red>That's too many!</color></size>\r\n>... [panting]",
            $">... {totalTerminals.ToTitleCase()} in all!\r\n>... <size=200%><color=red>I'm done!</color></size>\r\n>... [gunfire]",
            $">... We need {totalTerminals}!\r\n>... <size=200%><color=red>Where are they?!</color></size>\r\n>... [alarm]",

            // Mid-mission exhaustion (with doneTerminals)
            $">... We've already done {doneTerminals}!\r\n>... <size=200%><color=red>I'm exhausted!</color></size>\r\n>... [breathing heavily]",
            $">... {doneTerminals.ToTitleCase()} terminals so far!\r\n>... <size=200%><color=red>Still more left!</color></size>\r\n>... [panting]",
            $">... We're at {doneTerminals}!\r\n>... <size=200%><color=red>How many more?!</color></size>\r\n>... [exhausted sigh]",
            $">... {doneTerminals.ToTitleCase()} down!\r\n>... <size=200%><color=red>I can't do more!</color></size>\r\n>... [sobbing]",
            $">... We've accessed {doneTerminals}!\r\n>... <size=200%><color=red>Still going!</color></size>\r\n>... [alarm blaring]",
            $">... {doneTerminals.ToTitleCase()} terminals!\r\n>... <size=200%><color=red>I'm done!</color></size>\r\n>... [crying]",
            $">... We're on {doneTerminals}!\r\n>... <size=200%><color=red>Too many left!</color></size>\r\n>... [gunfire]",
            $">... {doneTerminals.ToTitleCase()} so far!\r\n>... <size=200%><color=red>We're exhausted!</color></size>\r\n>... [breathing hard]",
            $">... We've done {doneTerminals} already!\r\n>... <size=200%><color=red>More to go!</color></size>\r\n>... [creatures approaching]",
            $">... {doneTerminals.ToTitleCase()} terminals!\r\n>... <size=200%><color=red>I can't!</color></size>\r\n>... [alarm]",
            $">... We're at {doneTerminals}!\r\n>... <size=200%><color=red>Still searching!</color></size>\r\n>... [panting]",
            $">... {doneTerminals.ToTitleCase()} down!\r\n>... <size=200%><color=red>I'm out of ammo!</color></size>\r\n>... [creatures shrieking]",
            $">... We've accessed {doneTerminals}!\r\n>... <size=200%><color=red>Not enough!</color></size>\r\n>... [gunfire]",
            $">... {doneTerminals.ToTitleCase()} terminals so far!\r\n>... <size=200%><color=red>How many left?!</color></size>\r\n>... [alarm blaring]",
            $">... We're on {doneTerminals}!\r\n>... <size=200%><color=red>I'm exhausted!</color></size>\r\n>... [breathing heavily]",
            $">... {doneTerminals.ToTitleCase()} already!\r\n>... <size=200%><color=red>Still more!</color></size>\r\n>... [sobbing]",
            $">... We've done {doneTerminals} terminals!\r\n>... <size=200%><color=red>Too many left!</color></size>\r\n>... [panting]",
            $">... {doneTerminals.ToTitleCase()} so far!\r\n>... <size=200%><color=red>I can't do this!</color></size>\r\n>... [crying]",
            $">... We're at {doneTerminals}!\r\n>... <size=200%><color=red>Keep going!</color></size>\r\n>... [alarm]",
            $">... {doneTerminals.ToTitleCase()} terminals!\r\n>... <size=200%><color=red>We're done!</color></size>\r\n>... [creatures approaching]",
            $">... We've accessed {doneTerminals}!\r\n>... <size=200%><color=red>More to find!</color></size>\r\n>... [gunfire]",
            $">... {doneTerminals.ToTitleCase()} down!\r\n>... <size=200%><color=red>I'm exhausted!</color></size>\r\n>... [breathing hard]",
            $">... We're on {doneTerminals}!\r\n>... <size=200%><color=red>How many more?!</color></size>\r\n>... [alarm blaring]",
            $">... {doneTerminals.ToTitleCase()} terminals so far!\r\n>... <size=200%><color=red>Still going!</color></size>\r\n>... [panting]",
            $">... We've done {doneTerminals} already!\r\n>... <size=200%><color=red>Not done yet!</color></size>\r\n>... [creatures shrieking]",
            $">... {doneTerminals.ToTitleCase()} accessed!\r\n>... <size=200%><color=red>I can't!</color></size>\r\n>... [sobbing]",
            $">... We're at {doneTerminals}!\r\n>... <size=200%><color=red>Too many left!</color></size>\r\n>... [gunfire]",
            $">... {doneTerminals.ToTitleCase()} terminals!\r\n>... <size=200%><color=red>I'm done!</color></size>\r\n>... [alarm]",
            $">... We've done {doneTerminals}!\r\n>... <size=200%><color=red>Still searching!</color></size>\r\n>... [breathing heavily]",
            $">... {doneTerminals.ToTitleCase()} so far!\r\n>... <size=200%><color=red>More to go!</color></size>\r\n>... [creatures approaching]",
            $">... We're on {doneTerminals}!\r\n>... <size=200%><color=red>I'm exhausted!</color></size>\r\n>... [panting]",
            $">... {doneTerminals.ToTitleCase()} terminals!\r\n>... <size=200%><color=red>How many left?!</color></size>\r\n>... [crying]",
            $">... We've accessed {doneTerminals}!\r\n>... <size=200%><color=red>Keep going!</color></size>\r\n>... [alarm blaring]",
            $">... {doneTerminals.ToTitleCase()} down!\r\n>... <size=200%><color=red>We're exhausted!</color></size>\r\n>... [gunfire]",
            $">... We're at {doneTerminals}!\r\n>... <size=200%><color=red>Still more!</color></size>\r\n>... [breathing hard]",
            $">... {doneTerminals.ToTitleCase()} terminals so far!\r\n>... <size=200%><color=red>I can't do this!</color></size>\r\n>... [sobbing]",
            $">... We've done {doneTerminals} already!\r\n>... <size=200%><color=red>Not enough!</color></size>\r\n>... [creatures shrieking]",
            $">... {doneTerminals.ToTitleCase()} accessed!\r\n>... <size=200%><color=red>Too many left!</color></size>\r\n>... [alarm]",
            $">... We're on {doneTerminals}!\r\n>... <size=200%><color=red>I'm done!</color></size>\r\n>... [panting]",
            $">... {doneTerminals.ToTitleCase()} terminals!\r\n>... <size=200%><color=red>More to find!</color></size>\r\n>... [gunfire]",
            $">... We've done {doneTerminals}!\r\n>... <size=200%><color=red>I'm exhausted!</color></size>\r\n>... [breathing heavily]",
            $">... {doneTerminals.ToTitleCase()} so far!\r\n>... <size=200%><color=red>How many more?!</color></size>\r\n>... [alarm blaring]",
            $">... We're at {doneTerminals}!\r\n>... <size=200%><color=red>Still going!</color></size>\r\n>... [creatures approaching]",
            $">... {doneTerminals.ToTitleCase()} terminals!\r\n>... <size=200%><color=red>I can't!</color></size>\r\n>... [crying]",
            $">... We've accessed {doneTerminals}!\r\n>... <size=200%><color=red>Keep going!</color></size>\r\n>... [panting]",

            // Terminal navigation (no variables)
            ">... [static]\r\n>... <size=200%><color=red>I can't find the terminal!</color></size>\r\n>... [breathing heavily]",
            ">... Where is it?!\r\n>... <size=200%><color=red>Wrong zone!</color></size>\r\n>... [panic]",
            ">... [creatures approaching]\r\n>... <size=200%><color=red>Terminal's not here!</color></size>\r\n>... [gunfire]",
            ">... We're lost!\r\n>... <size=200%><color=red>Can't find it!</color></size>\r\n>... [alarm blaring]",
            ">... [typing]\r\n>... This isn't the right one!\r\n>... <size=200%><color=red>Wrong terminal!</color></size>",
            ">... Where's the terminal?!\r\n>... <size=200%><color=red>It's not here!</color></size>\r\n>... [creatures shrieking]",
            ">... [running]\r\n>... <size=200%><color=red>We passed it!</color></size>\r\n>... [panting]",
            ">... This zone is empty!\r\n>... <size=200%><color=red>Where is it?!</color></size>\r\n>... [alarm]",
            ">... [searching]\r\n>... <size=200%><color=red>No terminal here!</color></size>\r\n>... [gunfire]",
            ">... We're backtracking!\r\n>... <size=200%><color=red>Wrong way!</color></size>\r\n>... [breathing hard]",
            ">... [creatures approaching]\r\n>... <size=200%><color=red>Still can't find it!</color></size>\r\n>... [alarm blaring]",
            ">... This isn't right!\r\n>... <size=200%><color=red>We're lost!</color></size>\r\n>... [panic]",
            ">... [typing]\r\n>... <size=200%><color=red>Wrong terminal again!</color></size>\r\n>... [sobbing]",
            ">... Where are we?!\r\n>... <size=200%><color=red>Can't find the zone!</color></size>\r\n>... [gunfire]",
            ">... [running]\r\n>... <size=200%><color=red>Terminal's missing!</color></size>\r\n>... [creatures shrieking]",
            ">... We've been here!\r\n>... <size=200%><color=red>Going in circles!</color></size>\r\n>... [alarm]",
            ">... [searching]\r\n>... <size=200%><color=red>It's not in this zone!</color></size>\r\n>... [breathing heavily]",
            ">... This is the wrong one!\r\n>... <size=200%><color=red>Not the terminal!</color></size>\r\n>... [gunfire]",
            ">... [creatures approaching]\r\n>... <size=200%><color=red>We're in the wrong zone!</color></size>\r\n>... [panic]",
            ">... Can't find it!\r\n>... <size=200%><color=red>Where is it?!</color></size>\r\n>... [alarm blaring]",
            ">... [typing]\r\n>... <size=200%><color=red>This isn't it!</color></size>\r\n>... [panting]",
            ">... We're going back!\r\n>... <size=200%><color=red>Wrong direction!</color></size>\r\n>... [creatures shrieking]",
            ">... [running]\r\n>... <size=200%><color=red>Terminal's elsewhere!</color></size>\r\n>... [gunfire]",
            ">... This zone is wrong!\r\n>... <size=200%><color=red>Not here!</color></size>\r\n>... [alarm]",
            ">... [searching]\r\n>... <size=200%><color=red>Can't locate it!</color></size>\r\n>... [breathing hard]",

            // Reading under pressure (no variables)
            ">... [typing]\r\n>... <size=200%><color=red>They're attacking!</color></size>\r\n>... [gunfire]",
            ">... Downloading!\r\n>... <size=200%><color=red>Cover me!</color></size>\r\n>... [creatures approaching]",
            ">... [alarm blaring]\r\n>... <size=200%><color=red>Can't see the screen!</color></size>\r\n>... [panic]",
            ">... Extract the data!\r\n>... <size=200%><color=red>They're here!</color></size>\r\n>... [creatures shrieking]",
            ">... [typing frantically]\r\n>... <size=200%><color=red>Giant incoming!</color></size>\r\n>... [roaring]",
            ">... Downloading!\r\n>... <size=200%><color=red>Interrupted!</color></size>\r\n>... [alarm]",
            ">... [gunfire]\r\n>... <size=200%><color=red>I can't type!</color></size>\r\n>... [creatures attacking]",
            ">... Extract now!\r\n>... <size=200%><color=red>They're breaking through!</color></size>\r\n>... [alarm blaring]",
            ">... [typing]\r\n>... <size=200%><color=red>Behind you!</color></size>\r\n>... [screaming]",
            ">... Downloading!\r\n>... <size=200%><color=red>Hurry!</color></size>\r\n>... [gunfire]",
            ">... [alarm]\r\n>... <size=200%><color=red>Can't finish!</color></size>\r\n>... [creatures approaching]",
            ">... Extract the data!\r\n>... <size=200%><color=red>They're on me!</color></size>\r\n>... [panic]",
            ">... [typing frantically]\r\n>... <size=200%><color=red>Charger incoming!</color></size>\r\n>... [creatures shrieking]",
            ">... Downloading!\r\n>... <size=200%><color=red>Download failed!</color></size>\r\n>... [alarm blaring]",
            ">... [gunfire]\r\n>... <size=200%><color=red>Protect the terminal!</color></size>\r\n>... [creatures attacking]",
            ">... Extract now!\r\n>... <size=200%><color=red>I'm out of ammo!</color></size>\r\n>... [breathing heavily]",
            ">... [typing]\r\n>... <size=200%><color=red>They're everywhere!</color></size>\r\n>... [alarm]",
            ">... Downloading!\r\n>... <size=200%><color=red>Almost done!</color></size>\r\n>... [gunfire]",
            ">... [creatures approaching]\r\n>... <size=200%><color=red>Can't finish the extraction!</color></size>\r\n>... [panic]",
            ">... Extract the data!\r\n>... <size=200%><color=red>Striker on the terminal!</color></size>\r\n>... [alarm blaring]",

            // General panic & failure (no variables)
            ">... [screaming]\r\n>... <size=200%><color=red>Run!</color></size>\r\n>... [gunfire]",
            ">... We're all dead!\r\n>... <size=200%><color=red>Forget the terminals!</color></size>\r\n>... [creatures shrieking]",
            ">... [sobbing]\r\n>... I can't find any more!\r\n>... <size=200%><color=red>We failed!</color></size>",
            ">... They're overrunning us!\r\n>... <size=200%><color=red>Retreat!</color></size>\r\n>... [alarm blaring]",
            ">... [breathing heavily]\r\n>... <size=200%><color=red>I'm the last one!</color></size>\r\n>... [creatures approaching]",
            ">... This is impossible!\r\n>... <size=200%><color=red>Too many terminals!</color></size>\r\n>... [gunfire]",
            ">... [crying]\r\n>... <size=200%><color=red>Leave me!</color></size>\r\n>... [screaming]",
            ">... We're scattered!\r\n>... <size=200%><color=red>Can't regroup!</color></size>\r\n>... [alarm]",
            ">... [panic]\r\n>... <size=200%><color=red>They're everywhere!</color></size>\r\n>... [creatures shrieking]",
            ">... I'm out!\r\n>... <size=200%><color=red>No ammo left!</color></size>\r\n>... [gunfire]",
            ">... [alarm blaring]\r\n>... <size=200%><color=red>It's over!</color></size>\r\n>... [screaming]",
            ">... We can't do this!\r\n>... <size=200%><color=red>Give up!</color></size>\r\n>... [sobbing]",
            ">... [creatures approaching]\r\n>... <size=200%><color=red>We're trapped!</color></size>\r\n>... [panic]",
            ">... This is the end!\r\n>... <size=200%><color=red>No!</color></size>\r\n>... [gunfire]",
            ">... [breathing heavily]\r\n>... <size=200%><color=red>I'm done for!</color></size>\r\n>... [creatures shrieking]",
            ">... We're finished!\r\n>... <size=200%><color=red>Run!</color></size>\r\n>... [alarm blaring]",
            ">... [crying]\r\n>... <size=200%><color=red>Help me!</color></size>\r\n>... [screaming]",
            ">... It's hopeless!\r\n>... <size=200%><color=red>Too many!</color></size>\r\n>... [gunfire]",
            ">... [panic]\r\n>... <size=200%><color=red>Where's everyone?!</color></size>\r\n>... [alarm]",
            ">... We failed!\r\n>... <size=200%><color=red>All for nothing!</color></size>\r\n>... [sobbing]",

            // Atmospheric & sound effects (no variables)
            ">... [static]\r\n>... <size=200%><color=red>Connection lost!</color></size>\r\n>... [silence]",
            ">... [downloading]\r\n>... [alarm blaring]\r\n>... <size=200%><color=red>Almost there!</color></size>",
            ">... [creatures shrieking]\r\n>... <size=200%><color=red>They heard us!</color></size>\r\n>... [gunfire]",
            ">... [whispering]\r\n>... The terminal is here.\r\n>... <size=200%><color=red>Extract the data!</color></size>",
            ">... [breathing heavily]\r\n>... <size=200%><color=red>I can't breathe!</color></size>\r\n>... [alarm]",
            ">... [typing]\r\n>... [alarm]\r\n>... <size=200%><color=red>No time!</color></size>",
            ">... [static crackling]\r\n>... <size=200%><color=red>Terminal failing!</color></size>\r\n>... [panic]",
            ">... [creatures roaring]\r\n>... <size=200%><color=red>Giants!</color></size>\r\n>... [gunfire]",
            ">... [alarm blaring]\r\n>... [downloading]\r\n>... <size=200%><color=red>Keep going!</color></size>",
            ">... [silence]\r\n>... <size=200%><color=red>Something's wrong!</color></size>\r\n>... [creatures shrieking]",
        }))!);
        #endregion
    }
}
