namespace AutogenRundown.DataBlocks.Custom.ExtraEnemyCustomization.Models.Materials;

public enum MaterialType
{
    None,

    MtrHeadHenk,
    Birther,
    MtrCocoon,
    MtrDestARMShtr,
    MtrDestChestSides,
    MtrDestHalfShtr,
    MtrDestHead1,
    MtrHipSide,
    MtrHipsHole,
    MtrHoleShtr,
    MtrLegShtr,
    Scout,
    Shooter,
    ShooterBig,
    ShooterRapidFire,
    ShooterHibernate,
    ShooterWave,
    MtrTank,
    MtrGibMeatTrailer,
    MtrStriker,
    MtrStrikerChild,
    MtrChestHole,
    MtrChestSideFix,
    MtrDestARM,
    MtrDestLeg,
    MtrHalf,
    MtrHeadshot,
    MtrHip,
    MtrStomacheFix,
    MtrStrikerBullrush,
    MtrStrikerBullrushHead,
    MtrStrikerHibernate,
    MtrStrikerWave,
    Striker,
    StrikerBig,
}
