name: Generate CHANGELOG.md

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  changelog:
    name: Generate CHANGELOG.md
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Generate CHANGELOG.md
        run: |
          ./generate-changelog.sh
      - name: Set Git Authors
        run: |
          git config user.email brgmnn@users.noreply.github.com
          git config user.name "Daniel Bergmann"
      - name: Commit CHANGELOG
        run: |
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md"

          git log
