name: Release (Thunderstore)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version number'
        required: false
        default: 'v0.0.0'

jobs:
  release:
    name: Upload to Thunderstore
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4

      - name: Determine tag and version
        id: tag
        run: |
          raw="$(gh release view --json tagName --jq '.tagName')"

          echo "tag=$raw" >> "$GITHUB_OUTPUT"
          echo "version=$(echo $raw | sed 's/^v//')" >> "$GITHUB_OUTPUT"

      # - name: Download release asset
      #   run: gh release download ${{ steps.tag.outputs.tag }} -p AutogenRundown_0.13.0.zip

      - name: Debug
        run: |
          echo "well? '${{ steps.tag.outputs.tag }}'"
          echo "ver? '${{ steps.tag.outputs.version }}'"


      # - name: Upload mod to Thunderstore
      #   uses: gtfo-mods/thunderstore-upload-action@v1
      #   with:
      #     api-key: ${{ secrets.THUNDERSTORE_API_KEY }}
      #     mod-path: ./publish
