name: Attach Assets

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: false
        default: ''

jobs:
  attach-assets:
    name: Attach assets to release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      # - uses: actions/checkout@v4
      - name: Determine version
        id: get-version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            echo "No version specified, using latest draft"
            echo "release=$(gh release list | head -n 1 | awk '{print $1}')" >> "$GITHUB_OUTPUT"
          else
            echo "release=${{ github.event.inputs.version }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Get build run
        id: get-build
        run: |
          echo "build_number=$(gh run list -w .NET --limit 1 --status completed --branch main --json number -q '.[].number')" >> "$GITHUB_OUTPUT"

      - name: Download artifacts
        run: |
          gh run download ${{ steps.get-build.outputs.build_number }} --workflow .NET

      - name: Debug
        run: |
          echo "${{ steps.get-version.outputs.release }}"
          echo "${{ steps.get-build.outputs.build_number }}"
          ls -ls
