name: Test on releases

on:
  workflow_dispatch:
  release:
    types:
      - created
      - edited
      - deleted

jobs:
  test-events:
    name: Generate CHANGELOG.md
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This is a test"
